oceanbase/odc

README-zh-CN.md
README.md

docs: fix link in README

---

.github/workflows/build_release.yaml
.github/workflows/build_test.yaml

actions: refine workflow config

---

README.md

docs(README): add discord link

---

.github/workflows/build_dev.yaml
.github/workflows/build_release.yaml
.github/workflows/build_test.yaml

Delete useless PAT in workflow config

update(workflow): delete useless PAT in workflow config

---

server/odc-service/src/main/java/com/oceanbase/odc/service/audit/AuditEventMetaService.java

audit meta list lack of export result set
add export result set to audit meta list

fix(audit): event meta list add export result set

---

server/odc-server/src/main/java/com/oceanbase/odc/server/web/trace/WebTraceUtils.java
server/odc-service/src/main/java/com/oceanbase/odc/service/iam/UserService.java

Unnecessary log printing can be removed to keep the log output clean
Remove useless log to keep the log output clean

delete: Remove useless log to keep the log output clean

---

.idea/eclipseCodeFormatter.xml

set eclipse formatter as idea project setting

build: set eclipse formatter as idea project setting

---

.github/workflows/build_artifact.yaml

Fix: Build rpm failed when execute build_artifact.yaml
```docs
```

fix(workflow): build rpm failed when execute build_artifact.yaml

---

.github/workflows/build_artifact.yaml
.github/workflows/build_daily.yaml
.github/workflows/build_dev.yaml

type-feature, type-refactor
We publish db-browser and ob-sql-parser by maven central repo, and we cannot publish to the central warehouse during the R&D process.
So, here is the solution. We install them into local machine which we run our workflow, so that we can build a jar that include what we modify on db-browser and ob-sql-parser
Fixes #
```docs
```

refactor(workflow): add mvn install step for dev

---

server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/util/MockDataTypeUtil.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/util/FlowTaskUtil.java

type-feature
module-mockData
mock data module adapt for native mysql5.7
#32
RD has self-tested that all ob mysql data-types currently supported by mock data also support native mysql
```docs
```

[Feature]: mock data adapt for native mysql5.7

---

.github/workflows/build_artifact.yaml
.github/workflows/build_daily.yaml
.github/workflows/build_release.yaml

bug
Fix client deps bug
Fixes #
```docs
```

fix(workflow): Make pnpm run in hoisted mode

---

server/integration-test/src/test/java/com/oceanbase/odc/service/onlineschemachange/DdlUtilsTest.java
server/integration-test/src/test/java/com/oceanbase/odc/service/onlineschemachange/OnlineSchemaChangeSwapTableTest.java
server/integration-test/src/test/java/com/oceanbase/odc/service/onlineschemachange/OscFactoryWrapperGeneratorTest.java
server/integration-test/src/test/java/com/oceanbase/odc/service/onlineschemachange/ddl/TableNameReplacerTest.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/DefaultOnlineSchemaChangeTaskHandler.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/ddl/BaseTableNameDescriptorFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/ddl/DdlUtils.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/ddl/DefaultTableNameDescriptor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/ddl/OBMySqlTableNameDescriptorFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/ddl/OBOracleTableNameDescriptorFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/ddl/OBOracleTableNameReplacer.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/ddl/OscFactoryWrapper.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/ddl/OscFactoryWrapperGenerator.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/ddl/TableNameDescriptor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/ddl/TableNameDescriptorFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/model/OnlineSchemaChangeScheduleTaskParameters.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/pipeline/BaseCreateOmsProjectValve.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/pipeline/ScheduleCheckOmsProjectValve.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/rename/DefaultRenameTableInvoker.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/rename/LockUserInterceptor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/rename/OBOracleRenameTableHandler.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/rename/RenameBackHandler.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/subtask/OscTaskCompleteHandler.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/subtask/SubTaskParameterFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/validator/OnlineSchemaChangeValidator.java

type-bug
module-Online schema change
fix oracle rename table failed 
1. fix oracle rename table sql don't  contain database name
2. fix oracle white account add connection config user with upper case
3. refactor build new table name and rename table name , create oracle new table name  prefix is "" and mysql new table name prefix is "_"
4. delete new table table after task failed 
```docs
```

fix(osc): fix oracle rename table failed

---

server/odc-service/src/main/java/com/oceanbase/odc/metadb/schedule/ScheduleRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java

type-bug
Fix the issue of empty task list query results in personal mode.
```docs
```

fix(task):fix the issue of empty task list query results in personal mode.

---

server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/validator/OnlineSchemaChangeValidator.java

type-bug
current exception is unexpected exception message, this is cannot readable
when input sql in valid throws BadArgumentException replace to SyntaxErrorException
```docs
```

fix(osc): fix wrap invalid ddl error message  when sql parsed failed

---

server/odc-migrate/src/main/resources/migrate/web/V_4_2_0_18__iam_permission.yaml
server/odc-migrate/src/main/resources/migrate/web/V_4_2_0_19__add_iam_role_permission.yaml
server/odc-migrate/src/main/resources/migrate/web/V_4_2_1_2__iam_role.yaml
server/odc-migrate/src/main/resources/migrate/web/V_4_2_1_3__iam_role_permission.yaml
server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/IndividualOrganizationMigrator.java
server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/TeamOrganizationMigrator.java
server/starters/desktop-starter/src/main/java/com/oceanbase/odc/migrate/jdbc/desktop/V42034OrganizationMigrate.java

type-feature
module-iam
Add a built-in role 'individual_space' which contains individual space management permissions, making user easier to grant permissions to users who need to use individual space.
Other changes: move some migration resource Yamls to the 'web' package which will be migrated during bootstrap other than login. This change will not have effects on users who upgrade from V4.2.0 because allow_duplicate is false in these Yamls.

feat(iam): add a built-in role 'individual_space'

---

server/odc-common/src/main/java/com/oceanbase/odc/common/crypto/AesBytesEncryptor.java
server/odc-common/src/main/java/com/oceanbase/odc/common/crypto/Encryptors.java
server/odc-common/src/main/java/com/oceanbase/odc/common/crypto/RsaBytesEncryptor.java
server/odc-common/src/test/java/com/oceanbase/odc/common/crypto/RsaBytesEncryptorTest.java
server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/DataSourceController.java
server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/EncryptionController.java
server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/OdcEncryptionController.java
server/odc-service/src/main/java/com/oceanbase/odc/config/BeanConfiguration.java
server/odc-service/src/main/java/com/oceanbase/odc/config/CommonSecurityProperties.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionHelper.java
server/odc-service/src/main/java/com/oceanbase/odc/service/datatransfer/model/DataTransferConfig.java
server/odc-service/src/main/java/com/oceanbase/odc/service/encryption/EncryptionFacadeImpl.java
server/odc-service/src/main/java/com/oceanbase/odc/service/encryption/EncryptionService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/encryption/SensitivePropertyHandler.java
server/odc-service/src/main/java/com/oceanbase/odc/service/encryption/SensitivePropertyHandlerImpl.java
server/odc-service/src/main/java/com/oceanbase/odc/service/info/OdcInfo.java
server/odc-service/src/main/java/com/oceanbase/odc/service/info/OdcInfoService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/integration/model/Encryption.java
server/odc-service/src/test/java/com/oceanbase/odc/service/connection/ConnectionHelperTest.java
server/odc-service/src/test/java/com/oceanbase/odc/service/encryption/SensitivePropertyHandlerImplTest.java

type-feature
Use asymmetric encryption instead of symmetric encryption.
Close #56 
The PR is WIP and merge will be enabled after self-testing.

feat(encryption): support asymmetric encryption

---

.secignore
server/odc-core/src/test/resources/sql/split/sql-splitter-10-string-with-backslash-inside.yml

type-security
add some URLs in .secignore to pass the data security scan

security: append white list in .secignore

---

libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OBOracleSchemaAccessor.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OracleSchemaAccessor.java

type-bug
filter out the internal schema when synchronizing the database:`PUBLIC、LBACSYS、ORAAUDITOR、__public`
Fixes #95
```docs
```

fix(syncDatabase): fix filter out the internal schema when synchronizing the database

---

.secignore

type-security
fix some URLs in .secignore to pass the data security scan

security: fix unmatched items in .secignore

---

libs/ob-sql-parser/src/main/resources/obmysql/sql/OBLexer.g4
libs/ob-sql-parser/src/main/resources/obmysql/sql/OBParser.g4
libs/ob-sql-parser/src/main/resources/oboracle/sql/OBLexer.g4
libs/ob-sql-parser/src/main/resources/oboracle/sql/OBParser.g4

type-refactor
OceanBase 4.1.0 added some new syntaxes, such as `get_diagnostics_stmt`. Current ob-sql-parser isn't adapt to new syntax, and cause some syntax error, so that we should add these new syntaxes.
Fixes #123 
Closes #123 
```docs
```

refactor(ob-sql-parser): add several new syntaxes which added in OceanBase 4.1.0

---

server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java

type-bug
modul-Online schema change
desktop odc use `flowInstanceService#createIndividualFlowInstance` to build flow configure which is different from web odc, and this leads to desktop odc cannot generate rollback plan.
Fixes #127 
```docs
```

fix(rollbackPlan): fix desktop odc cannot generate rollback plan

---

server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/instance/FlowInstanceConfigurer.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/CreateExternalApprovalTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/model/RuntimeTaskConstants.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/util/FlowTaskUtil.java

HotFix: Handle exception when failed to get flow approval instance
Fixes #67 
Has been tested on BPMS.

fix(integration): uncatched exception when failed to get flow instance

---

server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/PartitionPlanController.java
server/odc-service/src/main/java/com/oceanbase/odc/service/partitionplan/PartitionPlanService.java

type-bug
Fix security vulnerability and remove redundant code.
```docs
```

security: broken access control in the partition plan

---

server/odc-common/src/main/java/com/oceanbase/odc/common/util/SSRFChecker.java
server/odc-common/src/test/java/com/oceanbase/odc/common/util/SSRFCheckerTest.java
server/odc-core/src/main/java/com/oceanbase/odc/core/shared/PreConditions.java
server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/ErrorCodes.java
server/odc-core/src/main/resources/i18n/ErrorMessages.properties
server/odc-core/src/main/resources/i18n/ErrorMessages_zh_CN.properties
server/odc-core/src/main/resources/i18n/ErrorMessages_zh_TW.properties
server/odc-server/src/main/resources/data.sql
server/odc-service/src/main/java/com/oceanbase/odc/service/integration/HttpOperationService.java

type-bug
module-External integration
Check the url in whitelist when request to external URL
Fixes #170

fix(security): http request during integration may receive SSRF attack

---

server/odc-service/src/main/java/com/oceanbase/odc/service/pldebug/session/AbstractDebugSession.java
server/odc-service/src/main/java/com/oceanbase/odc/service/pldebug/session/DebuggeeSession.java
server/odc-service/src/main/java/com/oceanbase/odc/service/pldebug/session/DebuggerSession.java

type-bug
module-PL debug
And `"` wrappered database name in JDBC URL, and fix some issues.
Fixes #196 
Testing passed on OB 4.x

fix(pl-debug): Get connection failed when debug anonymous blocks in lowcase schema name

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionTestService.java
server/plugins/connect-plugin-api/src/main/java/com/oceanbase/odc/plugin/connect/api/InformationExtensionPoint.java
server/plugins/connect-plugin-api/src/main/java/com/oceanbase/odc/plugin/connect/api/TestResult.java
server/plugins/connect-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/connect/mysql/MySQLInformationExtension.java
server/plugins/connect-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/connect/obmysql/OBMySQLConnectionExtension.java
server/plugins/connect-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/connect/obmysql/OBMySQLInformationExtension.java
server/plugins/connect-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/connect/oboracle/OBOracleConnectionExtension.java

type-bug
Avoid database synchronization failure caused by user inputting the wrong database type.
Check database type when test connection.
```docs
```

fix(connection): check database type when test connection.

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionTestService.java
server/plugins/connect-plugin-api/src/main/java/com/oceanbase/odc/plugin/connect/api/InformationExtensionPoint.java
server/plugins/connect-plugin-api/src/main/java/com/oceanbase/odc/plugin/connect/api/TestResult.java
server/plugins/connect-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/connect/mysql/MySQLInformationExtension.java
server/plugins/connect-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/connect/obmysql/OBMySQLConnectionExtension.java
server/plugins/connect-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/connect/obmysql/OBMySQLInformationExtension.java
server/plugins/connect-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/connect/oboracle/OBOracleConnectionExtension.java

This reverts commit e510faf480fe7fafae28aea62a8febe563e0769b.
Fixes #
```docs
```

revert:check database type when test connection. 

---

pom.xml

type-bug
Upgrade dlm sdk version to 1.0.3
```docs
```

fix(dlm):upgrade dlm sdk version.

---

server/starters/desktop-starter/src/main/java/com/oceanbase/odc/service/audit/DesktopAuditEventHandler.java

type-bug
module-audit
audit meta for desktop lack of result export、 database  operation、 datasource manager and remove partition plan
fix audit meta return for desktop
```docs
```

fix(audit): fix audit meta event for desktop 

---

server/odc-service/src/main/java/com/oceanbase/odc/metadb/iam/UserOrganizationRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/DefaultOrganizationResourceMigrator.java
server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/TeamOrganizationMigrator.java
server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/UserOrganizationMigrator.java

type-bug
module-migration
Decoupling user organization migration and organization resources migration
Use a single class UserOrganizationMigrator to record user and organization relations, and fix the timing of recording user organization relation

fix(migration): missing user organization relation migration

---

server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/OdcJobListener.java

type-bug
Fix wrong organization id in individual space.
```docs
```

fix(schedule):wrong organization id in individual space.

---

server/odc-service/src/main/java/com/oceanbase/odc/service/partitionplan/PartitionPlanSubFlowThread.java

type-bug
Ignore pre-check node in individual space.
```docs
```

fix(partition-plan):ignore pre-check node in individual space.

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionEnvironmentAdapter.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionService.java

type-bug
The password of the connection will be overwritten if you modify it in the adapter.
Fix the issue of the adapter result has been overwritten.
```docs
```

fix(connection):adapter result has been overwritten.

---

server/odc-core/src/main/java/com/oceanbase/odc/core/shared/rest/OdcRestLogInterceptor.java
server/odc-core/src/main/java/com/oceanbase/odc/core/shared/rest/OdcRestTemplate.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/DatabaseSyncSchedules.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java

type-refactor
change log level from info to debug, preventing massive log

refactor: optimize log

---

server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/model/RuntimeTaskConstants.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/util/FlowTaskUtil.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/OnlineSchemaChangeFlowableTask.java

type-bug
module-Online schema change
fix personal individual area main uid error
fix get main account uid in personal individual area, store the uid in flow variable, and get it from executionContext  
```docs
```

fix(osc): fix personal individual space obtain main account id error

---

server/odc-common/src/test/java/com/oceanbase/odc/common/util/SSRFCheckerTest.java

Fix URL discovered by security scans

fix(security): risky URLs discovered by security scans

---

pom.xml
server/integration-test/src/test/java/com/oceanbase/odc/service/integration/model/ApprovalPropertiesTest.java
server/integration-test/src/test/resources/integration/approval_integration_template.yaml
server/integration-test/src/test/resources/integration/mocked_approval_server_config.json
server/odc-common/pom.xml
server/odc-common/src/main/java/com/oceanbase/odc/common/json/JsonUtils.java
server/odc-common/src/test/java/com/oceanbase/odc/common/json/JsonUtilsTest.java
server/odc-service/src/main/java/com/oceanbase/odc/service/integration/HttpOperationService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/integration/client/ApprovalClient.java
server/odc-service/src/main/java/com/oceanbase/odc/service/integration/client/OdcIntegrationResponseHandler.java
server/odc-service/src/main/java/com/oceanbase/odc/service/integration/client/SqlInterceptorClient.java
server/odc-service/src/main/java/com/oceanbase/odc/service/integration/model/IntegrationProperties.java
server/odc-service/src/main/java/com/oceanbase/odc/service/integration/model/OdcIntegrationResponse.java

type-feature
module-integration
Support retrieve xml format response
Closing #313 
Unit test has covered

feat(integration): support retrieve xml format response

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/model/ScheduleDetailResp.java

type-bug
Fixing some code that has potential NPE vulnerabilities.
Fixes #
```docs
```

fix(task):add non-null validation.

---

server/odc-service/src/test/java/com/oceanbase/odc/service/datasecurity/extractor/OBColumnExtractorTest.java
server/odc-service/src/test/resources/datasecurity/test_sensitive_column_extractor_sql.yaml

type-refactor
module-Data masking
Add missing unit test case

fix(data-masking): add unit test case for select sql syntax

---

libs/db-browser/pom.xml
pom.xml

upgrade db-browser's version to 1.0.2
Fixes #
```docs
```

feat(db-browser): upgrade db-browser's version to 1.0.2

---

libs/db-browser/pom.xml
pom.xml

upgrade jdbc to 2.4.5 to adapt to ob4.2.1

feat(jdbc): upgrade oceanbase-client to 2.4.5

---

server/odc-migrate/src/main/resources/init-config/init/regulation-rule-applying.yaml
server/odc-migrate/src/main/resources/init-config/init/regulation-rule-metadata.yaml

type-feature
module-security control
native mysql adapt for safety regulations.
The following 3 rules do not support mysql:
- sql-check.prefer-local-index
- sql-check.restrict-column-name-case
- sql-check.restrict-table-name-case
See the self-test results at related documents.
Fixes #2
```docs
```

feat(mysql): native mysql adapt for safety regulations

---

pom.xml
server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/extractor/OBColumnExtractor.java

type-feature
module-sql parser
Upgrade ob-sql-parser to 1.1.2 and adapt data-masking.

feat(sql-parser): upgrade ob-sql-parser to 1.1.2

---

libs/ob-sql-parser/src/main/resources/oracle/PlSqlParser.g4

type-bug
fix a parser's bug that failed to parse type's member proc without any parameters.
We can define a type or type body containing a member procedure without any parameters as follow:
```SQL
-- type
create or replace type t1 as object(member procedure p1); 
-- type body
create or replace type body t1 as 
member procedure p1 is
begin
xxx
end;
end;
```
the definition above can not pass the oracle parser's grammar check, it requires that the member proc must have parameters:
```SQL
-- type
create or replace type t1 as object(member procedure p1(p1 in integer)); -- at least one parameter
-- type body
create or replace type body t1 as 
member procedure p1(p1 in integer) is -- at least one parameter
begin
xxx
end;
end;
``` 
this pr fix this unreasonable constraint.
Fixes #545 
```docs
```

fix(ob-sql-parser): fix failed to parse member proc without parameters

---

server/odc-service/src/main/java/com/oceanbase/odc/service/feature/VersionDiffConfigService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/initializer/SwitchSchemaInitializer.java

type-feature
1. Remove the auto deletion logic for package `OBODC_PL_RUN_PACKAGE`.
ODC used to print `dbms_output` message through the package `OBODC_PL_RUN_PACKAGE`. We find another way using anonymous block to do the same thing on ODC 4.2.0. 
Thus, ODC will delete `OBODC_PL_RUN_PACKAGE` automatically whether it exists or not, so that it may cause a lot of error. Some users do not like this, We remove this auto deletion to avoid the error printing.
2. Remove the procedure test calls.
ODC will try to call a non-existent program to verify whether the OB supports the program. This logic will also cause many errors and even take a long time, so we delete it.
Fixes #257 #540 
```docs
```

fix(pl): remove stored procedure test calls and built-in package automatic deletion logic

---

README-zh-CN.md
README.md

No code modification, add pictures to the readme to enhance the expression
Check if the modification effect meets expectations
Fixes #
```docs
```

docs: update README, add diagrams

---

.gitignore
docs/en-US/DEVELOPER_GUIDE.md
docs/zh-CN/DEVELOPER_GUIDE.md
script/build_jar.sh
script/build_libs.sh
script/functions.sh
script/start-odc.sh
server/integration-test/src/test/java/com/oceanbase/odc/migrate/jdbc/common/MigrateTestUtils.java
server/integration-test/src/test/java/com/oceanbase/odc/migrate/jdbc/common/R4201AuditEventMetaMigrateTest.java
server/integration-test/src/test/java/com/oceanbase/odc/migrate/jdbc/common/V2412UserPasswordMigrateTest.java
server/integration-test/src/test/java/com/oceanbase/odc/migrate/jdbc/common/V2413ConnectPasswordMigrateTest.java
server/integration-test/src/test/java/com/oceanbase/odc/migrate/jdbc/common/V2422ConnectSysPasswordMigrateTest.java
server/integration-test/src/test/java/com/oceanbase/odc/migrate/jdbc/common/V3309SqlScriptMigrateTest.java
server/integration-test/src/test/java/com/oceanbase/odc/migrate/jdbc/common/V41018PermissionMigrateTest.java
server/integration-test/src/test/java/com/oceanbase/odc/migrate/jdbc/common/V4103ConnectionLabelMigrateTest.java
server/integration-test/src/test/java/com/oceanbase/odc/migrate/jdbc/common/V42013OAuth2ConfigMetaMigrateTest.java
server/integration-test/src/test/java/com/oceanbase/odc/migrate/jdbc/common/V42017InitRegulationRuleMetadataTest.java
server/integration-test/src/test/java/com/oceanbase/odc/migrate/jdbc/web/V4131InitialPasswordMigrateTest.java
server/odc-core/src/main/java/com/oceanbase/odc/core/session/ConnectionSessionUtil.java
server/odc-migrate/src/main/java/com/oceanbase/odc/migrate/jdbc/common/V42013OAuth2ConfigMetaMigrate.java
server/odc-server/src/main/resources/config/application.yml
server/odc-server/src/main/resources/config/bootstrap.yml
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/util/ConnectionInfoUtil.java
server/odc-service/src/main/java/com/oceanbase/odc/service/db/browser/DBSchemaAccessors.java
server/odc-service/src/main/java/com/oceanbase/odc/service/integration/model/SSOIntegrationConfig.java

type-bug
the ODC v4.2.0 involve much changes, broke bastion integration feature.
here we recover account integration and auto datasource configuration.
Fixes #558 To #70 
there exits migration error for OAuth2 ingration configuration,
which result into OAuth2 configuration not works if there exits multiple ogranization.
this pr also contains some build script fix, we can use local build by script/build_jar.sh now.
```docs
```

fix(integration): recover bastion integration

---

libs/ob-sql-parser/src/main/resources/oracle/PlSqlParser.g4
server/odc-service/src/main/java/com/oceanbase/odc/service/pldebug/session/DebuggerSession.java

type-bug
module-PL Debugger
this is fix two issues:
1. Some user will add some ob's grammar to PL body, such as `set autocommit='OFF'` which is not supported by oracle's parser and lead to error report when debugging.
This pr supports set_variables statement and count(*) in pivot clause to avoid syntax error.
2. Fix can not step in a sub-procedure or sub-function that defined by package.
ODC can only supports step in a standalone procedure or function in anonymous block which is a bug and we solve this by handling the two cases separately.
Fixes #560 
```docs
```

fix(pl-debug): fix failed to step in a subprocedure or subfunction defined in package

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/ConnectionConfig.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/TestConnectionReq.java
server/odc-service/src/main/java/com/oceanbase/odc/service/pldebug/session/AbstractDebugSession.java
server/odc-service/src/main/java/com/oceanbase/odc/service/pldebug/session/DebuggerSession.java

type-debug
make session init script works in pl-debug
Fixes #251 
```docs
```

feat(pl-debug): add timeout settings

---

server/plugins/connect-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/connect/obmysql/OBMySQLDiagnoseExtension.java

type-bug
Now when explain execution plan failed, the exception would be eaten. It's hard to find root cause.
So in this PR, the exception and origin plan text will be printed.
Fixes #439

fix(diagnose): optimize log information when explain failed 

---

server/odc-service/src/main/java/com/oceanbase/odc/service/datatransfer/DataTransferService.java

type-bug
It's a coding error. Data objects and schema objects would be set into wrong positions.

fix(data-transfer): fix wrong data objects and schema objects

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionSessionHistoryService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/DatabaseSyncSchedules.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBSchemaService.java
server/plugins/schema-plugin-api/src/main/java/com/oceanbase/odc/plugin/schema/api/DatabaseExtensionPoint.java
server/plugins/schema-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/schema/obmysql/OBMySQLDatabaseExtension.java
server/plugins/schema-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/schema/oboracle/OBOracleDatabaseExtension.java

1. avoid creating `ConnectSession` when syncing datasource and create a schema.
2. cherry-pick 9f8c81f6 from dev/4.2.x into dev/4.2.2
3. add log printing when failed to sync datasource
Fixes #613 
```docs
```

enhancement: add log printing and avoid creating connect session when syncing datasource 

---

.github/workflows/build_dev.yaml

close #112 
Add PR title check rule in workflow.

build(action): add pr title specification

---

server/odc-server/src/main/java/com/oceanbase/odc/server/config/MvcConfiguration.java

type-bug
module-web
`editor.worker.js` static resource not found because the server does not config this resource mapping.
Fixes #
```docs
```

fix(web): editor.worker.js static resource 404 not found

---

libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/DBSchemaAccessor.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/MySQLNoGreaterThan5740SchemaAccessor.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OracleSchemaAccessor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/datatransfer/DBObjectNameAccessor.java

type-bug
When getting export objects, the DBSchamaAccessor#listPackage method will only return packages without body.
So I add a method `listPackageBodies` to list package bodies.
Fixes #482 
```docs
```

fix(data-transfer): no package body 

---

server/odc-migrate/src/main/resources/init-config/init/regulation-rule-applying.yaml
server/plugins/connect-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/connect/obmysql/diagnose/DiagnoseUtil.java

type-bug
failed to get query plan on OceanBase 4.2.1, you can get more details from the issue mentioned as follow.
Fixes #655 
```docs
```

fix(sql-diagnose): fix failed to get execute plan 

---

server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/PreCheckRuntimeFlowableTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/BaseSqlChecker.java
server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/factory/SyntaxErrorExistsFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/parser/SyntaxErrorStatement.java
server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/SqlCheckRules.java
server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/SyntaxErrorExists.java

type-bug
syntax error sql-check rule can not be disabled, which is not expected.
The root cause of it is that the syntax error rule is hard coded in odc which can not be disabled.
I create the `SyntaxErrorExists` rule to check if user's statement is illegal. This is a normal sql-check rule, so that it can be disabled.
Fixes #639 
```docs
```

fix(sql-check): fix syntax error check rule can not be disabled

---

server/odc-service/src/main/java/com/oceanbase/odc/metadb/regulation/ruleset/MetadataEntity.java
server/odc-service/src/main/java/com/oceanbase/odc/metadb/regulation/ruleset/PropertyMetadataEntity.java

type-bug
module-migration
Rule metadata will be deleted and inserted once every time the ODC server starts up, while we expect that if there is no change between records in `regulation-rule-metadata.yaml` and in the metadb, we do not update the metadata.
The issue is that we only override the `equals()` and `hashCode()` method in `MetadataEntity` but do not override them in `PropertyMetadataEntity`.
Fixes #574 
```docs
```

fix(migration): rule metadata migration will be triggered every time the ODC server starts up

---

server/integration-test/src/test/java/com/oceanbase/odc/service/session/NlsFormatInterceptorTest.java
server/odc-common/src/main/java/com/oceanbase/odc/common/util/TraceWatch.java
server/odc-core/src/main/java/com/oceanbase/odc/core/sql/execute/SqlExecuteStages.java
server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/DataMaskingInterceptor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/integration/ExternalSqlInterceptor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/ConnectConsoleService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/interceptor/BaseTimeConsumingInterceptor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/interceptor/DatabasePermissionInterceptor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/interceptor/NlsFormatInterceptor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/interceptor/SqlCheckInterceptor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/interceptor/SqlConsoleInterceptor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/util/SchemaExtractor.java

type-bug
1. add several time consuming sub-stages to pre-handle stage and after-completion:
2. fix the issue that the sum of sub-stage's time consuming is not equal to total duration. 
Fixes #640 
```docs
```

fix(sql-execute): fix failed to get time consuming

---

server/odc-migrate/src/main/resources/runtime/V_4_2_0_28__add_masking_algorithm_segment.yaml

type-bug
Meta data of built-in masking algorithm sgement is wrong, I fix it in this PR.
Fixes #642 

fix(data-security): meta data of built-in masking algorithm sgement is wrong

---

server/odc-service/src/main/java/com/oceanbase/odc/service/pldebug/session/DebuggeeSession.java

type-bug
odc will hang up on arm architecture ob when debugging. this problem is caused by observer, but odc can do somethings to prevent it. 
you can get more infos from the related issue.
Fixes #341 
```docs
```

fix(pl-debug): fix the problem of hang when debugging on arm architecture ob

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/DataArchivePreprocessor.java

type-bug
Set default schema before create connection session.
Fixes #623
```docs
```

fix(dlm): submit task got condition not supported error while condition contains subquery

---

server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/SSOController.java
server/odc-service/src/main/java/com/oceanbase/odc/metadb/integration/IntegrationRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/service/integration/IntegrationEvent.java
server/odc-service/src/main/java/com/oceanbase/odc/service/integration/IntegrationService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/integration/model/IntegrationConfig.java
server/odc-service/src/main/java/com/oceanbase/odc/service/integration/oauth2/SSOEventHandler.java
server/odc-service/src/main/java/com/oceanbase/odc/service/integration/oauth2/TestLoginManager.java

saved SSO intergration test login failed
cause by [issue](https://github.com/oceanbase/odc/pull/99)
Encryption#secret is set to  Access.WRITE_ONLY
Fixes https://github.com/oceanbase/odc/issues/674
fix can't test  a saved SSO intergration login 
```docs
```

fix(SSO):saved SSO intergration test login failed

---

server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/OdcJobListener.java

type-bug
When a sub-task of a periodic work order is rolled back, the status of the work order will not be affected.
Fixes #704
```docs
```

fix(dlm):wrong order status when task is rollback

---

CHANGELOG-zh-CN.md
CHANGELOG.md

type-build
Fixes #
```docs
```

builds: update submodule

---

server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/DataBaseController.java
server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/OscController.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/OscService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/model/OscDatabaseInfo.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/model/OscLockDatabaseUserInfo.java

type-feature
module-Online schema change
show database selected should lock db user when create osc task
Fixes #
old api is `/databases/{id:[\d]+}` is common api in font web, add a  alone api `/lockDatabaseUserRequired/{databaseId:[\d]+}` to query database lock user info,  cooperation succeed with front-end
```docs
```

feat(osc): reactor api get database about lock user required

---

.github/obfarm/Dockerfile
.github/obfarm/action.yaml
.github/obfarm/obfarm.py
.github/workflows/build_dev.yaml
server/integration-test/src/test/java/com/oceanbase/odc/service/flow/ExpiredDocumentProviderTest.java
server/odc-common/src/test/java/com/oceanbase/odc/common/util/SystemUtilsTest.java

1. support run odc ut in obfarm
2. add the custom action with obfarm
Fixes #
```docs
```

build(unit-test): executing unit test in obfarm

---

README-zh-CN.md
README.md

docs: update desktop version install package link

---

distribution/docker/build.sh
distribution/docker/odc/Dockerfile
script/build_rpm.sh

type-build
simplify arm docker build
1. same Dockerfile for both amd64 and arm64 arch
2. default argument for rpm build and docker build
now we can build arm docker locally with 2 steps
- step1 script/build_rpm.sh, with no argument ,  will set release number automatically
- step2 cd distribution/docker && ./build.sh build && ./build.sh save, with no argument , will calculate image tag automatically from odc version and cpu arch
Fixes #
```docs
```

build: simplify arm docker build

---

server/odc-service/src/main/java/com/oceanbase/odc/service/db/util/OBOracleCallProcedureBlockCallBack.java

type-bug
the column's name is wrong when I view a cursor's result, this pr fix this issue
Fixes #751 
```docs
```

fix(pl): fix column name is wrong when viewing cursor's content

---

server/odc-service/src/main/java/com/oceanbase/odc/service/pldebug/PLDebugService.java

type-bug
pldebug monitor does not exit block process exiting while web listen port occupied
Fixes #717
```docs
```

fix(pldebug): pldebug monitor does not exit block process exiting

---

libs/db-browser/pom.xml
pom.xml
server/odc-core/src/main/java/com/oceanbase/odc/core/sql/execute/mapper/OracleGeneralDateMapper.java
server/odc-core/src/test/java/com/oceanbase/odc/core/sql/execute/tool/DateCellData.java

type-feature
upgrade oceanbase-client to 2.4.7.1
Fixes #730 #728 #727 
```docs
```

feat(jdbc): upgrade jdbc to 2.4.7.1

---

server/odc-service/src/main/java/com/oceanbase/odc/service/permissionapply/project/ApplyProjectParameter.java
server/odc-service/src/main/java/com/oceanbase/odc/service/permissionapply/project/ApplyProjectPreprocessor.java

type-bug
module-apply project
Resource role name in DTO could by modified but trusted by ODC. This PR fix it.
Fixes #759

fix(apply-project): Resource role name in DTO is modified but be trusted

---

server/odc-migrate/src/main/resources/init-config/init/regulation-rule-applying.yaml
server/odc-migrate/src/main/resources/init-config/init/regulation-rule-metadata.yaml

type-feature
module-security control
safety regulation adapt to ODP sharding MySQL
Fixes #32
```docs
```

feat(security-control): safety regulation adapt to ODP sharding MySQL

---

server/odc-migrate/src/main/java/com/oceanbase/odc/migrate/jdbc/common/V42013OAuth2ConfigMetaMigrate.java
server/odc-service/src/main/java/com/oceanbase/odc/service/integration/model/Oauth2Parameter.java
server/odc-service/src/main/java/com/oceanbase/odc/service/integration/model/SSOIntegrationConfig.java

fix test login redirect url schema may not match. see https://github.com/oceanbase/odc/issues/210
ODC not use {baseUrl} to rewrite redirect Url, instead of , use the host obtained by the front-end.
Fixes #https://github.com/oceanbase/odc/issues/210
```docs
```

fix(SSO): test login protocal not match

---

server/odc-service/src/main/java/com/oceanbase/odc/service/iam/LoginHistoryService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/iam/auth/CustomAuthenticationSuccessHandler.java

reduce trigger frequency of LOGIN_SUCCESS automation event
Fixes #
https://github.com/oceanbase/odc/issues/789
```docs
```

fix(automation): reduce automation triggler frequency

---

server/odc-service/src/main/java/com/oceanbase/odc/service/regulation/ruleset/RuleService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/interceptor/SqlCheckInterceptor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/SqlCheckService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/factory/NoColumnCommentExistsFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/factory/NoTableCommentExistsFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/OracleNoColumnCommentExists.java
server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/OracleNoTableCommentExists.java
server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/SqlCheckRules.java
server/odc-service/src/test/java/com/oceanbase/odc/service/sqlcheck/OracleSqlCheckerTest.java
server/odc-service/src/test/java/com/oceanbase/odc/service/sqlcheck/SqlCheckRulesTest.java

sql-check will load all rules from metadb for every query which costs too much time and I reuse the ruleset cache to accelerate it.
Fixes #666 
```docs
```

enhancement(sql-check): add cache for sql-check

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataArchiveDeleteJob.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataArchiveRollbackJob.java

type-bug
Regenerate the ID for the rollback task and delete task to avoid task failure due to duplicate IDs
Fixes #734
```docs
```

Fix(dlm): data deletion failed after archiving the data

---

server/odc-service/src/main/java/com/oceanbase/odc/service/dml/model/DataModifyUnit.java

type-bug
module-Data viewing and editing
optimize error message when the length of data inserted into a json field exceeds the maximum limit.
before:
after:
Fixes #401
```docs
```

fix(data-editing): optimize error message when the length of field exceeds the maximum limit

---

server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/recognizer/RegexColumnRecognizer.java

type-bug
ODC server may suffer ReDos attack. The PR #843 still has some problem and this PR fix it.
Fixes #842 

fix(data-security): regex column recognization rule may suffer ReDos 2

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/DataDeletePreprocessor.java

type-bug
Create a rate limiter for the data-delete job when creating the job
Fixes #836
```docs
```

fix(dlm):update limiter failed after data-delete job was created

---

server/odc-core/src/main/java/com/oceanbase/odc/core/migrate/ResourceMigrator.java

type-bug
this pr fix that odc failed to start up when there is no users or organizations
Fixes #
```docs
```

fix(migrate): failed to start up when there is no users or organizations

---

server/odc-common/src/main/java/com/oceanbase/odc/common/trace/TraceContextHolder.java

fix RESPONSE_TIME not removed from MDC
Fixes #
```docs
```

fix(trace): rt miscalculation

---

pom.xml

type-bug
upgrade version of spring-security to 5.7.10
upgrade version of hutool to 5.8.23
upgrade version of netty to 4.1.94.Final
upgrade version of pf4j to 3.10.0
by the way, what does netty use? @yizhouxw 
Fixes #
```docs
```

fix(security): upgrade the version of some modules to avoid security problems

---

libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/util/TimeoutTokenStream.java

type-bug
the timeout settings for ob-sql-parser may overflow, this pr fix this issue
Fixes #
```docs
```

fix(ob-sql-parser): ob-sql-parser's timeout setting may overflow

---

server/odc-migrate/src/main/resources/migrate/common/V_4_2_3_5__modify_upload_file_config.sql
server/odc-server/src/main/resources/data.sql
server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/LocalFileTransferService.java

This PR (#864 ) is wrong, and this PR fix it.

fix(config): modify bad system configuration

---

server/odc-service/src/main/java/com/oceanbase/odc/service/session/factory/DruidDataSourceFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/factory/OBConsoleDataSourceFactory.java
server/plugins/connect-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/connect/mysql/MySQLConnectionExtension.java
server/plugins/connect-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/connect/obmysql/OBMySQLConnectionExtension.java

type-bug
module-security
When establishing a new connection, fill in the following content in HOST:
```
xx.xxx.xxx.xx:3307/information_schema?allowLoadLocalInfile=true&allowUrlInLocalInfile=true&maxAllowedPacket=655360#
```
where # represents comments, this will cause the subsequent parameters spliced in jdbcURL by odc server to be invalid.
the jdbcURL generated by odc server is:
```
jdbc:mysql://xx.xxx.xxx.xx:3307/jingtian_test?allowLoadLocalInfile=true&allowUrlInLocalInfile=true&maxAllowedPacket=655360#:3307/information_schema?allowUrlInLocalInfile=false&maxAllowedPacket=64000000&noDatetimeStringSync=true&connectTimeout=5000&tinyInt1isBit=false&allowMultiQueries=true&zeroDateTimeBehavior=round&jdbcCompliantTruncation=false&sendConnectionAttributes=false&allowLoadLocalInfile=false&useSSL= …
```

security: MySQL JDBC arbitrary file reading vulnerability

---

server/odc-core/src/main/java/com/oceanbase/odc/core/sql/util/JdbcDataTypeUtil.java

type-bug
ODC can not execute a procedure/function that contains an out sys_refcursor parameter and this pr fix it.
Fixes #910 
```docs
```

fix(pl): failed to execute a pl that contains an out sys_refcursor parameter

---

server/odc-service/src/main/java/com/oceanbase/odc/service/session/factory/DruidDataSourceFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/factory/OBConsoleDataSourceFactory.java
server/plugins/connect-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/connect/mysql/MySQLConnectionExtension.java

type-bug
module-security
fix MySQL JDBC deserialization Security vulnerability
add jdbc parameter:
```
properties.setProperty("autoDeserialize", "false");
```
Fixes #
```docs
```

security: fix mysql jdbc deserialization security vulnerability

---

server/odc-core/src/main/java/com/oceanbase/odc/core/sql/util/JdbcDataTypeUtil.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/factory/DruidDataSourceFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/factory/OBConsoleDataSourceFactory.java
server/plugins/connect-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/connect/mysql/MySQLConnectionExtension.java

type-builds
merge dev/4.2.2 into main
Fixes #
```docs
```

merge dev/4.2.2 into main

---

server/integration-test/src/test/java/com/oceanbase/odc/service/flow/FlowResponseMapperFactoryTest.java
server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/TaskType.java
server/odc-core/src/main/resources/i18n/BusinessMessages.properties
server/odc-core/src/main/resources/i18n/BusinessMessages_zh_CN.properties
server/odc-core/src/main/resources/i18n/BusinessMessages_zh_TW.properties
server/odc-server/src/main/java/com/oceanbase/odc/server/OdcServer.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/K8sJobCaller.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/constants/JobConstants.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/BaseTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/JobContextProvider.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/JobContextProviderFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/K8sJobContextProvider.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/Task.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/TaskApplication.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/TaskExecutor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/TaskFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/ThreadPoolTaskExecutor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/sampletask/SampleTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/sampletask/SampleTaskParameter.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/sampletask/SampleTaskResult.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/util/SystemEnvUtil.java

module-task framwork
Basic implementation for task executor
- `Task` interface define the method for all task implementatios, and `SampleTask` is a sample for test, in whcih a list of SQLs will be executed one by one.
- `TaskExecutor` interface define the method for all executor implementations, and `ThreadPoolTaskExecutor` is a sample for test, in which a new task will be executed in a thread pool.
- `JobContextProvider` interface define the method for all `JobContext` providers, and `K8sJobContextProvider` is a implementation in which the job context will be extracted from negotiated system env variables.
- `TaskApplication` is the bootstrap class, it initializes `JobContextProvider` and encapsulate a task, and then using `TaskExecutor` to execut it.
This PR only provides basic …

feat(task-framwork): task executor basic implementation

---

server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/BaseTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/K8sJobContextProvider.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/TaskApplication.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/sampletask/SampleTask.java

type-feature
Fix some bugs and refine implementation.

feat(taskframework): refine task executor implementation

---

script/start-odc.sh
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/model/QuartzKeyGenerator.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/DefaultJobContext.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/JobContext.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/NativeK8sJobClient.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/DefaultSpringJobConfiguration.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/JobConfiguration.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/JobConfigurationHolder.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/TaskFrameworkConfiguration.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/DefaultJobDefinition.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/JobDefinition.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/JobIdentity.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/JobScheduler.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/PrepareCallJob.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/ScheduleSourceType.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/StdJobScheduler.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/TriggerBuilder.java
server/odc-service/src/test/java/com/oceanbase/odc/service/task/JobSchedulerTest.java

type-feature
1.integrate scheduler with task-framework, we can put a job describe by `JobDefinition` to `JobScheduler` to schedule,
and job will be scheduled by trigger config
Fixes #
```docs
```

feat(taskframework): add job scheduler to taskframework

---

server/odc-core/src/main/java/com/oceanbase/odc/core/session/ConnectionSessionConstants.java
server/odc-core/src/main/java/com/oceanbase/odc/core/session/ConnectionSessionUtil.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/factory/DefaultConnectSessionFactory.java

fix(connection):add back connection cluster name

---

server/integration-test/src/test/java/com/oceanbase/odc/service/task/HttpResultClientTest.java
server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/TaskController.java
server/odc-service/src/main/java/com/oceanbase/odc/config/CommonSecurityProperties.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/DefaultTaskResult.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/TaskResult.java

type-feature
module-task framework
1. `TaskController` add task result upload
2. `TaskResult` represent task result
Fixes #
```docs
```

feat(taskframwork): add task result upload api

---

server/integration-test/src/test/java/com/oceanbase/odc/service/datasecurity/MaskingAlgorithmServiceTest.java
server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/MaskingAlgorithmController.java
server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/MaskingAlgorithmService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/model/MaskingAlgorithm.java

type-bug
Do not trust user-input `MaskingAlgorithm` when test masking algorithm.
Fixes #986 
```docs
```

fix(data-security): test masking algorithm may lead to security issue

---

server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/PodParam.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/dispatch/ImmediateJobDispatcher.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/JobCallerBuilder.java

module-task framework
type-feature
1. support set request cpu/mem/diskSize/mountPath param for pod
Fixes #
```docs
```

feat(taskframework): support set request cpu/mem/diskSize/mountPath param for pod

---

pom.xml
server/integration-test/src/test/java/com/oceanbase/odc/service/integration/HttpOperationServiceTest.java
server/integration-test/src/test/java/com/oceanbase/odc/service/integration/model/ApprovalPropertiesTest.java
server/integration-test/src/test/resources/integration/approval_integration_template.yaml
server/odc-common/pom.xml
server/odc-common/src/main/java/com/oceanbase/odc/common/json/JsonUtils.java
server/odc-common/src/test/java/com/oceanbase/odc/common/json/JsonUtilsTest.java
server/odc-service/src/main/java/com/oceanbase/odc/service/integration/HttpOperationService.java

type-bug
module-integration
In ODC 4.2.3, if the response of external system is:
```json
{
"company": {
"employee": [
{
"id": "1",
"name": "John Doe",
"department": "Engineering",
"skills": {
"skill": [
"Java",
"Python",
"SQL"
]
}
},
{
"id": "2",
"name": "Jane Smith",
"department": "Marketing",
"skills": {
"skill": [
"Marketing Strategy",
"Communication",
"Analytics"
]
}
}
]
}
}
```
Then we cannot deal with the array, because I have not use `ExpressionParser` in a right way and only support use SpEL like `[company][employee]`. In this PR, I fix it. And you can use SpEL like `company.employee[0].skills.skill[1]` which is easier for common user.
By the way, I refine the `xmlToJson` and `jsonToXml` methods by using `org.json`, and the dependency `jackson-dataformat-xml` is removed. Bucause …

fix(integration): cannot deal with array when parsing json or xml response

---

server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/JobMetaFactory.java

type-bug
The current task connection pool size is determined by the number of task threads, but in scenarios where the number of threads is configured to be small, there may be a problem of insufficient connections causing the task to freeze.
Fixes #1033
```docs
```

fix(dlm):task cannot be executed due to insufficient connections

---

server/odc-migrate/src/main/resources/migrate/common/R_2_0_0__initialize_version_diff_config.sql
server/odc-service/src/main/java/com/oceanbase/odc/service/feature/VersionDiffConfigService.java

type-bug
add `sys_refcursor` data type for oracle mode
Fixes #240 
```docs
```

fix(pl): no sys_refcursor shown in return type select panel when creating function

---

libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/parser/listener/MysqlModeSqlParserListener.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/parser/listener/OracleModeSqlParserListener.java

type-bug
The parser doesn't distinguish `desc/describe` and `explain` types given that they are synonyms. However, the sql console rule 'allow-sql-types' involves both `desc` and `explain`. The result is that the `desc` will not work forever because the parser considers `desc` as `explain`.
This PR distinguish `desc/describe` with `explain`.
Fixes #775 
```docs
```

fix(sql-rule): the sql type 'desc' does not work in the allow-sql-types rule

---

server/odc-service/src/main/java/com/oceanbase/odc/service/resultset/DumperResultSetExportTaskManager.java

type-bug
There is no result-set export log printed in ODC. This is because the DumperResultSetExportTaskManager#logDir is a global variable, but it's been used as a private variable.
So the logDir will be generated for every taskId.
Fixes https://github.com/oceanbase/odc/issues/1016

fix(result-export): there is no log printed for result export task

---

server/odc-service/src/main/java/com/oceanbase/odc/service/session/util/SchemaExtractor.java
server/odc-service/src/test/java/com/oceanbase/odc/service/session/SchemaExtractorTest.java

type-bug
When checking if the sql accesses the database that the current user doesn't have permission in the team space sql console, I didn't consider dblink, which would cause the user to execute sql with dblink like `SELECT * FROM DB1.TB1@DBLINK1` because we detected that the current user doesn't have permission to DB1, however this could be wrong given that DB1 may belong to another datasource.
The solution is that we do not extract schema if the sql contains dblink when detecting the database permission.
Fixes #217 
```docs
```

fix(sql-rule): cannot execute sqls with dblink in team space's sql console

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java

type-bug
Project participants who have datasource management permissions can create databases and assign them to the project. This PR restricts that only DBA and OWNER could add databases to the project.
Fixes #1094 
```docs
```

fix(project): project participants can create database and add them into the project

---

server/odc-core/src/main/java/com/oceanbase/odc/core/shared/model/TraceSpan.java
server/odc-core/src/test/java/com/oceanbase/odc/core/sql/util/FullLinkTraceUtilTest.java
server/odc-service/src/main/java/com/oceanbase/odc/service/diagnose/fulllinktrace/JaegerConverter.java

type-bug
When downloading a json file of full-link-trace, the tags are always empty.
This is because some internal classes in `JaegerConverter` do not have getter methods.
Fixes #1002

fix(full-link-trace): no tags and references in downloaded json file

---

server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/project/ProjectService.java

type-bug
The project owner can remove all project DBAs from the project, then the project has no DBAs any more which violates our design.
The root cause is that the delete method doesn't involve a transaction, so when the exception throws the delete operation doesn't rollback.
Fixes #1064  #1065 
```docs
```

fix(project): the project owner can remove all project dbas from the project

---

server/odc-service/src/main/java/com/oceanbase/odc/service/flow/ApprovalPermissionService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/iam/ResourceRoleService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/iam/UserService.java

type-bug
Listing all tickets returned empty in the individual space, because when listing current user project roles, we do not query by organization_id, then in individual space we obtain the user's team space's resource roles which cause the logic error.
When listing resource roles, add organization_id into query condition.
Fixes #893 
```docs
```

fix(ticket): list all tickets returns empty in individual space

---

server/odc-service/src/main/java/com/oceanbase/odc/metadb/flow/FlowInstanceViewSpecs.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java

type-bug
1. When the user lists tickets in some specific projects, it shows tickets for all projects. The root cause is bad code which doesn't filter project_id;
2. Users cannot see auto-approval tickets in 'all-tickets' option. The root cause is a SQL logic error.
Fixes #998 #1037
```docs
```

fix(ticket): tickets not filtered by projects

---

server/plugins/connect-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/connect/mysql/MySQLInformationExtension.java

type-bug
module-connect-plugin
fix `VersionUtils#compareVersions` method throws ` java.lang.NumberFormatException.forInputString`  exception when there is "-" in DBVersion String.
Fixes #1109
```docs
```

fix(connect-plugin): failed to connect to native percona mysql datasource when there is "-" in DBVersion String

---

server/odc-service/src/main/java/com/oceanbase/odc/metadb/flow/UserTaskInstanceRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/ApprovalPermissionService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/shadowtable/ShadowTableComparingService.java

type-bug
Shadow table sync tickets should be seen by creators and approvers but after the tickets are approved by the approval, it would occur an error when the approver clicks the ticket again.
The root cause is that when we query approval candidates, we use 'EXECUTING' status to filter the approval instances, but not filter the 'APPROVED' approval instances.
This PR changed the method signature and could list both approving and approved approval instances.
Fixes #1048 
```docs
```

fix(ticket): approvers viewing shadow table sync ticket fails after the ticket is approved/rejected

---

server/odc-service/src/main/java/com/oceanbase/odc/service/resultset/ResultSetExportTask.java

type-bug
If export result set in excel format, you will get a xlsx file with no data.
This is caused by setting file path incorrectly.
Fixes #1129

fix(result-set-export): there is no data in exported xlsx file

---

server/odc-service/src/main/java/com/oceanbase/odc/config/HookConfiguration.java
server/odc-service/src/main/java/com/oceanbase/odc/metadb/collaboration/ProjectRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/metadb/connection/DatabaseRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/iam/ResourceRoleService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/iam/UserService.java

type-bug
module-project
When deleting users, we do not verify if they are project members which may cause the problem that some project doesn't have any OWNER after deletion, then nobody could assign a new OWNER to this project because only OWNER could assign project roles.
This PR adds a pre-delete-user hook to detect if the deleting user still joins some project, if yes then reject the operation.
Fixes #922 
```docs
```

fix(project): could delete users who are currently joining projects

---

server/odc-core/src/main/resources/i18n/BusinessMessages.properties
server/odc-core/src/main/resources/i18n/BusinessMessages_zh_CN.properties
server/odc-core/src/main/resources/i18n/BusinessMessages_zh_TW.properties
server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBTableService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/db/model/UpdateTableDdlCheck.java

type-bug
module-Database object
Provide relevant prompts to users for high-risk operations such as index changes when generate update table ddl. Three situations are currently distinguished：
- The generated change SQL involves create index
- The generated change SQL involves drop index
- The generated change SQL involves create and drop index
Fixes #1142
```docs
```

fix(database-object) :Provide relevant prompts to users for high-risk operations when drop or create index

---

server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DlmLimiterService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/AbstractDlmJobPreprocessor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/DataArchivePreprocessor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/DataDeletePreprocessor.java

type-bug
Fixed the problem of incomplete information display after task editing.
Fixes #
```docs
```

fix(dlm):displays incomplete information after editing

---

.idea/codeStyles/Project.xml
server/odc-service/src/main/java/com/oceanbase/odc/service/integration/ExternalSqlInterceptor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/regulation/ruleset/SqlConsoleRuleService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/regulation/ruleset/model/Rule.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/ConnectConsoleService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/interceptor/SqlCheckInterceptor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/interceptor/SqlConsoleInterceptor.java

type-bug
This PR fixed several bugs:
- if the sql is intercepted by sql-console rules, then sql-check rules will not be checked;
- make the rule 'max-execute-sql-size' apply to the last sql;
- when the rule 'allow-execute-sql-type' value is empty, users could execute any type of sqls;
- when quering data, make sql-console rules not take effect;
Fixes #1159 #1162 #1166
```docs
```

fix(sql-rule): several sql interception bugs

---

server/integration-test/src/test/java/com/oceanbase/odc/service/onlineschemachange/DBUserLogStatusMonitorTest.java
server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/OdcConstants.java
server/odc-core/src/main/java/com/oceanbase/odc/core/shared/rest/OdcRestTemplate.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/DefaultOnlineSchemaChangeTaskHandler.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/OnlineSchemaChangeContextHolder.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/OnlineSchemaChangeFlowableTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/ddl/DdlConstants.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/model/OnlineSchemaChangeParameters.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/monitor/DBUserLogStatusMonitor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/monitor/DBUserLogStatusMonitorFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/monitor/DBUserMonitorExecutor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/pipeline/BaseCreateOmsProjectValve.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/pipeline/SwapTableNameValve.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/OnlineSchemaChangeCompleteJob.java

type-bug
1. after`OnlineSchemaChangeFlowableTask` started and executing,  thread  should be wait unit all osc schedule task completed, on `onProgressUpdate` method persist to update task status,   thread executing in `onProgressUpdate` will notify the task started thread.
2. when task percentage or status is changed, then update task
3. fix finalTableDdl for alter sql type
Fixes #
```docs
```

fix(osc): osc log is not show totally and  flow task is done unnormally

---

server/odc-service/src/main/java/com/oceanbase/odc/service/partitionplan/PartitionPlanService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/partitionplan/model/DatabasePartitionPlan.java

type-feature
The partition plan does not support configuring scheduling time currently. For OB data sources, deleting partitions will cause global index failure. If executed during peak business periods, it may cause performance problems. Therefore, it is necessary to support custom scheduling time to ensure that partition deletion operations are performed during low business periods.
Fixes #
```docs
```

feat(partition-plan):support setting scheduling strategy

---

server/odc-service/src/main/java/com/oceanbase/odc/config/MetaDBConfiguration.java
server/odc-service/src/main/java/com/oceanbase/odc/config/druid/DruidMonitorAspect.java

fix druid stats may merge sql error by use oceanbase dbType, use mysql parser instead.
Fixes #
```docs
```

fix(monitor): druid stats use mysql parser

---

server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/ErrorCodes.java
server/odc-core/src/main/resources/i18n/ErrorMessages.properties
server/odc-core/src/main/resources/i18n/ErrorMessages_zh_CN.properties
server/odc-core/src/main/resources/i18n/ErrorMessages_zh_TW.properties
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/DatabaseSyncSchedules.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java

type-bug
This PR optimizes error message of synchronizing databases failure.
Fixes #773 
```docs
```

fix(database): optimize error message of synchronizing databases failure

---

server/odc-server/src/main/resources/config/application.yml
server/odc-service/src/main/java/com/oceanbase/odc/config/MetaDBConfiguration.java
server/odc-service/src/main/java/com/oceanbase/odc/config/druid/DruidMonitorAspect.java

remove default druid merge sql
Fixes #
```docs
```

fix(monitor):fix druid stats parser error

---

server/odc-core/src/main/java/com/oceanbase/odc/core/alarm/AlarmEventNames.java
server/odc-core/src/main/java/com/oceanbase/odc/core/shared/rest/OdcRestTemplate.java
server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/GlobalExceptionHandler.java
server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/RestExceptionHandler.java
server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v1/HeartbeatController.java

add api unknown error alam and restApi error alarm
Fixes #
```docs
```

feat(monitor):add api alarm

---

server/odc-service/src/main/java/com/oceanbase/odc/service/flow/model/FlowNodeInstanceDetailResp.java
server/odc-service/src/main/java/com/oceanbase/odc/service/permissionapply/project/ApplyProjectFlowableTask.java

type-bug
The execution deadline of a timed task is displayed incorrectly and this PR fix it.
Fixes #1236 
```docs
```

fix(apply-project): failed to set mdc value

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionService.java

type-bug
After I upgraded ODC from V4.1.2 to V4.2.2, I encountered an error message that said 'duplicate data source name' when was creating a team space's data source however I did not create any team space's data source before.
The root cause is that private connection migration happens when each user logs in. When we create a data source, ODC will check if the data source name is occupied in the current organization, and it is possible that the user actually has a private connection with the same name and this user has not logged in yet. Then the name occupation check will fail.
In this PR, I added the VisibleScope.ORGANIZATION into condition when checking data source name duplication. In this way, even if there exists a private connection that has not been migrated yet, it will not …

fix(datasource): it occurs 'duplicate data source name' error when creating a data source in team space

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/PartitionPlanJob.java

type-bug
When the partition plan task is executed, disabled partition plans are not filtered out, which will cause the paused partition plan to become invalid.
Fixes #1234
```docs
```

fix(partition plan):failed to disable table partition plan

---

server/plugins/schema-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/schema/obmysql/parser/OBMySQLGetDBTableByParser.java
server/plugins/schema-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/schema/oboracle/parser/OBOracleGetDBTableByParser.java

type-bug
module-database object
remove identifiers before set partition name 
Fixes #1244
```docs
```

fix(schema-plugin): show partition name with identifiers

---

server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java

type-bug
Project "pending approval" tickets shows other project's "pending approval" tickets.
The root cause is query condition lacks project_id.
Fixes #1259 
```docs
```

fix(ticket): project "pending approval" tickets shows other project's "pending approval" tickets

---

server/odc-service/src/main/java/com/oceanbase/odc/config/jpa/EnhancedJpaRepository.java

fix batch create ps not close
Fixes # https://github.com/oceanbase/odc/pull/1183
```docs
```

fix(flow): close prepared stmt and resultset when batch creating end

---

server/odc-service/src/main/java/com/oceanbase/odc/service/flow/util/FlowTaskUtil.java

type-bug
the data-mocker can not recognize the charset key of 'UTF8'
Fixes #1269 
```docs
```

fix(mock-data): failed to recognize the charset key of 'UTF8'

---

server/odc-core/src/main/java/com/oceanbase/odc/core/alarm/AlarmService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/common/DruidMonitor.java

format alarm error stack to inline, BTW, fix lastErrorTime type to Object
Fixes #
```docs
```

fix(monitor): format alarm error stack to inline

---

server/integration-test/src/test/java/com/oceanbase/odc/service/resultset/DumperResultSetExportTaskManagerTest.java
server/odc-service/src/main/java/com/oceanbase/odc/service/resultset/DumperResultSetExportTaskManager.java
server/odc-service/src/main/java/com/oceanbase/odc/service/resultset/ResultSetExportTask.java
server/plugins/task-plugin-api/src/main/java/com/oceanbase/odc/plugin/task/api/datatransfer/model/DataTransferConfig.java
server/plugins/task-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/task/mysql/datatransfer/job/TransferJobFactory.java
server/plugins/task-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/task/mysql/datatransfer/job/datax/ConfigurationResolver.java
server/plugins/task-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/task/mysql/datatransfer/job/datax/DataXTransferJob.java
server/plugins/task-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/task/mysql/datatransfer/job/datax/GroovyMaskRuleGenerator.java
server/plugins/task-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/task/mysql/datatransfer/job/datax/model/parameter/MySQLReaderPluginParameter.java
server/plugins/task-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/task/mysql/datatransfer/job/datax/model/parameter/MySQLWriterPluginParameter.java

type-bug
1. when import csv file with blank spaces in filename like 'da ta.csv', thie URL#getFile will get 'da%20da.csv', causing FileNotFoundException. So I use URL#toUri instead. 
2. there are some bugs in result-set-export for mysql datasource , I fixed them...
Fixes #1271 #1268

fix(result-export): failed to export mysql data

---

pom.xml
server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMConfiguration.java

type-bug
Fixed an issue where monitoring logs were routed to non-specified files.
Fixes #1295
```docs
```

feat(dlm): upgrade dlm's version to 1.0.8

---

pom.xml
server/odc-migrate/src/main/resources/migrate/common/V_4_2_3_5__delete_system_config.sql
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/model/MockProperties.java

Increase the max number of the mock data to 100 million
Fixes #1297 
```docs
```

feat(mock-data): increase the max number of the mock data to 100 million

---

server/odc-migrate/src/main/resources/migrate/common/V_4_2_3_10__adjust_sql_console_rules.sql

type-bug
The rule 'allow-sql-types' of the dev environment is disabled by default. The root cause is that the default value was wrongly set to disabled in ODC V4.2.0.
This PR corrects it to 'enabled' if this rule is not edited by users.
Fixes #1301 
```docs
```

fix(sql-rule): the rule 'allow-sql-types' of dev environment is disabled by default

---

script/functions.sh

build: fix local rpm build failed due wrong copy obclient logic

---

server/integration-test/src/test/java/com/oceanbase/odc/service/cloud/config/ObjectStorageConfigurationTest.java
server/odc-server/src/main/resources/data.sql
server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/cloud/CloudResourceConfigurations.java
server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/cloud/CloudResourceService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/cloud/model/CloudObjectStorageProperties.java
server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/cloud/model/DefaultCloudEnvConfigurations.java
server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/cloud/model/ObjectStorageConfiguration.java
server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/cloud/model/OssConfiguration.java

module-objectstorage
Support internal-endpoint in cloud storage configuration. If internal-endpoint is set, then it will use internal-endpoint; otherwise, it will use public-endpoint.
Fixes #
```docs
```

enhancement: add internal-endpoint for cloud storage configuration

---

server/odc-migrate/src/main/resources/migrate/common/V_3_2_3_2__add_configuration.sql

type-refactor
delete the configuration that not in use.
Fixes #
```docs
```

refactor: delete unused configuration

---

server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowTaskInstanceService.java

type-bug
module-database change task
Fixes #1315 
```docs
```

fix(database-change): query task details throw file not found exception

---

server/integration-test/src/test/java/com/oceanbase/odc/service/iam/UserServiceTest.java
server/odc-service/src/main/java/com/oceanbase/odc/metadb/flow/UserTaskInstanceRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/metadb/iam/RoleRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/ApprovalPermissionService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/iam/UserService.java

type-bug
module-ticket
When a project OWNER query the details of a database change task created by a SQL plan, then not found exception will be thrown. 
The root cause is that ODC will judge the user permission, the current user must be the creator or approver for this task, otherwise the task will not be readable. But in the latest ODC, the owner can view all tickets. This PR fix it by add a judgement: if the current user is OWNER of the project, then will skip auth.
By the way, there is a unauthorized issue in method `ApprovalPermissionService#getApprovableApprovalInstances()` and this PR fix it.
Fixes #1326
```docs
```

fix(database-change): query task details throw flow instance not found exception

---

pom.xml
server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DataSourceInfoBuilder.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/AbstractDlmJobPreprocessor.java

type-feature
1. Upgrade DLM SDK version to 1.0.9
2. DLM supports sharding using unique indexes
Fixes #
We have to wait until the SDK is released before merging.
```docs
```

feat(dlm):supports sharding using unique indexes

---

server/integration-test/src/test/java/com/oceanbase/odc/service/task/JobSchedulerTest.java
server/odc-server/src/main/resources/data.sql
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowableAdaptorImpl.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/factory/FlowFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/mapper/OdcRuntimeDelegateMapper.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/PodParam.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/DefaultJobConfiguration.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/DefaultSpringJobConfiguration.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/JobConfiguration.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/TaskFrameworkProperties.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/constants/JobEnvConstants.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/dispatch/ImmediateJobDispatcher.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/enums/TaskRunModeEnum.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/context/JobContextProviderFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/DefaultJobImageNameProvider.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/JobImageNameProvider.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/ServiceNameHostUrlProvider.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/StdJobScheduler.java

type-feature
add pod config to meta  db, contains:  imageName , pod cpu/memory request and limit 
Fixes #
```docs
```

feat(taskframework): add pod config in meta-db and task legacy run model

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataArchiveDeleteJob.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataArchiveRollbackJob.java

type-bug
Fix the problem that the log file does not exist.
Fixes #
```docs
```

fix(dlm): the task log file does not exist

---

pom.xml
server/odc-service/src/main/java/com/oceanbase/odc/service/encryption/EncryptionService.java

type-security
1. upgrade aliyun-oss-sdk version to 3.17.3 to avoid potential security issues.
2. add @SkipAuthorize annotation to indicate that it is no need to check authority on this method.
Fixes #
```docs
```

security: upgrade aliyun-oss-sdk version

---

pom.xml

type-feature
Upgrade DLM SDK version to 1.0.10.
Fixes #
```docs
```

feat(dlm):upgrade SDK to 1.0.10

---

pom.xml

type-bug
odc will shutdown mock data task when mock task is succeed or failed and mock data task will set status when upload operation is not completed, so that the upload operation will be interrupted.
Fixes #
```docs
```

fix(mock-data): failed to upload file to oss

---

server/odc-service/src/main/java/com/oceanbase/odc/metadb/iam/UserRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/service/common/util/WebRequestUtils.java

module-iam
add `updateUsernameById` method in `UserRepository`
Fixes #
```docs
```

enhancement: add update username method in UserRepository

---

server/odc-service/src/main/java/com/oceanbase/odc/service/flow/instance/FlowTaskInstance.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/BaseRuntimeFlowableDelegate.java

type-bug
add null checking
Fixes #
```docs
```

fix(flow): can not set task status correctly when creating task concurrently

---

server/odc-service/src/main/java/com/oceanbase/odc/service/iam/auth/CustomAuthenticationFailureHandler.java
server/odc-service/src/main/java/com/oceanbase/odc/service/info/InfoAdapter.java
server/odc-service/src/main/java/com/oceanbase/odc/service/info/OdcInfo.java
server/odc-service/src/main/java/com/oceanbase/odc/service/info/OdcInfoService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/integration/model/LdapContextHolder.java
server/odc-service/src/main/java/com/oceanbase/odc/service/integration/oauth2/SSOTestInfo.java
server/odc-service/src/main/java/com/oceanbase/odc/service/integration/oauth2/TestLoginManager.java
server/starters/web-starter/src/main/java/com/oceanbase/odc/service/iam/auth/ldap/LdapAbstractTestLoginAuthenticationFilter.java
server/starters/web-starter/src/main/java/com/oceanbase/odc/service/iam/auth/ldap/LdapSecurityConfigureHelper.java
server/starters/web-starter/src/main/java/com/oceanbase/odc/service/info/WebInfoAdapter.java

Frontend-Backend integration testing fix.
rewrite isSSoLoginEnabled and add ssoLoginType into `OdcInfo`, add testRegistrationId into  `SSOTestInfo`
Fixes #
```docs
```

fix(sso): frontend-backend integration testing fix

---

server/integration-test/src/test/java/com/oceanbase/odc/service/flow/FlowableAdaptorTest.java
server/odc-service/src/main/java/com/oceanbase/odc/metadb/flow/NodeInstanceEntityRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowableAdaptorImpl.java

The setFlowableElements method is called at new creation, when there is no data in the database. 
remove unnecessary flow_instance_node query
Fixes #
```docs
```

fix(flow):remove unnecessary flow_instance_node query

---

server/integration-test/src/test/java/com/oceanbase/odc/service/datatransfer/DataTransferServiceTest.java
server/odc-service/src/main/java/com/oceanbase/odc/service/datatransfer/DefaultDataTransferAdapter.java
server/odc-service/src/main/java/com/oceanbase/odc/service/datatransfer/task/DataTransferTask.java

type-feature
Now we would compress export output to zip format no mater on the web mode or the client mode.
However, the zip format supports up to 4GB of compressed data. And we don't have a limit on exporting data size in the desktop version. So in the client mode, we will not compress it.
Feat #829

feat(data-transfer): not compress export output in client mode

---

server/odc-service/src/main/java/com/oceanbase/odc/service/permission/database/DatabasePermissionHelper.java

type-bug
module-database permission control
The front-end list database by the database permission. But in individual space, user holds no DB permission in the metaDB or from project members. So user may "has no permission for databases". This PR fix it by fill-in all database permission for databases in individual space.
Fixes #1466 
Self-test Passed!
```docs
```

fix(database-permission): User holds no db permission in personal space

---

pom.xml
server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/NativeK8sJobClient.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/ScheduleTaskResultHandleService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/TaskTaskResultHandleService.java

type-bug
security scan hole 
1. upgrade kubernetes-client.version to 19.0.0 which dependency com.squareup.okio:okio-jvm upgrade to 4.11.0
2. ScheduleTaskResultHandleService/TaskTaskResultHandleService add @SkipAuthorize
```docs
```

fix(taskframework):  lower k8s client version cause security problem

---

server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/PreCheckRuntimeFlowableTask.java

type-bug
module-pre check
A small bug, this PR fix it.
Fixes #1469 
```docs
```

fix(pre-check): load uploaded files failed

---

server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java

type-bug
There is a bug caused by #1439 ,this PR fix it.
Fixes #1477 
```docs
```

fix(flow): NPE when creating a ticket without connection information

---

server/odc-service/src/main/java/com/oceanbase/odc/service/audit/AuditEventAspect.java

type-bug
module-doc
module-audit
This issue is related to the table `audit_event` in ODC metadb. When executing a SQL, ODC will record this SQL in audit_event. However, in this test case, audit_event's character_set is set to GBK as we don't explicitly set default charset while creating the table and the `character_set_database` variable is GBK, so while inserting a rare word in the format of utf8 into a GBK table, the observer will return an error 'Incorrect String value'. If the `audit_event`'s charset is utf8, this problem is resolved.
So the root cause is that ODC metadb's default charset was set to GBK. And even if the audit module bypasses the problem, it will still happen in other scenarios, like creating datasources with a rare word name. So we have two actions here and this PR …

fix(audit): executing sql with rare words failed when metadb's default character is GBK

---

server/integration-test/src/test/java/com/oceanbase/odc/service/flow/FlowInstanceServiceTest.java
server/odc-migrate/src/main/resources/migrate/common/V_4_2_3_15__add_flow_instance_index.sql
server/odc-migrate/src/main/resources/migrate/common/V_4_2_4_5__add_flow_instance_index.sql
server/odc-service/src/main/java/com/oceanbase/odc/metadb/flow/FlowInstanceRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/metadb/flow/ServiceTaskInstanceRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/factory/FlowResponseMapperFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/model/FlowNodeStatus.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java

optimize flow query and add index to flow related table
BTW, pick https://github.com/oceanbase/odc/pull/1402 and https://github.com/oceanbase/odc/pull/1383 from branch 4.2.x 
Fixes #
```docs
```

perf(flow): optimize performance for flow instances query

---

server/odc-service/src/main/java/com/oceanbase/odc/service/partitionplan/PartitionPlanService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java

…d trigger does not exist.
type-bug
When deleting the operation, currently the Trigger is used to find the associated job and delete it. If the Trigger does not exist, the expected job deletion cannot be achieved.
Fixes #
```docs
```

fix(partition-plan):delete job failed if the associated trigger does not exist

---

script/start-job.sh
server/integration-test/src/test/java/com/oceanbase/odc/service/task/ProcessModeTest.java
server/odc-common/src/main/java/com/oceanbase/odc/common/util/SystemUtils.java
server/odc-server/src/main/resources/log4j2.xml
server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/ExecutorProcessBuilderFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/JobEnvironmentFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/ProcessJobCaller.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/util/JobUtils.java

type-bug
1. fix `java -jar` command start odc executor by odc job
2. fix command `SystemUtils#isProcessRunning` 
3. start odc executor set memory properties `-Xms1024m`
Fixes #
1. test in linux on mac ok
2. windows should be test again
```docs
```

fix(taskframework): start process failed when local odc server start by java -jar

---

server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowTaskInstanceService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/logger/LoggerService.java

type-reactor
reactor add LoggerService for DLM query log
Fixes #
```docs
```

refactor(taskframework): add LoggerService for DLM query log

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionEnvironmentAdapter.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/OBInstanceType.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/OBTenant.java

type-bug
This PR adapt cloud serverless instance: 
- add `OBInstanceType` enums;
- delete useless fastjson annotations;
Fixes #
```docs
```

fix(cloud): serverless instance adaption

---

server/integration-test/src/test/java/com/oceanbase/odc/service/onlineschemachange/ddl/TableNameReplacerTest.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/DefaultOnlineSchemaChangeTaskHandler.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/ddl/OBMysqlTableNameReplacer.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/ddl/OBOracleTableNameReplacer.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/ddl/OscFactoryWrapper.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/ddl/OscFactoryWrapperGenerator.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/ddl/TableNameReplacer.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/model/OnlineSchemaChangeParameters.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/subtask/SubTaskParameterFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/validator/OnlineSchemaChangeValidator.java

type-bug
`
CREATE TABLE "YAOBIN"."COUNTRY8" (
"ID" NUMBER,
"NAME" VARCHAR2(255),
CONSTRAINT "PERSON_COUNTRY_PK2211333" PRIMARY KEY ("ID")
)
;
CREATE  INDEX IDX_COUNTRY_NAME11121 ON COUNTRY8(NAME);
`
support user input  create index  sql after create ddl in ob oracle model .
Fixes #
```docs
```

fix(osc): support create index sql in ob oracle 

---

server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/ErrorCodes.java
server/odc-core/src/main/resources/i18n/ErrorMessages.properties
server/odc-core/src/main/resources/i18n/ErrorMessages_zh_CN.properties
server/odc-core/src/main/resources/i18n/ErrorMessages_zh_TW.properties
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/OscService.java

type-bug
When user has click `swap table` button, and click aggin, return hint `Swap table has started`
```docs
```

fix(osc): fix i18n hint when user started swap table

---

server/odc-service/src/main/java/com/oceanbase/odc/service/flow/util/FlowTaskUtil.java

type-bug
this issue is involved by this pr #1494 
and this pr set an error dialect type when ob-mysql
Fixes #
```docs
```

fix(mock-data): failed to mock any data for ob-mysql mode

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionEnvironmentAdapter.java

type-bug
Fix get cloud tenant/serverless instance logic. We directly get the instance type from obcloud instead of judging by ourselves.
Fixes #
```docs
```

fix(cloud): tenant/serverless instance test connection failed in some specific scenery

---

server/odc-test/src/main/java/com/oceanbase/odc/test/database/TestDBConfigurations.java
server/plugins/connect-plugin-doris/src/test/java/com/oceanbase/odc/plugin/connect/doris/BaseExtensionPointTest.java
server/plugins/connect-plugin-doris/src/test/java/com/oceanbase/odc/plugin/connect/doris/DorisExtensionTest.java

Enhancement the unit test framework.
Fixes #1598 
```docs
```

enhancement(unit-test): on-demand loading of unit test dependent data sources

---

server/odc-service/src/main/java/com/oceanbase/odc/service/notification/DingTalkSender.java
server/odc-service/src/main/java/com/oceanbase/odc/service/notification/FeishuSender.java
server/odc-service/src/main/java/com/oceanbase/odc/service/notification/HttpSender.java
server/odc-service/src/main/java/com/oceanbase/odc/service/notification/WeComSender.java
server/odc-service/src/main/java/com/oceanbase/odc/service/notification/helper/MessageResponseValidator.java
server/odc-service/src/main/java/com/oceanbase/odc/service/notification/model/WebhookChannelConfig.java

type-feature
ODC allows users to configure webhook channels. But the previous HTTP requests were built-in and had lower usability.
In this PR, we support user to input custom http header / body / response validation for webhook channel.

feat(notification): support custom http request for wehbook channel

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataArchiveJob.java

type-bug
Create target table failed because of  invalid cursor position
Fixes #
```docs
```

fix(dlm):create target table failed

---

server/odc-core/src/main/resources/i18n/BusinessMessages.properties
server/odc-core/src/main/resources/i18n/BusinessMessages_zh_CN.properties
server/odc-core/src/main/resources/i18n/BusinessMessages_zh_TW.properties

PL debug on OceanBase maybe a high-level risk action, so I updated the description of this rule.
Fixes #1339
```docs
```

enhancement(sql-rule): optimize the rule 'not-allow PL debug''s description

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java

type-bug
module-database permission
When a data source is deleted, then the related database permission records should be deleted. This PR just do it.
Fixes #1618 
```docs
```

fix(database-permission): delete related permission records when deleting data source

---

server/integration-test/src/test/java/com/oceanbase/odc/service/dlm/DLMServiceTest.java
server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/DLMController.java
server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/model/GetRealSqlListReq.java
server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/model/PreviewSqlStatementsReq.java

type-feature
It is currently impossible to view the filtering conditions after ODC parsing when creating a dlm task, and there is a certain risk. This PR provides a SQL preview function to help customers understand the SQL to be executed.
Fixes #
```docs
```

feat(dlm): supports review sql

---

server/odc-migrate/src/main/resources/init-config/init/notification-policy-metadata.yaml
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DatabaseChangeRuntimeFlowableTaskCopied.java
server/odc-service/src/main/java/com/oceanbase/odc/service/notification/helper/EventBuilder.java
server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/OdcTriggerListener.java
server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/config/QuartzConfiguration.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/JobSchedulerFactoryBean.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/listener/JobTerminateNotifyListener.java

type-feature
Since DLM-related tasks are scheduled by the task framework, there was no adaptation of notifications before. Therefore, the adaptation of this function is completed in this PR.
In addition, it supports sending "scheduling failed" notification when job is misfired.
Fixes #
#1539 #1540

feat(notification): support scheduling failed and task terminated

---

server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/ErrorCodes.java
server/odc-core/src/main/resources/i18n/ErrorMessages.properties
server/odc-core/src/main/resources/i18n/ErrorMessages_zh_CN.properties
server/odc-core/src/main/resources/i18n/ErrorMessages_zh_TW.properties
server/odc-service/src/main/java/com/oceanbase/odc/service/config/UserConfigService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/OdcStatementCallBack.java
server/odc-service/src/main/resources/config-meta/user-config-meta.yml

type-bug
fix some problems foudn during debug.
1. The value for language modification doesn't match between frontend and backend: the frontend uses hyphens (-), while the backend employs underscores (_). For example, if the frontend sets 'en-US', the corresponding backend locale value would be 'en_US'.
2. fter reverting to default configurations, the shortcut keys are not F8 and F9.
3. When End-to-end TRACE is turned off, it indeed becomes inaccessible; however, the prompt message still reads "Full-stack tracing is only available on OceanBase versions higher than 4.0." This should be modified to state that "Full link trace is currently not enabled."
4. There's an error where the default value for continuing execution after an error is incorrect: it should be False but currently is set to …

fix(config): wrong reason while full link trace not enabled

---

server/odc-service/src/main/java/com/oceanbase/odc/service/config/UserConfigFacadeImpl.java
server/odc-service/src/main/java/com/oceanbase/odc/service/config/UserConfigService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/snippet/BuiltinSnippet.java
server/odc-service/src/main/java/com/oceanbase/odc/service/snippet/BuiltinSnippetService.java
server/odc-service/src/main/resources/builtin-snippet/ob-mysql-3.x-snippet.yml
server/odc-service/src/main/resources/builtin-snippet/ob-mysql-4.x-snippet.yml
server/odc-service/src/main/resources/builtin-snippet/ob-sys-snippet.yml

type-feature
more builtin snippets.
and fix a snippet match logic error for sys tenant scenario.
Fixes #
```docs
```

feat(snippet): more builtin snippets

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/AbstractDlmJob.java

type-bug
The bean should only be obtained if the task framework is enabled.
Fixes #
```docs
```

fix(dlm):job scheduler not found

---

server/odc-migrate/src/main/resources/migrate/common/V_4_2_4_12__update_task_framework_enabled.sql
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/mapper/OdcRuntimeDelegateMapper.java

1. enable taskframework in migrate
2. remove database change in `OdcRuntimeDelegateMapper`
Fixes #
```docs
```

fix(taskframework): enable taskframework default

---

server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java

type-bug
This PR(#1578) cause a bug that cannot create a database change task in private space. The root cause is that flow instance created in private space has no PreCheck task. This PR just fix it.
Fixes #1693 
```docs
```

fix(database-change): create database change task failed in private sapce

---

server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/partitionplan/mapper/CellDataProcessors.java
server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/partitionplan/mapper/OBMySQLTimeDataTypeProcessor.java
server/plugins/task-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/task/oboracle/partitionplan/mapper/OBOracleDateTypeProcessor.java
server/plugins/task-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/task/oboracle/partitionplan/mapper/OBOracleTimestampTypeProcessor.java

type-bug
avoid npe when input sql expression is invalid. as you can see, if we input an invalid sql expression, the execution result of this expr is null:
Fixes #
```docs
```

fix(partition-plan): npe will be thrown when input is invalid

---

server/odc-service/src/main/java/com/oceanbase/odc/service/partitionplan/PartitionPlanScheduleService.java

type-feat
disable the previous flow instance when a partition plan is related to an exists flow
Fixes #
```docs
```

feat(partition-plan): disable the previous flow instance when a partition plan is related to an exists flow

---

server/integration-test/src/test/java/com/oceanbase/odc/service/notification/NotificationServiceTest.java
server/odc-service/src/main/java/com/oceanbase/odc/metadb/notification/PolicyMetadataEntity.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/PartitionPlanRuntimeFlowableTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/PreCheckRuntimeFlowableTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/model/DatabaseChangeParameters.java
server/odc-service/src/main/java/com/oceanbase/odc/service/notification/NotificationService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/notification/helper/EventBuilder.java
server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/OdcJobListener.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/PartitionPlanJob.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/SqlPlanJob.java

type-bug
Added a parameter `parentTaskType` for `DatabaseChangeParameters`. This is a flag for notification to identify whether a task is a real database change task or not.

fix(notification): failed to send notification for partition plan

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/factory/ScheduleResponseMapperFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/model/ScheduleDetailResp.java

type-bug
Simplified scheduled task return entities.
Fixes #1657
```docs
```

fix(dlm):database not found

---

server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java

type-bug
Fix bug described in #1769, the root cause is a wrong usage of JPA query.
Fixes #1769 
```docs
```

fix(flow): create flow instance failed when environment absent

---

server/odc-common/src/main/java/com/oceanbase/odc/common/crypto/RsaBytesEncryptor.java
server/odc-common/src/test/java/com/oceanbase/odc/common/crypto/RsaBytesEncryptorTest.java
server/odc-service/src/main/java/com/oceanbase/odc/service/encryption/SensitivePropertyHandlerImpl.java

type-bug
This PR fix a concurrcy flaw in `SensitivePropertyHandlerImpl.java` by add double-check.
Fixes #1731 
```docs
```

fix(encryption): sensitive property handler suffers from concurrcy flaw

---

server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/BaseTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/DataArchiveTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/runtime/DatabaseChangeTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/runtime/PreCheckTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/runtime/RollbackPlanTask.java

type-bug
modify `doStart` return boolean to update task status.
Fixes #
```docs
```

fix(taskframework): fix task update final status when completed

---

server/odc-core/src/main/java/com/oceanbase/odc/core/alarm/AlarmEventNames.java
server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/OdcTriggerListener.java

add scheduling failed alarm
Fixes #
```docs
```

fix(alarm): add scheduling failed alarm

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java

type-bug
After using the task framework, we need to use the task framework interface to terminate the task.
Fixes #
```docs
```

fix(dlm): interrupt job failed.

---

server/integration-test/src/test/java/com/oceanbase/odc/service/partitionplan/PartitionPlanScheduleServiceTest.java
server/integration-test/src/test/java/com/oceanbase/odc/service/partitionplan/PartitionPlanServiceV2Test.java
server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/FlowInstanceController.java
server/odc-service/src/main/java/com/oceanbase/odc/service/partitionplan/PartitionPlanScheduleService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/partitionplan/PartitionPlanServiceV2.java
server/odc-service/src/main/java/com/oceanbase/odc/service/partitionplan/model/PartitionPlanDBTable.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/PartitionPlanJob.java

type-feat
Added associated partition configuration information to the return value of the listCandidateTables interface.
I add these additional data for front end's need, so that we can know the detail of each table's partition plan config:
Fixes #
```docs
```

feat(partition-plan): returns partition table configs when list candidate tables

---

server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/AuditEventAction.java
server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/AuditEventType.java
server/odc-core/src/main/resources/i18n/BusinessMessages.properties
server/odc-core/src/main/resources/i18n/BusinessMessages_zh_CN.properties
server/odc-core/src/main/resources/i18n/BusinessMessages_zh_TW.properties
server/odc-migrate/src/main/resources/init-config/default-audit-event-meta.yml
server/odc-service/src/main/java/com/oceanbase/odc/service/audit/AuditEventAspect.java

type-bug
The operations of  the automation module、notification module and sensitive column module , have not been recorded in the  
user operation audit records. This PR adds the audit of these three modules.
Fixes #610

fix(audit): add audit keys and i18n messages for some module 

---

server/odc-service/src/main/java/com/oceanbase/odc/service/logger/LoggerService.java

fix(taskframework): deserialize log occur error from remote 

---

server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java

type-bug
We should retrieve the database ID from the meta database when the operation type is neither 'CREATE' nor 'UPDATE'
Fixes #1640
```docs
```

fix(dlm): check database permission failed

---

server/integration-test/src/test/java/com/oceanbase/odc/service/collaboration/ProjectServiceTest.java
server/integration-test/src/test/java/com/oceanbase/odc/service/connection/DatabaseServiceTest.java
server/integration-test/src/test/java/com/oceanbase/odc/service/iam/ResourceRoleServiceTest.java
server/odc-common/src/main/java/com/oceanbase/odc/common/util/StringUtils.java
server/odc-migrate/src/main/resources/migrate/common/V_4_2_4_16__add_resource_role.yaml
server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/DataBaseController.java
server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/FlowInstanceController.java
server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/IamController.java
server/odc-service/src/main/java/com/oceanbase/odc/metadb/connection/ConnectionEntity.java
server/odc-service/src/main/java/com/oceanbase/odc/metadb/iam/resourcerole/ResourceRoleRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/metadb/iam/resourcerole/UserResourceRoleRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/service/automation/AbstractAutomationEventHandler.java
server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/project/ProjectService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/common/util/PackageValidator.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/model/Database.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/model/GetDatabaseOwnerResp.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/model/ModifyDatabaseOwnerReq.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/model/TransferDatabasesReq.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/model/CreateFlowInstanceReq.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/CreateExternalApprovalTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/iam/ResourceRoleService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/iam/UserService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/iam/model/UserResourceRole.java
server/odc-service/src/main/java/com/oceanbase/odc/service/integration/model/TemplateVariables.java
server/odc-service/src/main/java/com/oceanbase/odc/service/regulation/risklevel/RiskLevelService.java

type-feature
database
Enhanced user roles and approval workflows
Fixes https://github.com/oceanbase/odc/issues/1679
1. Add the owner role to the database, supporting approval workflow to use the owner role of the database.
2. Add variables for integrating external approval.
such as:
database.owner.accounts
database.owner.ids
database.owner.names
database.name
environment.name
task.description
risk.level
odc.task.url
3. Adjust the database permission request form, and split the form when applying for multiple databases.
Additional documentation e.g., usage docs, etc.:

feat(collaboration): support database resource role

---

server/odc-service/src/main/java/com/oceanbase/odc/service/regulation/risklevel/model/RiskDetectRuleCondition.java

type-bug
This PR deleted the i18n of the risk detect rule value. The front-end will directly map the i18n key to i18n value which is also passed by the back-end. Otherwise, when updating the environment, the front-end will pass the i18n value to the server rather than the i18n key.
Fixes #1640
```docs
```

fix(environment): flow instance selects wrong approval flow config after updating risk detect rules

---

server/odc-service/src/main/java/com/oceanbase/odc/service/session/factory/DefaultConnectSessionIdGenerator.java

type-bug
use url base64 encoder or decoder to encode or decode the session id to avoid '/' char.
Fixes #
```docs
```

fix(connect): sometimes open sql console result in 404 error

---

server/integration-test/src/test/java/com/oceanbase/odc/service/flow/FlowInstanceServiceTest.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DatabaseChangeThread.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/model/SizeAwareInputStream.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/util/DatabaseChangeFileReader.java
server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/util/ObjectStorageUtils.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/runtime/DatabaseChangeTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/runtime/PreCheckTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/runtime/RollbackPlanTask.java

type-bug
module-database change
module-task framework
There is a bug (#1777 ) caused by this PR (#1720). 
This PR fix it and aggregate duplicate code into a single util method.
Fixes #1777 
```docs
```

fix(database-change): read sql file failed causing sql not executed

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java

type-bug
When editing a task, an error of insufficient permissions will be reported.This is because when resourceRoleNames is empty, the verification method will determine that the operation has no permissions.
Fixes #1526
```docs
```

fix(schedule): no permission to edit

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/OBDatabaseUserType.java

type-bug
module-multi-cloud
fix cannot create new connection with read only account
Fixes #
```docs
```

fix(multi-cloud): failed to create new connection with read only account

---

server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/MySQLOfflineDdlExists.java
server/odc-service/src/test/java/com/oceanbase/odc/service/sqlcheck/MySQLCheckerTest.java

type-bug
npe will be thrown when some alter statements exists
Fixes #1864 
```docs
```

fix(sql-check): npe will be thrown when some alter statements exists

---

server/odc-core/src/main/java/com/oceanbase/odc/core/alarm/AlarmEventNames.java
server/odc-server/src/main/java/com/oceanbase/odc/server/web/trace/TraceHandlerInterceptor.java

add api rt alarm
Fixes #
```docs
```

feat(monitor): add api rt alarm

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java

It is bug caused by #1843 , this PR fix it.
Fixes #
```docs
```

fix(database-management): unable to create a connection using database details

---

docs/zh-CN/DEVELOPER_GUIDE.md

update start programmer command
Fixes #
```docs
```

docs: correct developer guide

---

server/odc-migrate/src/main/resources/migrate/common/V_4_2_3_18__create_list_flow_instance_view.sql
server/odc-service/src/main/java/com/oceanbase/odc/metadb/flow/FlowInstanceViewSpecs.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java

builds: merge dev/4.2.3 into main

---

server/odc-service/src/main/java/com/oceanbase/odc/service/task/constants/JobAttributeEntityColumn.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/BaseTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java

type-bug
if job is retrying, log attribute will replicated, so update the new value is exists
Fixes #
```docs
```

fix(taskframework):  fix retry log attribute

---

server/odc-core/src/main/java/com/oceanbase/odc/core/datasource/SingleConnectionDataSource.java

builds: merge from dev/4.2.3 into main

---

server/odc-core/src/main/java/com/oceanbase/odc/core/datasource/SingleConnectionDataSource.java
server/odc-migrate/src/main/resources/migrate/common/V_4_2_3_18__create_list_flow_instance_view.sql
server/odc-service/src/main/java/com/oceanbase/odc/metadb/flow/FlowInstanceViewSpecs.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java

build: merge main into dev/4.2.x 

---

server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/DBTableController.java

type-bug
this issue is involved by this pr #1608  by a mistake~
Fixes #
```docs
```

fix(partition-plan): fix wrong api's path variable

---

server/odc-service/src/main/java/com/oceanbase/odc/service/iam/UserBatchImportPreviewer.java
server/odc-service/src/main/java/com/oceanbase/odc/service/iam/model/BatchImportUser.java

type-bug
In `UserBatchImportPreviewer` , we used `Collections.emptyList()` incorrectly. It caused failures to import user.
Also optimized the error message of verification failure.
Fixes #1900

fix(iam): failed to batch import user with roles

---

server/odc-service/src/main/resources/builtin-snippet/ob-sys-snippet.yml

type-bug
refine prefix for sys tenant, avoid duplicated name with mysql mode.
all sys tenant query use`query_all` prefix:
Fixes #
```docs
```

fix(builtin-snippet): refine prefix for sys tenant, avoid duplicated name with mysql mode

---

server/odc-service/src/main/java/com/oceanbase/odc/service/flow/util/DescriptionGenerator.java

type-bug
module-i18n
The default task description use Chinese character when locale language is English. This PR fix it.
Fixes #1909 
```docs
```

fix(i18n): default task description use Chinese character when locale language is English

---

pom.xml
server/integration-test/src/test/java/com/oceanbase/odc/service/resultset/DumperResultSetExportTaskManagerTest.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DataTransferRuntimeFlowableTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/resultset/DumperResultSetExportTaskManager.java
server/odc-service/src/main/java/com/oceanbase/odc/service/resultset/ResultSetExportTask.java
server/plugins/task-plugin-api/src/main/java/com/oceanbase/odc/plugin/task/api/datatransfer/dumper/BinaryFile.java
server/plugins/task-plugin-api/src/main/java/com/oceanbase/odc/plugin/task/api/datatransfer/model/DataTransferConfig.java
server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/datatransfer/factory/BaseParameterFactory.java
server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/datatransfer/factory/DumpParameterFactory.java
server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/datatransfer/factory/LoadParameterFactory.java
server/plugins/task-plugin-ob-mysql/src/main/resources/session.config.json

upgrade ob-loader-dumper to 4.2.8.2-RELEASE

enhancement(data-transfer): upgrade ob-loader-dumper to 4.2.8.2-RELEASE

---

server/odc-service/src/main/java/com/oceanbase/odc/service/notification/Converter.java

type-bug
When the channel is unbound from the policy , the relatiion will also be deleted.
So the `mappedRelations` could get a null, then NPE occurs.
Fixes #1935

fix(notification): NPE occurred when convert event to message

---

server/odc-service/src/main/java/com/oceanbase/odc/service/state/StatefulRouteInterceptor.java

stateful optional allow nullable
Fixes #
```docs
```

fix(stateful):stateful optional allow nullable

---

server/plugins/task-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/task/mysql/datatransfer/job/BaseSchemaExportJob.java
server/plugins/task-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/task/mysql/datatransfer/job/datax/DataXTransferJob.java
server/plugins/task-plugin-ob-mysql/pom.xml
server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/datatransfer/factory/BaseParameterFactory.java

type-bug
After the transfer is completed, the directory is not cleared.
Fixes #1912
```docs
```

fix(data-transfer): after data transfer is completed, the directory is not cleared

---

server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/FlowTaskCallBackApprovalService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/BaseJobCaller.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/CheckRunningJob.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java

type-bug
fix  update some column when job be setting to `RETRYING` 
Fixes #
```docs
```

fix(taskframework): fix retry job reset destroy and heart time 

---

server/odc-service/src/main/resources/builtin-snippet/mysql-snippet.yml
server/odc-service/src/main/resources/builtin-snippet/ob-mysql-3.x-snippet.yml
server/odc-service/src/main/resources/builtin-snippet/ob-mysql-4.x-snippet.yml
server/odc-service/src/main/resources/builtin-snippet/ob-oracle-4.x-snippet.yml
server/odc-service/src/main/resources/builtin-snippet/ob-sys-snippet.yml

type-bug
fix some wrong description for builtin snippets
Fixes #
```docs
```

fix(builtin-snippets): fix wrong description for builtin snippets

---

libs/ob-sql-parser/src/main/resources/obmysql/sql/OBParser.g4

type-bug
"json_table" is a reserved key word and It should not be used as table name.
I checked the syntax file of ob and found that ob is allowed as a table name, so I modified it here to be consistent with OB.
Fixes #1655 
```docs
```

fix(parser): failed to parse insert statement with a table named 'json_table'

---

server/odc-service/src/main/java/com/oceanbase/odc/config/HookConfiguration.java
server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/environment/EnvironmentService.java

type-bug
This PR fixed 2 issues:
1. The error message of disabling environments which are still referenced by data sources is incorrect.
2. The environments reference check is missing the condition of the environment names.
Fixes #1575 #1854 
```docs
```

fix(environment): modify the error message while disabling environments

---

server/integration-test/src/test/java/com/oceanbase/odc/service/task/BaseJobTest.java
server/odc-service/src/main/java/com/oceanbase/odc/metadb/task/JobRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/BaseJobCaller.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/K8sJobCaller.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/ProcessJobCaller.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/server/RequestHandler.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/TaskFrameworkService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/util/HttpUtil.java

type-bug
1. if job status set to `CANCELING`, report result will be ignored
2.fix cancel request return `no content`
3.log query add default size when parameter is null
4.fix update execution_times failed
Fixes #
```docs
```

fix(taskframework): fix cancel job and update executionTimes failed

---

server/integration-test/src/test/java/com/oceanbase/odc/service/flow/FlowInstanceServiceTest.java
server/odc-service/src/main/java/com/oceanbase/odc/config/jpa/EnhancedJpaRepository.java

type-builds
merge from main into dev/4.2.x
Fixes #
```docs
```

merge from main into dev/4.2.x

---

.github/ISSUE_TEMPLATE/bug-report.yaml

remove the cloud section from the issue template
Fixes #
```docs
```

enhancement(github): remove the cloud section from the issue template

---

server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/BaseODCFlowTaskDelegate.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DBStructureComparisonFlowableTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/model/MockDataTaskResult.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/ConnectSessionService.java
server/odc-service/src/test/java/com/oceanbase/odc/service/structurecompare/DBObjectComparisonResultTest.java
server/plugins/connect-plugin-oracle/src/main/java/com/oceanbase/odc/plugin/connect/oracle/OracleTraceExtension.java

type-bug
fix several bug:
1. fix failed to covert json to taskResult class, the root cause is taskResult is save as a List in `BaseODCFlowTaskDelegate#setDownloadLogUrl`
2. fix the DB execution time of alter type sql is always displayed as 0，because we cannot query the time consuming of alter sql in `SYS.V$SQL`
3. fix the commit mode setting in personal settings is not taking effect for the Oracle database
Fixes #1962
Fixes #1965 
Fixes #1979 
```docs
```

fix(flowTask): fix failed to get flow task results

---

server/plugins/schema-plugin-doris/pom.xml
server/plugins/schema-plugin-doris/src/main/java/com/oceanbase/odc/plugin/schema/doris/DorisDatabaseExtension.java
server/plugins/schema-plugin-doris/src/main/java/com/oceanbase/odc/plugin/schema/doris/DorisFunctionExtension.java
server/plugins/schema-plugin-doris/src/main/java/com/oceanbase/odc/plugin/schema/doris/DorisProcedureExtension.java
server/plugins/schema-plugin-doris/src/main/java/com/oceanbase/odc/plugin/schema/doris/DorisTableExtension.java
server/plugins/schema-plugin-doris/src/main/java/com/oceanbase/odc/plugin/schema/doris/DorisViewExtension.java
server/plugins/schema-plugin-doris/src/main/java/com/oceanbase/odc/plugin/schema/doris/utils/DBAccessorUtil.java

type-bug
module-datasource
Access to Doris failed due to wrong DBAccessor usage. This PR fix it!
Fixes #1980 
```docs
```

fix(connect): can not access Doris datasource

---

server/integration-test/src/test/java/com/oceanbase/odc/service/shadowtable/ShadowTableComparingServiceTest.java
server/odc-service/src/main/java/com/oceanbase/odc/service/shadowtable/ShadowTableComparingService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/structurecompare/StructureComparisonService.java

type-bug
This PR changed the authentication method of shadowtable and structure comparing tasks. The former method will cause to NPE when the ticket is auto-approvable.
Fixes #1699 
```docs
```

fix(shadowtable): NPE occurs when project admins detail the shadowtable and structure comparing task

---

server/odc-service/src/main/java/com/oceanbase/odc/service/encryption/SensitivePropertyHandlerImpl.java

type-debug
module-encryption
Occasionally, ODC login fails due to failure of encryption and decryption of sensitive fields, add print logs for troubleshooting in subsequent replications.
Fixes #1790 
```docs
```

fix(encryption): add log output when failed to decrypt

---

server/odc-core/src/main/java/com/oceanbase/odc/core/sql/execute/mapper/MySQLTimestampMapper.java

type-bug
Fixes #1671
```docs
```

fix(sql): precision is lost when displaying timestamps

---

server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/server/ThreadPoolTaskExecutor.java

fix(taskframework): fix cancel result when status is done  

---

server/integration-test/src/test/java/com/oceanbase/odc/service/notification/helper/MessageTemplateProcessorTest.java
server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/OdcConstants.java
server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/NotificationController.java
server/odc-service/src/main/java/com/oceanbase/odc/config/BeanConfiguration.java
server/odc-service/src/main/java/com/oceanbase/odc/metadb/notification/ChannelPropertyRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/metadb/notification/ChannelRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/service/notification/NotificationScheduleConfiguration.java
server/odc-service/src/main/java/com/oceanbase/odc/service/notification/NotificationService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/notification/constant/EventLabelKeys.java
server/odc-service/src/main/java/com/oceanbase/odc/service/notification/helper/EventBuilder.java
server/odc-service/src/main/java/com/oceanbase/odc/service/notification/helper/MessageTemplateProcessor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/notification/model/WebhookChannelConfig.java

1. The sign key of the notification channel is not encrypted. This PR fixed it, when front-end send `null` value as sign, meaning it's already in metadb, we won't update this key.
2. Now only project's owner could test channel.
3. Support `ticketUrl` as event label key
Fixes #2000

fix(notification): fix some security vulnerabilities

---

server/starters/web-starter/src/main/java/com/oceanbase/odc/service/iam/auth/ldap/LdapUserDetailsContextMapper.java

ldap mapper can't load on not local type
Fixes #
```docs
```

fix(sso):ldap mapper can't load on not local type

---

server/odc-core/src/main/java/com/oceanbase/odc/core/session/BaseConnectionSessionManager.java
server/odc-service/src/main/java/com/oceanbase/odc/service/dispatch/RequestDispatcher.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/ConnectConsoleService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/ConnectSessionService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/SessionLockRemoveListener.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/SessionProperties.java
server/odc-service/src/main/resources/config-meta/user-config-meta.yml

type-bug
typ-enhancement
1. I add a new user config called `odc.sqlexecute.default.addInternalRowId` to determine whether adding rowid for sql query.
2. add a lock control for session creating automatically~
Fixes #1380 
```docs
```

fix(sql-execute): add an user config and add concurrent control for session creating

---

server/integration-test/src/test/java/com/oceanbase/odc/service/task/TestLogUtils.java
server/odc-service/src/main/java/com/oceanbase/odc/service/logger/LoggerService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/logger/LogBizImpl.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/logger/LogUtils.java

fix(taskframework): cannot preview latest log for dlm

---

libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/ODPOBMySQLSchemaAccessor.java
server/plugins/schema-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/schema/obmysql/parser/OBMySQLGetDBTableByParser.java
server/plugins/schema-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/schema/obmysql/utils/DBAccessorUtil.java
server/plugins/schema-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/schema/oboracle/OBOracleTableExtension.java
server/plugins/schema-plugin-odp-sharding-ob-mysql/src/main/java/com/oceanbase/odc/plugin/schema/odpsharding/obmysql/ODPShardingOBMySQLTableExtension.java

type-bug
sofaodp does not support `information_schema.key_column_usage` and we will get an exception when we attempt to obtain it.
out elder version does not support constraint either~
Fixes #1826 
```docs
```

fix(schema-plugin): failed to view table's detail on sofa odp

---

libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OracleSchemaAccessor.java

type-bug
remove spaces before and after ddl of view and trigger in oracle mode
Fixes #1954
Fixes #1907
```docs
```

fix(db-browser): remove spaces before and after ddl in oracle mode

---

server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/BaseODCFlowTaskDelegate.java

type-bug
This PR refine the code logic for uploading log files.
Fixes #
```docs
```

fix(task): try to upload log file even through the task has no log file

---

server/odc-service/src/main/java/com/oceanbase/odc/service/session/interceptor/SqlConsoleInterceptor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/MySQLOfflineDdlExists.java

type-bug
there will be a npe, I avoid it~
Fixes #2054 
```docs
```

fix(sql-check): fix npe caused by offline statement detection

---

libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/parser/listener/MysqlModeSqlParserListener.java

…te type
type-bug
module-sql execution
Fixes #1568
```docs
```

fix(db-browser): create table statement containing index is not recognized as a create type

---

server/integration-test/src/test/java/com/oceanbase/odc/TestConnectionUtil.java

Load test DB connect session on demand.
Fixes #
```docs
```

fix(unit-test): load test DB connect session on demand

---

server/plugins/schema-plugin-doris/src/main/java/com/oceanbase/odc/plugin/schema/doris/DorisDatabaseExtension.java

type-bug
Failed to create doris database when input charset and collation:
This PR fix it.
Fixes #2075 
```docs
```

fix(database): failed to create doris database when input charset and collation

---

server/odc-service/src/main/resources/builtin-snippet/mysql-snippet.yml

type-bug
Fixes #1997 #1998 
```docs
```

fix(builtin-snippets): duplicated prefix and wrong column for ob 3.x

---

script/build_jar.sh
script/start-job.sh
script/start-odc.sh
server/odc-server/pom.xml
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/TaskApplication.java

type-bug
fix start job failed by start-job.sh
Fixes #
```docs
```

feat(taskframework): support external log4j configuration file

---

server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/environment/EnvironmentService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/config/SystemConfigService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/config/UserConfigFacadeImpl.java
server/odc-service/src/main/java/com/oceanbase/odc/service/config/UserConfigMetaService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/integration/oauth2/TestLoginManager.java
server/odc-service/src/main/java/com/oceanbase/odc/service/notification/NotificationService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/regulation/risklevel/RiskLevelService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/regulation/ruleset/RulesetService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/snippet/BuiltinSnippetService.java

type-bug
Add horizontal authentication for service
Fixes #
```docs
```

fix(security): add horizontal authentication for service

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/PreCheckRuntimeFlowableTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/interceptor/DatabasePermissionInterceptor.java

When users execute SQLs, ODC will check if they have the associated database permissions. However, some data directory schema is not filtered out which will cause a bad user experience, as these data directory schemas are default granted to every database user.
Therefore, in this PR, I filter out the `SYS` in the Oracle dialect type and `information_schema` in the MySQL dialect type no matter if these two schemas are placed in the project.
Fixes #2048 
```docs
```

enhancement: filter out data directory schema while checking the database permission

---

server/odc-service/src/main/java/com/oceanbase/odc/metadb/structurecompare/StructureComparisonTaskEntity.java
server/odc-service/src/main/java/com/oceanbase/odc/service/shadowtable/ShadowTableComparingService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/structurecompare/StructureComparisonService.java

type-bug
It occurs NPE because before the shadow table tasks have been bound to a flow instance, the `ShadowTableComparingTaskEntity#getId` will be null. If this is the case, we just need to compare the task's creatorId and currentUserId.
Fixes #2039 
```docs
```

fix(shadowtable): it occurs NPE while creating shadow table comparing tasks

---

server/odc-service/src/main/java/com/oceanbase/odc/service/config/SystemConfigService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/iam/JwtService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/iam/auth/JwtSecurityContextRepository.java

add @SkipAuthorize in `SystemConfigService`
change @Service to @Component of JwtSecurityContextRepository

fix(security): add authorize annotation in service class

---

libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/stats/mysql/DorisStatsAccessor.java
server/odc-migrate/src/main/resources/migrate/common/R_2_0_0__initialize_version_diff_config.sql

type-bug
doris doesn't have `information_schema.PROCESSLIST` and our session management will throw an exception when we attempt to query it. I use `show full processlist` instead:
there is some fields missing such as `status` and so on~
I have tried kill query and kill session and these are normal.
Fixes #2034 
```docs
```

fix(doris): failed to view active db sessions in doris

---

server/odc-service/src/main/java/com/oceanbase/odc/service/session/factory/OBConsoleDataSourceFactory.java

type-bug
failed to sync datasource's databases cause that the init script is not executed when we sync the datasource~
Fixes #
```docs
```

fix(connect): failed to sync standby cluster's databases

---

server/plugins/task-plugin-doris/pom.xml
server/plugins/task-plugin-doris/src/main/java/com/oceanbase/odc/plugin/task/doris/datatransfer/DorisDataTransferExtension.java
server/plugins/task-plugin-doris/src/main/java/com/oceanbase/odc/plugin/task/doris/datatransfer/DorisDataTransferJob.java
server/plugins/task-plugin-doris/src/main/java/com/oceanbase/odc/plugin/task/doris/datatransfer/job/DorisSchemaExportJob.java
server/plugins/task-plugin-doris/src/main/java/com/oceanbase/odc/plugin/task/doris/datatransfer/job/DorisScriptImportJob.java
server/plugins/task-plugin-doris/src/main/java/com/oceanbase/odc/plugin/task/doris/datatransfer/job/DorisTransferJobFactory.java
server/plugins/task-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/task/mysql/datatransfer/job/datax/DataXTransferJob.java
server/plugins/task-plugin-oracle/src/main/java/com/oceanbase/odc/plugin/task/oracle/datatransfer/job/OracleSqlScriptImportJob.java

type-bug
There some issues in task-plugin-doris. It should not extend task-plugin-mysql simply. I fixed these issues.
Fixes #2025 #2026

fix(data-transfer): support data transfer for doris

---

server/starters/web-starter/src/main/java/com/oceanbase/odc/service/iam/auth/MappingRuleConvert.java

`userAccountName` is no longer required to be a String.
Fixes #
```docs
```

fix(sso): userAccountName allow non String

---

server/odc-core/src/main/java/com/oceanbase/odc/core/session/ConnectionSessionUtil.java
server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/extractor/OBColumnExtractor.java

type-bug
module-data-masking
Fix cannot masking result set when using Oracle.
Fixes #
```docs
```

fix(data-masking): cannot masking result set when using Oracle

---

server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/BaseODCFlowTaskDelegate.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DBStructureComparisonFlowableTask.java

fix failed to update task status when task fails
type-bug
Fixes #2105
```docs
```

fix(structure-comapre): failed to update task status when task fails

---

server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMJobFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/AbstractDlmJob.java

type-bug
Fixes #2091 #2092 
```docs
```

fix(dlm):interrupt job failed

---

server/odc-server/src/main/resources/log4j2.xml

type-bug
Fixed routing of non-task logs to task logs.
Fixes #2136
```docs
```

fix(alter-schedule): correct the log routing path

---

server/odc-migrate/src/main/resources/migrate/oceanbase/V_4_2_4_18__add_stateful_route.sql

default disabled stateful route
Fixes #
```docs
```

fix(stateful): default disabled stateful route

---

server/integration-test/src/test/java/com/oceanbase/odc/migrate/jdbc/common/V42417HistoricalPartitionPlanMigrateTest.java
server/odc-migrate/src/main/java/com/oceanbase/odc/migrate/jdbc/common/V42417HistoricalPartitionPlanMigrate.java

type-bug
we need to skip partition plan table configs that is not enable~
Fixes #
```docs
```

fix(partition-plan): migrate useless partition plan table config

---

server/odc-service/src/main/java/com/oceanbase/odc/metadb/task/JobRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java

fix(taskframework): fix refresh entity replaced by native sql

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/AlterScheduleTask.java

fix(log): correct the log routing path

---

CHANGELOG.md

refine v4.2.4 changelog for english language per @JessieWuJiexi 's review

docs: fix v4.2.4 changelog for english language

---

server/odc-migrate/src/main/java/com/oceanbase/odc/migrate/jdbc/common/V42417HistoricalPartitionPlanMigrate.java

type-bug
odc will startup failed when all partition plan configs is disabled~ we may delete these data to work around this issue.
Fixes #2156 
```docs
```

fix(partition-plan): failed to migrate historical partition plan data

---

server/odc-server/pom.xml

swagger-ui.html page 404 notfound
rootcause was springfox-wagger-ui dependency missed.

fix(web-framework): swagger-ui.html page 404 notfound

---

libs/db-browser/pom.xml
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/OBMySQLSchemaAccessor.java
pom.xml

type-bug
fix failed to listTables in `api/v2/connect/sessions/{sessionId}/metadata/identities` interface when lack mysql schema permissions
Fixes #2182
```docs
```

fix(db-browser): failed to listTables when lack mysql schema permissions

---

server/odc-service/src/main/java/com/oceanbase/odc/service/notification/Broker.java
server/odc-service/src/main/java/com/oceanbase/odc/service/notification/JdbcEventQueue.java
server/odc-service/src/main/java/com/oceanbase/odc/service/notification/helper/EventMapper.java

type-bug
1. There maybe some null value of event labels, and these null would leads to failure of enqueue.
2. In `FlowInstanceService#reject`, although the enqueue exception has been successfully captured, the hibernate mechanism has caused the session to fail. And subsequent database operations cannot proceed, resulting in rejection failure.
So I set the propegation of `Broker#enqueueEvent` to REQUIRES_NEW. Start a new transaction to insert an event.
Fixes #2183

fix(notification): failure to enqueue event will result in failure of ticket rejection

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java

type-bug
fix horizontal privilege escalation issue of getDatabase interface.
Fixes #
```docs
```

fix(security):horizontal privilege escalation issue of getDatabase interface

---

server/odc-core/src/main/java/com/oceanbase/odc/core/datasource/SingleConnectionDataSource.java

fix(connection): add some log about datasource lock

---

.secignore

add public webhook host into security ignore file

enhancement(security): add public webhook host into security ignore file

---

server/integration-test/src/test/java/com/oceanbase/odc/service/connection/ConnectionTestingTest.java
server/odc-service/src/main/java/com/oceanbase/odc/service/config/UserConfigService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionTesting.java

add Configuration Consumer for UserConfigService
Fixes #
```docs
```

fix(configuration): add Configuration Consumer for UserConfigService

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionTesting.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/DefaultConnectionAdapter.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/CloudConnectionConfig.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/ConnectionConfig.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/OBInstanceRoleType.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/OBTenant.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/TestConnectionReq.java
server/odc-service/src/main/java/com/oceanbase/odc/service/pldebug/session/AbstractDebugSession.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/factory/DruidDataSourceFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/factory/OBConsoleDataSourceFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/initializer/BackupInstanceInitializer.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/initializer/DataSourceInitScriptInitializer.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/initializer/SessionCreatedInitializer.java

type-feature
If DataSource is an OB backup instance, then we automatically add 'set ob_read_consistency='WEAK';' when the session was created.
Fixes #
```docs
```

feat(connect): support connect backup instance

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionTesting.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/initializer/BackupInstanceInitializer.java

Before OceanBase 4.x, we need to execute `set ob_read_consistency = weak ` to connect to a backup cluster; but after OceanBase 4.x, we do not need to(and not recommended to) do this. So this PR add a OceanBase version check.
Fixes #
```docs
```

fix(connection): add version check before set weak read consistency

---

server/odc-service/src/main/java/com/oceanbase/odc/config/TagConfiguration.java
server/odc-service/src/main/java/com/oceanbase/odc/service/tag/DefaultTagServiceFacadeImpl.java

TagConfiguration use same methodName to create bean
Fixes #
```docs
```

fix(tag): can‘t find tagServiceFacade 

---

server/integration-test/src/test/java/com/oceanbase/odc/service/task/NativeK8sClientTest.java
server/odc-server/src/main/resources/data.sql
server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/DefaultK8sJobResponse.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/K8sJobCaller.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/K8sJobClient.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/K8sJobResponse.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/NativeK8sJobClient.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/PodConfig.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/PodStatus.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/K8sProperties.java

type-bug
pending pod timeout after exceed two hours
Fixes #
```docs
```

fix(taskframework): pending pod timeout after exceed one hour

---

server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/OscService.java

type-bug
`getOscDatabaseInfo`  exists  horizontal privilege 
Fixes #
```docs
```

fix(security): horizontal privilege escalation issue of getOscDatabaseInfo interface

---

server/odc-service/src/main/java/com/oceanbase/odc/service/tag/DefaultTagServiceFacadeImpl.java

change default tag key
Fixes #
```docs
```

fix(tag): change default tag key

---

server/odc-core/src/main/java/com/oceanbase/odc/core/authority/permission/ConnectionPermission.java
server/odc-core/src/main/java/com/oceanbase/odc/core/authority/permission/DatabasePermission.java
server/odc-core/src/main/java/com/oceanbase/odc/core/authority/permission/PrivateConnectionPermission.java
server/odc-core/src/main/java/com/oceanbase/odc/core/authority/permission/ResourcePermission.java
server/odc-core/src/main/java/com/oceanbase/odc/core/authority/permission/ResourceRoleBasedPermission.java
server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/project/ProjectService.java

type-bug
error message of permission is not readable and this pr fix this issue~
Fixes #2226 
```docs
```

fix(permission): permission error message is not readable

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java

module-connection
Current database synchronization involves all databases, including those with no longer existing clusters. In this case, we are not supposed to sync them.
Fixes #
```docs
```

enhancement(connection): stop synchronizing databases whose cluster no longer exists

---

server/odc-migrate/src/main/resources/migrate/common/R_2_0_0__initialize_version_diff_config.sql

type-feature
update odc_version_diff_config for ob oracle SDO_GEOMETRY datatype
Fixes #2216
```docs
```

feat(datatype): update odc_version_diff_config for ob oracle SDO_GEOMETRY datatype

---

server/odc-server/src/main/resources/log4j2.xml
server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/OdcJobListener.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/ScheduleTaskContextHolder.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/AbstractDlmJob.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/PartitionPlanJob.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/SqlPlanJob.java

type-feature
The scheduled task logs are difficult to review. We are now adding a unique ID to locate task logs more easily.
Fixes #
```docs
```

enhancement(log):opt scheduled task log

---

server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/CheckRunningJob.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/DestroyExecutorJob.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/DoCancelingJob.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/StartPreparingJob.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java

fix alarm notification is not effective, AlarmUtils.warn is only print log but not send notification, so  call `AlarmUtils.alarm` to  send notification
```docs
```

fix(taskframework): alarm notification is not  effective

---

server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/OdcTriggerListener.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java

type-feature
This PR introduces a check for the database status to prevent unnecessary resource consumption. Previously, scheduled tasks would continue to be scheduled even when the database was nonexistent, consuming resources. With this update, once the database is deleted, the scheduling of tasks ceases.
Fixes #
```docs
```

enhancement(schedule): terminate the schedule if the database does not exist.

---

server/odc-service/src/main/java/com/oceanbase/odc/service/task/dispatch/ImmediateJobDispatcher.java

set podPendingTimeoutSeconds in podConfig
```docs
```

fix(taskframework): add pod config from properties

---

server/odc-server/src/main/resources/data.sql
server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/config/QuartzConfiguration.java

Add a task concurrency configuration item and set the default value to 30.
Add a configuration option to control the number of concurrent tasks, with a default value set to 30.
Fixes #
```docs
```

enhancement(task):increase the number of concurrent tasks from 10 to 30

---

server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMJobFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/model/DlmTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/AbstractDlmJob.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataArchiveJob.java

…ective.
type-bug
Data archiving tasks support customizing target table names in non-task framework mode.
Fixes #
```docs
```

fix(dlm): custom target table names invalid in non-task framework mode

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataArchiveRollbackJob.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataDeleteJob.java

type-bug
The table does not exist because the rollback task was not generated with swapped table names when customizing the target table name.
Fixes #
```docs
```

fix(dlm): rollback task failed when customizing target table names.

---

pom.xml
server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMJobFactory.java

upgrade dlm sdk to 1.1.1
Fixes #
```docs
```

feat(dlm):upgrade dlm sdk to 1.1.1

---

server/odc-common/src/main/java/com/oceanbase/odc/common/util/SSRFChecker.java
server/odc-common/src/test/java/com/oceanbase/odc/common/util/SSRFCheckerTest.java
server/odc-server/src/main/resources/data.sql
server/odc-service/src/main/java/com/oceanbase/odc/service/notification/NotificationProperties.java
server/odc-service/src/main/java/com/oceanbase/odc/service/notification/helper/ChannelConfigValidator.java
server/odc-service/src/main/java/com/oceanbase/odc/service/notification/helper/EventBuilder.java

cherry pick #2249  #2267 to obcloud_202404

fix(notificatiion): cherry pick from 4.2.x to solve security issues

---

server/odc-service/src/main/java/com/oceanbase/odc/service/notification/helper/EventBuilder.java

type-bug
When approve or reject a ticket, access denied exception is thrown because the user login context is cleared by notification eventer builder (`com.oceanbase.odc.service.notification.helper.EventBuilder`). This PR fixed it.
Fixes #
```docs
```

fix(ticket): access denied when approve a ticket

---

server/odc-server/src/main/resources/log4j2.xml
server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java

fix job attribute Column 'job_id' is null 
Fixes #
```docs
```

fix(taskframework): column 'job_id' cannot be null

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataArchiveJob.java

type-bug
Automatic table creation fails in Oracle mode, this PR disables automatic table creation.
Fixes #
```docs
```

fix(dlm):get table ddl failed in oracle mode

---

server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/BaseJobCaller.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/DefaultTaskFrameworkDisabledHandler.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/CheckRunningJob.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/DestroyExecutorJob.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/DoCancelingJob.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/StartPreparingJob.java

fix(taskframework): optimize log

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataArchiveJob.java

type-bug
When closing the task framework, the automatic table creation function did not adapt to the custom target table name, resulting in an error of the target table not existing.
Fixes #
```docs
```

fix(dlm): the target table does not exist

---

server/odc-server/src/main/java/com/oceanbase/odc/server/web/trace/TraceHandlerInterceptor.java

alarm msg add request
Fixes #
```docs
```

fix(alarm): alarm msg add request

---

server/odc-core/src/main/java/com/oceanbase/odc/core/datasource/SingleConnectionDataSource.java
server/odc-core/src/test/java/com/oceanbase/odc/core/datasource/SingleConnectionDataSourceTest.java

type-bug
`Connection#isValid` may be blocked when connection is occupied cause that driver execute a sql to verify a connect
Fixes #
```docs
```

fix(connection): connection may be blocked

---

server/odc-service/src/main/java/com/oceanbase/odc/service/partitionplan/PartitionPlanService.java
server/plugins/schema-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/schema/obmysql/browser/DBSchemaAccessors.java
server/plugins/task-plugin-api/src/main/java/com/oceanbase/odc/plugin/task/api/partitionplan/AutoPartitionExtensionPoint.java
server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/partitionplan/OBMySQLAutoPartitionExtensionPoint.java
server/plugins/task-plugin-ob-mysql/src/test/java/com/oceanbase/odc/plugin/task/obmysql/partitionplan/OBMySQLAutoPartitionExtensionPointTest.java
server/plugins/task-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/task/oboracle/partitionplan/OBOracleAutoPartitionExtensionPoint.java
server/plugins/task-plugin-ob-oracle/src/test/java/com/oceanbase/odc/plugin/task/oboracle/partitionplan/OBOracleAutoPartitionExtensionPointTest.java

type-bug
db-browser needs tenant name to list all partitioned tables but we give a null value to it.
I add a parameter to fix this issue~
Fixes #2321 
```docs
```

fix(partition-plan): failed to list partitioned tables on OceanBase 1.4.79

---

server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/OnlineSchemaChangeFlowableTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java

type-bug
module-schedule
because schedule task input param from osc do not contain project id, so quartz job will be deleted by  `ScheduleService#terminateIfDatabaseNotExisted`
Fixes #
```docs
```

fix(osc): osc job is terminated when database id is not exist

---

libs/db-browser/src/main/resources/schema/sql/mysql/mysql_5_6_x.yaml
libs/db-browser/src/main/resources/schema/sql/mysql/mysql_5_7_x.yaml
libs/db-browser/src/main/resources/schema/sql/obmysql/obmysql_4_0_x.yaml

type-bug
the partition definitions is not ordered on OceanBase 4.x and MySQL
Fixes #
```docs
```

fix(db-browser): partition definitions is not ordered

---

server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/OdcJobListener.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/model/JobType.java

type-bug
When a node crashes causing an abnormal exit and the task status is not updated correctly, this PR automatically corrects the historical task status upon the next scheduled execution of the planned task.
Fixes #
```docs
```

fix(dlm): correct the task status when the task exits abnormally

---

server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/TaskFrameworkConfiguration.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/StartPreparingJob.java

fix(taskframework): always print warn log about "Task-framework isEnabled" 

---

server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/partitionplan/OBMySQLAutoPartitionExtensionPoint.java

type-bug
the partition defs is not ordered on OceanBase 4.x and the generated partition is not expected when we want to generate partition by last partition value.
I ordered these partition defs to fix this issue
Fixes #2325 
```docs
```

fix(partition-plan): generated partition expression is not contiguous

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/AbstractDlmJob.java

…e task was cancelled.
type-bug
Fixed the issue where the task status was set to completed when the task was canceled.
Fixes #
```docs
```

fix(dlm):  the task status was set to completed when the task was canceled

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/model/ScheduleStatus.java

fix(schedule): status not found

---

.github/workflows/build_artifact.yaml
.github/workflows/build_daily.yaml
.github/workflows/build_dev.yaml
.github/workflows/build_release.yaml

type-build
Upgrade workflow action version to v4. 
This is because that some old version actions will not be available soon in the future, and v4 improve the performance of upload/download artifact.
Fixes #
```docs
```

build: upgrade workflow action version to v4

---

server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java

type-bug
log info is  missing when cancel job or close task-framework, so we should update oss `LOG_STORAGE_ALL_OBJECT_ID` and `LOG_STORAGE_BUCKET_NAME` in job_attribute in report result
- case 1: 
1. start job, job is running and can show log
2. cancel job 
result: log can be show normally
- case 2:
1. start job, job is running and can show log
2. close task-framework and restart
result: job is failed and log can be show normally
above 2 cases has test passed
```docs
```

fix(taskframework): oss log info is ignored when cancel job

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/ConnectionConfig.java

type-bug
as pr's title saying~
Fixes #
```docs
```

fix(flow): task will be failed when its execution undergoes a version upgrade

---

server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java

reactor save log meta data
Fixes #
```docs
```

reactor(taskframework): reactor save log meta data

---

server/odc-core/src/main/java/com/oceanbase/odc/core/shared/exception/AccessDeniedException.java
server/odc-service/src/main/java/com/oceanbase/odc/config/CommonSecurityProperties.java
server/odc-service/src/main/java/com/oceanbase/odc/service/common/util/WebResponseUtils.java
server/odc-service/src/main/java/com/oceanbase/odc/service/iam/auth/OrganizationAuthenticationInterceptor.java

type-bug
in application integration sceanario, client need fetch csrfToken before call POST/PUT/PATCH/DELETE method.
/api/v1/user/csrfToken API does not return xsrf-token in response cookie due it was set in authenticaton whitelist.
Fixes #2263

fix(web-framework): csrfToken API does not return token

---

server/odc-service/src/main/java/com/oceanbase/odc/config/CsrfConfigureHelper.java

type-bug
Fixes #2367
```docs
```

fix(web-framework): csrf prevention conflict with basic authentication

---

server/odc-service/src/main/java/com/oceanbase/odc/service/iam/UserService.java

type-bug
module-account integration (SSO, Bastion, PlayStation)
When updating the extra properties of existed user, then the user cannot login. The root cause is due to bad codes and this PR fix it.
Fixes #2326 
```docs
```

fix(account-integration): failed to login after updating user extra properties

---

server/odc-migrate/src/main/resources/migrate/common/V_4_3_0_4__add_unique_identifier.sql

type-feature
add unique identifier in collaboration project
Fixes #
```docs
```

feat(migrate):add unique identifier in collaboration project

---

server/odc-common/src/main/java/com/oceanbase/odc/common/crypto/RsaBytesEncryptor.java
server/odc-common/src/test/java/com/oceanbase/odc/common/crypto/RsaBytesEncryptorTest.java

…rently (#2371)
cherry pick from :https://github.com/oceanbase/odc/pull/2371
Fixes #
```docs
```

fix(encryption): exception occurs when invoking RSA decryption concurrently

---

.github/workflows/build_artifact.yaml
.github/workflows/build_daily.yaml
.github/workflows/build_release.yaml

type-feature
support build the web artifact in arm64
Fixes #
```docs
```

builds: supports build web in arm64

---

server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/SensitiveColumnService.java

Cherry-pick #2355 to dev/4.2.x
Fixes #
```docs
```

bugfix(data-masking): unavailable when existing invalid database with duplicated name

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java

type-bug
If the data source was previously failing to connect, changing it to a connectable data source will result in a database synchronization failure with the error message: "Data Source is synchronizing". The reason for this is that the JDBC lock from the last data source synchronization was never released, preventing other tasks from acquiring the lock. The lock was not released because` DataSource.getConnection` got stuck, even though we set the `connectTimeout` to `5000 ms`. It may be related to our ` DataSource.getLoginTimeout` always returning 0. The specific mechanism needs to be further discussed with our JDBC colleagues. 
This PR has just implemented a timeout mechanism at the service layer to ensure that deadlocks do not occur.
Fixes #2376 
```docs
```

fix(database): database sync failed after updated an invalid datasource to a valid datasource

---

CHANGELOG-zh-CN.md
CHANGELOG.md
CHANGELOG.rst

type-docs
add changelog
Fixes #
```docs
```

docs: change log for v4.2.4bp2

---

server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/TaskType.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/BaseODCFlowTaskDelegate.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/FlowTaskCallBackApprovalService.java

merge from dev/4.2.x into main
Fixes #
```docs
```

merge from dev/4.2.x into main

---

script/build_jar.sh

fix build_jar.sh remove old version jar not works

build: fix build_jar.sh remove old version jar not works

---

server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMJobFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/DataArchivePreprocessor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/AbstractDlmJob.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataArchiveDeleteJob.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataArchiveRollbackJob.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataDeleteJob.java

type-bug
The archiving of the specified partition failed because the job parameters were not set in the job request.
Fixes #
```docs
```

fix(dlm): archiving specified partition failed

---

server/odc-migrate/src/main/resources/init-config/init/notification-policy-metadata.yaml
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/MultipleDatabaseChangeRuntimeFlowableTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/model/MultipleDatabaseChangeParameters.java
server/odc-service/src/main/java/com/oceanbase/odc/service/notification/helper/EventBuilder.java

type-feature
This PR adds support for multiple database change task.

feat(notification): notification support multiple database change task

---

server/integration-test/src/test/java/com/oceanbase/odc/service/collaboration/ProjectServiceTest.java
server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/project/ProjectService.java

type-bug
when update project's name to an existed project name, then exception will be thrown.
This PR optimize the error message.
Fixes #2438 
```docs
```

fix(project): optimize error message when update a project name to an existed project name

---

server/odc-service/src/main/java/com/oceanbase/odc/config/ScheduleConfiguration.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/ConnectionConfig.java
server/odc-service/src/main/java/com/oceanbase/odc/service/datatransfer/DataTransferService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/datatransfer/task/DataTransferTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/resultset/ResultSetExportFlowableTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/resultset/ResultSetExportTask.java
server/plugins/task-plugin-api/src/main/java/com/oceanbase/odc/plugin/task/api/datatransfer/model/ConnectionInfo.java
server/plugins/task-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/task/mysql/datatransfer/MySQLDataTransferJob.java
server/plugins/task-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/task/mysql/datatransfer/job/BaseSqlScriptImportJob.java
server/plugins/task-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/task/mysql/datatransfer/job/datax/ConfigurationResolver.java
server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/datatransfer/factory/BaseParameterFactory.java
server/plugins/task-plugin-oracle/src/main/java/com/oceanbase/odc/plugin/task/oracle/datatransfer/OracleDataTransferJob.java

type-feature
When import and export data in odc, the jdbc parameters are unchangeable now.  This can cause some tasks to fail, such as https://github.com/oceanbase/odc/issues/2429 .
So we support apply jdbc parameters and scripts in connection config to data transfer tasks.
Fixes #2429 #2375

feat(data-transfer): apply jdbc parameters and scripts in connection config to data transfer

---

server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMJobFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMTableStructureSynchronizer.java
server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DataSourceInfoMapper.java
server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/model/DataArchiveTableConfig.java

type-bug
Fixed the issue with structure synchronization failure.
Fixes #2482
```docs
```

fix(dlm): sync table structure failed

---

server/odc-service/src/main/java/com/oceanbase/odc/metadb/config/SystemConfigEntity.java
server/odc-service/src/main/java/com/oceanbase/odc/metadb/config/SystemConfigRepository.java

feat(config):add creator_id to config entity

---

server/odc-service/src/main/java/com/oceanbase/odc/metadb/config/ConfigEntity.java
server/odc-service/src/main/java/com/oceanbase/odc/metadb/config/SystemConfigEntity.java

refactor(config): Add more fields to configEntity

---

server/odc-service/src/main/java/com/oceanbase/odc/service/session/interceptor/NlsFormatInterceptor.java

type-bug
failed to set nls parameter for native oracle in sql-console
Fixes #2421 
```docs
```

fix(session): failed to set nls parameters for native oracle in sql-console

---

server/integration-test/src/test/java/com/oceanbase/odc/service/databasechange/DatabaseChangeChangingOrderTemplateServiceTest.java
server/odc-service/src/main/java/com/oceanbase/odc/service/databasechange/DatabaseChangeChangingOrderTemplateService.java

type-bug
The current response for viewing the template list and details does not contain the database details.This pr allows the corresponding results to include the database information
Fixes #2506
```docs
```

fix(multiple database): hover the template name does not show the contained database

---

server/odc-service/src/main/java/com/oceanbase/odc/service/iam/auth/CustomBasicAuthenticationFilter.java
server/odc-service/src/main/java/com/oceanbase/odc/service/iam/auth/UsernamePasswordConfigureHelper.java

type-bug
basic auth miss onAuthenticationSuccess handler process, leads to authorization AccessDenied, and the login record mechanism not works.
Fixes #2547

fix(integration): basic auth miss authentication initialization

---

server/odc-service/src/main/java/com/oceanbase/odc/service/databasechange/DatabaseChangeChangingOrderTemplateService.java

type-bug
Absent project permission check in exist method, users who do not belong to the current project can also get the response result. Add project verification to avoid this situation
Fixes #
```docs
```

fix(multiple database): add project permission verification to the exist method

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java

type-bug
module-collaboration
This PR fix an vertical unauthorizing.
Fixes #
```docs
```

fix(collaboration): vertical unauthorizing exists when editing database owners

---

pom.xml

type-feature
Fixes #
```docs
```

feat(dlm):upgrade dlm sdk version to 1.1.3

---

server/odc-service/src/main/java/com/oceanbase/odc/metadb/schedule/ScheduleRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/project/ProjectService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java

Added validation to prevent archiving the project if any enabled schedules exist.
Fixes #[2180](https://github.com/oceanbase/odc/issues/2180)
```docs
```

fix(schedule): schedule cannot be disabled if project is archived

---

server/integration-test/src/test/java/com/oceanbase/odc/metadb/config/SystemConfigRepositoryTest.java
server/odc-service/src/main/java/com/oceanbase/odc/metadb/config/ConfigEntity.java
server/odc-service/src/main/java/com/oceanbase/odc/metadb/config/SystemConfigEntity.java
server/odc-service/src/main/java/com/oceanbase/odc/metadb/config/SystemConfigRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/service/common/response/PaginatedData.java
server/odc-service/src/main/java/com/oceanbase/odc/service/common/response/PaginatedResponse.java
server/odc-service/src/main/java/com/oceanbase/odc/service/config/SystemConfigService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/systemconfig/DbConfigChangeMatcher.java

refactor: pick changes from 43x

---

server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMConfiguration.java
server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMJobFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMJobStore.java
server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/model/DataArchiveParameters.java
server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/model/DataDeleteParameters.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/AbstractDlmJob.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataArchiveJob.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataDeleteJob.java

type-bug
In task framework mode, the task throws a 'table not found' exception because the 'dlm_job' was renamed to 'dlm_table_unit'.
Fixes #
```docs
```

fix(dlm): table not found in task framework mode

---

server/odc-service/src/main/java/com/oceanbase/odc/service/databasechange/DatabaseChangeChangingOrderTemplateService.java

type-bug
Returns an empty page object when the template in the project is empty. Avoid executing the following logic
Fixes #2615
```docs
```

fix(multiple database): error occurs when viewing the list without templates

---

server/odc-service/src/main/java/com/oceanbase/odc/service/dml/converter/OBOracleGeometryConverter.java
server/odc-service/src/test/java/com/oceanbase/odc/service/dml/DataConvertUtilTest.java

type-bug
Fixes #2503
```docs
```

fix(dml): failed to modify data which is geometry type

---

libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/editor/DBTablePartitionEditor.java

type-bug
the table editor append `partition 5` into the partition defs which is wrong, this pr fix this problem~
Fixes #2491
```docs
```

fix(structure-comparison): syntax error when executing structure comparison

---

server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/model/DataArchiveParameters.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/DataArchivePreprocessor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/AbstractDlmJob.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataArchiveDeleteJob.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataArchiveJob.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataArchiveRollbackJob.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataDeleteJob.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/DataArchiveTask.java

type-bug
Add timeout monitor for dlm job.
Fixes #
```docs
```

fix(dlm): task timeout was not effective

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataDeleteJob.java

fix(dlm): target database id is null in task framework mode

---

server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java

type-bug
Fixes #2683
```docs
```

fix(apply database): failing to apply database permission deliver

---

server/plugins/task-plugin-oracle/src/main/java/com/oceanbase/odc/plugin/task/oracle/datatransfer/job/factory/OracleTransferJobFactory.java

type-bug
When importing data for native oracle, we use `preSql` option to set `truncate table` statement .
But DataX would not execute `session` options before executing preSqls. And we rely on `session` options to switch the schema. So the truncate would failed.
Fixes #2588

fix(data-transfer): truncate will cause the import task to fail

---

server/starters/desktop-starter/src/main/java/com/oceanbase/odc/migrate/DesktopResourceHandle.java

type-bug
Fixes #2500 
```docs
```

fix(desktop): failed to bootstrap odc when upgrading from the version 3.2.0

---

server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/PreCheckRuntimeFlowableTask.java

type-bug
The current return logic will directly skip the subsequent permission verification, resulting in users who do not have the permission to change the database can also initiate 
Fixes #2696
```docs
```

fix(multiple database): the return of method intercepted in multiple database pre check node is incorrect 

---

server/odc-migrate/src/main/resources/migrate/common/V_3_3_0_1__add_flow.sql
server/odc-migrate/src/main/resources/migrate/common/V_4_3_0_7__alter_flow_instance_node_add_index.sql

type-bug
ODC would query a `flow_instance_approval_view` view, which is generated by two table joining.  One of the join columns is `flow_instance_node_approval.flow_instance_id` . But there is no index on this column.
Fixes #2496

enhancement(flowable): adding indexes to improve query efficiency of flowable

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataDeleteJob.java

type-bug
alter execute task job type for data cleaning.
alter execute task job type for data cleaning.
Fixes #
```docs
```

fix(dlm): alter execute task job type for data cleaning

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/parser/LogicalTableService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMService.java

fix(security): add skip auth annotation

---

libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OracleSchemaAccessor.java
server/plugins/connect-plugin-oracle/src/main/java/com/oceanbase/odc/plugin/connect/oracle/OracleSessionExtension.java

type-bug
Fixes #2695
```docs
```

fix(db-browser): failed to open SYS console when user without query sys permissions

---

server/integration-test/src/test/java/com/oceanbase/odc/service/flow/FlowResponseMapperFactoryTest.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/factory/FlowResponseMapperFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/model/FlowInstanceDetailResp.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/model/FlowNodeInstanceDetailResp.java

type-bug
a ticket can only be aborted by its creator and I refactor this. a ticket can be aborted by its creator and project owner~
Fixes #2387
```docs
```

fix(ticket): project owners failed to abort a ticket

---

server/odc-service/src/main/java/com/oceanbase/odc/config/CommonSecurityProperties.java

refactor(security): add configurable security whitelists

---

pom.xml

fix(dlm): upgrade dlm sdk to 1.1.4

---

server/odc-service/src/main/java/com/oceanbase/odc/metadb/flow/FlowInstanceViewSpecs.java

type-bug
the root cause of this problem is that we add `distinct` at the query and we will get the query like this when we attempt to `count(1)`:
```sql
select distinct count(a) from xxx group by flow_instance_id, task_type
```
almost every group's size is equal to 1 so the distinct operation will lead to wrong result~
Fixes #2480
```docs
```

fix(ticket): failed to view all tickets

---

server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/FlowInstanceController.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowTaskInstanceService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/factory/ScheduleResponseMapperFactory.java

refactor(schedule): add without permission method

---

server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/MultipleDatabaseChangeRuntimeFlowableTask.java

type-bug
Permissions have been checked when creating multi-database change. Initiating a child work order belongs to the execution process of the multi-database and should not include permission verification. Change it to the same as the sql plan initiating child tickets.
Fixes #
```docs
```

fix(multiple database): change the method when initiating child tickets

---

server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/PreCheckRuntimeFlowableTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/structurecompare/comparedbobject/DBTableConstraintStructureComparator.java
server/odc-service/src/main/java/com/oceanbase/odc/service/structurecompare/comparedbobject/DBTableIndexStructureComparator.java

type-bug
the structure-comparison will sort columns in index which lead to this issue
Fixes #2718
```docs
```

fix(structure-comparison): get a wrong result when comparing two same tables

---

server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/OdcTriggerListener.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java

type-bug
Fixes #2722
```docs
```

fix(schedule): terminate if schedule is invalid

---

.github/obfarm/action.yaml
.github/obfarm/obfarm.py
.github/workflows/build_release.yaml

…lease.yaml to run it by obfarm
type-feature
support run build release by ob farm
```docs
```

feat(CI): support run build release by ob farm

---

server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/BaseJobCaller.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/JobCaller.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/K8sJobCaller.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/ProcessJobCaller.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/DefaultJobConfiguration.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/DefaultSpringJobConfiguration.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/JobConfiguration.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/dispatch/ImmediateJobDispatcher.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/DefaultTaskFrameworkDisabledHandler.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/CheckRunningJob.java

because stop remote task and destroy executor is two phases, stop remote action cannot be rollback if destroy failed, we should do check conditional about executor can be destroy
Fixes #
```docs
```

fix(taskframework): cannot rollback stop when destroy executor failed

---

server/odc-service/src/main/java/com/oceanbase/odc/service/databasechange/MultipleDatabaseChangePreprocessor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/MultipleDatabaseChangeRuntimeFlowableTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/model/MultipleDatabaseChangeParameters.java

type-bug
Before to get FlowTaskExecutionStrategy object, using  'flowInstanceService.detail(getFlowInstanceId())' in class MultipleDatabaseChangeRuntimeFlowableTask, which will print a log. The solution is to persist FlowTaskExecutionStrategy objec into MultipleDatabaseChangeParameters
Fixes #
```docs
```

fix(multiple database): frequently printing logs

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java

type-bug
allow creator to alter schedule
Fixes #2773
```docs
```

fix(schedule): creator is not allowed to alter schedule

---

server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/server/TaskMonitor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/BaseTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/Task.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java

type-bug
running task will be canceled due to heartbeat timeout,  executor will report `CANCELED` status to odc server, but task will be retry and running again, so odc server receive a incorrect signal and terminal task, so we ignore `CANCELED` result but receive `FAILED` status
Fixes #
```docs
```

fix(taskframework): running task be canceled incorrect due to heartbeat timeout 

---

server/odc-server/src/main/resources/data.sql
server/odc-service/src/main/java/com/oceanbase/odc/service/notification/HttpSender.java
server/odc-service/src/main/java/com/oceanbase/odc/service/notification/NotificationProperties.java

Some users want us to support configuring the timeout for sending notifications. Therefore, a configuration has been added to the system config table.
Fixes #2582

enhancement(notification): support configuring network timeout for http sender

---

.github/CODEOWNERS

type-builds
Update code owner configuration.

builds: update code owner configuration

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/permission/DBResourcePermissionHelper.java
server/odc-service/src/main/java/com/oceanbase/odc/service/resultset/ResultSetExportFlowableTask.java

type-bug
module-db permission
When we merge code from 4.3.0 to 4.3.x, the codes for the whitelist of databases during DB permission check is mistake, and this PR added it.
Fixes #
```docs
```

fix(database-permission): mistake caused by code merge

---

server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/datatransfer/task/BaseOceanBaseTransferJob.java
server/starters/desktop-starter/src/main/java/com/oceanbase/odc/migrate/DesktopResourceHandle.java

type-bug
ODC desktop failed to start Because an incorrect iam_user_role relationship was generated.
Fixes #2760

fix(clientMode): fail to migrate metadb in client mode

---

server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMService.java
server/odc-service/src/main/resources/sql-check/obmysql-reserved-words.yml
server/odc-service/src/main/resources/sql-check/oboracle-reserved-words.yml
server/odc-service/src/test/java/com/oceanbase/odc/service/sqlcheck/MySQLCheckerTest.java
server/odc-service/src/test/java/com/oceanbase/odc/service/sqlcheck/OracleSqlCheckerTest.java

type-bug
id should not be considered as the key word in mysql and oracle~
Fixes #
```docs
```

fix(sql-check): remove the word 'id' from the reserved words

---

server/odc-common/src/main/java/com/oceanbase/odc/common/trace/TraceContextHolder.java

feat(auth): add projectId in TraceContextHolder

---

server/odc-service/src/main/java/com/oceanbase/odc/service/common/ConditionOnServer.java
server/odc-service/src/main/java/com/oceanbase/odc/service/common/ExcludeProfileCondition.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionSchedules.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/DatabaseSyncSchedules.java
server/odc-service/src/main/java/com/oceanbase/odc/service/databasechange/DatabaseChangeChangingOrderTemplateSchedules.java
server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/DBSchemaSyncScheduler.java
server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DlmLimiterService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowSchedules.java
server/odc-service/src/main/java/com/oceanbase/odc/service/lab/LabSchedules.java
server/odc-service/src/main/java/com/oceanbase/odc/service/notification/NotificationScheduleConfiguration.java
server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/QuartzJobService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/config/QuartzConfiguration.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/TaskFrameworkConfiguration.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/listener/DefaultJobProcessUpdateListener.java

Allows some beans to be loaded only in server mode.To be specific，add config `odc.server.condition.exclude-profile` to indicates that those profiles are not server mode.
Fixes #
```docs
```

feat(server): allows some beans to be loaded only in server mode

---

server/odc-service/src/main/java/com/oceanbase/odc/service/flow/model/FlowInstanceDetailResp.java

refactor(flow): add organizationId to flow instance detail 

---

server/odc-service/src/main/java/com/oceanbase/odc/service/iam/auth/OrganizationAuthenticationInterceptor.java

fix(auth): access denied for current project interface

---

server/odc-service/src/main/java/com/oceanbase/odc/service/session/ConnectConsoleService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/model/AsyncExecuteContext.java

fix(data viewing): get result-set timeout

---

server/odc-server/src/main/resources/data.sql
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowTaskInstanceService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/cloud/CloudResourceConfigurations.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/TaskLoggerService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/BaseTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/util/CloudObjectStorageServiceBuilder.java

task log download support multiple region scenario.
add TENCENT_CLOUD and HUAWEI_CLOUD supports.

feat(task-framework): task log download support multiple region scenario

---

libs/ob-sql-parser/src/main/resources/oboracle/sql/OBLexer.g4

type-bug
the interval value can not be recognized for ob oracle, the root cause is that our lex file goes wrong
Fixes #2871
```docs
```

fix(ob-sql-parser): failed to recognize interval expression in ob-oracle mode

---

server/odc-core/src/main/java/com/oceanbase/odc/core/migrate/Migrates.java

feat(util): enhance duplicated migrator validation, output detail scripts info

feat(util): enhance duplicated migrator validation, output detail scripts info

---

server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/IndividualOrganizationMigrator.java

fix
fix login process resource load faild, caused by delete useless yaml
Fixes #2880
```docs
```

fix(migrate): fix login process resource load faild

---

server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBVariablesService.java
server/plugins/connect-plugin-api/src/main/java/com/oceanbase/odc/plugin/connect/api/SessionExtensionPoint.java
server/plugins/connect-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/connect/obmysql/OBMySQLSessionExtension.java
server/plugins/connect-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/connect/oboracle/OBOracleSessionExtension.java
server/plugins/connect-plugin-oracle/src/main/java/com/oceanbase/odc/plugin/connect/oracle/OracleSessionExtension.java

fix(sql): the sql of modifying session parameter in oracle is error

---

server/odc-server/src/main/resources/log4j2-task.xml
server/odc-server/src/main/resources/log4j2.xml

feat(log): display time zone when printing logs

---

server/odc-service/src/main/java/com/oceanbase/odc/metadb/dlm/DlmTableUnitEntity.java
server/odc-service/src/main/java/com/oceanbase/odc/metadb/dlm/DlmTableUnitRepository.java

fix(dlm):add uk constraint to entity

---

.github/CODEOWNERS

type-refactor
change the CODEOWNERS
Fixes #
```docs
```

refactor: change the CODEOWNERS

---

server/integration-test/src/test/java/com/oceanbase/odc/metadb/schedule/LatestTaskMappingRepositoryTest.java
server/odc-migrate/src/main/resources/migrate/common/V_4_3_0_8__add_schedule_change_log.sql
server/odc-service/src/main/java/com/oceanbase/odc/metadb/dlm/DlmTableUnitEntity.java
server/odc-service/src/main/java/com/oceanbase/odc/metadb/dlm/DlmTableUnitRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/metadb/schedule/LatestTaskMappingEntity.java
server/odc-service/src/main/java/com/oceanbase/odc/metadb/schedule/LatestTaskMappingRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/OdcJobListener.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleTaskService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/factory/ScheduleResponseMapperFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/listener/DefaultJobProcessUpdateListener.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/processor/DLMResultProcessor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/util/JobPropertiesUtils.java

fix(dlm): start job failed 

---

server/odc-service/src/main/java/com/oceanbase/odc/service/pldebug/session/PLDebugSession.java

type-bug
the null pointer exception will be thrown in some situations.
Fixes #2693
```docs
```

fix(pl-debug): avoid npe during the pl debugging

---

server/odc-service/src/main/java/com/oceanbase/odc/service/iam/auth/OrganizationAuthenticationInterceptor.java

fix(api): add instance change api to white list.

---

server/odc-service/src/main/java/com/oceanbase/odc/metadb/dlm/DlmTableUnitRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/factory/ScheduleResponseMapperFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/processor/DLMResultProcessor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/StartPreparingJob.java

fix(task-framework):  refresh task result failed

---

server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v1/DBTableColumnController.java

fix(statefulRoute): fix list column can't reach

---

server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/model/DataArchiveParameters.java
server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/model/DataDeleteParameters.java
server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/OdcJobListener.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/model/CreateScheduleReq.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/model/ScheduleTaskDetailResp.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/StartPreparingJob.java

fix(cloud): validate several parameters

---

server/odc-service/src/main/java/com/oceanbase/odc/service/permission/DBResourcePermissionHelper.java

type-bug
If  a user is granted some tables' permission without database permission, he could not sumit database change ticket.
Fixes #2915

fix(permission): fail to submit ticket if lack of database permission

---

server/odc-core/src/main/java/com/oceanbase/odc/core/alarm/AlarmEventNames.java
server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/BuiltinSnippetController.java
server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/ScheduleController.java
server/odc-service/src/main/java/com/oceanbase/odc/service/state/RouteHealthManager.java
server/odc-service/src/main/java/com/oceanbase/odc/service/state/StateRouteAspect.java
server/odc-service/src/main/java/com/oceanbase/odc/service/state/model/RouteInfo.java

1. fix  listBuiltinSnippets can't reach.
2. add some log.
3. add retry to healthy check.
Fixes #
```docs
```

fix(statefulRoute): failed to list built-in snippets

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/LogicalDatabaseSyncManager.java

1. modify `LogicalDatabaseSyncManager` from `Service` to `Component`
2. add `SkipAuth` annotation to `DatabaseService#updateObjectSyncStatus`

security: modify annotations on some service classes

---

server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMJobStore.java
server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DlmLimiterService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/cloud/CloudObjectStorageService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/factory/ScheduleResponseMapperFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/processor/DLMResultProcessor.java

fix(task-framework): ignore location validation and update task status after refresh

---

server/odc-server/src/main/resources/config/application.yml

fix(web): modify tomcat keepAliveTimeout to 70 seconds

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/OBInstanceType.java

fix(connect): failed to connect to AP instance

---

server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/DefaultOnlineSchemaChangeTaskHandler.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/OscService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/pipeline/ScheduleCheckOmsProjectValve.java

BugFix
This PR include two bug fix
1. When online schema change service start, but the async flow task has not scheduled. Request 
to /api/v2/osc/updateRateLimitConfig may throw NPE.
2. When  /api/v2/osc/updateRateLimitConfig  requested before swap table action. server will loop restart OMS task cause limit config not saved correctly.
Rate limit diff check depends on message stored in schedule_schedule and schedule_task table. The message will not generated until flow task triggered. issue 1 happened before flow task triggered. 
If rate limit resolved different between schedule_schedule and schedule_task, update OMS config operation will triggered. Then schedule_task will assign same rate limit of schedule_schedule. issue 2 save previous rate limit again.
Fixes #
```docs
```

fix(osc): the online schema change blocked when rate limiter modified before swap table action

---

server/odc-service/src/main/java/com/oceanbase/odc/service/state/StatefulUuidStateIdGenerator.java

`odc.web.stateful-route.enabled` should only control route, `StatefulUuidStateIdGenerator` is used to generate stateId, should not conditional load.
Fixes #
```docs
```

fix(stateful): remove wrong condition

---

server/odc-service/src/main/java/com/oceanbase/odc/service/state/StatefulUuidStateIdGenerator.java

so as https://github.com/oceanbase/odc/pull/2975
Fixes #
```docs
```

fix(stateful): remove wrong generator conditional load

---

server/plugins/connect-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/connect/obmysql/OBMySQLDiagnoseExtension.java
server/plugins/connect-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/connect/oboracle/OBOracleDiagnoseExtension.java

type-bug
There may be some ob inner sqls sharing same trace id with target sql in sql audit view. We should filter these.

fix(diagnose): get incorrect record from sql audit

---

server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/OdcJobListener.java
server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/OdcTriggerListener.java
server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/QuartzJobService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleTaskService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/model/ScheduleChangeLog.java

fix(schedule): parameters missing in changelog 

---

server/odc-server/src/main/resources/log4j2-task.xml

fix(log):print time zone in task log

---

server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java

fix(task): failed to refresh status when canceling the job

---

server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowTaskInstanceService.java

type-bug
the type reference of the pre_check task is wrong and this pr fix this~
Fixes #2724
```docs
```

fix(pre-check): failed to get sql check result when the check result file is not on this machine

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java

fix(dlm): sync limit configuration when updating the schedule

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java

fix(schedule): fail to update trigger config

---

server/integration-test/src/test/java/com/oceanbase/odc/metadb/connection/DatabaseRepositoryTest.java
server/odc-service/src/main/java/com/oceanbase/odc/metadb/connection/DatabaseRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseSyncManager.java
server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/DBSchemaIndexService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/DBSchemaSyncScheduler.java
server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/DBSchemaSyncTaskManager.java
server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/GlobalSearchProperties.java

type-bug
the front-end will call sync api continuously, the reason of it is that the object sync status is 'PENDING' without changing by the time. 
I add a new property `max-pending-hours` to limit the maximum time an object's state can be kept on 'PENDING' to fix this issue.
Fixes #2767
```docs
```

fix(global-search): unable to stop data object synchronization

---

libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/parser/CacheElement.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/parser/listener/MysqlModeSqlParserListener.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/parser/listener/OracleModeParserListener.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/parser/listener/OracleModeSqlParserListener.java
libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/parser/PLParserTest.java
libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/parser/SqlParserTest.java
server/plugins/schema-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/schema/obmysql/OBMySQLTableExtension.java
server/plugins/schema-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/schema/oboracle/OBOracleTableExtension.java

type-bug
failed to recognize the commit and rollback statement
Fixes #2979 #2973
```docs
```

fix(db-browser): failed to recognize the commit and rollback statement

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java

fix(schedule): check cron expression

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java

fix(dlm): update limit config throw NPE

---

server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/OdcTriggerListener.java

fix(alarm): publish alarm when skip execution

---

server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/OdcJobListener.java
server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/OdcTriggerListener.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java

fix(schedule): concurrent executing job

---

server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/StdJobScheduler.java

fix(log):  print job parameters in task log file

---

server/odc-service/src/main/java/com/oceanbase/odc/service/session/ConnectConsoleService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/OBQueryProfileExecutionListener.java
server/plugins/connect-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/connect/obmysql/diagnose/DiagnoseUtil.java

type-bug
1. modify the version supporting query profile to  `[4.2.4, 4.3.0) || [4.3.3, )`
2. fix explain error
Fixes #2833 #2996
```docs
```

fix(query-profile): modified the version supporting query profile

---

server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/DestroyExecutorJob.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/DoCancelingJob.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/StartPreparingJob.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java

fix(alarm): task alarm add exception message

---

server/odc-service/src/main/java/com/oceanbase/odc/service/iam/OrganizationService.java

fix(organization): failed to list individual organization

---

server/odc-server/src/main/resources/data.sql
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/processor/CreateFlowInstanceProcessAspect.java

type-bug
validate cron trigger and throw exception if trigger interval less than 600s.
Fixes #3008
```docs
```

fix(schedule): validate trigger interval when create scheduler

---

server/integration-test/src/test/java/com/oceanbase/odc/metadb/schedule/ScheduleTaskRepositoryTest.java
server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/TaskStatus.java
server/odc-service/src/main/java/com/oceanbase/odc/metadb/schedule/ScheduleTaskRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/OdcJobListener.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleTaskService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/AbstractDlmJob.java

fix(schedule):  concurrent execution

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java

type-bug
Create the database under the data source failed. The root cause is that the `connect_database` ddl changed in this version, but the code did not set the `type` and the `dialect_type` when creating the database.
Fixes #2913 #2957 
```docs
```

fix(database): creating databases under the data source failed

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/model/UnauthorizedDBResource.java
server/odc-service/src/main/java/com/oceanbase/odc/service/permission/DBResourcePermissionHelper.java

type-bug
Add the projected in the response so that the front-end could select the specific database/table when apply the permissions.
Fixes #2912 
```docs
```

fix(table-permission): not select the specific database/table by default when create the permission application ticket
