server/odc-service/src/main/java/com/oceanbase/odc/service/flow/processor/CreateFlowInstanceProcessAspect.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/DataDeletePreprocessor.java

type-bug
Fixes #3022 #3027 #3024 #3032 
```docs
```

fix(dlm):  several bug related to editing data cleaning

---

server/odc-service/src/main/java/com/oceanbase/odc/service/permission/DBResourcePermissionHelper.java

type-bug
rollback code of the PR 2946
Fixes #3010 #3019 #3011 #3013 #3015 
```docs
```

fix(table-permission): could create tickets when users have no permission to the database

---

server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMTableStructureSynchronizer.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/AbstractDlmJob.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/DataArchiveTask.java

type-bug
Fixes #3031
```docs
```

fix(dlm): create the target table if the sync table structure is off in MySQL mode

---

server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/PreCheckRuntimeFlowableTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/interceptor/DBResourcePermissionInterceptor.java

type-bug
SQL Parser cannot distinguish packages and schemas in the sql which is expected. So when users execute sql like `SELECT dbms_metadata.get_ddl('INDEX', 'NON_PARTRANGE_8_OBPK_1713838892387241', 'HX') DDL from dual;`, it will be rejected because of 'lack database permissions'.
This PR list all the schemas under the data source, and if the parsed 'schema' does not exist in the list, we ignore it.
Fixes #3055 
```docs
```

fix(database-permission): wrongly recognize packages as schemas

---

server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/PreCheckRuntimeFlowableTask.java

type-bug
As database/table permission ticket may relate to more than one database or environment, so the approval flow is not accurately selected. This PR will always select the highest risk level approval flow for these two kinds of tickets.
Fixes #3068 
```docs
```

fix(flow): wrong approval flow for database/table permission apply ticket

---

server/odc-service/src/main/java/com/oceanbase/odc/service/session/util/DBSchemaExtractor.java
server/odc-service/src/test/java/com/oceanbase/odc/service/session/DBSchemaExtractorTest.java

type-bug
failed to recognize the schema or package name from an anonymous block
Fixes #3064
```docs
```

fix(parser): failed to recognize the schema or package name from an anonymous block

---

CHANGELOG.md
CHANGELOG.rst

docs: update 4.3.1 changelog 

---

pom.xml
server/integration-test/src/test/java/com/oceanbase/odc/service/onlineschemachange/BaseOscTestEnv.java
server/integration-test/src/test/java/com/oceanbase/odc/service/onlineschemachange/OnlineSchemaChangeExpiredTest.java
server/odc-core/pom.xml
server/odc-service/pom.xml
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/oms/OmsRequestUtil.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/oms/client/BaseOmsClient.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/pipeline/ProjectStepResultChecker.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/pipeline/ScheduleCheckOmsProjectValve.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/pipeline/SwapTableNameValve.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/rename/DefaultRenameTableInvoker.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/rename/LockRenameTableFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/rename/LockTableInterceptor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/rename/OBMySQLRenameTableHandler.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/rename/OBOracleRenameTableHandler.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/rename/OscDBUserUtil.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/rename/SwapTableUtil.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/subtask/OmsResourceCleanHandler.java
server/odc-service/src/test/java/com/oceanbase/odc/service/onlineschemachange/pipeline/ProjectStepResultCheckerTest.java
server/odc-service/src/test/java/com/oceanbase/odc/service/onlineschemachange/pipeline/SwapTableNameValveTest.java
server/odc-service/src/test/java/com/oceanbase/odc/service/onlineschemachange/rename/LockTableInterceptorTest.java
server/odc-service/src/test/java/com/oceanbase/odc/service/onlineschemachange/rename/OBMySQLRenameTableHandlerTest.java
server/odc-service/src/test/java/com/oceanbase/odc/service/onlineschemachange/rename/OBOracleRenameTableHandlerTest.java
server/odc-service/src/test/java/com/oceanbase/odc/service/onlineschemachange/rename/OscDBUserUtilTest.java
server/odc-service/src/test/java/com/oceanbase/odc/service/onlineschemachange/rename/SwapTableUtilTest.java

osc support lock table for ob-mysql 4.2.5, fix data loss issue when switch table, fix thread leak issue when release Oms project
type-bug
1. support lock table for ob-mysql 4.2.5
2. fix data loss issue when switch table,
3. fix thread leak issue when release OMS project
4. support special schema/table
Fixes #
1. support lock table for ob-mysql with version greater than 4.2.5
2. cause the missing check of data apply progress，data may loss during table switch,. Now we will wait until increment checkpoint in timestamp greater than the timestamp recorded after lock table. Notice, this waiting may take about 10 - 20 seconds now. We will optimize this lock table waiting time in future release.
3. fix thread leak when release OMS project. change to sync call instead of create a new Thread pool. …

fix(osc): enhance osc feature

---

server/odc-service/src/main/java/com/oceanbase/odc/service/session/util/DBSchemaExtractor.java
server/odc-service/src/test/resources/session/test_db_schema_extractor.yaml

type-bug
#3101 missed the fix in Oracle mode. This PR add the fix in Oracle mode.
Fixes #
```docs
```

fix(permission): users cannot call function in oracle mode

---

server/odc-service/src/main/java/com/oceanbase/odc/service/notification/HttpSender.java
server/odc-service/src/main/java/com/oceanbase/odc/service/notification/helper/MessageResponseValidator.java

type-bug
In the previous version, when ODC were using `RestTemplate#Exchange`, we specified the class as MAP, which means we can only handle responses in the `applicaton/json` format.
Fixes #3113
```docs
```

fix(notification): support response type `text/plain` and others

---

server/odc-service/src/main/java/com/oceanbase/odc/service/notification/FeishuSender.java
server/odc-service/src/main/java/com/oceanbase/odc/service/notification/WeComSender.java

type-bug
In https://github.com/oceanbase/odc/pull/3114 , we changed the reponse extract type from `Map` to `String`. But missed to update it in `FeishuSender` and `WeComSender`. 
Fixes #3117
```docs
```

fix(notification): ClassCastException would be thrown when sending to feishu or wecom

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/OBInstanceType.java

type-feature
adaption for obcloud kv instance type
Fixes #
```docs
```

feat(connection): adaption for obcloud kv instance type

---

server/integration-test/src/test/java/com/oceanbase/odc/service/onlineschemachange/BaseOscTestEnv.java
server/integration-test/src/test/java/com/oceanbase/odc/service/onlineschemachange/OnlineSchemaChangeOBMysqlSwapTableTest.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/oscfms/action/oms/OmsSwapTableAction.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/oscfms/action/oms/ProjectStepResultChecker.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/rename/DefaultRenameTableInvoker.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/rename/SwapTableUtil.java
server/odc-service/src/test/java/com/oceanbase/odc/service/onlineschemachange/oscfms/OscTestUtil.java
server/odc-service/src/test/java/com/oceanbase/odc/service/onlineschemachange/oscfms/action/oms/OmsSwapTableActionTest.java
server/odc-service/src/test/java/com/oceanbase/odc/service/onlineschemachange/rename/SwapTableUtilTest.java

type-feature
make osc swap table reentrant for future error recovery
connection will be recreated when retry swap table
Fixes #
test if swap table has finished before required lock. if ghost table not exist, then consider swap table has done
1. if swap table has not done, do swap table action
2. if swap table has done, ignore swap table
3. if drop old table enabled, check if table has been dropped to avoid unexpected exception
integrate test has made up for above situation
```docs
```

feat(osc):enhance osc, let swap table reentrant

---

server/integration-test/src/test/java/com/oceanbase/odc/service/git/GitIntegrationServiceTest.java
server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/ResourceType.java
server/odc-core/src/main/resources/i18n/BusinessMessages.properties
server/odc-core/src/main/resources/i18n/BusinessMessages_zh_CN.properties
server/odc-core/src/main/resources/i18n/BusinessMessages_zh_TW.properties
server/odc-migrate/src/main/resources/migrate/common/V_4_3_2_1__add_integration_git.sql
server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/GitIntegrationController.java
server/odc-server/src/main/resources/data.sql
server/odc-service/src/main/java/com/oceanbase/odc/metadb/git/GitRepoRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/metadb/git/GitRepoStageRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/metadb/git/GitRepositoryStageEntity.java
server/odc-service/src/main/java/com/oceanbase/odc/service/git/GitClientOperator.java
server/odc-service/src/main/java/com/oceanbase/odc/service/git/GitIntegrationService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/git/model/GitIntegrationProperties.java
server/odc-service/src/main/java/com/oceanbase/odc/service/git/model/GitProvider.java
server/odc-service/src/main/java/com/oceanbase/odc/service/git/model/QueryGitRepositoryParams.java
server/odc-service/src/main/java/com/oceanbase/odc/service/git/model/RepoState.java
server/odc-service/src/main/java/com/oceanbase/odc/service/git/repo/GitRepositoryManager.java
server/odc-service/src/main/java/com/oceanbase/odc/service/git/repo/RepositoryManager.java
server/odc-service/src/test/java/com/oceanbase/odc/service/git/GitClientOperatorTest.java

feat(git-integration): add service layer for git repository integration

---

server/odc-service/src/main/java/com/oceanbase/odc/config/RestTemplateConfig.java

refactor(web): remove unnecessary bean

---

server/odc-core/src/main/java/com/oceanbase/odc/core/alarm/AlarmEventNames.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/PartitionPlanRuntimeFlowableTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/PartitionPlanJob.java
server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/partitionplan/OBMySQLAutoPartitionExtensionPoint.java

type-bug
failed to generate partition name when using custom generator
Fixes #3132 #3133
```docs
```

fix(partition-plan): failed to generate partition name when using custom generator

---

libs/db-browser/pom.xml
pom.xml
server/odc-server/src/main/resources/config/application.yml
server/odc-server/src/main/resources/config/bootstrap.yml
server/odc-service/src/main/java/com/oceanbase/odc/service/session/factory/OBConsoleDataSourceFactory.java
server/plugins/connect-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/connect/obmysql/OBMySQLConnectionExtension.java
server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/datatransfer/factory/BaseParameterFactory.java

upgrade jdbc to 2.4.12
1. If dont set `useCompatibleMetadata` to true , springboot could not start.
2. set `sendConnectionAttributes` to true.
3. set `enableFullLinkTrace` to  true.

build: upgrade jdbc to 2.4.12

---

server/odc-core/src/main/java/com/oceanbase/odc/core/alarm/AlarmEventNames.java
server/odc-service/src/main/java/com/oceanbase/odc/config/RestTemplateConfig.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/PartitionPlanRuntimeFlowableTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/PartitionPlanJob.java
server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/partitionplan/OBMySQLAutoPartitionExtensionPoint.java

type-builds
merge from dev/4.3.1 into main
Fixes #
```docs
```

merge from dev/4.3.1 into main

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/LogicalTableService.java

type-bug
When there only exists one table in the database, `LogicalTableRecognitionUtils.recognizeLogicalTablesWithExpression` will return empty list. In this case, we should just return the full-qualified name of the table.
Fixes #
```docs
```

fix(logicaldatabase): index out of bound when there only exists one table in the database

---

.github/workflows/build_artifact.yaml
.github/workflows/build_daily.yaml
.github/workflows/build_dev.yaml
.github/workflows/build_release.yaml
script/functions.sh
server/odc-service/pom.xml

type-build
install pty4j manually
Fixes #
```docs
```

builds: install pty4j manually

---

libs/db-browser/pom.xml
libs/ob-sql-parser/pom.xml
pom.xml

upgrade ob-sql-parser to 1.3.1

build: upgrade ob-sql-parser to 1.3.1

---

server/odc-server/src/main/resources/config/application.yml

The tomcat configuration is incompatible after the springboot version upgrade.
Fixes #
```docs
```

fix(web): fix tomcat threads config

---

server/odc-core/src/main/java/com/oceanbase/odc/core/alarm/AlarmEventNames.java
server/odc-server/src/main/resources/config/application.yml
server/odc-service/src/main/java/com/oceanbase/odc/config/RestTemplateConfig.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/PartitionPlanRuntimeFlowableTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/PartitionPlanJob.java
server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/partitionplan/OBMySQLAutoPartitionExtensionPoint.java

type-build
merge from main into dev/4.3.x
Fixes #
```docs
```

merge from main into dev/4.3.x

---

pom.xml
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/DataArchiveTask.java

type-feature
upgrade dlm sdk version to 1.1.4.bp1
Fixes #
```docs
```

feat(dlm): update dlm sdk version to 1.1.4.bp1

---

pom.xml
server/odc-service/pom.xml
server/odc-service/src/main/java/com/oceanbase/odc/service/datatransfer/DataTransferService.java
server/plugins/task-plugin-ob-mysql/pom.xml
server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/datatransfer/factory/BaseParameterFactory.java
server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/datatransfer/factory/DumpParameterFactory.java
server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/datatransfer/factory/LoadParameterFactory.java

type-build
upgrade ob-loader-dumper version to 4.3.1.1
Fixes #
Additional documentation e.g., usage docs, etc.:

build(data-transfer): upgrade ob-loader-dumper version to 4.3.1.1

---

server/integration-test/src/test/java/com/oceanbase/odc/service/datatransfer/loader/PLSqlMultiFileOutputTest.java
server/integration-test/src/test/java/com/oceanbase/odc/service/datatransfer/loader/PLSqlSingleFileOutputTest.java
server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/ErrorCodes.java
server/odc-core/src/main/resources/i18n/ErrorMessages.properties
server/odc-core/src/main/resources/i18n/ErrorMessages_zh_CN.properties
server/odc-core/src/main/resources/i18n/ErrorMessages_zh_TW.properties
server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/DataTransferController.java
server/odc-service/src/main/java/com/oceanbase/odc/service/datatransfer/DataTransferService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/datatransfer/loader/PLSqlDeveloperExportFormat.java
server/odc-service/src/main/java/com/oceanbase/odc/service/datatransfer/loader/PLSqlDirectoryOutput.java
server/odc-service/src/main/java/com/oceanbase/odc/service/datatransfer/loader/PLSqlMultiFileOutput.java
server/odc-service/src/main/java/com/oceanbase/odc/service/datatransfer/loader/PLSqlSingleFileOutput.java
server/odc-service/src/main/java/com/oceanbase/odc/service/datatransfer/loader/PlSqlDirOutput.java
server/odc-service/src/main/java/com/oceanbase/odc/service/datatransfer/loader/PlSqlMultiFileOutput.java
server/odc-service/src/main/java/com/oceanbase/odc/service/datatransfer/loader/ThirdPartyOutputConverter.java
server/odc-service/src/main/java/com/oceanbase/odc/service/datatransfer/task/DataTransferTask.java
server/plugins/task-plugin-api/src/main/java/com/oceanbase/odc/plugin/task/api/datatransfer/dumper/ExportOutput.java
server/plugins/task-plugin-api/src/main/java/com/oceanbase/odc/plugin/task/api/datatransfer/model/DataTransferConfig.java
server/plugins/task-plugin-api/src/main/java/com/oceanbase/odc/plugin/task/api/datatransfer/model/UploadFileResult.java
server/plugins/task-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/task/mysql/datatransfer/MySQLDataTransferJob.java
server/plugins/task-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/task/mysql/datatransfer/job/factory/BaseTransferJobFactory.java
server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/datatransfer/factory/LoadParameterFactory.java

type-feature
data import now supports choosing file directory
Fixes #
Additional documentation e.g., usage docs, etc.:

feat(data-transfer): data import supports file directory

---

server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/DataBaseController.java
server/odc-service/src/main/java/com/oceanbase/odc/metadb/connection/ConnectionConfigRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/metadb/dbobject/DBObjectRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/table/TableService.java

enhancement(sql-console): sort the lists of data sources, databases, and database objects in ascending order by name

---

server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/DBRecyclebinController.java
server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/PLController.java
server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBPLService.java

fix(statefulRoute): batchCompilations and getRecyclebinSettings will failed if statefulroute enabled

---

server/odc-migrate/src/main/java/com/oceanbase/odc/migrate/jdbc/common/V4325Oauth2UseStateParamDefaultFalse.java

fix(sso): azure integration migrate failed

---

server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/SensitiveColumnScanningTaskManager.java
server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/SensitiveColumnService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/model/SensitiveColumnScanningTaskInfo.java

fix(statefulRoute):sensitive column may can't get result

---

server/odc-service/src/main/java/com/oceanbase/odc/service/integration/oauth2/Oauth2StateManager.java

fix(sso): get state params may failed when use load banlance

---

server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/FlowStatus.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowTaskInstanceService.java

type-bug
At present, after clicking manual execution button on the ticket, the status of ticket in the database will remain in wait_for_execution for a period of time, and the front end displays the execution button according to this status. Therefore, after clicking manual execution, the execution button will appear for a period of time, and an error will be reported when the user clicks execution button again.
The improvement is to change the status of the ticket to not ‘wait_for_execution’ immediately after clicking Manual execution button
Fixes #
```docs
```

fix(manual execution):manual execution button should not be displayed after clicking manual execution in odc431

---

pom.xml
server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/model/DataDeleteParameters.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/DataArchivePreprocessor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/DataDeletePreprocessor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataDeleteJob.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/DataArchiveTask.java

type-feature
A sharding strategy configuration option has been added to the DataArchive task, allowing users to choose their own sharding strategy.
Fixes #
```docs
```

feat(dlm): support configure sharding strategy

---

server/odc-service/src/main/java/com/oceanbase/odc/service/resultset/ResultSetExportTask.java
server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/datatransfer/OBMySQLDataTransferExtension.java
server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/datatransfer/factory/DumpParameterFactory.java

fix several bugs.
1. cherry-pick https://github.com/oceanbase/odc/pull/3254
2. the `DumpParameter#blockSize` was set to an incorrect value. This PR use `BinarySizeUnit` to fix it. fix #3264
3. OB 4.0.0  mysql mode does not support SEQUENCE, we modify the version. fix #3277
Fixes #
```docs
```

fix(data-transfer): fix several data-transfer bugs

---

server/odc-core/src/main/java/com/oceanbase/odc/core/alarm/AlarmEventNames.java
server/odc-server/src/main/java/com/oceanbase/odc/server/OdcServer.java

add server restart alarm
Fixes #
```docs
```

fix(web): add server restart alarm

---

server/odc-common/src/main/java/com/oceanbase/odc/common/dfa/AbstractDfa.java
server/odc-common/src/main/java/com/oceanbase/odc/common/dfa/DfaStateTransfer.java
server/odc-common/src/test/java/com/oceanbase/odc/common/dfa/DfaTest.java
server/odc-common/src/test/java/com/oceanbase/odc/common/dfa/K8sPodStatusDfa.java
server/odc-common/src/test/java/com/oceanbase/odc/common/dfa/K8sPodStatusDfaTransfer.java

type-refactor
move dfa from odc-core to odc-common
Fixes #
```docs
```

refactor(dfa): move it from odc-core to odc-common

---

server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/model/DatabaseChangeParameters.java

type-bug
Create SQL plan failed because the parameter type is unrecognized
Fixes #3211
```docs
```

fix(sql-plan): create sql-plan failed

---

server/odc-core/src/main/resources/i18n/BusinessMessages.properties
server/odc-core/src/main/resources/i18n/BusinessMessages_zh_CN.properties
server/odc-core/src/main/resources/i18n/BusinessMessages_zh_TW.properties

type-bug
The developer localization in the project role shows 'ordinary member', which should be 'developer'
Fixes #3262
```docs
```

fix(apply project):fix developer localized display errors in applying project permission

---

server/odc-service/src/main/java/com/oceanbase/odc/service/datatransfer/dumper/SchemaMergeOperator.java

type-bug
When obdumper generate ddl file for PL objects, the format would be like :
```sql
drop procedure xxx;
delimiter $$
create or replace xxx
...
end;
&&
```
If we merge then straightly, the output would like :
```sql
drop procedure xxx;
delimiter $$
create or replace xxx
...
end;
&&
drop procedure xxx;
delimiter $$
create or replace xxx
...
end;
&&
```
As you can see, the format is incorrect. The delimiter should be restore to `;` after PL objects ends.
Fixes #3306
```docs
```

fix(data-transfer): incorrect schema file would be generated when merge schema

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleTaskService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/PublishSqlPlanJobReq.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/SqlPlanJob.java
server/odc-service/src/main/java/com/oceanbase/odc/service/sqlplan/model/SqlPlanTaskResult.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/SqlPlanTask.java

type-bug
sql plan task add schedule job, the value of task_result is obtained from the job_job.
Fixes #
```docs
```

fix(database-change): missing sql plan task execution result 

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/factory/ScheduleResponseMapperFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/sqlplan/model/SqlPlanParameters.java

type-bug
SQL plan refactoring does not accommodate data from the older versions
Fixes #
```docs
```

fix(sql-plan): detail sql-plan failed

---

server/integration-test/src/test/java/com/oceanbase/odc/metadb/resource/ResourceRepositoryTest.java
server/odc-migrate/src/main/resources/migrate/common/V_4_3_2_8__add_task_resource.sql
server/odc-service/src/main/java/com/oceanbase/odc/metadb/resource/ResourceEntity.java
server/odc-service/src/main/java/com/oceanbase/odc/metadb/resource/ResourceRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/metadb/resource/ResourceSpecs.java
server/odc-service/src/main/java/com/oceanbase/odc/service/resource/ResourceEntityConverter.java
server/odc-service/src/main/java/com/oceanbase/odc/service/resource/ResourceID.java
server/odc-service/src/main/java/com/oceanbase/odc/service/resource/ResourceLocation.java
server/odc-service/src/main/java/com/oceanbase/odc/service/resource/ResourceManager.java
server/odc-service/src/main/java/com/oceanbase/odc/service/resource/ResourceOperator.java
server/odc-service/src/main/java/com/oceanbase/odc/service/resource/ResourceOperatorBuilder.java
server/odc-service/src/main/java/com/oceanbase/odc/service/resource/k8s/DefaultResourceOperatorBuilder.java
server/odc-service/src/main/java/com/oceanbase/odc/service/resource/k8s/K8sResourceOperator.java
server/odc-service/src/main/java/com/oceanbase/odc/service/resource/k8s/builder/BaseNativeK8sResourceOperatorBuilder.java
server/odc-service/src/main/java/com/oceanbase/odc/service/resource/k8s/builder/NativeK8sConfigMapOperatorBuilder.java
server/odc-service/src/main/java/com/oceanbase/odc/service/resource/k8s/builder/NativeK8sPodOperatorBuilder.java
server/odc-service/src/main/java/com/oceanbase/odc/service/resource/k8s/client/NativeK8sJobClient.java
server/odc-service/src/main/java/com/oceanbase/odc/service/resource/k8s/model/K8sConfigMap.java
server/odc-service/src/main/java/com/oceanbase/odc/service/resource/k8s/model/K8sPod.java
server/odc-service/src/main/java/com/oceanbase/odc/service/resource/k8s/model/K8sResource.java
server/odc-service/src/main/java/com/oceanbase/odc/service/resource/k8s/model/QueryResourceParams.java
server/odc-service/src/main/java/com/oceanbase/odc/service/resource/k8s/operator/BaseNativeK8sResourceOperator.java
server/odc-service/src/main/java/com/oceanbase/odc/service/resource/k8s/operator/NativeK8sConfigMapOperator.java
server/odc-service/src/main/java/com/oceanbase/odc/service/resource/k8s/operator/NativeK8sPodOperator.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/NativeK8sJobClient.java
server/odc-service/src/test/java/com/oceanbase/odc/service/resource/k8s/K8SResourceOperatorTest.java
server/odc-service/src/test/java/com/oceanbase/odc/service/resource/k8s/K8sResourceOperatorTest.java

type-refactor
adapting resource modules to workflows
Fixes #
```docs
```

feat(resource): adapting resource modules to workflows 

---

server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/ScheduleController.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/model/ChangeScheduleResp.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/model/ChangeScheduleResponse.java

change response, add changeLog for schedule edit

feat(schedule): adaption for support obcloud operation event

---

server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DataSourceInfoMapper.java

type-bug
Connection creation failed due to an incorrect username when using the sys user.
Fixes #3353 
```docs
```

fix(dlm): create connection failed in oracle

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/SqlPlanJob.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/processor/SqlPlanPreprocessor.java

type-bug
sql plan job set database name as default schema
Fixes #
```docs
```

fix(database-change): sql plan job set database name as default schema

---

server/odc-service/src/main/java/com/oceanbase/odc/service/session/util/DBSchemaExtractor.java

type-bug
Refer to the picture above ,we should display only 'ccc' without 'ccc1';
Fixes #3340
```docs
```

fix(permission): failed to execute sql of renaming table

---

server/integration-test/src/test/java/com/oceanbase/odc/metadb/worksheet/CollaborationWorksheetRepositoryTest.java
server/integration-test/src/test/java/com/oceanbase/odc/service/worksheet/WorksheetServiceFacadeImplTest.java
server/odc-migrate/src/main/resources/migrate/common/V_4_3_2_7__add_collaboration_worksheet.sql
server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/WorksheetController.java
server/odc-service/src/main/java/com/oceanbase/odc/metadb/worksheet/CollaborationWorksheetEntity.java
server/odc-service/src/main/java/com/oceanbase/odc/metadb/worksheet/CollaborationWorksheetRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/WorksheetServiceFacade.java
server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/WorksheetServiceFacadeImpl.java
server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/constants/WorksheetConstants.java
server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/service/DefaultWorksheetService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/service/RepoWorksheetService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/service/WorksheetService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/utils/WorksheetUtil.java
server/odc-service/src/test/java/com/oceanbase/odc/service/worksheet/WorksheetServiceFacadeImplTest.java
server/odc-service/src/test/java/com/oceanbase/odc/service/worksheet/service/DefaultWorksheetServiceTest.java

type-feature
add organizationId and workspaceId to worksheet
Fixes #
```docs
```

feat(worksheet): add organizationId and workspaceId to worksheet

---

server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBTableService.java

type-bug
When generating logical table ddl, it should ignore the logical database name, and use the user-defined logical table expression.
Fixes #3375 
```docs
```

fix(logicaldatabase): wrong generated ddl of creating and altering logical tables

---

server/odc-migrate/src/main/resources/migrate/common/V_4_3_2_6__add_history_resource_last_access.sql

… history_resource_last_access
type-refactor
shorten the length of index index names in history_resource_last_access
Fixes #
```docs
```

refactor(resourcehistory): shorten the length of index index names in history_resource_last_access

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/LogicalDatabaseService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/LogicalTableExtractTask.java

type-bug
Logical database last sync time not set when creating and extracting logical tables.
Fixes #3382 
```docs
```

fix(logicaldatabase): logical database last sync time not shown

---

server/odc-service/src/main/java/com/oceanbase/odc/service/session/util/DBSchemaExtractor.java

type-bug
Fixes #3343
```docs
```

fix(table permission): partition name shouldn't display in the table permission check window

---

script/build_rpm_without_sqlconsole.sh
script/functions.sh

fix(script): local build libs failure

---

server/odc-service/src/main/java/com/oceanbase/odc/service/common/response/batch/BatchOperationResult.java
server/odc-service/src/main/java/com/oceanbase/odc/service/common/response/batch/ResourceOperationResult.java

type-bug
import com.oceanbase.odc.service.common.response.Error for Error in ResourceOperationResult;
add method add in BatchOperationResult
Fixes #
```docs
```

fix(response): error dependency for Error in ResourceOperationResult

---

server/odc-service/src/main/java/com/oceanbase/odc/service/permission/database/ApplyDatabasePermissionPreprocessor.java

type-bug
The logical database has no related data source, which would cause to NPE in `ApplyDatabasePermissionPreprocessor`.
This PR fixed it by ignoring it if the related data source not found.
Fixes #3229 
```docs
```

fix(logicaldatabase): apply logicla database permission caused to NPE

---

server/odc-service/src/main/java/com/oceanbase/odc/service/flow/util/DescriptionGenerator.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/factory/ScheduleResponseMapperFactory.java

type-bug
some information of the schedule lacks, this PR fixed it.
Fixes #3352 
```docs
```

fix(logicaldatabase): project info not shown and schedule description shows 'null'

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/factory/ScheduleResponseMapperFactory.java

type-bug
The logical database does not belong to one data source, so it may cause to NPE.
Fixes #3453 
```docs
```

fix(schedule): get schedule detail may cause NPE in logical database job

---

server/integration-test/src/test/java/com/oceanbase/odc/service/connection/logicaldatabase/LogicalTableFinderTest.java
server/odc-migrate/src/main/resources/migrate/common/V_4_3_2_9__add_logical_database_change_task.sql
server/odc-service/src/main/java/com/oceanbase/odc/metadb/connection/logicaldatabase/DatabaseMappingRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/metadb/connection/logicaldatabase/TableMappingEntity.java
server/odc-service/src/main/java/com/oceanbase/odc/metadb/connection/logicaldatabase/TableMappingRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/LogicalDatabaseSyncManager.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/LogicalTableExtractTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/core/LogicalTableFinder.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/core/model/DataNode.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/table/TableService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/permission/database/ApplyDatabaseFlowableTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/permission/database/ApplyDatabasePermissionPreprocessor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/permission/database/DatabasePermissionService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/permission/database/model/ApplyDatabaseParameter.java
server/odc-service/src/main/java/com/oceanbase/odc/service/permission/table/ApplyTableFlowableTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/permission/table/ApplyTablePermissionPreprocessor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/permission/table/TablePermissionService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/permission/table/model/ApplyTableParameter.java

type-bug
This PR adapts logical database/table permission apply. If grant logical database/table permissions, the related physical databases/tables are also granted together.
Fixes #3230 
```docs
```

fix(logicaldatabase): adapt logical database/table permission apply

---

server/odc-service/src/main/java/com/oceanbase/odc/service/session/factory/OBConsoleDataSourceFactory.java

fix(datasource): fail to access the MySQL data source via a proxy

---

server/odc-service/src/main/java/com/oceanbase/odc/metadb/connection/logicaldatabase/DatabaseMappingRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/LogicalDatabaseService.java

type-bug
This PR add a precheck that guarantee  physical databases who have already belonged to a logical database should not be able to configure again/
Fixes #3219 
```docs
```

fix(logicaldatabase): physical databases who have already belonged to a logical database should not be able to configure again

---

server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/LimitMetric.java
server/odc-core/src/main/resources/i18n/BusinessMessages.properties
server/odc-core/src/main/resources/i18n/BusinessMessages_zh_CN.properties
server/odc-core/src/main/resources/i18n/BusinessMessages_zh_TW.properties

type-feature
add WORKSPACE_COUNT_IN_PROJECT in LimitMetric
Fixes #
```docs
```

feat(shared): add WORKSPACE_COUNT_IN_PROJECT in LimitMetric

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/LogicalTableExtractTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBTableService.java

type-bug
When creating tables, users need to enter a logical table expression, so we need to preHandle the schema and table names; while altering tables, we should not pre handle it because we only need to treat the logical table as the physical table.
Fixes #3448 
```docs
```

fix(logicaldatabase): generate wrong ddl when alter table

---

server/odc-migrate/src/main/resources/migrate/common/V_4_3_2_12__alter_list_user_table_permission_view.sql

type-bug
make the view `list_user_database_permission_view` and `list_user_table_permission_view` DDL from `inner join connect_connection` to `left join connect_connection`, because the logical database does not belong to a connection, and the connection_id will be null.
Fixes #
```docs
```

fix(permission): logical database/table permission not shown

---

server/odc-service/src/main/java/com/oceanbase/odc/service/databasechange/MultipleDatabaseChangePreprocessor.java

type-bug
Fixes #3481
```docs
```

fix(multiple database): all database type must be same in multiple databases task

---

server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/DataBaseController.java

type-bug
The databases list should be order by type and name by default. As the LOGICAL_DATABSE > PHYSICAL_DATABASE，so we just need add type in the front of the name in sort, the direction is ASC.
Fixes #3489 
```docs
```

fix(database): the databases list should be ordered by type and name by default

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/LogicalDatabaseService.java

type-bug
Add a precheck that the physical database count should be less than or equals to 1000.
Fixes #
```docs
```

fix(logicaldatabase): add max physical database count limit in one logical database

---

server/odc-server/src/main/java/com/oceanbase/odc/server/OdcServer.java
server/odc-service/src/main/java/com/oceanbase/odc/config/BeanConfiguration.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/CloudMetadataClient.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/model/ScheduleTaskMapper.java
server/odc-service/src/test/java/com/oceanbase/odc/service/schedule/ScheduleTaskMapperTest.java

type-bug
1. When odc start as task mode, the classes under `modules` are not loaded.
2. Fix update schedule_task failed because parameters_json is null.
3. Add `createDatabaseUser` and `deleteDatabaseUsers` into CloudMetadataClient 
4. Add `ConnectionService#listSkipPermissionCheck` for internal usage

fix(load-data): several bugfix

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/LogicalDatabaseService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/LogicalDatabaseChangeJob.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/LogicalDatabaseChangeTask.java

type-bug
1. When the user executes SQL containing physical databases that do not belong to the logical database, the front-end will crash. The solution is to throw the exception instead and notify users that the database is not found.
2. skip the permission check when publishing tasks to the task framework.
Fixes #3354 #3514 
```docs
```

fix(logicaldatabase): when sql contains physical databases that does not belong to the logical database, the front-end crashes

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/core/executor/execution/ExecutionSubGroupUnit.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/LogicalDatabaseChangeTask.java

Terminal sub-tasks failed. The root cause is to get the wrong parameters. And I optimized terminal logic, making it repeatable.
Fixes #3517 
```docs
```

fix(logicaldatabase): terminal sub-tasks failed

---

server/odc-service/src/main/java/com/oceanbase/odc/service/resource/k8s/builder/NativeK8sDeploymentOperatorBuilder.java
server/odc-service/src/main/java/com/oceanbase/odc/service/resource/k8s/model/K8sDeployment.java
server/odc-service/src/main/java/com/oceanbase/odc/service/resource/k8s/operator/NativeK8sDeploymentOperator.java
server/odc-service/src/main/java/com/oceanbase/odc/service/resource/k8s/status/K8sDeploymentMatcher.java
server/odc-service/src/test/java/com/oceanbase/odc/service/resource/k8s/K8sDeploymentStatusDfaTest.java

type-refactor
The original method of obtaining the pod associated with a deployment is to use the name of the deployment as a prefix to filter, which is not rigorous.
The current filtering method is to use the deployment selector to filter, which can be more accurate
Fixes #
```docs
```

refactor(resource): refactor the logic of getting related pods of a deployment

---

server/odc-service/src/main/java/com/oceanbase/odc/service/flow/util/DescriptionGenerator.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/DefaultApprovalFlowClient.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/model/CreateScheduleReq.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/model/ScheduleChangeParams.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/processor/ScheduleChangePreprocessor.java

type-bug
Set parameters when operating a schedule to select the risk level
Fixes #
```docs
```

fix(schedule): risk level mismatch when operating a schedule

---

server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/OdcJobListener.java
server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/OdcTriggerListener.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/SqlPlanJob.java

type-bug
1. Skip creating schedule tasks for SQL plans and partition plans because it is unnecessary
2. Apply a lock when operating on the scheduleTask to prevent concurrent requests.
Fixes #3511 
```docs
```

fix(sqlplan): generate task failed

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/LogicalDatabaseService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/LogicalDatabaseSyncManager.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/LogicalDatabaseUtils.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/LogicalTableExtractTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/LogicalTableService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/core/executor/execution/ExecutionSubGroupUnit.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/core/executor/execution/GroupExecutionEngine.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/core/executor/sql/SqlExecutionHandler.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/core/model/DataNode.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/LogicalDatabaseChangeJob.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/model/PublishLogicalDatabaseChangeReq.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/ProcessJobCaller.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/LogicalDatabaseChangeTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/listener/DefaultJobTerminateListener.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java

type-bug
1. no logical database extract task is submitted after the logical change task is completed. This is because the job_type is distinguished from cases.
2. optimize the code to reduce useless `ConnectionConfig` passed into the task framework.
Fixes #3525 #3369 
```docs
```

fix(logicaldatabase): no logical database extract task is submitted after the logical change task is completed

---

server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/util/DescriptionGenerator.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/factory/ScheduleResponseMapperFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/DefaultApprovalFlowClient.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/model/CreateScheduleReq.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/model/ScheduleChangeParams.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/processor/ScheduleChangePreprocessor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/listener/DefaultJobTerminateListener.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/processor/DLMResultProcessor.java

fix(dlm): cherry pick from 4.3.x 

---

server/odc-service/src/main/java/com/oceanbase/odc/service/task/listener/DefaultJobProcessUpdateListener.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java

type-bug
1. Remove useless saving results in case of updating status failure. `schedule_task.result_json` is a deprecated column, which may cause updating failure because `text` is short for the result value.
2. In the Proccess mode, skip saving log metadata.
Fixes #3556 
```docs
```

fix(task-framework): remove useless saving results in case of updating status failure

---

server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/DBSchemaIndexService.java

type-bug
Fixes #3442
```docs
```

fix(schema): enable syncing databases by datasource in sql console

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java

fix(schedule): wrong status

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/LogicalDatabaseUtils.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/core/model/DataNode.java
server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBTableService.java
server/odc-service/src/test/java/com/oceanbase/odc/service/connection/logicaldatabase/LogicalDatabaseUtilsTest.java

type-bug
When creating a table, the entire expression should be enclosed in backticks, rather than adding one pair for the database and another for the table. For example, it should be `create table db_[0-3].tb_[0-3](a varchar(32))` instead of `create table db_[0-3].tb_[0-3](a varchar(32))`.
Reasons:
It's more logical as the expression itself is a whole.
We are supporting enumeration syntax, for example, `create table db_1.tb_[1,2], db_2.tb_[7,8]`, where the expression must be treated as a whole before parsing.
Fixes #
```docs
```

fix(logicaldatabase): generated create logical table ddl is wrong

---

server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/OdcJobListener.java
server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/OdcTriggerListener.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/SqlPlanJob.java

* fix execute sqlplan
* fix execute sqlplan
Fixes #
```docs
```

fix(schedule):  cherry pick from 4.3.x

---

pom.xml
server/odc-service/pom.xml
server/odc-service/src/main/java/com/oceanbase/odc/service/datatransfer/DataTransferService.java
server/plugins/task-plugin-ob-mysql/pom.xml
server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/datatransfer/factory/BaseParameterFactory.java
server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/datatransfer/factory/DumpParameterFactory.java
server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/datatransfer/factory/LoadParameterFactory.java

type-fix
revert upgrade ob-loader-dumper version to 4.3.1.1
Fixes # 
Additional documentation e.g., usage docs, etc.:

fix(data-transfer): revert upgrade obloaderdumper 4311

---

server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java

type-bug
Filter out all ALTER_SCHEDULE flow instances in 'all tickets', 'created by me' and 'approving by me'.
The flow instance that created by schedule should be not seen in the tickets. If users want to view them, go to the schedule module.
Fixes #
```docs
```

fix(flow): filter out all ALTER_SCHEDULE flow instances in 'all tickets', 'created by me' and 'approving by me'

---

server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/FlowInstanceController.java
server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/ScheduleController.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowTaskInstanceLoggerService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowTaskInstanceService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleLogProperties.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduledTaskLoggerService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/logger/LogUtils.java

type-feature
Fixes #
the pr is to update the obcloud code about read log.
```docs
```

feat(schedule): cherry-pick the new read log code to obcloud

---

pom.xml

feat(dlm): upgrade dlm sdk version to 1.1.6

---

pom.xml

feat(dlm): upgrade dlm sdk to 1.1.6

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/processor/AbstractDlmPreprocessor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/processor/DataArchivePreprocessor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/processor/DataDeletePreprocessor.java

fix(dlm): check datasource cloud provider and region

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/factory/ScheduleResponseMapperFactory.java

type-bug
detail database failed if dss throw exception when get datasource info
Fixes #
```docs
```

fix(schedule): detail schedule failed

---

server/modules/sample-module/src/main/java/com/oceanbase/odc/service/sample/SampleService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/project/ProjectService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/LogicalDatabaseChangeService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleChangeLogService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/WorksheetServiceFacadeImpl.java

security
some method lacks permission check or `@SkipAuthorize`
Fixes #
```docs
```

security: some method lacks permission check

---

server/odc-service/src/main/java/com/oceanbase/odc/metadb/dbobject/DBObjectRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/LogicalDatabaseChangeService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/LogicalTableExtractTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/LogicalTableService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/core/LogicalTableFinder.java
server/odc-service/src/main/java/com/oceanbase/odc/service/permission/database/ApplyDatabasePermissionPreprocessor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/permission/database/model/ApplyDatabaseParameter.java

type-bug
1. Exclude the physical tables that have already belonged to a logical table.
2. Ignore those logical tables that have only one physical table.
3. Show more details for the front-end in the API
Fixes #3544 #3564 
```docs
```

fix(logicaldatabase): several bugfixes when extacting logical databases and showing the databases

---

server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/ExecutorEndpointManager.java

security: add @SkipAuthorize annotation

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/processor/AbstractDlmPreprocessor.java

type-bug
validate all columns is no null for unique key in mysql.
Fixes #
```docs
```

fix(dlm): OOM occurs when a table's unique key contains nullable columns

---

server/integration-test/src/test/java/com/oceanbase/odc/metadb/schedule/ScheduleChangeLogRepositoryTest.java
server/odc-service/src/main/java/com/oceanbase/odc/metadb/schedule/ScheduleChangeLogRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleChangeLogService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/processor/ScheduleChangePreprocessor.java

fix(schedule): wrong status when a schedule change is rejected

---

server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMJobStore.java

fix(dlm): update rate limit failed

---

server/odc-migrate/src/main/java/com/oceanbase/odc/migrate/AbstractMetaDBMigrate.java
server/odc-migrate/src/main/java/com/oceanbase/odc/migrate/AbstractMigrate.java
server/odc-migrate/src/main/java/com/oceanbase/odc/migrate/VectorDBMigrate.java
server/odc-migrate/src/main/java/com/oceanbase/odc/migrate/jdbc/vectordb/V2001PlaceholderMigrate.java
server/odc-migrate/src/main/resources/migrate/vectordb/V_2_0_0__placeholder.sql
server/odc-service/pom.xml
server/odc-service/src/main/java/com/oceanbase/odc/config/BaseLockConfiguration.java
server/odc-service/src/main/java/com/oceanbase/odc/config/MetaDBConfiguration.java
server/odc-service/src/main/java/com/oceanbase/odc/config/MetaDBLockConfiguration.java
server/odc-service/src/main/java/com/oceanbase/odc/config/VectorDBConfiguration.java
server/odc-service/src/main/java/com/oceanbase/odc/config/VectorDBLockConfiguration.java

type-feat
add a vectordb configuration for ai application
Fixes #
```docs
```

feat(vectordb): add a vectordb configuration for ai application

---

server/odc-core/src/main/resources/i18n/BusinessMessages.properties
server/odc-core/src/main/resources/i18n/BusinessMessages_zh_CN.properties
server/odc-core/src/main/resources/i18n/BusinessMessages_zh_TW.properties

add internationalizaiton for data archive task

i18n: add internationalizaiton for data archive task

---

server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/OscTableUtil.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/oscfms/action/CreateGhostTableAction.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/oscfms/action/oms/OmsCleanResourcesAction.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/oscfms/action/oms/OmsSwapTableAction.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/validator/OnlineSchemaChangeValidator.java

type-feature
1. check ghost table not exist before dispatch flow task to guarantee ghost table must be created by osc task
2. drop ghost table when clean resources cause ghost table must be created by osc task
3. fix clean resource not handle exception correctly when release oms resource
Fixes #
```docs
```

feat(osc): check ghost table not exist before dispatch flow task

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/processor/AbstractDlmPreprocessor.java

fix(dlm): NPE when create task

---

server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/MySQLOfflineDdlExists.java
server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/OracleOfflineDdlExists.java
server/odc-service/src/test/java/com/oceanbase/odc/service/sqlcheck/MySQLCheckerTest.java

type-bug
a specific sql will lead to npe
the sql is as bellow 
```sql
ALTER TABLE `teacher_relation` CHANGE `bind_time` `bind_time` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT 'xxx';
```
Fixes #3612 
```docs
```

fix(sql-check): a specific sql will lead to npe

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleTaskService.java

type-refactor
Fixes #
```docs
```

refactor(schedule): add listByJobNames to ScheduleTaskService

---

server/odc-service/src/main/java/com/oceanbase/odc/service/session/interceptor/SqlExecuteInterceptorService.java

type-feature
add sql.execute.interceptor.enabled to control whether SQL check\console... interceptor is enabled or not
Fixes #
```docs
```

feat(sql): add sql.execute.interceptor.enabled

---

server/odc-core/src/main/resources/i18n/BusinessMessages.properties
server/odc-core/src/main/resources/i18n/BusinessMessages_zh_CN.properties
server/odc-core/src/main/resources/i18n/BusinessMessages_zh_TW.properties
server/odc-core/src/main/resources/i18n/ErrorMessages_zh_CN.properties
server/odc-core/src/main/resources/i18n/ErrorMessages_zh_TW.properties

type-feature
change  i18n message of workspace and worksheet
Fixes #
```docs
```

feat(i18n): change message of workspace and worksheet

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/SqlPlanJob.java

type-bug
fix datasource can not connect
Fixes #
```docs
```

fix(database-change):datasource can not connect

---

server/odc-service/src/main/java/com/oceanbase/odc/service/workspace/adapter/WorkspaceDataSourceAdapter.java
server/odc-service/src/main/java/com/oceanbase/odc/service/workspace/model/CreateWorkspaceReq.java
server/odc-service/src/main/java/com/oceanbase/odc/service/workspace/model/UpdateWorkspaceInstanceAccountReq.java
server/odc-service/src/main/java/com/oceanbase/odc/service/workspace/model/UpdateWorkspaceReq.java

type-feature
decouple odc-workspace and obcloud-starter by moving WorkspaceDataSourceAdapter from odc-workspace to odc-service.
Fixes #
```docs
```

feat(workspace): move WorkspaceDataSourceAdapter from odc-workspace to odc-service

---

server/odc-server/pom.xml

type-bug
There is an error in the bash script in the `server/odc-server/pom.xml`  file. This will result in the docker image built without installation of obclient
Fixes https://github.com/oceanbase/odc/issues/3616
```docs
```

fix(build): obclient installation is missing from the ODC image

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/SqlPlanJob.java

type-bug
Fixed an issue where the database connection failed due to invalid password
Fixes #
```docs
```

fix(database-change): database connect failed  due to password invalid

---

server/integration-test/src/test/java/com/oceanbase/odc/service/objectstorage/client/OSSCloudObjectStorageClientTest.java
server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/client/CloudObjectStorageClient.java
server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/client/LocalObjectStorageClient.java
server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/client/ObjectStorageClient.java
server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/cloud/CloudObjectStorage.java
server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/cloud/CloudObjectStorageService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/cloud/client/AlibabaCloudClient.java
server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/cloud/client/AmazonCloudClient.java
server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/cloud/client/NullCloudClient.java

type-feature
add generatePresignedUrlWithCustomFileName, which can custom set filename in generatePresignedUrl
Fixes #
```docs
```

feat(objectstorage): add generatePresignedUrlWithCustomFileName

---

server/integration-test/src/test/java/com/oceanbase/odc/service/resourcehistory/ResourceLastAccessServiceTest.java
server/odc-service/src/main/java/com/oceanbase/odc/metadb/resourcehistory/ResourceLastAccessRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/service/resourcehistory/ResourceLastAccessService.java

type-feature
add batchAdd in ResourceLastAccessService
Fixes #
```docs
```

feat(resourcehistory): add batchAdd in ResourceLastAccessService

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/OBInstance.java

add region and cloudProvider into OBInstance.

fix(load-data): add instanceId and tenantId into OBInstance

---

server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/ScheduleController.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java

fix(databaseChange): fail to  filter database changes by organization

---

server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/client/CloudObjectStorageClient.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/SqlPlanTask.java

type-bug
Return the input stream before closing it, and ensure to close the stream after its usage is complete.
Return the input stream before closing it, and ensure to close the stream after its usage is complete.
Fixes #
```docs
```

fix(database-change): get object input stream error

---

server/odc-service/src/main/java/com/oceanbase/odc/service/loaddata/model/LoadDataResource.java

type-feature
add dataset id into LoadDataResource

feat(dataset): add dataset id into LoadDataResource

---

server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/SqlPlanTask.java

type-bug
1. add log printf
2. resolve the issue with sql plan execution failure
Fixes #
```docs
```

fix(database-change): sql plan task execute failed

---

server/odc-service/src/main/java/com/oceanbase/odc/service/iam/auth/OrganizationAuthenticationInterceptor.java

type-factor
skip the OrganizationAuthenticationInterceptor when request schedule task full log download

refator(schedule): add schedule task full log download url to OrganizationAuthenticationInterceptor whiteList

---

server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/client/CloudObjectStorageClient.java
server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/client/LocalObjectStorageClient.java
server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/client/ObjectStorageClient.java
server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/cloud/CloudObjectStorageService.java

type-feature
support get abortable object stream

feat(object-storage): support get abortable object stream

---

server/odc-service/src/main/java/com/oceanbase/odc/service/iam/auth/AuthenticationFacade.java
server/odc-service/src/main/java/com/oceanbase/odc/service/iam/auth/DefaultAuthenticationFacade.java
server/starters/web-starter/src/main/java/com/oceanbase/odc/service/iam/auth/WebAuthenticationFacade.java

type-feature
add currentProjectId in AuthenticationFacade
Fixes #
```docs
```

feat(authentication): add currentProjectId in AuthenticationFacade

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleTaskConfiguration.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/DefaultApprovalFlowClient.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/NoApprovalFlowClient.java

fix(approval): default no approval in obcloud

---

server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/logger/LogBizImpl.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/server/TaskMonitor.java

fix(taskframework): cannot release pod if OSS initialization fails

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/ConnectionConfig.java

fix(datasource): missing tenantName and instanceName in data source details

---

.scanignore
.secignore
server/odc-common/src/main/java/com/oceanbase/odc/common/security/SensitiveDataUtils.java
server/odc-common/src/test/java/com/oceanbase/odc/common/security/SensitiveDataUtilsTest.java

feat(common): sensitive data utils support mask json

---

server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMService.java

update final status to failed if create pod timeout
fix the issue of wrong status if create pod timeout
Fixes #
```docs
```

fix(dlm): the status is incorrect if creating the pod timeout

---

server/odc-service/src/main/java/com/oceanbase/odc/service/sqlplan/model/SqlPlanTaskResult.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/SqlPlanTask.java

type-bug
1 .Fixed a bug where sql attachment execution failed.
2.Sql attachment display added to the Task Details page.
Fixes #
```docs
```

fix(database-change): sql plan task execute file script failed

---

server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/ErrorCodes.java
server/odc-core/src/main/resources/i18n/ErrorMessages.properties
server/odc-core/src/main/resources/i18n/ErrorMessages_zh_CN.properties
server/odc-core/src/main/resources/i18n/ErrorMessages_zh_TW.properties

type-feature
add ErrorCodes: WorkspaceDatabaseUserTypeMustBeAdmin
Fixes #
```docs
```

fix(errorcodes): add ErrorCodes: WorkspaceDatabaseUserTypeMustBeAdmin

---

server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/model/DataDeleteParameters.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/processor/DataArchivePreprocessor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/processor/DataDeletePreprocessor.java

type-bug
Set the default sharding strategy only when the request parameter is nul
Fixes #
```docs
```

fix(dlm): custom sharding strategy being ineffective

---

pom.xml
server/odc-service/pom.xml
server/odc-service/src/main/java/com/oceanbase/odc/service/datatransfer/DataTransferService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/loaddata/model/ObjectStorageConfig.java
server/plugins/task-plugin-ob-mysql/pom.xml
server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/datatransfer/factory/BaseParameterFactory.java
server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/datatransfer/factory/DumpParameterFactory.java
server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/datatransfer/factory/LoadParameterFactory.java

upgrade ob-loader-dumper version to 4.3.1.1.
Please note that when this branch is merged into the master or other dev branches, the version of ob-loader-dumper is based on the target branch

feat(data-transfer): upgrade ob-loader-dumper version to 4.3.1.1 (#3247)

---

server/odc-service/src/main/java/com/oceanbase/odc/metadb/connection/DatabaseRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBPLService.java

type-bug
PL Debug will fail when there are databases with the same name under the data source (one exists and one does not).
The root cause is that the query sql does not add `is_existed=true` in the where condition.
Fixes #3649
```docs
```

fix(pl): PL debug will fail when there are databases with the same name under the data source (one exists and one does not)

---

server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/OnlineSchemaChangeFlowableTask.java
server/odc-service/src/test/java/com/oceanbase/odc/service/onlineschemachange/OnlineSchemaChangeFlowableTaskTest.java

type-bug
when osc task entry oms monitor step and full transfer progress is zero,  task result will not update, cause progress variable not changed. 
compare oms step info to force update task result.
Fixes #
```docs
```

fix(osc): osc task result not update when oms step info changed

---

server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/OnlineSchemaChangeFlowableTask.java
server/odc-service/src/test/java/com/oceanbase/odc/service/onlineschemachange/OnlineSchemaChangeFlowableTaskTest.java

* fix osc task result not update when oms step changed
* fix osc task result not update when oms step changed
type-bug
when osc task entry oms monitor step and full transfer progress is zero, task result will not update, cause progress variable not changed.
compare oms step info to force update task result.
Fixes #
```docs
```

fix(osc): osc task result not update when oms step info changed 

---

server/odc-service/src/main/java/com/oceanbase/odc/service/loaddata/model/ObjectStorageConfig.java

type-bug
fix start ob-loader without region

fix(load-data): fix start load task without region

---

server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/SqlPlanTask.java

type-bug
Fixed an issue where the flow was closed during task executio.
Fixes #
```docs
```

fix(database-change): stream closesed during task execution

---

pom.xml
server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/model/DataDeleteParameters.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/DataArchiveTask.java

[WIP] fix(dlm): upgrade dlm sdk version to 1.1.6.bp

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java

type-bug
Fix the PR #3688 , wrong order of the parameters passing to the method.
Fixes #
```docs
```

fix(collaboration): databases' environment have not been updated after the datasource's environment changed

---

server/odc-migrate/src/main/java/com/oceanbase/odc/migrate/jdbc/common/R4237DefaultRuleApplyingMigrate.java
server/odc-migrate/src/main/java/com/oceanbase/odc/migrate/jdbc/common/V43213CustomizedRuleMigrate.java
server/odc-service/src/main/java/com/oceanbase/odc/metadb/regulation/ruleset/RulesetRepository.java

type-bug
The root cause is that the customized ruleset does not involve the new rules after upgrading ODC versions.
The solution is:
1. All the customized rules will be disabled by default.
2. All the customized rules' default values will follow the value of the built-in default environment.
Additionally, as some users have already upgraded to ODC 4.3.2, I added another script to migrate the rules that added in ODC 4.3.2, and the script is repeatable, so it's safe for other users who want to upgrate from a lower version to 4.3.2-bp1 directly.
Fixes #3651
```docs
```

fix(rule): Executing SQLs occurs NPE when the database belongs to a customized environment after upgrading to 4.3.2

---

server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/SqlPlanTask.java

type-bug
fix task execute sql content failed
Fixes #
```docs
```

fix(database-change): task execute sql content failed

---

server/odc-service/src/main/java/com/oceanbase/odc/metadb/schedule/ScheduleRepository.java

type-bug
The `creatorIds` field in QueryScheduleParams is not valid.

fix(schedule): the creatorIds field in QueryScheduleParams is not valid

---

server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/SqlPlanTask.java

type-bug
fix task status error
Fixes #
```docs
```

fix(database-change): task status error

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/factory/ScheduleResponseMapperFactory.java

fix(schedule):  pick schedule fix from obcloud 202409

---

pom.xml
server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/model/DataDeleteParameters.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/DataArchiveTask.java

* upgrade dlm sdk version to 1.1.6.bp
* fix
* bugfix
Fixes #
```docs
```

fix(dlm): cherry pick bug fix from 4.3.2bp to 24v4

---

server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/SqlPlanTask.java

type-bug
fix sql content delimiter invalid
Fixes #
```docs
```

fix(database-change): sql content delimiter invalid

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/ConnectionConfig.java

type-bug
return dss datasource id when detail datasource
Fixes #
```docs
```

fix(datasource): no return DSS datasource id

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java

type-bug
allow delete finished schedule
Fixes #
```docs
```

fix(database-chabge): allow delete finished schedule

---

server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java

fix(task-framework): starting the job twice

---

server/odc-core/src/main/java/com/oceanbase/odc/core/datasource/SingleConnectionDataSource.java

type-bug
npe will be thrown when calling get connection concurrently
Fixes #
```docs
```

fix(datasource): npe will be thrown when calling get connection concurrently

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/server/ExecutorRequestHandler.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/server/TaskMonitor.java

fix(schedule): fail to filter by tenantId and clusterId

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionService.java

type-bug
ob multi cloud cancel permission verification
Fixes #
```docs
```

fix(database-change): ob multi cloud cancel permission verification

---

server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/DoCancelingJob.java

fix(task-framework): check job status before cancel

---

server/odc-service/src/main/java/com/oceanbase/odc/service/session/OBQueryProfileExecutionListener.java

set observer's version to 4.3.3.1

fix(query-profile): set observer's version to 4.3.3.1

---

server/integration-test/src/test/java/com/oceanbase/odc/metadb/task/JobRepositoryTest.java
server/odc-service/src/main/java/com/oceanbase/odc/metadb/task/JobRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/processor/LoadDataResultProcessor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java

fix https://github.com/oceanbase/odc/pull/3721
only update load data task result, To avoid possible state errors

fix(taskframework): update load data task result only

---

server/integration-test/src/test/java/com/oceanbase/odc/metadb/connection/DatabaseRepositoryTest.java
server/odc-service/src/main/java/com/oceanbase/odc/metadb/connection/DatabaseRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/table/TableService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/GlobalSearchProperties.java
server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/syncer/column/AbstractDBColumnSyncer.java
server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/syncer/object/AbstractDBObjectSyncer.java

type-bug
any exception happened is database syncing will lead to 'PENDING' status and `object_last_sync_time` is null
database will never be syncing when such situation happened, this pr fix this problem.
Fixes #3730
```docs
```

fix(global-search): failed to sync database which get 'PENDING' status and 'object_last_sync_time' is null

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleTaskService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/listener/DefaultJobProcessUpdateListener.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/processor/DLMResultProcessor.java

fix(taskframework): abnormal status caused by concurrent updates

---

server/odc-service/src/main/java/com/oceanbase/odc/service/db/session/DefaultDBSessionManage.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/oms/client/BaseOmsClient.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/rename/LockUserInterceptor.java
server/odc-service/src/test/java/com/oceanbase/odc/service/onlineschemachange/rename/LockUserInterceptorTest.java

type-bug
if user in user@'ip' format, list user and list session will not match any user, that will ignore lock user and kill session operation which leads to data loss
Notice: this pr has a amplify impact for kill user range. eg if user choose lock user1@ip1, and it has use1@ip2 account as well.   user@ip1 and user @ip2 will both be locked and killed
Fixes #
```docs
```

fix(osc): remove ip mask when match user and session

---

server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/FlowTaskSubmitter.java
server/odc-service/src/main/java/com/oceanbase/odc/service/monitor/DefaultMeterName.java
server/odc-service/src/main/java/com/oceanbase/odc/service/monitor/InMemoryMeterManager.java
server/odc-service/src/main/java/com/oceanbase/odc/service/monitor/MeterKey.java
server/odc-service/src/main/java/com/oceanbase/odc/service/monitor/MeterName.java
server/odc-service/src/main/java/com/oceanbase/odc/service/monitor/MonitorConfiguration.java
server/odc-service/src/main/java/com/oceanbase/odc/service/monitor/datasource/GetConnectionFailedEventListener.java
server/odc-service/src/main/java/com/oceanbase/odc/service/monitor/session/ConnectionSessionMonitorListener.java
server/odc-service/src/main/java/com/oceanbase/odc/service/monitor/session/SessionMetrics.java
server/odc-service/src/main/java/com/oceanbase/odc/service/monitor/task/job/JobMonitorListener.java
server/odc-service/src/main/java/com/oceanbase/odc/service/monitor/task/schdule/ScheduleMetrics.java
server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/executor/AbstractQuartzJob.java
server/odc-service/src/main/java/com/oceanbase/odc/service/state/StateRouteAspect.java

efactor MeterName to interface and exclude repository metrics
Fixes #
```docs
```

refactor(monitor): refactor MeterName to interface and exclude repository metrics

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/DBSessionResp.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/ConnectSessionService.java

fix(session): session status typo

---

pom.xml
server/odc-service/pom.xml
server/odc-service/src/main/java/com/oceanbase/odc/service/datatransfer/DataTransferService.java
server/plugins/task-plugin-ob-mysql/pom.xml
server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/datatransfer/factory/BaseParameterFactory.java
server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/datatransfer/factory/DumpParameterFactory.java
server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/datatransfer/factory/LoadParameterFactory.java

upgrade ob-loader-dumper to 4.3.1.1
copy from #3247

feat(load-data): upgrade ob-loader-dumper to 4.3.1.1

---

server/odc-service/src/main/java/com/oceanbase/odc/metadb/schedule/ScheduleTaskSpecs.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleTaskService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/model/QueryScheduleTaskParams.java

type-bug
add list task by creator
Fixes #
```docs
```

fix(schedule): list task by creator invalid

---

server/odc-service/src/main/java/com/oceanbase/odc/service/task/Task.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/base/BaseTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/DefaultTaskResult.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/TaskMonitor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/TaskResult.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/listener/DefaultJobProcessUpdateListener.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/state/JobStatusFsm.java
server/odc-service/src/test/java/com/oceanbase/odc/service/task/status/JobStatusFsmTest.java

type-feature
let task get status return TaskStatus, That means task will not known nothing about job. job status will be refreshed depends on task status
Fixes #
```docs
```

feat(task): refactor task getStatus interface return TaskStatus instead of JobStatus

---

server/odc-service/src/main/java/com/oceanbase/odc/service/resource/k8s/builder/NativeK8sConfigMapOperatorBuilder.java
server/odc-service/src/main/java/com/oceanbase/odc/service/resource/k8s/builder/NativeK8sDeploymentOperatorBuilder.java
server/odc-service/src/main/java/com/oceanbase/odc/service/resource/k8s/builder/NativeK8sPodOperatorBuilder.java
server/odc-service/src/main/java/com/oceanbase/odc/service/resource/k8s/builder/NativeK8sServiceOperatorBuilder.java

type-refactor
remove useless exception stack printing
Fixes #
```docs
```

refactor(resource): remove useless exception stack printing

---

server/odc-server/src/main/resources/config/application.yml
server/odc-server/src/main/resources/data.sql
server/odc-service/src/main/java/com/oceanbase/odc/config/BeanConfiguration.java

type-security
use secure cookie setting 'secure' and 'http-only' for http session

secure(framework): enable secure cookie for http session

---

server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/OnlineSchemaChangeFlowableTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/OscService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/oscfms/ActionScheduler.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/oscfms/OscActionFsmBase.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/oscfms/action/YieldContextAction.java
server/odc-service/src/test/java/com/oceanbase/odc/service/onlineschemachange/OnlineSchemaChangeFlowableTaskTest.java

type-bug
1.mdc is static variable and may be set by other thread. MDC not enduring. so different ODC node have different value maybe. resume and switch osc operation will lead to unknown result of MDC. use information stored to build MDC info
2. fix session leak
3. status change will always trigger result update  for task result column
Fixes #
```docs
```

fix(osc):  mdc context may not correct

---

server/odc-service/src/main/java/com/oceanbase/odc/service/notification/helper/ChannelConfigValidator.java

type-security
User would use some illegal characters to invoke SSRF attack. We should filter these characters.

security(notification): filter illegal characters in notification webhook

---

server/odc-service/src/main/java/com/oceanbase/odc/service/session/factory/OBSysUserDataSourceFactory.java

fix(session): use sys datasource may database not exits

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java

type-feature
Check  the  validity  of  the  schedule  and  terminate  any  invalid  ones,  such  as:
1. The status of the schedule is not enabled.
2. The database is invalid or does not belong to the current project.
3. The project is archived.
Fixes #
```docs
```

feat(schedule): check the validity of the task each time it is scheduled

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/ConnectionConfig.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/ddl/OscDBAccessorFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/foreignkey/BaseForeignKeyHandler.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/oscfms/OscActionFsmBase.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/oscfms/action/CreateGhostTableAction.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/oscfms/action/oms/OmsCreateDataTaskAction.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/rename/ForeignKeyInterceptor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/rename/LockTableInterceptor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/rename/LockUserInterceptor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/rename/RenameTableHandlers.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/factory/DefaultConnectSessionFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/factory/OBConsoleDataSourceFactory.java

type-bug
for  osc situation, we should guarantee all command is send by one connection. CONSOLE_DATASOURCE with single connection is right choose.
Fixes #
```docs
```

fix(osc): correct osc session get key to CONSOLE_DATASOURCE

---

server/odc-service/src/main/java/com/oceanbase/odc/service/partitionplan/model/PartitionPlanConfig.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/model/ScheduleMapper.java

fix(schedule): can map PartitionPlan paramter

---

server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/cloud/CloudResourceConfigurations.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduledTaskLoggerService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/logger/LogUtils.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/TaskFrameworkService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/util/CloudObjectStorageServiceBuilder.java

security-bug
Because the server only authenticates and verifies the `scheduleId`, but does not verify whether a `scheduleTaskId` belongs to the `scheduleId`, the problem that arises is that if I have a verified `scheduleId`, I can access any other scheduleTask resource.
There is some code in the logging module that only fits `obcloud_202409`, so it is included this time
Fixes #
```docs
```

security:  follow a authenticated schedule id allows you to perform operations on any other schedule tasks

---

server/odc-service/src/main/java/com/oceanbase/odc/service/monitor/MeterKey.java

fix(monitor): meterKey construct use interface

---

server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/OdcTriggerListener.java

fix(alarm): delete duplicate alarm

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/table/TableService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/DBSchemaSyncService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/syncer/DBSchemaSyncer.java
server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/syncer/column/AbstractDBColumnSyncer.java
server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/syncer/object/AbstractDBObjectSyncer.java
server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/syncer/object/DBExternalTableSyncer.java
server/odc-service/src/main/java/com/oceanbase/odc/service/feature/VersionDiffConfigService.java

fix(external table):get table and external table together without exception

---

server/integration-test/src/test/java/com/oceanbase/odc/service/task/TaskApplicationTest.java
server/odc-core/src/main/java/com/oceanbase/odc/core/alarm/AlarmUtils.java
server/odc-server/pom.xml
server/odc-server/src/main/java/com/oceanbase/odc/agent/TaskApplication.java
server/odc-server/src/main/java/com/oceanbase/odc/agent/runtime/ExecutorRequestHandler.java
server/odc-server/src/main/java/com/oceanbase/odc/agent/runtime/TaskMonitor.java
server/odc-server/src/main/java/com/oceanbase/odc/agent/runtime/TaskRuntimeInfo.java
server/odc-server/src/main/java/com/oceanbase/odc/agent/runtime/ThreadPoolTaskExecutor.java
server/odc-server/src/test/java/com/oceanbase/odc/agent/runtime/TaskMonitorTest.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/TaskEventListener.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/base/BaseTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/base/databasechange/DatabaseChangeTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/base/precheck/PreCheckTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/base/rollback/RollbackPlanTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/base/sqlplan/SqlPlanTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/DefaultTaskResultBuilder.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/DestroyResourceJob.java
server/odc-service/src/test/java/com/oceanbase/odc/service/task/executor/task/BaseTaskTest.java

type-feature
1. move redundant class member out of base task
2. let task executor depends on Task instead of BaseTask
Fixes #
```docs
```

feat(task): refactor base task, let it not be force depended any more

---

server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/cloud/util/CloudObjectStorageUtil.java

type-security
When generating and using object key , we didn't validate whether the user id is consistent with the object . So in some scenarios, attackers may be able to directly access files after obtaining the object keys of certain users.

security(object-storage): add user id into object key

---

server/odc-server/src/main/resources/data.sql

change default setting for cookie secure from true to false,
for avoid http depolyment not works by default.

feat(web): session cookie secure default false

---

server/odc-service/src/main/java/com/oceanbase/odc/metadb/connection/ConnectionConfigRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionService.java

type-bug
Data source sync failed due to wrong SQL. This PR fixed the SQL.
Fixes #
```docs
```

fix(datasource): data source sync failed

---

server/integration-test/src/test/java/com/oceanbase/odc/metadb/connection/ConnectionConfigRepositoryTest.java

type-bug
Add unit test cases
Fixes #
```docs
```

fix(datasource): add unit tests for sync data source

---

server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMJobStore.java

fix(dlm): do not print logs if the data source is uninitialized

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/monitor/InMemoryMeterManager.java
server/odc-service/src/main/java/com/oceanbase/odc/service/monitor/MeterManager.java
server/odc-service/src/main/java/com/oceanbase/odc/service/monitor/MonitorAutoConfiguration.java
server/odc-service/src/main/java/com/oceanbase/odc/service/monitor/datasource/ConnectFailedListenerDelegate.java
server/odc-service/src/main/java/com/oceanbase/odc/service/monitor/datasource/EventStore.java
server/odc-service/src/main/java/com/oceanbase/odc/service/monitor/datasource/GetConnectionFailedEventListener.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/factory/DefaultConnectSessionFactory.java

fix(session): DefaultConnectSessionFactory will failed if not in spring context

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java

fix(schedule): correct the status when scheduling tasks

---

server/odc-service/src/main/java/com/oceanbase/odc/service/db/session/DefaultDBSessionManage.java

type-bug
When judging if it supports kill session/query, return false if it's a logical session.
Fixes #
```docs
```

fix(session): disable kill session/query for logical database session

---

server/odc-service/src/main/java/com/oceanbase/odc/service/flow/util/DescriptionGenerator.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleTaskConfiguration.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/util/DefaultScheduleDescriptionGenerator.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/util/ScheduleDescriptionGenerator.java

type-bug
Customize description generator according to different environments
Fixes #
```docs
```

fix(schedule): customize description generator according to different environments

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/DBSessionResp.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/ConnectSessionService.java

fix(session): put killCurrentQuerySupported into session

---

server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/LimitMetric.java
server/odc-core/src/main/resources/i18n/BusinessMessages.properties
server/odc-core/src/main/resources/i18n/BusinessMessages_zh_CN.properties
server/odc-core/src/main/resources/i18n/BusinessMessages_zh_TW.properties
server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DlmLimiterService.java

type-feature
FYI
Fixes #
```docs
```

fix(dlm): opt error message when editing the limit configuration

---

server/odc-service/src/main/java/com/oceanbase/odc/config/ScheduleConfiguration.java

This PR cherry-picks PR #3829 manually.
Fixes #
```docs
```

optimization(datasource): optimize data source sync thread pool config

---

server/odc-service/src/main/java/com/oceanbase/odc/config/ScheduleConfiguration.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/DatabaseSyncSchedules.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/ConnectionSyncErrorReason.java

type-bug
This PR fixed two issues:
1. The `RejectedExecutionHandler` of the `syncDatabaseTaskExecutor` is `DiscardPolicy` which would cause to miss the datasources for sync. The solution is to use `CallerRunsPolicy`.
2. It didn't consider the situation where the tenant did not exist. This solution adds the handler by parsing the error message.
Fixes #
```docs
```

fix(datasource): datasource sync failed

---

server/odc-common/src/main/java/com/oceanbase/odc/common/util/ExceptionUtils.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/DefaultTaskResultBuilder.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/listener/DefaultJobTerminateListener.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/listener/JobTerminateEvent.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java
server/odc-service/src/test/java/com/oceanbase/odc/service/task/executor/task/BaseTaskTest.java

fix(task): add task framework error message

---

server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/OdcTriggerListener.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java

type-feature
Fixes #
```docs
```

enhancement(schedule): alarm based on specific error messages

---

libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/parser/ParserUtil.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/parser/constant/SqlType.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/parser/listener/MysqlModePLParserListener.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/parser/listener/MysqlModeSqlParserListener.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/parser/listener/OracleModePLParserListener.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/parser/listener/OracleModeParserListener.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/parser/listener/OracleModeSqlParserListener.java
libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/parser/PLParserTest.java
libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/parser/ParserUtilTest.java
libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/parser/SqlParserTest.java
server/odc-migrate/src/main/resources/init-config/init/regulation-rule-metadata.yaml
server/odc-service/src/main/java/com/oceanbase/odc/service/session/interceptor/SqlConsoleInterceptor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/model/SqlExecuteResult.java

type-feature
sql console adapt sql type extension.
The following syntax types are supported:
1. COMMENT ON COLUMN table_name.column_name IS 'XXX';
2. CALL procedureName();
3. SET SESSION time_zone = '+00:00';
4. ALTER SESSION SET time_zone = '+00:00';
Fixes #
```docs
```

feat(sql console rule): sql console adapt sql type of call ,comment on and set session

---

server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/ErrorCodes.java
server/odc-core/src/main/resources/i18n/ErrorMessages.properties
server/odc-core/src/main/resources/i18n/ErrorMessages_zh_CN.properties
server/odc-core/src/main/resources/i18n/ErrorMessages_zh_TW.properties

… version conflict error
type-feature
add EditVersionConflict in ResourceType for general version conflict error
Fixes #
```docs
```

feat(ErrorCodes): add EditVersionConflict in ResourceType 

---

server/odc-service/src/main/java/com/oceanbase/odc/service/loaddata/model/DataBaseInstanceCredential.java
server/odc-service/src/main/java/com/oceanbase/odc/service/loaddata/model/LoadDataParameters.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleTaskService.java

type-feature
LoadData use datasourceId instead of instanceId and tenantId

feat(loaddata): support dss datasource

---

server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/LimitMetric.java
server/odc-core/src/main/resources/i18n/BusinessMessages.properties
server/odc-core/src/main/resources/i18n/BusinessMessages_zh_CN.properties
server/odc-core/src/main/resources/i18n/BusinessMessages_zh_TW.properties

…SHBOARD in LimitMetric
type-feature
add DASHBOARD_COUNT_IN_WORKSPACE/CHART_COUNT_IN_DASHBOARD in LimitMetric
Fixes #
```docs
```

feat(LimitMetric): add DASHBOARD_COUNT_IN_WORKSPACE/CHART_COUNT_IN_DASHBOARD in LimitMetric

---

server/odc-service/src/main/java/com/oceanbase/odc/service/db/session/DBSessionService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/ConnectSessionService.java

fix(session): logical session status will npe 

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleTaskService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/logger/LogBizImpl.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/server/TaskMonitor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/listener/DefaultJobProcessUpdateListener.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java

fix(taskframework): merge 24v4 into 202407

---

server/odc-service/src/main/java/com/oceanbase/odc/service/session/OBQueryProfileExecutionListener.java

(cherry picked from commit aaefe64e5f96838b94bcda7940feddfa38bcd292)

fix(query-profile): set observer's version to 4.3.3.1 (#3723)

---

server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/DBTableController.java

enhancement(external table):add swagger annotation for sync external table files

---

server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/ScheduleController.java

fix(schedule): allowed to filter by datasource name

---

server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/ScheduleController.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/factory/ScheduleResponseMapperFactory.java

type-bug
list datasources with attributes in the schedule list
Fixes #
```docs
```

fix(schedule): list datasources with attributes

---

server/odc-server/src/main/resources/data.sql

type-bug
add system config to enabled/disable the logical database feature
Fixes #
```docs
```

fix(logicaldatabase): add system config to enabled/disable the logical database feature

---

server/odc-server/src/main/resources/data.sql

type-build
Fixes #
```docs
```

feat(logicaldatabase): add missed code for data.sql when merge main to dev/4.3.x

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataArchiveJob.java

type-feature
ata archive support generating dynamic target table name
Fixes #
```docs
```

feat(dlm): data archive support generating dynamic target table name

---

server/odc-server/src/main/java/com/oceanbase/odc/agent/runtime/DefaultTaskResultBuilder.java
server/odc-server/src/test/java/com/oceanbase/odc/agent/runtime/TaskContainerTest.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/base/sqlplan/SqlPlanTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/processor/result/DLMResultProcessor.java

type-build
Fixes #
```docs
```

builds: merge from main into dev/4.3.x

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java

type-bug
FYI
Fixes #
```docs
```

fix(schedule): schedule can be edited while subtasks are still in progress 

---

server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/BaseAffectedRowsExceedLimit.java
server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/OracleAffectedRowsExceedLimit.java

fix(sql-check): cannot get oracle affect sql rows

---

server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/DBRecyclebinController.java
server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/PLController.java
server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/SensitiveColumnScanningTaskManager.java
server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/SensitiveColumnService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/model/SensitiveColumnScanningTaskInfo.java
server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBPLService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataDeleteJob.java

Auto-merging server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/DataArchiveTask.java
Auto-merging server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataDeleteJob.java
CONFLICT (content): Merge conflict in server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataDeleteJob.java
CONFLICT (modify/delete): server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/DataDeletePreprocessor.java deleted in HEAD and modified in dev/4.3.1. Version dev/4.3.1 of server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/DataDeletePreprocessor.java left in tree.
CONFLICT (modify/delete): server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/DataArchivePreprocessor.java deleted …

merge 202406 into main

---

pom.xml

type-security
fix potential security issue CVE-2022-45047
Fixes #
```docs
```

security: exclude sshd-common from spring-cloud-context

---

server/integration-test/src/test/java/com/oceanbase/odc/service/session/ConnectConsoleServiceTest.java
server/odc-core/src/main/java/com/oceanbase/odc/core/sql/execute/SessionOperations.java
server/odc-core/src/test/java/com/oceanbase/odc/core/sql/execute/TestSessionOperations.java
server/odc-migrate/src/main/resources/migrate/common/R_2_0_0__initialize_version_diff_config.sql
server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/ConnectSessionController.java
server/odc-service/src/main/java/com/oceanbase/odc/service/db/session/DBSessionService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/db/session/DefaultDBSessionManage.java
server/odc-service/src/main/java/com/oceanbase/odc/service/db/session/KillResult.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/ConnectConsoleService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/DBSessionManageFacade.java
server/plugins/connect-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/connect/obmysql/OBMySQLSessionExtension.java
server/plugins/connect-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/connect/oboracle/OBOracleSessionExtension.java
server/plugins/connect-plugin-oracle/src/main/java/com/oceanbase/odc/plugin/connect/oracle/OracleSessionExtension.java

type-feature
This PR implements the Oracle kill session feature. Additionally, it refactors the `DefaultDBSessionManage` with the following changes: 
1. Removed the confusing logic of adding comments in SQL to indicate `ServerAddress`; 
2. Unified the kill logic within `DefaultDBSessionManage`, consolidating it into a single class.
Fixes #
```docs
```

feat(session): support Oracle kill session

---

server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/DBRecyclebinController.java
server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/PLController.java
server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/SensitiveColumnScanningTaskManager.java
server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/SensitiveColumnService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/model/SensitiveColumnScanningTaskInfo.java
server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBPLService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataDeleteJob.java

merge from 202406 into 202407bp

---

pom.xml
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/server/TaskMonitor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/processor/result/DLMResultProcessor.java

fix(taskframework): cherry-pick the bug fix from obcloud_202409bp

---

libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/model/DBTablePartitionDefinition.java
server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/DBTableController.java
server/plugins/schema-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/schema/obmysql/parser/BaseOBGetDBTableByParser.java
server/plugins/schema-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/schema/obmysql/parser/OBMySQLGetDBTableByParser.java
server/plugins/schema-plugin-ob-mysql/src/test/java/com/oceanbase/odc/plugin/schema/obmysql/parser/OBMySQLGetDBTableByParserTest.java
server/plugins/schema-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/schema/oboracle/parser/OBOracleGetDBTableByParser.java
server/plugins/schema-plugin-ob-oracle/src/test/java/com/oceanbase/odc/plugin/schema/oboracle/parser/OBOracleGetDBTableByParserTest.java

the sub partition needs to contain information about  partition associated with it, which is required for rendering in the following figure
Fixes #
```docs
```

feat(sub partition) : add the associated partition information for sub partition 

---

server/odc-server/src/main/resources/config/application-clientMode.yml

fix(clinetmode): can't start MAC client mode

---

server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/OscService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/configuration/OnlineSchemaChangeProperties.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/oscfms/action/oms/OmsSwapTableAction.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/rename/DefaultRenameTableInvoker.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/rename/LockRenameTableFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/rename/LockTableSupportDecider.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/rename/OscDBUserUtil.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/validator/OnlineSchemaChangeValidator.java
server/odc-service/src/test/java/com/oceanbase/odc/service/onlineschemachange/oscfms/action/oms/OmsSwapTableActionTest.java
server/odc-service/src/test/java/com/oceanbase/odc/service/onlineschemachange/rename/LockTableSupportDeciderTest.java
server/odc-service/src/test/java/com/oceanbase/odc/service/onlineschemachange/rename/OscDBUserUtilTest.java

…range is 4.2.[5 - 9]
type-bug
1. lock table feature for ObMySQL version is [4.2.5 ~ 4.3.0) for now.
2. previous logic will enable lock table for Ob version greater than 4.2.5 which have no rollback control for 4.3.x
3. introduce white list format in json array, default value is  [4.2.[5 - 9].*].  matched with java regex lib.
4. value is stored in config_system_configuration with key "odc.osc.support-lock-table-ob-version-json" , use sql like :"insert into config_system_configuration(`key`, `application`, `profile`, `label`, `description`, value) values('odc.osc.support-lock-table-ob-version-json', 'odc', 'default', 'master', 'control odc enable lock table version, default is ["4\\\\.2\\\\.5.*"]', '["4\\\\.2\\\\.5.*"]')"    to init it. 
5. if config_system_configuration has no rule, …

fix(osc):add version whitelist  to enable lock table feature

---

server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/StdJobScheduler.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/DestroyExecutorJob.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java

type-bug
job_job.executor_destroy_time is needed for judge if job has been destroyed and will be used calculate task throttle. 
if there exits more than 5 task with status not in preparing but executor_destroy_time is null. new task will not dispatched.
rollback DestroyExecutorJob class to destroy executor which will update executor_destroy_time as well.
Fixes #
```docs
```

fix(task): rollback DestroyExecutorJob to do destroy job action

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/factory/ScheduleResponseMapperFactory.java

refactor(schedule): fill attribute at scheduleMapper

---

server/odc-migrate/src/main/resources/migrate/common/V_4_3_3_1__alter_resource_resource_add_index.sql
server/odc-service/src/main/java/com/oceanbase/odc/metadb/resource/ResourceEntity.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java

type-bug
DestroyResourceJob will try destroy all resource with ABANDON status which is not expected.
change filter condition to "status = ABANDON and resource_type = cloudK8s"
Fixes #
```docs
```

fix(task): add index to resource_resource table

---

libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/model/DBSession.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/stats/mysql/OBMySQLNoLessThan400StatsAccessor.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/stats/oracle/OBOracleNoLessThan400StatsAccessor.java
server/odc-core/src/main/java/com/oceanbase/odc/core/shared/model/OdcDBSession.java

fix(session): add svrIp in session list

---

server/integration-test/src/test/java/com/oceanbase/odc/service/db/TableServiceTest.java
server/odc-service/src/main/java/com/oceanbase/odc/metadb/dbobject/DBObjectRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/table/TableService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/permission/DBResourcePermissionHelper.java
server/odc-service/src/main/java/com/oceanbase/odc/service/permission/table/ApplyTablePermissionPreprocessor.java
server/odc-test/src/main/java/com/oceanbase/odc/test/database/TestDBConfigurations.java

type-feature
Displays view objects in the application permission table ticket module
Fixes #
```docs
```

feat(permission): add view permission control

---

server/integration-test/src/test/java/com/oceanbase/odc/service/objectstorage/client/OSSCloudObjectStorageClientTest.java
server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/client/CloudObjectStorageClient.java
server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/client/LocalObjectStorageClient.java
server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/client/ObjectStorageClient.java

type-feature
add copyObject in ObjectStorageClient
Fixes #
```docs
```

feat(ObjectStorage): add copyObject in ObjectStorageClient

---

server/odc-server/src/main/resources/config/application.yml

fix(actuator): diasble actuator by default

---

server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DataSourceInfoMapper.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/DataArchiveTask.java

fix(data-archive): table not exist

---

server/odc-common/src/main/java/com/oceanbase/odc/common/json/JsonUtils.java

type-feature
reduce JsonUtils log output of exception stack
Fixes #
```docs
```

feat(common): reduce log of JsonUtils

---

server/odc-core/src/main/java/com/oceanbase/odc/core/datasource/SingleConnectionDataSource.java
server/odc-core/src/test/java/com/oceanbase/odc/core/datasource/SingleConnectionDataSourceTest.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/oscfms/OscActionFsmBase.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/factory/DefaultConnectSessionFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/factory/OBConsoleDataSourceFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/SqlCheckService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/base/precheck/PreCheckTask.java

type-feature
This PR adds a new feature for `SingleConnectionDataSource` which is keep alive. When keepAlive set to true, there will be a schedule task to execute `SELECT 1 FROM DUAL` every 5 minutes to keep the connection alive. If it fails more than 5 times in a row, the keep alive task will be terminated.
Fixes #
```docs
```

feat(session): SQL console connection keep alive

---

server/odc-service/src/main/java/com/oceanbase/odc/service/task/util/JobPropertiesUtils.java

fix incorrect cloud provider enum

fix(task): fix incorrect cloud provider enum

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java

check subtask when delete schedule.
type-bug
delete schedule with check sub running tasks.
Fixes #
```docs
```

fix(schdule):delete schedule with check sub running tasks

---

.github/CODEOWNERS

build: change code owners

---

server/odc-service/src/main/java/com/oceanbase/odc/service/permission/database/model/ApplyDatabaseParameter.java

type-bug
Fixes #3953
```docs
```

fix(permission):time is missing when initiating apply database task again

---

server/odc-server/src/main/resources/config/application-clientMode.yml

fix(actuator): disable actuator autoconfiguration in client mode

---

libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/model/DBSession.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/stats/mysql/OBMySQLNoLessThan400StatsAccessor.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/stats/oracle/OBOracleNoLessThan400StatsAccessor.java
pom.xml
server/odc-common/src/main/java/com/oceanbase/odc/common/json/JsonUtils.java
server/odc-common/src/main/java/com/oceanbase/odc/common/util/VersionUtils.java
server/odc-common/src/test/java/com/oceanbase/odc/common/util/VersionUtilsTest.java
server/odc-core/src/main/java/com/oceanbase/odc/core/shared/model/OdcDBSession.java
server/odc-server/src/main/resources/config/application-clientMode.yml
server/odc-server/src/main/resources/config/application.yml
server/odc-server/src/main/resources/data.sql
server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DataSourceInfoMapper.java
server/odc-service/src/main/java/com/oceanbase/odc/service/feature/VersionDiffConfigService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/OscService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/configuration/OnlineSchemaChangeProperties.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/oscfms/action/oms/OmsSwapTableAction.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/rename/DefaultRenameTableInvoker.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/rename/LockRenameTableFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/rename/LockTableSupportDecider.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/rename/OscDBUserUtil.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/validator/OnlineSchemaChangeValidator.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/server/TaskMonitor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/DataArchiveTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/processor/result/DLMResultProcessor.java
server/odc-service/src/test/java/com/oceanbase/odc/service/onlineschemachange/oscfms/action/oms/OmsSwapTableActionTest.java
server/odc-service/src/test/java/com/oceanbase/odc/service/onlineschemachange/rename/LockTableSupportDeciderTest.java
server/odc-service/src/test/java/com/oceanbase/odc/service/onlineschemachange/rename/OscDBUserUtilTest.java

type-build
Fixes #
```docs
```

merge dev/4.3.2 into main

---

server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/ddl/OscOBMySqlAccessor.java

type-bug
distinct key word will be case  insensitive for MySQL select query.
distinct('odc', 'ODC') will only return one value.
Fixes #
```docs
```

fix(osc): remove distinct from osc query user sql

---

server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/utils/DataArchiveConditionUtil.java
server/odc-service/src/test/java/com/oceanbase/odc/service/dlm/utils/DataArchiveConditionUtilTest.java

feat(schedule): opt offset calculator

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/db/session/DefaultDBSessionManage.java

fix(authorize): skip authorization for inner methods

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java

fix(schedule): no rollback occurred when schedule creation failed

---

server/odc-server/src/main/resources/log4j2-task.xml

We must store the task logs in a single file. If there are multiple files, some might be missing when uploading to OSS
Fixes #
```docs
```

fix(task-framework): task log file is incomplete

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java

fix(changelog): incorrect detail in the change log

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleChangeLogService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java

fix(changelog): opt the changelog content

---

server/odc-core/src/main/java/com/oceanbase/odc/core/shared/PreConditions.java
server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/ErrorCodes.java
server/odc-core/src/main/resources/i18n/ErrorMessages.properties
server/odc-core/src/main/resources/i18n/ErrorMessages_zh_CN.properties
server/odc-core/src/main/resources/i18n/ErrorMessages_zh_TW.properties
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java

feat(schedule):  opt error message

---

server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java

type-bug
Fixes #4066 
```docs
```

fix(flow):view export function can be initiated without permission

---

server/integration-test/src/test/java/com/oceanbase/odc/service/collaboration/ProjectServiceTest.java
server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/project/ProjectService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/model/ScheduleStatus.java

type-bug
1. Checking ticket references will involve all projects' tickets because the project_id does not take effect.
2. Ignore the partition plan check because it will always be enabled after it was created. Instead, disable all partition plans when archiving projects.
3. Cannot pass the ticket reference check when archiving projects because the PAUSE status means disabled.
Fixes #4034 
```docs
```

fix(project): archiving projects will fail because of wrong check of tickets references

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java

fix(approval): approval is not needed in individual organizations

---

server/odc-service/src/main/java/com/oceanbase/odc/service/integration/saml/SamlRegistrationConfigHelper.java

spring security's default use UrlResource for loading metaUri has no connection timeout, if use wrong metaUri may lead to block thread.
Fixes #
```docs
```

fix(saml): saml may blocked tomcat thread

---

server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/K8sJobCaller.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/ResourceIDUtil.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/dummy/LocalMockK8sJobClient.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/util/JobPropertiesUtils.java

type-bug
correct region key name for K8S mode resource Id build
Fixes #
```docs
```

fix(task): correct region key name for resourceID

---

libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/MySQLNoLessThan5700SchemaAccessor.java
libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/parser/PLParserTest.java

type-bug
Currently, procedure's ddl is pieced together, and the above types of ddl will be displayed correctly.
An improved approach is to return the ddl that is retrieved directly from the database
Fixes #4023 
```docs
```

fix(dbbrowser): cant get correct ddl of procedure

---

server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/project/ProjectService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/model/FlowInstanceDetailResp.java

type-bug
Add `currentUserResourceRole` in the flow API for the front end to judge if the ticket could be operated by current user.
Fixes #
```docs
```

fix(flow): add currentUserResourceRole in flow APIs

---

server/odc-service/src/main/java/com/oceanbase/odc/service/notification/constant/EventLabelKeys.java
server/odc-service/src/main/java/com/oceanbase/odc/service/notification/helper/ChannelConfigValidator.java
server/odc-service/src/main/java/com/oceanbase/odc/service/notification/helper/EventBuilder.java

type-feature
1. support send account name in message
2. do not verify channel webhook
Fixes #
```docs
```

fix(notification): support send account name in message

---

server/plugins/connect-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/connect/obmysql/diagnose/PlanGraphBuilder.java

type-bug
Sometimes there maybe incorrect number in sql execution plan from  observer. So we should check it before casting.
Fixes #3243 
```docs
```

fix(execution-plan): avoid invalid number

---

server/odc-service/src/main/java/com/oceanbase/odc/service/notification/helper/EventBuilder.java

type-bug
Alter schedule task did not generate event
Fixes #3964 
```docs
```

fix(notification): fail to enqueue schedule event

---

server/odc-migrate/src/main/java/com/oceanbase/odc/migrate/jdbc/common/R4237DefaultRuleApplyingMigrate.java

type-bug
The newly added rules will not migrate successfully because of the wrong ruleset name.
Fixes #3651
```docs
```

fix(migrate): newly added sql check rules in 4.3.2 will not be migrated successfully

---

pom.xml

fix(dlm): upgrade dlm sdk version to 1.1.6.bp3

---

server/odc-service/src/main/java/com/oceanbase/odc/service/flow/factory/FlowResponseMapperFactory.java

type-bug
When users don't configure hyperlinkExpression, it will cause NPE.
Fixes #2753 
```docs
```

fix(integration): external approval integration will cause NPE if hyperlinkExpression is null

---

pom.xml

fix(dlm): upgrade dlm sdk version to 1.1.6.bp4

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/DBSchemaSyncTaskManager.java

type-bug
It doesn't sync internal schemas in the project in the bastion mode. By default, the internal schema will not sync to the projects, but we should do that in bastion mode.
I added the `basetionEnabled` to judge if we should sync internal schemas to the projects.
Fixes #2753 
```docs
```

fix(integration): it doesn't sync internal schemas in the project in the bastion mode

---

server/odc-migrate/src/main/resources/migrate/common/V_4_3_3_6__complete_connect_database.sql

type-bug
In the previous version, it added `connect_type` in `connect_database`, but `connect_type` was set to `default null`, which caused dirty data. This PR completed the `connect_type` whose value is null by setting it to `connect_connection.type.`
Fixes #4082
```docs
```

fix(migrate): complete data for connect_database.connect_type

---

server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/project/ProjectService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/project/model/Project.java
server/odc-service/src/main/java/com/oceanbase/odc/service/iam/PermissionService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/iam/ResourceRoleService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/iam/UserService.java

type-bug
1. I added `derivedFromGlobalProjectRole` in `ProjectMember` to identify if this project role is derived from the global project role for the front end to disable/enable some features.
2. I fixed the global role acquiring method. The previous is wrong which acquires from `iam_user_permission`. The correct way is from `iam_user_role`.
Fixes #
```docs
```

fix(permission): global project role cannot see approvable tickets

---

server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBPLModifyHelper.java

type-bug
When pl name contains `@`, need to add quote, otherwise the create and drop statements will fail
Fixes #
```docs
```

fix(db):miss quote of pl name which contains @ causes pl edit failed

---

server/odc-service/src/main/java/com/oceanbase/odc/service/db/session/DefaultDBSessionManage.java

Type-Bug
The issue causing a potential NullPointerException when fixing the killSession is that the value may be null during the toMap operation.
Fixes #4049
```docs
```

fix(session): kill session may lead npe

---

server/odc-service/src/main/java/com/oceanbase/odc/config/ScheduleConfiguration.java
server/odc-service/src/main/java/com/oceanbase/odc/config/Schedulers.java

type-bug
In some scenarios, such as obcloud, schedule annotations written in the configuration class do not take effect. This will cause the system configuration to fail to refresh

fix(schedule): invalid  schedule annotation

---

server/odc-server/src/main/resources/log4j2-task.xml
server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/ProcessJobCaller.java

type-bug
log4j-task.xml not provide Policy field for RollingFileAppender. That will lead to log4j context set failed.
Fixes #
```docs
```

fix(task): log4j set failed for task

---

server/odc-service/src/main/java/com/oceanbase/odc/service/feature/VersionDiffConfigService.java

`kill-query-or-session.max-supported-ob-version` excpect only effect ob mode
Fixes #
```docs
```

fix(session): oracle mode effected by kill-query-or-session.max-supported-ob-version

---

server/odc-service/src/main/java/com/oceanbase/odc/service/session/factory/OBConsoleDataSourceFactory.java

fix(datasource): set the proxy configuration for oracle

---

server/odc-service/src/main/java/com/oceanbase/odc/service/resource/ResourceManager.java

add double check, take most effort to avoid multi invoke of destroy resource operation
Fixes #
```docs
```

feat(resource): add double check when destroy resource

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java

type-bug
check has running task when delete
Fixes #
```docs
```

fix(schedule):check has running task when delete

---

server/odc-server/src/main/resources/config/application-clientMode.yml

client mode exclude saml
Fixes #
```docs
```

fix(sso): client mode exclude saml

---

server/integration-test/src/test/java/com/oceanbase/odc/metadb/schedule/ScheduleTaskRepositoryTest.java
server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/TaskStatus.java
server/odc-service/src/main/java/com/oceanbase/odc/metadb/schedule/ScheduleTaskRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleTaskService.java

fix(schedule): remove slow sql

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java

type-bug
The operation of the schedule failed because the datasource is invalid.
Fixes #
```docs
```

fix(schedule): do not request external services when describe database

---

server/plugins/connect-plugin-oracle/src/main/java/com/oceanbase/odc/plugin/connect/oracle/OracleSessionExtension.java

type-bug
Kill Oracle session may cause socket timeout because the kill SQL doesn't include `IMMEDIATE`.
Fixes #
The IMMEDIATE option forces the session to terminate immediately. It doesn't wait for the session to finish current operations or release resources; instead, it interrupts the session right away.
```docs
```

fix(session): kill oracle session may cause sockettimeout

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/processor/ScheduleChangePreprocessor.java

type-bug
only describe database when operate the schedule
Fixes #
```docs
```

fix(schedule): fail to operate schedule if database is invalid

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/processor/ScheduleChangePreprocessor.java

cherry-pick describe database
Fixes #
```docs
```

fix(schedule): cherry pick describe database

---

server/odc-service/src/main/java/com/oceanbase/odc/service/resource/k8s/status/K8sConfigMapStatusDfa.java
server/odc-service/src/main/java/com/oceanbase/odc/service/resource/k8s/status/K8sDeploymentStatusDfa.java
server/odc-service/src/main/java/com/oceanbase/odc/service/resource/k8s/status/K8sPodStatusDfa.java
server/odc-service/src/main/java/com/oceanbase/odc/service/resource/k8s/status/K8sServiceStatusDfa.java

type-bug
fix incorrect k8s status dfa

fix(k8s): k8s component status is incorrect

---

server/odc-service/src/main/java/com/oceanbase/odc/service/db/session/DefaultDBSessionManage.java

type-bug
The original expression is used to match hint, so the regular pattern string is `/* <ip>:<port> */`, but it is no longer obtained from hint, so `/*` and `*/ `are not needed.
Fixes #
```docs
```

fix(session): kill session  may happen invalid server ip address

---

server/odc-core/src/main/resources/i18n/BusinessMessages.properties
server/odc-core/src/main/resources/i18n/BusinessMessages_zh_CN.properties
server/odc-core/src/main/resources/i18n/BusinessMessages_zh_TW.properties
server/odc-migrate/src/main/resources/init-config/init/regulation-rule-applying.yaml
server/odc-migrate/src/main/resources/init-config/init/regulation-rule-metadata.yaml
server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/factory/CreateTableAsExistsFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/factory/CreateTableLikeExistsFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/model/SqlCheckRuleType.java
server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/BaseMissingRequiredColumns.java
server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/CreateTableAsExists.java
server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/CreateTableLikeExists.java
server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/MySQLNoTableCommentExists.java
server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/MySQLRestrictTableAutoIncrement.java
server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/NoPrimaryKeyExists.java
server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/OracleNoTableCommentExists.java
server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/SqlCheckRules.java

type-bug
Two additional sql check rules in above picture have been added to handle these statements like 'create table a like b' and 'create table a as select * from b'  separately.
Those sql check rules in the four red boxes above shouldn‘t take effect for those statements.
Fixes #3627 
```docs
```

fix(sql check):add two sql check rules for CREATE LIKE/AS statement

---

server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/project/ProjectService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/table/TableService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/db/session/DefaultDBSessionManage.java
server/odc-service/src/main/java/com/oceanbase/odc/service/iam/GlobalResourceRoleService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/iam/ResourceRoleService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/iam/UserService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/integration/IntegrationService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/integration/oauth2/TestLoginManager.java
server/starters/web-starter/src/main/java/com/oceanbase/odc/service/iam/auth/saml/DefaultSamlUserService.java

type-security
This PR added `@SkipAuthorize` for all public methods added in 4.3.3 to skip security check,
Fixes #
```docs
```

security: add @SkipAuthorize in public method

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java

type-bug
delete without running task.
Fixes #
```docs
```

fix(schedule):delete without running task

---

server/odc-service/src/main/java/com/oceanbase/odc/service/integration/IntegrationService.java

type-security
add `@SkipAuthorize` for `IntegrationService`
Fixes #
```docs
```

security: add @SkipAuthorize for IntegrationService

---

libs/db-browser/pom.xml
pom.xml

build: upgrade db-browser to 1.2.1

---

server/odc-service/src/main/java/com/oceanbase/odc/service/db/session/DefaultDBSessionManage.java

build: merge main to dev/4.3.3

---

server/odc-service/src/main/java/com/oceanbase/odc/service/db/session/DefaultDBSessionManage.java

type-bug
Kill sessions failed in OSC tasks. The root cause is the kill SQL is wrongly set to `kill query session_id`, which should be `kill session_id`
Fixes #
```docs
```

fix(session): killing sessions failed in OSC tasks

---

pom.xml

type-feature
exclusion aws-java-sdk-bundle
Fixes #
```docs
```

feat(oss): exclusion aws-java-sdk-bundle

---

libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/stats/mysql/OBMySQLNoLessThan400StatsAccessor.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/stats/oracle/OBOracleNoLessThan400StatsAccessor.java

type-bug
DBSession's svr_ip should use sql_port,  instead of svr_port. svr_port is the port of the rpc，while sql_port for sql connection.
Fixes #
```docs
```

fix(session): get wrong server port 

---

libs/db-browser/pom.xml
pom.xml

type-bug
upgrade db-browser from 1.2.1 to 1.2.2
Fixes #
```docs
```

build: upgrade db-browser from 1.2.1 to 1.2.2

---

server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/datatransfer/factory/LoadParameterFactory.java

type-bug
When importing external csv file, odc would not set batchSize for obloader.
Fixes #
```docs
```

fix(datatransfer): invalid batchSize when importing external csv file

---

server/odc-service/src/main/java/com/oceanbase/odc/service/db/session/DefaultDBSessionManage.java

type-bug
DBStatsAccessors use console session, may lead  to session occupied. Now use new ConnectionSession to list all session.
Fixes #
```docs
```

fix(session): kill console query may failed cause session occupied

---

server/odc-service/src/main/java/com/oceanbase/odc/service/db/session/DefaultDBSessionManage.java

type-bug
The `oceanbase.gv$ob_processlist` is not in-time after kill sessions. So I added a retry logic when checking the session list.
Fixes #
```docs
```

fix(session): add retry logic when get session list

---

server/integration-test/src/test/java/com/oceanbase/odc/service/integration/IntegrationServiceTest.java
server/odc-migrate/src/main/resources/migrate/h2/V_4_3_3_1__alter_integration.sql
server/odc-migrate/src/main/resources/migrate/oceanbase/V_4_3_3_1__alter_integration.sql

type-bug
modify column may not effect on ob1479
Fixes #
```docs
```

fix(migrate): 4331 migrate script may failed on ob1479

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/factory/ScheduleResponseMapperFactory.java

type-bug
In the individual space, there is no project related to the schedule. This PR adds a judgement if the projected is null, then skill detail the project.
Fixes #
```docs
```

fix(schedule): detail schedule in the individual space may fail

---

server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/TooLongCharLength.java

type-bug
In the SQL check rule 'TooLongCharLength', it may occur NPE as the dataType is nullable, but the caller does not consider it.
Fixes #
```docs
```

fix(sql-check): it may occur NPE when doing SQL check

---

server/odc-migrate/src/main/java/com/oceanbase/odc/migrate/jdbc/common/R4237DefaultRuleApplyingMigrate.java

type-bug
We should skip migrating builtin rulesets when migrating user-defined rules.
Fixes #
```docs
```

fix(migrate): skip builtin ruleset migration when migrating rules

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java

type-bug
The check organization type function failed due to incorrect parameter.
Fixes #
```docs
```

fix(schedule): check organization type failure

---

server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/QuartzJobService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java

type-bug
Catch exception when a change error occurs and update status to failed.
Fixes #
```docs
```

fix(changelog): the status does not progress to 'Failed' when a change error occurs

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/AlterScheduleTask.java

type-bug
Transaction will rollback if update status in executeScheduleChange method, so we need to update status in call method
Fixes #
```docs
```

fix(changelog): cannot rollback update changelog status

---

.github/workflows/build_dev.yaml

type-build
specify mvn and jvm version for aci
Fixes #
```docs
```

fix(build): specify maven and jvm version fro aci

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleTaskConfiguration.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/AbstractDlmJob.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/AbstractOdcJob.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/submitter/DefaultJobSubmitter.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/submitter/JobSubmitter.java

type-feature
Customized task submission for different environments
Fixes #
```docs
```

feat(taskframework): customized task submission

---

server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/OscService.java

type-bug
Project owners and DBAs should be allowed to execute swapping tables in OSC tables, while current implementation is liming the operator to the creator.
Fixes #
```docs
```

fix(permission): 'AccessDenied' happens when project owners try swapping tables in an osc task

---

server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/DoCancelingJob.java

type-bug
when task run in process mode, JobCaller.finish not called cause job_job.destroyed_time column is set unexpected,
remove this code to let destroyExecutor daemon task handle remain clean action.
Fixes #
```docs
```

fix(task): process mode not invoke destroy action when job is canceled

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionTesting.java
server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/utils/DataArchiveConditionUtil.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java

type-bug
1. Allow choosing minutes and seconds as the offset unit
2. Only check permission for OBInstance
Fixes #
```docs
```

fix(schedule): unreasonable parameter validation

---

server/odc-server/src/main/java/com/oceanbase/odc/agent/runtime/TaskMonitor.java
server/odc-server/src/main/java/com/oceanbase/odc/agent/runtime/TaskReporter.java

…port
type-bug
report task result in TaskMonitor is not synchronized. that may cause unexpected result save.
this patch sync report call, if doFinal called, the following report will be ignored
Fixes #
```docs
```

fix(task): sync report taskResult call

---

server/odc-service/src/main/java/com/oceanbase/odc/service/task/base/dataarchive/DataArchiveTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/processor/terminate/DLMTerminateProcessor.java

type-bug
1. correct subtask status when task is terminated
Fixes #
```docs
```

fix(dlm): correct status when task is terminated

---

server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/OscService.java

type-bug
if rate limiter config not provide in ScheduleEntity.OnlineSchemaChangeParameters, npe will be caused.
OscActionBase access for this variable has handled the issue in OscActionFsmBase.parseOnlineSchemaChangeParameters
Fixes #
```docs
```

fix(osc): updateRateLimiterConfig npe issue

---

server/odc-migrate/src/main/resources/migrate/common/V_4_3_3_7__update_system_config.sql

add task enabled configurations
Fixes #
```docs
```

fix(config): add task enabled configurations

---

server/odc-service/src/main/java/com/oceanbase/odc/config/ScheduleConfiguration.java

type-bug
The default waiting queue of the flowTaskExecutor thread pool is the largest, causing the number of threads in the pool to not increase. This PR sets the coreThreadSize and maxThreadSize to be the same and makes this number configurable.
Fixes #
```docs
```

fix(flowable): flowable task may be blocked

---

server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/oscfms/action/oms/OmsModifyDataTaskAction.java

type-bug
add uid for osc when invoke UpdateOmsConfig open API
Fixes #
```docs
```

fix(osc): add uid for oms updateConfigRequest

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/SqlPlanJob.java

type-feature
FYI
Fixes #
```docs
```

feat(sql-plan): sync schedule description to subtask

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ssl/ConnectionSSLAdaptor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ssl/DefaultConnectionSSLAdaptor.java
server/plugins/connect-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/connect/obmysql/OBMySQLConnectionExtension.java

Adaptioin for supporting ssl connect in obcloud.
I created a new interface `ConnectionSSLAdaptor`.
Fixes #
```docs
```

adaption(cloud): support ssl connect in obcloud

---

server/odc-service/src/main/java/com/oceanbase/odc/service/flow/listener/ApprovalStatusNotifyListener.java
server/odc-service/src/main/java/com/oceanbase/odc/service/iam/ResourceRoleService.java

type-bug
ResourceRoleService#listByResourceIdentifierIn requires organization. And when calling it asynchronously, it would throw an AccessDeniedException.

fix(notification): fail to generate notification event

---

libs/db-browser/pom.xml
libs/ob-sql-parser/pom.xml
pom.xml

type-bug
The github artifact would failed like https://github.com/oceanbase/odc/actions/runs/13306599104/job/37158911752 .
According to https://stackoverflow.com/questions/75652635/a-required-class-was-missing-while-executing-maven-plugin-with-github-action , fixed it.

build: fail to build artifact

---

server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/model/OnlineSchemaChangeScheduleTaskParameters.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/oscfms/action/CreateGhostTableAction.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/oscfms/action/oms/OmsCreateDataTaskAction.java

type-feature
drop column not blocked any more, but drop column and add column can't do in same time
Fixes #
```docs
```

feat(osc): support drop column sql

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/OBInstanceType.java

type-bug
fix failed to deserialize OBInstanceType when value is "CLUSTER", because the value of OBInstanceType.CLUSTER is "cluster", so i change value to lowercase uniformly when deserializing.
Fixes #
```docs
```

fix(cloud):failed to deserialize OBInstanceType

---

server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/project/ProjectService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/iam/ResourceRoleService.java

fix failed to remove user from organization in obcloud due to organization Authentication.
Fixes #
```docs
```

fix(obcloud): failed to remove user from organization in obcloud

---

server/odc-service/src/main/java/com/oceanbase/odc/service/pldebug/session/AbstractDebugSession.java

type-bug
Fixes #
In pl debug, the username configured for new odp connections does not contain cluster names. If one odp reversed-proxy multiple clusters, an error message is displayed. Therefore, should add the cluster name for odp connection.
```docs
```

fix(pl debug):the username configured for new odp connections does not contain cluster names.

---

libs/db-browser/pom.xml
libs/ob-sql-parser/pom.xml
pom.xml

build: fail to build artifact #4231

---

pom.xml
server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/TaskStatus.java
server/odc-server/src/main/java/com/oceanbase/odc/agent/runtime/TaskContainer.java
server/odc-server/src/main/java/com/oceanbase/odc/agent/runtime/TaskMonitor.java
server/odc-server/src/main/resources/data.sql
server/odc-server/src/main/resources/log4j2-task.xml
server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMJobFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMTableStructureSynchronizer.java
server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/model/DataArchiveParameters.java
server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/model/DataArchiveTableConfig.java
server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/model/DlmTableUnitParameters.java
server/odc-service/src/main/java/com/oceanbase/odc/service/info/OdcInfoService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/OdcJobListener.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DLMJobReq.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataArchiveJob.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/processor/DataArchivePreprocessor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/base/dataarchive/DataArchiveTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/enums/JobStatus.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/listener/DefaultJobTerminateListener.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/state/JobStatusFsm.java

type-feature
1. create temporary tables when data is archived to file system
2. add an exec_timeout status to distinguish between execution timeout and manual cancellation.
3. automatically resume execution after a timeout during the next scheduling attempt.
Fixes #
```docs
```

feat(dlm): create temporary tables when data is archived to file system

---

server/odc-common/src/main/java/com/oceanbase/odc/common/util/StringUtils.java
server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMTableStructureSynchronizer.java

fix(sync-table): the default value is considered missing when it is whitespace

---

server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMTableStructureSynchronizer.java

type-bug
FYI
Fixes #
```docs
```

fix(sync-table): throw NPE when target table is not exist

---

server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMTableStructureSynchronizer.java

fix(sync-table): default value is too long

---

server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/ScheduleController.java
server/odc-service/src/main/java/com/oceanbase/odc/service/exporter/impl/LocalJsonExporter.java
server/odc-service/src/main/java/com/oceanbase/odc/service/exporter/model/ExportRowDataMapper.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/archiverist/ScheduleTaskExporter.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/archiverist/model/DataArchiveScheduleRowData.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/archiverist/model/DataDeleteScheduleRowData.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/archiverist/model/ExportedDataSource.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/archiverist/model/ExportedDatabase.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/archiverist/model/PartitionPlanScheduleRowData.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/archiverist/model/SqlPlanScheduleRowData.java

type-feature
schedule export support sqlPlain and PartitionPlan
Fixes #
```docs
```

feat(export):schedule export support sqlPlain and PartitionPlan

---

server/odc-service/src/main/java/com/oceanbase/odc/service/task/enums/JobStatus.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/v2/DoStopJobV2.java

type-bug
findWithPessimisticLock call need in transaction context. use doInTransactionWithoutResult open transaction explicitly
Fixes #
```docs
```

fix(task): doStopV2 scheduler not in transaction exception

---

server/odc-service/src/main/java/com/oceanbase/odc/service/permission/DBResourcePermissionHelper.java

type-bug
When executing sql in an sql window, a permission check on a table involves a database that does not exist
Fixes #
```docs
```

fix(table permission): When executing sql in an sql window, a permission check on a table involves a database that does not exist

---

server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/ImportController.java
server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/ScheduleController.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/export/model/ImportDatabaseView.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/export/model/ImportScheduleTaskView.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/export/model/ImportTaskResult.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/export/model/ScheduleNonImportableType.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/export/model/ScheduleTaskImportRequest.java

type-feature
Add schedule task import api.
Fixes #
```docs
```

feat(schedule): add schedule task import api

---

server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/v2/StartPreparingJobV2.java

type-feature
PullTaskV2 is always run for task v2 mode, so let process mode run in pull mode to avoid duplicate update of job_job
Fixes #
```docs
```

feat(task): let task v2 force start executor in pull mode

---

server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/v2/PullTaskResultJobV2.java

type-bug
PullResult should trigger event notify if taskResult changed or task finished. previous implement not send Event with taskResult before task finished
Fixes #
```docs
```

fix(task): taskResult event not send before task finished

---

server/odc-service/src/main/java/com/oceanbase/odc/service/task/enums/JobStatus.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/StdJobScheduler.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/v2/PullTaskResultJobV2.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java

… saveOrUpdateLogMetadata method
type-bug
cancel task http call may re-entry, add isTerminating when canceling has called
add timeout for PullTaskResultV2 handle doCanceling status
add transactional annotate for  saveOrUpdateLogMetadata method call
Fixes #
```docs
```

fix(task): cancel task  may not wait log meta uploaded

---

server/integration-test/src/test/java/com/oceanbase/odc/service/script/ScriptServiceWithLocalTest.java
server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/ScriptController.java
server/odc-service/src/main/java/com/oceanbase/odc/service/script/ScriptService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/script/util/ScriptUtils.java

type-feature
add batch download scripts method
Fixes #
```docs
```

feat(script): add batch download scripts method

---

pom.xml
server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMConfiguration.java
server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/model/DataDeleteParameters.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataDeleteJob.java

type-feature
FYI
Fixes #
```docs
```

feat(dlm): supports setting a CPU limit

---

server/odc-service/src/main/java/com/oceanbase/odc/service/task/base/dataarchive/DataArchiveTask.java

type-feature
FYI
Fixes #
```docs
```

feat(dlm): support configure thread

---

server/odc-migrate/src/main/resources/migrate/common/V_4_3_3_10__add_file_import_history.sql

fix(migrate): fix script

---

server/odc-service/src/main/java/com/oceanbase/odc/service/task/net/HttpServer.java

type-feature
this adjustment will improve the response performance for http server component
Fixes #
```docs
```

feat(task): adjust http server netty thread pool to fix size

---

server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/client/CloudObjectStorageClient.java

fix(cloud): fail to start odc when oss location is finance region

---

pom.xml

upgrade tomcat version to 9.0.98 to fix CVE-2024-50379

security: upgrade tomcat version to 9.0.98

---

server/odc-service/src/main/java/com/oceanbase/odc/service/datatransfer/DataTransferService.java
server/plugins/task-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/task/mysql/datatransfer/job/datax/ConfigurationResolver.java
server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/datatransfer/factory/BaseParameterFactory.java
server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/datatransfer/task/BaseOceanBaseTransferJob.java
server/plugins/task-plugin-ob-mysql/src/test/java/com/oceanbase/odc/plugin/task/obmysql/datatransfer/LoadParameterFactoryTest.java

type-bug
Obdumper has added a new logic in 43x: merge files after export is complete. The status of this merging is determined through the `isAllTasksFinished` method. If judged solely by `isAllTasksSuccessed`, closing the context at this time will result in file merge failure.

fix(data-transfer): fail to merge file

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionService.java

type-bug
FYI
Fixes #
```docs
```

fix(database): listing interface did not display datasource attributes

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/export/ScheduleTaskExporter.java

type-bug
although connectionService.getForConnectionSkipPermissionCheck named skipPermissionCheck, still will permission check internal. 
Fixes #
```docs
```

fix(export): Incorrect check export permission

---

server/odc-migrate/src/main/resources/migrate/common/V_4_3_3_9__add_index.sql

type-bug
add organization_id index on `task_task`, `schedule_schedule` and `data_masking_rule_applying`
Fixes #
```docs
```

fix(tripartite): Improve the query efficiency of precheck

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/OBTenantStatus.java

fix(obcloud):filter obcloud tenants when status is not connected

---

server/odc-service/src/main/java/com/oceanbase/odc/metadb/task/JobRepository.java

type-bug
pull task will check if job has expired . If job.last_heart_time is null, it will use job.create_time to compute heartbeat timeout.
but job may queued before executed, that may cause wrong timeout check cause queued time always computed. 
force update job.last_heart_time when job started to avoid compute queued time
Fixes #
```docs
```

fix(task): force update job last_heart_time once when job started

---

server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java

type-bug
execute timeout is a terminate state for task, resource should be released for this state
Fixes #
```docs
```

fix(task): find execute timeout task to destroy

---

pom.xml
server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMConfiguration.java
server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/model/DataDeleteParameters.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataDeleteJob.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/base/dataarchive/DataArchiveTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java

merge 4.3.3 into aliyun_202502

---

pom.xml
server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMConfiguration.java
server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/model/DataDeleteParameters.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataDeleteJob.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/base/dataarchive/DataArchiveTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java

merge 4.3.3 into obcloud_25v1

---

pom.xml
server/odc-server/src/main/resources/log4j2-task.xml
server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMJobStore.java

type-feature
1. Upgrade the SDK to version 1.2.3
2. Delete some unnecessary logs
3. Print task logs with the thread name
Fixes #
```docs
```

feat(dlm): supports generated column

---

libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/parser/listener/MysqlModeSqlParserListener.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/parser/listener/OracleModeSqlParserListener.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/OBMySQLBetween400And432SchemaAccessor.java
libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/parser/ParserUtilTest.java
libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/parser/SqlParserTest.java
libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/template/MysqlMViewTemplateTest.java
libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/template/OracleMViewTemplateTest.java
server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBIdentitiesService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/feature/VersionDiffConfigService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/permission/DBResourcePermissionHelper.java
server/odc-service/src/main/java/com/oceanbase/odc/service/permission/table/ApplyTablePermissionPreprocessor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/ConnectConsoleService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/model/SqlExecuteResult.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/util/DBSchemaExtractor.java
server/odc-service/src/test/resources/session/test_db_schema_extractor.yaml

type-feature
1. add materialized view permission control in sql window
2. query result sets in sql window involving materialized views are disabled for editing
3. add code auto-completion
Fixes #
```docs
```

feat(materialized view): materialized view adapt to existing functions in odc

---

server/odc-core/src/main/java/com/oceanbase/odc/core/alarm/AlarmService.java
server/odc-core/src/main/java/com/oceanbase/odc/core/alarm/AlarmUtils.java
server/odc-server/src/main/java/com/oceanbase/odc/server/OdcServer.java

type-bug
remove redundant alarm
Fixes #
```docs
```

fix(alarm): Listener may not load

---

server/odc-core/src/main/java/com/oceanbase/odc/core/alarm/AlarmService.java
server/odc-core/src/main/java/com/oceanbase/odc/core/alarm/AlarmUtils.java
server/odc-server/src/main/java/com/oceanbase/odc/server/OdcServer.java

type-bug
change spi to register listener manually
Fixes #
```docs
```

fix(alarm):  Listener may not load

---

server/odc-service/src/main/java/com/oceanbase/odc/service/session/interceptor/SqlConsoleInterceptor.java

It solves the adaptation problem of the query limit, and ensures that there will be no exceptions when front interaction and internal call.
```docs
```

fix(session): fix query limit conflict

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/processor/ScheduleChangePreprocessor.java

type-bug
support delete when datasource invalid
Fixes #
```docs
```

fix(schedule): support delete when datasource invalid

---

server/integration-test/src/test/java/com/oceanbase/odc/service/task/ProcessModeTest.java
server/odc-server/src/main/java/com/oceanbase/odc/agent/runtime/TaskMonitor.java
server/odc-server/src/test/java/com/oceanbase/odc/agent/runtime/TaskMonitorTest.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DatabaseChangeRuntimeFlowableTaskCopied.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/PreCheckRuntimeFlowableTaskCopied.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/RollbackPlanRuntimeFlowableTaskCopied.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/LogicalDatabaseChangeJob.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/submitter/DefaultJobSubmitter.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/constants/JobParametersKeyConstants.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/state/JobStatusFsm.java
server/odc-service/src/test/java/com/oceanbase/odc/service/task/status/JobStatusFsmTest.java

…urate
type-feature
correct task timeout to end time to let task execute control more accurate
job status will not changed if it's terminate state
Fixes #
```docs
```

feat(task): correct task timeout to endtime

---

libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OBOracleSchemaAccessor.java
server/plugins/connect-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/connect/obmysql/diagnose/PlanGraphBuilder.java

type-bug
fail to parse explain with invalid characters

fix(sql-explain): fail to parse explain with invalid characters

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/model/InnerQueryFlowInstanceParams.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java

type-bug
At present, partition plans are still managed by the Flow module, and there is no associated Schedule module, resulting in inaccurate statistics

fix(schedule): the partition plan statistics are incorrect

---

server/odc-service/src/main/java/com/oceanbase/odc/service/partitionplan/PartitionPlanService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/PartitionPlanJob.java

type-bug
partition plan invaild when delete table
Fixes #
```docs
```

fix(partition-plan): partition plan invaild when delete table

---

server/odc-migrate/src/main/resources/migrate/common/V_4_3_4_9__remove_kill_sessesion_max_support_version.sql
server/odc-service/src/main/java/com/oceanbase/odc/service/db/session/DefaultDBSessionManage.java

type-feature
Remove the restriction of `odc.session.kill-query-or-session.max-supported-ob-version`;
Duplicate SIDs are removed during kill session。
Fixes #
```docs
```

feat(session): support client session

---

server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/DBMaterializedViewController.java
server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBMaterializedViewService.java

type-feature
Materialized view logs and container tables are no longer displayed when the base table list is fetched
Fixes #
```docs
```

feat(materialized view):mask container table and materialized view log display in 'listAllBases' controller

---

server/odc-migrate/src/main/resources/init-config/init/regulation-rule-applying.yaml
server/odc-migrate/src/main/resources/init-config/init/regulation-rule-metadata.yaml
server/odc-service/src/test/java/com/oceanbase/odc/service/sqlcheck/OracleSqlCheckerTest.java

the sql check rule that unable to Judge affected rows doesn‘t support ob oracle and oracle
Fixes #
```docs
```

fix(sql check):There are no ob oracle and oracle options for sql check rule that unable to Judge affected rows 

---

server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMJobStore.java

type-bug
FYI
Fixes #
```docs
```

fix(metadb):  close save point if datasource is not odc metadb

---

server/odc-migrate/src/main/resources/init-config/init/notification-policy-metadata.yaml
server/odc-server/src/main/resources/data.sql
server/odc-service/src/main/java/com/oceanbase/odc/metadb/notification/MessageRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/service/notification/Broker.java
server/odc-service/src/main/java/com/oceanbase/odc/service/notification/JdbcNotificationQueue.java
server/odc-service/src/main/java/com/oceanbase/odc/service/notification/NotificationProperties.java
server/odc-service/src/main/java/com/oceanbase/odc/service/notification/NotificationQueue.java
server/odc-service/src/main/java/com/oceanbase/odc/service/notification/NotificationScheduleConfiguration.java

1. Sometimes a message could be sent twice. So we should fail it when it's timeout.
2. There is no message for  online schema change and data archive .

fix(notification): fix metadata and message resending

---

pom.xml

upgrade tomcat from 9.0.98 to 9.0.99

security: upgrade tomcat from 9.0.98 to 9.0.99

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionService.java

type-security
When listing data sources of another user, it doesn't check if current user have the read permission to that user.
This PR added this permission check.
Fixes #
```docs
```

security: lack permission check when listing another user's resources

---

server/odc-service/src/main/java/com/oceanbase/odc/service/iam/auth/CustomAuthenticationFailureHandler.java

type-security
The attacker can distinguish between "username does not exist" and "wrong password" through the details in the error response during login, making it possible to enumerate usernames. This PR removes this error message.
Fixes #
```docs
```

security: return error details when login failed

---

server/odc-service/src/main/java/com/oceanbase/odc/metadb/connection/DatabaseRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/DBSchemaIndexService.java

type-bug
For individual space, fixed a bug that would not sync all databases under the current organization

fix(database): Supports synchronization of individual space to all current organization databases

---

libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OBOracleSchemaAccessor.java

fix(db-browser):the ddl of produce has two semicolons

---

server/odc-service/src/main/java/com/oceanbase/odc/service/task/base/dataarchive/DataArchiveTask.java

enhancement
Sort the table by id and then execute in order.
Fixes #
```docs
```

enhancement(dlm): sort table by id

---

server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/project/ProjectService.java

type-bug
Synchronizing organization would fail for access denied.

fix(collaboration): access denied when synchronizing obcloud organization

---

server/integration-test/src/test/java/com/oceanbase/odc/service/script/ScriptServiceWithLocalTest.java
server/odc-service/src/main/java/com/oceanbase/odc/service/script/ScriptService.java

type-bug
add duplicated filename tag before suffix of filename
Fixes #
```docs
```

fix(Script): add duplicated filename tag before suffix of filename

---

server/odc-core/src/main/resources/i18n/BusinessMessages.properties
server/odc-core/src/main/resources/i18n/BusinessMessages_zh_CN.properties
server/odc-core/src/main/resources/i18n/BusinessMessages_zh_TW.properties
server/odc-migrate/src/main/resources/init-config/init/regulation-rule-applying.yaml
server/odc-migrate/src/main/resources/init-config/init/regulation-rule-metadata.yaml
server/odc-migrate/src/main/resources/migrate/common/V_4_2_3_10__adjust_sql_console_rules.sql
server/odc-service/src/main/java/com/oceanbase/odc/service/regulation/ruleset/RuleService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/regulation/ruleset/model/SqlConsoleRules.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/SessionSettingsService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/interceptor/SqlConsoleInterceptor.java

enhancement
Rename 'max-return-rows' rule-meta name and description, for synchronize the description of the query limit in the organization configuration item.
```docs
```

enhancement(regulation): rename 'max-return-rows' rule-meta name and description

---

pom.xml
server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/datatransfer/factory/DumpParameterFactory.java
server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/datatransfer/factory/LoadParameterFactory.java
server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/datatransfer/task/BaseOceanBaseTransferJob.java

upgrade ob-loader-dumper to 4.3.3.1-RELEASE

build: upgrade ob-loader-dumper to 4.3.3.1-RELEASE

---

server/odc-common/src/main/java/com/oceanbase/odc/common/task/RouteLogCallable.java
server/odc-migrate/src/main/resources/migrate/common/V_4_3_3_10__add_file_import_history.sql
server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/ExportController.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/iam/UserService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/export/ScheduleExportService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/export/ScheduleTaskExportCallable.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/export/model/BaseScheduleRowData.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/export/model/FileExportResponse.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/export/model/FileExportStatus.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/export/model/ScheduleExportListView.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/model/ScheduleMapper.java
server/odc-service/src/main/java/com/oceanbase/odc/service/state/StatefulUuidStateIdGenerator.java
server/odc-service/src/main/java/com/oceanbase/odc/service/state/model/StatefulUuidStateId.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/TaskService.java

type-feature
support community edition export schedule
Fixes #
```docs
```

feat(export): support community edition export schedule

---

server/odc-service/src/main/java/com/oceanbase/odc/service/resource/ResourceManager.java

type-bug
destroy may invoked multi times, cause it may be invoked by multi ODC node.
add database lock and status check to avoid this issue.
Fixes #
```docs
```

fix(resource): let resource destroy concurrent safe

---

server/odc-service/src/main/java/com/oceanbase/odc/service/flow/factory/FlowResponseMapperFactory.java

fix(flow): can view project when locate at applyDatabasePermission or applyTablePermission 

---

server/integration-test/src/test/java/com/oceanbase/odc/migrate/jdbc/common/V42013OAuth2ConfigMetaMigrateTest.java
server/integration-test/src/test/java/com/oceanbase/odc/migrate/jdbc/common/V4349OrganizationSecretMigrateTest.java
server/odc-migrate/src/main/java/com/oceanbase/odc/migrate/jdbc/common/V42013OAuth2ConfigMetaMigrate.java
server/odc-migrate/src/main/java/com/oceanbase/odc/migrate/jdbc/common/V4349OrganizationSecretMigrate.java
server/odc-service/src/main/java/com/oceanbase/odc/metadb/config/OrganizationConfigDAO.java
server/odc-service/src/main/java/com/oceanbase/odc/metadb/iam/OrganizationRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/service/config/OrganizationConfigKeys.java
server/odc-service/src/main/java/com/oceanbase/odc/service/config/OrganizationConfigService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/config/OrganizationConfigUtils.java
server/odc-service/src/main/java/com/oceanbase/odc/service/config/model/Configuration.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionEncryption.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/encryption/EncryptionFacadeImpl.java
server/odc-service/src/main/java/com/oceanbase/odc/service/iam/OrganizationService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/integration/util/EncryptionUtil.java
server/odc-service/src/main/resources/config-meta/organization-config-meta.yml
server/odc-service/src/test/java/com/oceanbase/odc/service/config/OrganizationConfigMetaServiceTest.java

feat
This PR add a data source key configuration item in the organization configuration.
-->
```docs
```

feat(config): Add a data source key configuration item in the organization configuration.

---

libs/db-browser/pom.xml
libs/ob-sql-parser/pom.xml
pom.xml

…ctively.
Update db-browser and ob-sql-parser versions to 1.2.3 and 1.4.2 respectively.
Fixes #
```docs
```

enhancement(odc):update version of db-browser and ob-sql-parser

---

server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/cloud/client/AmazonCloudClient.java

type-bug
fix response InvalidArgument error when download file from download presigned url of aws s3
Fixes #
```docs
```

fix(objectstorage): response InvalidArgument error when download file from download presigned url of aws s3

---

server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/DBMetadataController.java
server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBIdentitiesService.java

fix(session): Supports fuzzy matching of table names and view names

---

server/integration-test/src/test/java/com/oceanbase/odc/migrate/jdbc/common/V43410OrganizationSecretMigrateTest.java
server/odc-migrate/src/main/java/com/oceanbase/odc/migrate/jdbc/common/V43410OrganizationSecretMigrate.java

fix
rename migrate file
```docs
```

fix(migrate): rename duplicate migrate file

---

libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/OBMySQLSchemaAccessor.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OBOracleSchemaAccessor.java
libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/schema/OBMySQLSchemaAccessorTest.java
libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/schema/OBOracleSchemaAccessorTest.java

type-feature
Fixes #
```docs
```

feat(materialized view):adapt to the latest ob4352 changes

---

server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/cloud/client/AmazonCloudClient.java

type-bug
cherry pick from commit https://github.com/oceanbase/odc/pull/4375/commits/200e74d91bef7b69a3f129ac9591b04e21a10423
fix(objectstorage): response InvalidArgument error when download file from download presigned url of aws s3 
Fixes #
```docs
```

fix(objectstorage): response InvalidArgument error when download file from download presigned url of aws s3 

---

libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OBOracleSchemaAccessor.java

type-bug
The absence of the `schema `leads to an error reporting that the view does not exist
Fixes #
```docs
```

fix(db browser):desc view without schema

---

server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/project/ProjectService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/factory/FlowResponseMapperFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/iam/UserService.java

type-bug
ProjectService#listByIds , set creator by currentUser instead of creatorId
Fixes #
```docs
```

fix(flow): flow mapper not skip auth

---

libs/db-browser/pom.xml
libs/ob-sql-parser/pom.xml

documentation(pom):add developer in db-browser and ob-sql-parser

---

pom.xml
server/odc-service/pom.xml

build: add webflux dependency

---

server/integration-test/src/test/java/com/oceanbase/odc/metadb/config/OrganizationConfigDAOTest.java
server/odc-service/src/main/java/com/oceanbase/odc/metadb/config/OrganizationConfigDAO.java

fix
1.complete the missing parts in the configuration records
```docs
```

fix(config): fix organization config record information is incomplete

---

libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/MySQLNoLessThan5700SchemaAccessor.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/OBMySQLSchemaAccessor.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OBOracleBetween410And432SchemaAccessor.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OBOracleSchemaAccessor.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OracleSchemaAccessor.java

fix(db-browser): Add '%' when to like table name

---

server/odc-service/src/main/java/com/oceanbase/odc/service/datatransfer/task/DataTransferTask.java

type-bug
we should load hadoop.dll on windows

fix(data-transfer): load hadoop.dll on windows

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/LogicalTableExtractTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/core/LogicalTableFinder.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java

type-bug
1. fix the bug that the Apply Project tickets are not shown when created and under approval.
2. add some logs for logical table extract tasks.
Fixes #
```docs
```

fix(flow):  apply project tickets not shown when it's under approval

---

libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/OBMySQLSchemaAccessor.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OBOracleSchemaAccessor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBMaterializedViewService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBTableService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBViewService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/db/model/DatabaseAndMVs.java
server/odc-service/src/main/java/com/oceanbase/odc/service/db/model/DatabaseAndViews.java

1. Previously, odc would send multiple sql requests to obtain tables based on the number of schemas. Currently, it has been changed to sending only one sql request
2. Previously, if there were no base tables in the schema, the schema would not be displayed to the user. Currently, it has been changed to be displayed as well
Fixes #
```docs
```

enhancement(materialized view):Display all the databases when creating materialized views or views

---

server/odc-service/src/main/java/com/oceanbase/odc/metadb/flow/UserTaskInstanceRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/ApprovalPermissionService.java

fix(security): Approving flowInstance can over step authority

---

libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/DBSchemaAccessor.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/doris/DorisSchemaAccessor.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/MySQLNoLessThan5700SchemaAccessor.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/OBMySQLSchemaAccessor.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/ODPOBMySQLSchemaAccessor.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OBOracleBetween410And432SchemaAccessor.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OBOracleSchemaAccessor.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OracleSchemaAccessor.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/postgre/PostgresSchemaAccessor.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/util/MySQLSqlBuilder.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/util/OracleSqlBuilder.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/util/SqlBuilder.java
libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/schema/MySQLNoLessThan5700SchemaAccessorTest.java
libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/schema/OBMySQLSchemaAccessorTest.java
libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/schema/OracleSchemaAccessorTest.java
server/integration-test/src/test/java/com/oceanbase/odc/service/db/DBIdentitiesServiceTest.java
server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/DBMetadataController.java
server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBIdentitiesService.java

fix(db-browser): Support search table or view by identityNameLike

---

server/odc-service/src/main/java/com/oceanbase/odc/service/config/OrganizationConfigService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/git/GitIntegrationService.java

enhancement(config): adaptive multi cloud

---

server/odc-migrate/src/main/resources/init-config/default-audit-event-meta.yml
server/odc-service/src/main/java/com/oceanbase/odc/service/audit/AuditEventAspect.java

fix
Fix the database operation type in the audit event that does not record database information
```docs
```

fix(audit): Fix the database operation type in the audit event that does not record database info

---

libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/DBSchemaAccessor.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/doris/DorisSchemaAccessor.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/MySQLNoLessThan5700SchemaAccessor.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/OBMySQLBetween432And4352SchemaAccessor.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/OBMySQLSchemaAccessor.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OBOracleBetween432And4352SchemaAccessor.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OBOracleSchemaAccessor.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OracleSchemaAccessor.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/postgre/PostgresSchemaAccessor.java
libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/schema/MySQLNoLessThan5700SchemaAccessorTest.java
libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/schema/OBMySQLSchemaAccessorTest.java
libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/schema/OBOracleSchemaAccessorTest.java
libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/schema/OracleSchemaAccessorTest.java

type-bug
1. fix the sql error of the fuzzy query in the materialized view
2. modify the method signature of the materialized view
3. add tests for fuzzy query
Fixes #
```docs
```

fix(db browser): fix the syntax error of fuzzy query

---

server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/FlowInstanceController.java
server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/ScheduleController.java
server/odc-server/src/main/resources/log4j2.xml
server/odc-service/src/main/java/com/oceanbase/odc/config/ScheduleConfiguration.java
server/odc-service/src/main/java/com/oceanbase/odc/service/common/FutureCache.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/model/BatchTerminateFlowResult.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/export/ScheduleExportService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/export/ScheduleTaskImportService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/export/model/ScheduleTerminateCmd.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/export/model/ScheduleTerminateResult.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/util/BatchSchedulePermissionValidator.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/logger/LogUtils.java

type-feature
support batch terminal schedule and schedule task;
support batch terminal flow instance;
Fixes #
```docs
```

feat(shecule): add batch terminal

---

libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/model/DBTableColumn.java

type-bug
odc is not compatible with the `duplicate index`, resulting in failure
Fixes #
```docs
```

fix(db browser):failed to get table in doris

---

server/odc-service/src/main/java/com/oceanbase/odc/metadb/schedule/ScheduleRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/model/InnerQueryFlowInstanceParams.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/model/QueryScheduleStatParams.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/model/ScheduleStat.java

type-bug
Add a field to count the number of all state schedule for each scheduleType type

fix(schedule): To stat the count of all state schedule for each scheduleType type

---

pom.xml

type-bug
FYI
Fixes #
```docs
```

fix(dlm): upgrade sdk version to 1.2.5

---

pom.xml
server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMJobStore.java
server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/executor/AbstractQuartzJob.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataArchiveDeleteJob.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataArchiveRollbackJob.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/listener/DefaultJobTerminateListener.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/processor/terminate/DLMTerminateProcessor.java

type-bug
FYI
Fixes #
```docs
```

fix(dlm): upgrade sdk version to 1.2.3.1

---

server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/cloud/CloudResourceConfigurations.java

type-feature
support awscn
Fixes #
```docs
```

fix(object): support awscn

---

server/odc-service/src/main/java/com/oceanbase/odc/service/loaddata/model/ObjectStorageConfig.java

type-feature
support awscn
Fixes #
```docs
```

fix(objects): support awscn

---

server/odc-core/src/main/java/com/oceanbase/odc/core/alarm/AlarmUtils.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/PartitionPlanJob.java

type-bug
add partitionplan alarm
Fixes #
```docs
```

fix(alarm): add partitionplan alarm

---

server/odc-service/src/main/java/com/oceanbase/odc/service/partitionplan/PartitionPlanScheduleService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java

type-bug
fix cycle dependence
Fixes #
```docs
```

fix(scheudle): fix cycle dependence

---

server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/DefaultSpringJobConfiguration.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/DefaultTaskFrameworkProperties.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/TaskFrameworkProperties.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/resource/manager/strategy/k8s/K8SResourceManageStrategy.java

type-feature
let  supervisor pod release back time configureable, default value is 300 seconds
Fixes #
```docs
```

feat(task): let supervisor pod release back time configureable

---

server/odc-server/src/main/resources/config/application.yml
server/odc-server/src/main/resources/config/bootstrap.yml

type-feature
metadb jdbc url support configure
Fixes #
```docs
```

feat(config): metadb jdbc url support configure

---

.vscode/settings.json
server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/CloudMetadataController.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/CloudMetadataClient.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/OBInstance.java

type-bug
The obcloud needs to support find instances by obcloud project id, so I add a mothod in the interface.
Fixes #
```docs
```

fix(obcloud): add method listInstancesByProjectId for CloudMetadataClient

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/factory/OBConsoleDataSourceFactory.java

type-bug
The Oracle datasource's connect/socket timeout is not set correctly, which may cause to connection leak.
Fixes #
```docs
```

fix(connection): The Oracle datasource's connect/socket timeout is not set correctly which may cause to connection leak.

---

server/integration-test/src/test/java/com/oceanbase/odc/service/config/UserConfigServiceTest.java
server/odc-service/src/main/java/com/oceanbase/odc/service/config/UserConfigService.java

type-bug
We should add consumers in list default configurations, instead of list configurations. 
Fixes #
```docs
```

fix(config): add user default configurations consumers 

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/OBInstance.java

type-bug
Add 'scenario' field in OBInstance class to distinguish ap/tp instances.
Fixes #
```docs
```

fix(obcloud): add 'scenario' field in OBInstance class

---

server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/oscfms/action/oms/ProjectStepResultChecker.java

type-bug
Oms removed increment progress compute, that will cause ODC osc check if OMS if ready failed.
Fixes #
```docs
```

fix(osc): remove increment progress check

---

server/odc-service/src/main/java/com/oceanbase/odc/service/partitionplan/PartitionPlanScheduleService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/util/BatchSchedulePermissionValidator.java

type-bug
fix circular dependency
Fixes #
```docs
```

fix(flowable): fix circular dependency

---

server/odc-service/src/main/java/com/oceanbase/odc/service/permission/DBResourcePermissionHelper.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/processor/ScheduleChangePreprocessor.java

type-bug
add permission check when creating schedule tasks
Fixes #
```docs
```

fix(permissoin): add permission check when creating schedule tasks

---

server/odc-server/src/main/java/com/oceanbase/odc/agent/runtime/TaskMonitor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/DefaultSpringJobConfiguration.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/DefaultTaskFrameworkProperties.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/TaskFrameworkProperties.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/constants/JobEnvKeyConstants.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/resource/manager/strategy/k8s/K8SResourceManageStrategy.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/v2/DoFinishJobV2.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/v2/StartPreparingJobV2.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/util/JobUtils.java

merge: merge 4.3.x task fix to 4.3.4

---

server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/MySQLOfflineDdlExists.java
server/odc-service/src/test/java/com/oceanbase/odc/service/sqlcheck/MySQLCheckerTest.java

fix(sqlcheck): fix online ddl check failed when createTable is null

---

distribution/docker/odc/Dockerfile

type-bug
upgrade python and pip version
Fixes #
```docs
```

fix(security): upgrade python and pip version

---

server/odc-service/src/main/java/com/oceanbase/odc/service/task/listener/DefaultJobTerminateListener.java

fix(task-framework): wrong status when task failed

---

server/odc-service/src/main/java/com/oceanbase/odc/service/task/listener/DefaultJobTerminateListener.java

* rollback correct status
* code format
Fixes #
```docs
```

fix(task-framework): wrong status when task failed (#4469)

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionService.java

fix(odc-desktop): download size of datasource_template always is 0B

---

server/odc-service/src/main/java/com/oceanbase/odc/metadb/notification/MessageRepository.java

type-bug
fix a jpa exception
Fixes #
```docs
```

fix(notification): can't send failSendingTimeoutMessages

---

server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java

type-bug
if process instance not exist, delete flow process instance will throw exception. check before  delete
Fixes #
```docs
```

firx(flow): check exists before delete flow process instance

---

server/odc-service/src/main/java/com/oceanbase/odc/service/exporter/impl/JsonExtractor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/export/ScheduleTaskExporter.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/export/ScheduleTaskImportService.java

type-bug
1. When in the personal space, the ProjectId will be equal to -1, and shuold not query db to find project.
2. When previewing the import task, closing the stream too early may cause the preview to fail.
Fixes #
```docs
```

fix(export): can't export partitionPlan in individual space 
