server/odc-service/src/main/java/com/oceanbase/odc/service/resultset/ResultSetExportTask.java

When dump result set on alibaba cloud, an wrong filename would be exported.
Use `File#getName` as filename instead.
Test env must be alibaba cloud or ob-cloud
N/A
N/A

[Fix]: fix get wrong filename when export result set

---

server/odc-service/src/main/java/com/oceanbase/odc/service/automation/model/AutomationRule.java
server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/model/MaskingAlgorithm.java
server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/model/SensitiveColumn.java
server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/model/SensitiveRule.java
server/odc-service/src/main/java/com/oceanbase/odc/service/iam/model/Role.java
server/odc-service/src/main/java/com/oceanbase/odc/service/integration/model/IntegrationConfig.java
server/odc-service/src/main/java/com/oceanbase/odc/service/regulation/risklevel/model/RiskDetectRule.java
server/odc-service/src/main/java/com/oceanbase/odc/service/regulation/risklevel/model/RiskLevel.java
server/odc-service/src/main/java/com/oceanbase/odc/service/regulation/ruleset/model/Rule.java

Read-write "id" field may lead to overstep
Make `id` field in DTO objects readonly
manually
Compatible

security: read-write "id" field may lead to overstep

---

server/integration-test/src/test/java/com/oceanbase/odc/service/session/ConnectConsoleServiceTest.java
server/odc-core/src/main/java/com/oceanbase/odc/core/session/ConnectionSessionUtil.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/factory/DefaultConnectSessionFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/model/SqlExecuteResult.java

After adding new columns to the table, when inserting table data,  the generated insert into statement still only has the original columns.
Backend get `columnList` from cache, so when the user adds a field to a table, the `columnList `does not have the new field. The front end relies on the `columnList` field to obtain the field information of the table, and all subsequent components pass information through this field.
Delete `tableColumnsCache` and `viewColumnsCache`.
The cache was used before because the oracle statement querying constraint information was time-consuming, but the current `tryToGetTableColumnsFromCache` method has removed this logic, only querying the column information, and the query of the column information is not time-consuming, so there is no need to use this …

[Fix]: Generated insert into statement error after executing alter table add column statement

---

.github/workflows/build_artifact.yaml
.github/workflows/build_daily.yaml
.github/workflows/build_dev.yaml
.github/workflows/build_release.yaml

type-feature
Refine workflow config,and add a new workflow dedicated to build artifacts:
1. rename build_test to build_daily;
2. add a new workflow dedicated to build artifacts.
```docs
```

refine(workflow): add new workflow for building artifact and refine config

---

.github/workflows/build_artifact.yaml

type-feature, type-refactor
We publish db-browser and ob-sql-parser by maven central repo, and we cannot publish to the central warehouse during the R&D process.
So, here is the solution. We install them into local machine which we run our workflow, so that we can build a jar that include what we modify on db-browser and ob-sql-parser
Fixes #
```docs
```

feat(workflow): add checkbox in workflow to decide weather to install db-browser and ob-sql-parser

---

server/odc-service/src/main/java/com/oceanbase/odc/service/session/factory/DefaultConnectSessionFactory.java

type-bug
module-resultset
Because a variable in the ConnectionSession has not been initialized, the task of exporting the result set fails to obtain sensitive columns. 
As a result, the data has not been desensitized. It is a serious bug.
Fixes  https://github.com/oceanbase/odc/issues/80
```docs
```

fix(result-set): fix NPE by setting column accessor during session initialization

---

server/integration-test/src/test/java/com/oceanbase/odc/service/dml/DeleteGeneratorTest.java
server/integration-test/src/test/java/com/oceanbase/odc/service/dml/InsertGeneratorTest.java
server/integration-test/src/test/java/com/oceanbase/odc/service/dml/UpdateGeneratorTest.java
server/odc-service/src/main/java/com/oceanbase/odc/service/dml/BaseDMLBuilder.java
server/odc-service/src/main/java/com/oceanbase/odc/service/dml/MySQLDMLBuilder.java
server/odc-service/src/main/java/com/oceanbase/odc/service/dml/OracleDMLBuilder.java
server/odc-service/src/main/java/com/oceanbase/odc/service/dml/TableDataService.java

type-bug
module-resultset
For any schema, when the number of rows in the edited result set exceeds 100, the time required to generate SQL is at the minute level.
The root cause of above problem is abundant database queries. In this PR, it's been fixed. Only one query would be executed during generating DMLs.
```docs
```

fix(result-set): generate dml slowly when edit result-set

---

server/odc-service/src/main/java/com/oceanbase/odc/service/info/InfoAdapter.java
server/odc-service/src/main/java/com/oceanbase/odc/service/info/OdcInfoService.java
server/starters/desktop-starter/src/main/java/com/oceanbase/odc/service/info/DesktopInfoAdapter.java
server/starters/web-starter/src/main/java/com/oceanbase/odc/service/info/WebInfoAdapter.java

type-refactor
This PR moves getBuildTime and getBuildVersion into InfoAdaptor interface. The reason for this change is making any other starters can define their own version and pass it to front-end

reafctor: move build time and build version into InfoAdaptor interface

---

server/integration-test/src/test/java/com/oceanbase/odc/service/onlineschemachange/DdlUtilsTest.java
server/integration-test/src/test/java/com/oceanbase/odc/service/onlineschemachange/ddl/TableNameReplacerTest.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/DefaultOnlineSchemaChangeTaskHandler.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/OnlineSchemaChangeFlowableTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/ddl/DdlUtils.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/pipeline/BaseCreateOmsProjectValve.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/subtask/OscTaskCompleteHandler.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/subtask/SubTaskParameterFactory.java

module-oneline schema change
1.Create table failed when table contains chinese charcter wrapped by quote
1.Create new table with origin wrapped character
2.Drop new table created by task when task is failed
3.fix checkTaskCronExpression which is not initlized
```docs
```

fix create oracle table failed with quote wrapped by special character

---

server/odc-core/src/main/java/com/oceanbase/odc/core/sql/execute/SqlExecuteStages.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/OdcStatementCallBack.java

type-feature
module-sql execution
1. Different data sources uniformly use `DB_SERVER_EXECUTE_SQL` as DB time-consuming, delete `OBSERVER_EXECUTE_SQL`
2.  fix native mysql show DB execution time unit conversion error
Fixes #2
```docs
```

feat(mysql): sql execution adaption for mysql5.7

---

server/odc-service/src/main/java/com/oceanbase/odc/service/session/interceptor/SqlCheckInterceptor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/BaseSqlChecker.java
server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/SqlCheckContext.java
server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/SqlCheckService.java

type-bug
this pr fix a bug, and you can get more details in related.
Fixes #108
```docs
```

fix(sql-check): fix can not detect table&column comment when execute a sqlscript

---

server/integration-test/src/test/java/com/oceanbase/odc/service/onlineschemachange/OscFactoryWrapperGeneratorTest.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/DefaultOnlineSchemaChangeTaskHandler.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/ddl/BaseTableNameDescriptorFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/ddl/DdlConstants.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/ddl/OBMySqlTableNameDescriptorFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/ddl/OBOracleTableNameDescriptorFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/ddl/OBOracleTableNameReplacer.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/model/OnlineSchemaChangeScheduleTaskParameters.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/subtask/SubTaskParameterFactory.java

type-debug
type-online schema change
fix alter type execute failed 
1. oracle new table name with suffix with  "OSC_NEW_" and renamed table suffix with "OSC_OLD_"
2. fix alter type sql replaced by new table name
3. fix oracle constraints name with uuid, old renamed style may overrun 128 characters
```docs
```

fix(osc): fix sql of alter replace table name not correct

---

server/integration-test/src/test/java/com/oceanbase/odc/service/flow/FlowApprovalInstanceTest.java
server/integration-test/src/test/java/com/oceanbase/odc/service/flow/FlowFactoryTest.java
server/integration-test/src/test/java/com/oceanbase/odc/service/flow/FlowInstanceServiceTest.java
server/integration-test/src/test/java/com/oceanbase/odc/service/flow/FlowInstanceTest.java
server/integration-test/src/test/java/com/oceanbase/odc/service/flow/FlowInstanceUtilTest.java
server/integration-test/src/test/java/com/oceanbase/odc/service/flow/FlowResponseMapperFactoryTest.java
server/integration-test/src/test/java/com/oceanbase/odc/service/flow/FlowableAdaptorTest.java
server/integration-test/src/test/java/com/oceanbase/odc/service/integration/IntegrationTestUtil.java
server/odc-core/src/main/java/com/oceanbase/odc/core/flow/model/FlowableElement.java
server/odc-service/src/main/java/com/oceanbase/odc/metadb/flow/UserTaskInstanceRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/factory/FlowFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/factory/FlowResponseMapperFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/instance/FlowApprovalInstance.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/instance/FlowInstanceConfigurer.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/model/FlowNodeInstanceDetailResp.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/CreateExternalApprovalTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/model/RuntimeTaskConstants.java
server/odc-service/src/main/java/com/oceanbase/odc/service/integration/ApprovalSynchronizer.java
server/odc-service/src/main/java/com/oceanbase/odc/service/integration/client/ApprovalClient.java
server/odc-service/src/main/java/com/oceanbase/odc/service/integration/client/SqlInterceptorClient.java
server/odc-service/src/main/java/com/oceanbase/odc/service/integration/model/TemplateVariables.java

Fix bug: A new instance of external approval is always created when a ticket is initiated
Fixes #67 
Close #67 
Already passed testing in BPMS.

fix(integration): external approval is always created when initiating a ticket

---

server/integration-test/src/test/java/com/oceanbase/odc/service/onlineschemachange/OnlineSchemaChangeValidatorTest.java
server/integration-test/src/test/java/com/oceanbase/odc/service/onlineschemachange/ddl/TableNameReplacerTest.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/ddl/OBMysqlTableNameReplacer.java

type-bug
type-Online schema change
occur duplicate key error when create a new table contain  foreign key with the same constraint name  exists in database
replace the old constraint name by TokenStreamRewriter when antlr invoke enterConstraint_name
```docs
```

fix(osc): fix duplicate foreign key constraint name when execute new table create ddl

---

server/odc-service/src/main/java/com/oceanbase/odc/service/pldebug/session/DebuggerSession.java

type-bug
module-PL debugger
this pr throw an exception when failed to starting debugging which gives a clear error information.
Fixes #162 
Close #162 
Executing and debugging an anonymous block inside an anonymous block fails because there is a '/' at the end of the anonymous block, which causes a syntax error. 
This is not a problem in itself, because the anonymous block window is designed not to split sentences, causing the '/' at the end of the anonymous block to be sent to the server for execution. 
The problem is that when the debugging failed, the user was not informed of the specific cause of the failure. This PR will inform the user of the specific cause of the error
```docs
```

fix(pl-debug): add exception prompt when debugging errors

---

libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/OBMySQLBetween2277And3XSchemaAccessor.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/OBMySQLSchemaAccessor.java
libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/schema/OBMySQLSchemaAccessorTest.java

type-bug
module-SyncDatabase
1. fix ob mysql before 4.x can see other tenant's  schemas when syncDatabase by adding filter:`where a.tenant_id=EFFECTIVE_TENANT_ID()` in `OBMySQLBetween2277And3XSchemaAccessor`
2. sys tenant can found `LBACSYS`、`ORAAUDITOR`、`__public` schema in `oceanbase.gv$database`，so filter these database names in `OBMySQLBetween2277And3XSchemaAccessor` and `OBMySQLSchemaAccessor`
Fixes #50
```docs
```

fix(syncDatabase): fix ob mysql before 4.x can see other tenant's  schemas when syncDatabase

---

server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/DefaultOnlineSchemaChangeTaskHandler.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/oms/client/BaseOmsClient.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/pipeline/ProjectStepResultChecker.java

type-bug
log password and check full verify result cause npe
1. fix check full verify result may cause npe when verify result is not arrived
2. fix clean up password in log when request oms create datasource failed
```docs
```

fix(osc): fix old running task throw npe when enable full verify  

---

server/odc-service/src/main/java/com/oceanbase/odc/service/pldebug/session/AbstractDebugSession.java
server/odc-service/src/main/java/com/oceanbase/odc/service/pldebug/session/DebuggeeSession.java
server/odc-service/src/main/java/com/oceanbase/odc/service/pldebug/session/DebuggerSession.java

type-bug
bugger attach session failed when connect to proxy
Debugger must connect to database host the same as debuggee, so debuggee connect to ob directly,  debugger clone a datasource by debuggee datasource and get connection from it.
```docs
```

fix(pldebug): fix debugger create new connection attach debuggee sessionId failed

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/ConnectSessionService.java

type-security
Some method does not check horizontal permission, which may cause broken horizontal access control. Use HorizontalDataPermissionValidator to validate permission

security: bad horizontal access control

---

server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/ErrorCodes.java
server/odc-core/src/main/resources/i18n/ErrorMessages.properties
server/odc-core/src/main/resources/i18n/ErrorMessages_zh_CN.properties
server/odc-core/src/main/resources/i18n/ErrorMessages_zh_TW.properties
server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBRecyclebinService.java

type-bug
this pr fix a bug that odc can not generate flashback sql on some types, just like `normal index`.
Fixes #295 
Close #295 
OceanBase only supports some specific types for flashback, `TABLE`, `VIEW`, `TENANT`, `DATABASE` and `SCHEMA`.
ODC will give up generating sql when recycle object's type is not in available types, that is why the api returns nothing.
To fix this bug, we generate a comment to tell the user that your recycle object's type is invalid rather than ignore it
```docs
```

fix(recyclebin): fix failed to generate flashback sql

---

server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DataTransferRuntimeFlowableTask.java

type-bug
module-data-transfer
In #73 , we supported user to preview transfer objects. But the status of these objects wouldn't be updated. In this PR, the status in table `task_task` will be updated real-time.
Fixes #271 
```docs
```

fix(data-transfer): failed to update data-transfer task status during running

---

server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/extractor/OBColumnExtractor.java
server/odc-service/src/test/java/com/oceanbase/odc/service/datasecurity/extractor/OBColumnExtractorTest.java
server/odc-service/src/test/resources/datasecurity/test_sensitive_column_extractor_sql.yaml

type-bug
module-Data masking
Fix bug during data masking
Fixes #319 
Unit test is covered

fix: data masking failed with multiple join clause in SQL

---

server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/DefaultOrganizationResourceMigrator.java
server/starters/desktop-starter/src/main/java/com/oceanbase/odc/service/collaboration/DesktopOrganizationResourceMigrator.java

type-bug
ODC failed to start on clientMode for ` No qualifying bean of type 'com.oceanbase.odc.service.collaboration.OrganizationResourceMigrator' available:`
After remove the `@Profile` annotation, ODC can start normally.
Fixes https://github.com/oceanbase/odc/issues/343
```docs
```

fix(clientMode): odc fail to start on clientMode

---

server/starters/desktop-starter/src/main/java/com/oceanbase/odc/service/collaboration/DesktopOrganizationResourceMigrator.java

type-bug 
In PR #345  , we added a service named DesktopOrganizationResourceMigrator. But it missed `@Service` annotation, leading to start failure for desktop.
Now it would be completed.
```docs
```

fix(clientMode): fail to start for lack of Service annotations

---

server/odc-server/src/main/java/com/oceanbase/odc/server/config/MvcConfiguration.java

type-bug
After the #338 commit was merged, I find the api response is converted into XML format, causing the ODC server cannot be used by front-end.
In this PR, I fix this issue by set `application/json` as the default content type by implements the `WebMvcConfigurer`:
```java
@Override
public void configureContentNegotiation(ContentNegotiationConfigurer config) {
config.defaultContentType(MediaType.APPLICATION_JSON, MediaType.ALL);
}
```

fix(mvc): api response content type converts to  xml

---

libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/OBMySQLBetween2277And3XSchemaAccessor.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/OBMySQLSchemaAccessor.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OBOracleSchemaAccessor.java
server/odc-migrate/src/main/resources/migrate/common/V_4_2_1_6__alter_connect_database.sql
server/odc-service/src/main/java/com/oceanbase/odc/config/RestTemplateConfig.java
server/odc-service/src/main/java/com/oceanbase/odc/config/ScheduleConfiguration.java
server/odc-service/src/main/java/com/oceanbase/odc/metadb/connection/ConnectionConfigRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/DatabaseSyncSchedules.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseSyncManager.java
server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBSchemaService.java

type-bug
This PR fixed these issues:
1. The individual space databases cannot be displayed in real-time.
2. Oceanbase MySQL datasource synchronization heavily depends on oceanbase.gv$database select privilege.
3. The datasource synchronization is not triggered when modifying the data source.
4. The datasource synchronization schedule is unexpectedly slow.
1. When listing databases, we do a datasource synchronization automatically
2. Use information_schema.schemata instead of oceanbase.gv$database. Additionally, we do not rely on a real unique database_id anymore, we just simply use the database name as the database_id instead.
3. After modifying datasource configuration, we trigger a datasource synchronization.
4. Add the thread pool size to 64.
1. Change the timeout of …

fix(datasource): optimize datasource synchronization

---

libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/editor/DBTableEditor.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/editor/mysql/MySQLTableEditor.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/editor/mysql/OBMySQLTableEditor.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/editor/oracle/OracleTableEditor.java
libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/editor/DBTableEditorTest.java
libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/editor/MySQLTableEditorTest.java
server/odc-service/src/main/java/com/oceanbase/odc/service/db/browser/DBTableEditorFactory.java
server/plugins/schema-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/schema/obmysql/OBMySQLTableExtension.java

module-Schema object
The table creation statement generated by DBTableEditor by  OB MYSQL mode cannot be executed in native MySQL.
In `DBTableEditor#appendTableOptions`:
```
if (Objects.nonNull(options.getReplicaNum())) {
sqlBuilder.append("REPLICA_NUM = ").append(String.valueOf(options.getReplicaNum())).space();
}
if (Objects.nonNull(options.getUseBloomFilter())) {
sqlBuilder.append("USE_BLOOM_FILTER = ").append(options.getUseBloomFilter() ? "TRUE" : "FALSE").space();
}
if (Objects.nonNull(options.getTabletSize())) {
sqlBuilder.append("TABLET_SIZE = ").append(String.valueOf(options.getTabletSize())).space();
}
```
These three parameters are unique to OB server. Neither native mysql nor oracle support these three parameters.
So `OBMySQLTableEditor` was created to distinguish these …

refactor(DBTableEditor): DBTableEditor adapt for native mysql and ob mysql

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/AbstractDlmJobPreprocessor.java

type-bug
Validate condition timeout when the amount of data is too large
```docs
```

fix(dlm): validate condition by sql explain.

---

server/odc-service/src/main/java/com/oceanbase/odc/metadb/datasecurity/SensitiveRuleRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/SensitiveColumnService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/SensitiveRuleService.java

type-bug
Here is a bug: when all recognition rules are selected, the disabled rules will be recognized together.
This PR will fix it by add `enbaled` into filtering condition
Fixes #433 
Close #433

fix(data-security): use disabeld recognition rules when select all rules

---

server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DatabaseChangeRuntimeFlowableTask.java

type-bug
module-database change task
`ConnectionSession` generated by `DefaultConnectSessionFactory` will be expired in 8 hour. So if a sql in database change task executing more than 8 hour, then the next sql will executing failed.
This PR fix it by setting the timeout to the timeout of the task rather than 8 hour.
Fixes #453

fix(database-change): database change failed if executing a sql more than 8 hour

---

server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/extractor/OBColumnExtractor.java

type-bug
In MySQL mode, if the column name is uppercase, then the data masking will fail.
The sensitive column name stored in ODC metaDB is case-insensitive when executing comparison. So we should compare the column name ignoring case. If there are two columns with the same name but different case, then we will recognize both of them as sensitive columns even though only one of them is marked sensitive.
This PR fixed it by using `equalsIgnoreCase` to compare column names.
Fixes #481 
Passed self-test

fix(data-security): data masking failed when using uppercase column name

---

server/integration-test/src/test/java/com/oceanbase/odc/metadb/connection/ConnectionAttributeRepositoryTest.java
server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/ErrorCodes.java
server/odc-core/src/main/resources/i18n/ErrorMessages.properties
server/odc-core/src/main/resources/i18n/ErrorMessages_zh_CN.properties
server/odc-core/src/main/resources/i18n/ErrorMessages_zh_TW.properties
server/odc-migrate/src/main/resources/migrate/common/V_4_2_2_3__add_connect_connection_attribute.sql
server/odc-service/src/main/java/com/oceanbase/odc/metadb/connection/ConnectionAttributeEntity.java
server/odc-service/src/main/java/com/oceanbase/odc/metadb/connection/ConnectionAttributeRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionTesting.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/ConnectionConfig.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/ConnectionTestResult.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/TestConnectionReq.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/util/ConnectTypeUtil.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/ConnectSessionService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/factory/DruidDataSourceFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/factory/OBConsoleDataSourceFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/initializer/SessionCreatedInitializer.java

type-feature
this pr add initialization configuration capabilities for data sources.
User can give a sql script that executed when jdbc connection created to init the connection. 
eg. if you want to set your sql execution timeout, you can give a sql script like this:
```SQL
set session ob_query_timeout=60000000;
set session ob_trx_timeout=60000000;
```
odc will execute them one by one when you want to create a session on this datasource.
odc connects to observer by jdbc, if you want to add some your custom jdbc parameters, you can to this by this pr. odc will append your custom jdbc parameters to the url.
this init config will work in every session creation scenario.
Fixes #93 
I create a new table named `connec_connection_attribute`, this table will be not only used by this feature, but …

feat(connection): add initialization configuration capabilities for data sources

---

libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/MySQLNoGreaterThan5740SchemaAccessor.java

type-bug
module-database object
fix get view failed without show view permission
Fixes #419
```docs
```

fix(view): fix get view failed without show view permission

---

server/odc-test/src/main/java/com/oceanbase/odc/test/database/TestDBConfigurations.java

type-security bug
The unit test log will expose sensitive info such as datasource password. This PR fix it.

fix(unit-test): unit test logs expose sensitive information

---

server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/extractor/OBColumnExtractor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/extractor/model/DBColumn.java
server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/model/SensitiveColumnMeta.java

type-bug
There are two bug:
1. If the table name or database name is uppercase in MySQL  mode, the data masking will failed. The root cause is that ODC will change DB object name to lowcase in MySQL mode. If the table name is uppercase in DB Server, then ODC cannot find the right table. 
2. The exists sensitive is not filtered.
This PR fix above two bugs. Table name and column name stored in ODC metaDB is case-insensitive. So ODC cannot deal with sensitive columns with same name in different case. So, ODC will  defaultly change the object name to lowcase in MySQL mode and uppercase in Oracle mode. If the object name is quoted, then ODC will keep the case themselves.
Fixes #475 

fix(data-security): exist sensitive is not filtered and view desensitization data failed

---

server/odc-core/src/main/java/com/oceanbase/odc/core/shared/model/TraceSpan.java
server/odc-core/src/main/java/com/oceanbase/odc/core/sql/util/FullLinkTraceUtil.java
server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBRecyclebinService.java

type-feature
feat-adapt to ob 4.2
this pr makes odc adapt to OceanBase 4.2. we do things in this pr as follow:
1. add schema in generated flashback sql.
the front end will create a new session when using recyclebin so that the observer will flashback the object to the schema where the connection connect to.
To avoid flashbacking a db object to an uncertain schema, we should add schema to the generated sql. 
Here is an example:
```SQL
flashback table `abcd` to before drop rename to `new_name`; -- before
flashback table `abcd` to before drop rename to `schema`.`new_name`; -- after
```
2. refactor the pojo object's (`TraceSpan`) structure of full-link trace and convert the field `tags`'s type from `List<Map<String, Object>>` to `List<Object>`. 
we will get the json string on OceanBase 4.1 …

feat: make odc adapt to OceanBase 4.2

---

server/integration-test/src/test/java/com/oceanbase/odc/service/flow/ExpiredDocumentProviderTest.java
server/odc-common/src/test/java/com/oceanbase/odc/common/util/SystemUtilsTest.java

type-bug
module-unit test
The `SystemUtilsTest` has unsafe log output, which will expose sensitive env variables.
The `ExpiredDocumentProviderTest#provide_BothExpired_ReturnAll` is unstable due to not strictly logical.
This PR fix these two issues.

fix(unit-test): unsafe log output and unstable test case

---

server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DatabaseChangeRuntimeFlowableTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DatabaseChangeThread.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/factory/OBConsoleDataSourceFactory.java

type-bug
databasechange task takes too long time to start up which causes error printing by monitor task. I move the sql script read logic to task running phase to reduce the startup time.
Fixes #550 
```docs
```

fix(databasechange): fix task costs too much time to start up

---

server/odc-service/src/main/java/com/oceanbase/odc/service/common/util/FileConvertUtils.java
server/odc-service/src/main/java/com/oceanbase/odc/service/datatransfer/LoadParameterFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/resultset/ResultSetExportTask.java

type-bug
When export result set into Excel format, and the records contains `\t` like `xxx\txxx`, OB-DUMPER will use double quote as escape char because of ODC's setting. So the final form in the file is like `...,"xxx"      xxxx",...`.
But when convert it into .xls format, ODC use `org.apache.commons.csv` to parse CSV file. It can not parse this record, and would report IOException.
So when export into csv, we use backslash instead of quote. The above record will be translated like `..."xxx\      xxx"...`, which common-csv could recognize.
Fixes #457
```docs
```

fix(result-export): failed to convert CSV file into Excel file

---

.gitignore
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/MySQLNoGreaterThan5740SchemaAccessor.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/OBMySQLSchemaAccessor.java
libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/schema/MySQLNoGreaterThan5740SchemaAccessorTest.java
libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/schema/OBMySQLSchemaAccessorTest.java
libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/schema/OBOracleSchemaAccessorTest.java

type-bug
module-Database object
1. Fix cannot get table charset in native mysql mode. OB mysql get table charset by `DBSchemaAccessorUtil#obtainOptionsByParse` which is not work for native mysql mode. 
we can get table by parse table ddl in both mysql and ob mysql mode. add `obtainOptionsByParser` method and use it to get table options.
2. optimize DBSchemaAccessor ut test by create `private static DBSchemaAccessor accessor`
3. fix `@Ignore("TODO: fix this test case")` ut test. I consulted kernel classmates and found that the `comment` field of the `information_schema.STATISTICS` table and the `comment` field of the `show index from` query have different sources and meanings. The `comment` field of `information_schema.STATISTICS` cannot be used to indicate the status of the index, so for …

fix(db-browser): cannot get table charset in native mysql mode

---

server/odc-service/src/main/java/com/oceanbase/odc/service/session/factory/OBConsoleDataSourceFactory.java

type-bug
`sendConnectionAttributes` is hard code in `OBConsoleDataSourceFactory` and ODC will ignore the user settings when he/she sets `sendConnectionAttributes`.
I changed the code logic to: User's settings can override hard coding.
Fixes #600 
```docs
```

fix(connection): fix failed to set 'sendConnectionAttributes' jdbc parameter

---

server/integration-test/src/test/java/com/oceanbase/odc/service/connection/ConnectionConfigServiceTest.java
server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/DataSourceController.java
server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/environment/EnvironmentService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/ConnectionConfig.java

type-bug
module-datasource
While there is a huge amount of data sources (like 3k), the data source list on the left side in the SQL console refreshes very slowly, and the data source connect status would always be loading without response. 
The related API:
- `/api/v2/collaboration/projects/databases/stats`
- `/api/v2/datasource/datasources/status`
The reason for the slow stats API is that when we convert entities to DTOs, our time cost is O(n) because we will query the environment entity for each data source. To solve this issue, we just query the environments only one time, to load the results into the map, and find the specific environment entity by id. In this way, the time cost is reduced to O(1).
The reason for not being able to load the data source status is that the browser limits …

fix(datasource): the data source list refreshes very slowly and cannot obtain the connect status while there are a huge amount of data sources

---

server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/SensitiveColumnService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/model/DatabaseWithAllColumns.java

type-feature
When manually add sensitive columns, we will show column type icon as followings:
Different databse type and version has different column type, so we need response data type unit to front-end.
Fixes #46

feat(data-security): add data type unit into response

---

server/odc-core/src/main/java/com/oceanbase/odc/core/sql/split/SqlCommentProcessor.java
server/odc-core/src/test/java/com/oceanbase/odc/core/sql/split/SqlCommentProcessorTest.java

type-feature
The `SqlCommentProcessor` needs to read SQL text into memory at once and then split it. When the SQL file is large, OOM exceptions may occur. 
This PR supports reading and splitting SQL through a `InputStream`.
none, just an optimization
The UT has passed.
```docs
```

feat(sql-splitter): support SqlCommentProcessor to split sql by stream

---

server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java

type-bug
module-database-change
after creating a scheduled database change task in personal space, the task details cannot be viewed after checking the option to generate a rollback plan.
The cause is `FlowInstanceService#buildWithoutApprovalNode` method incorrectly constructs `FlowInstance` when `rollbackPlanInstance` is added before the `service task`.
Fixes #414
```docs
```

fix(database-change): failed to view a scheduled database change task with rollback plan in personal space

---

server/odc-service/src/main/java/com/oceanbase/odc/service/resultset/DumperResultSetExportTaskManager.java
server/odc-service/src/main/java/com/oceanbase/odc/service/resultset/ResultSetExportTask.java

type-bug
There is a code bug which will lead to get wrong filename for result-set export task. So we use user-configured filename to upload result instead of origin filename.
none

fix(result-set-export): get wrong filename for result-set export task on cloud

---

server/odc-service/src/main/java/com/oceanbase/odc/service/session/ConnectSessionService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/factory/DefaultConnectSessionFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/factory/DruidDataSourceFactory.java

type-bug
odc's backend datasource will be set a default socket timeout which defined in system config. this socket timeout can not be changed even we set jdbc url parameter.
There is a bug for Druid that it can only set socketTimeout and connectTimeout by jdbc url parameter for MySQL datasource.  That is to say that we can not set these two properties for OceanBase datasource.
We set these two properties to a default value(60s), by the way, these to properties can not be set to zero, the druid will give them a default value(10s) if we do that. 
Next, we parse these two properties from the jdbc url, if we find any one of them, we will reset it.
Fixes #
```docs
```

fix(datasource): make 'socketTimeout' and 'connectTimeout' settings work for backend datasource

---

libs/db-browser/pom.xml
libs/ob-sql-parser/pom.xml
libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/OBMySQLParser.java
libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/OBOracleSQLParser.java
pom.xml

type-bug
the parser will not report any syntax error if the input's any prefix is grammatical. 
eg.
```SQL
select * from test asdasdasd asdasdas asdasdasd asd;
```
the sql above has syntax error obviously but the parser will consider that this is a sql without any syntax error cause that the prefix of this sql `select * from test` is grammatical.
the root cause of this issue is that the parser does not parse a sql from the beginning to the end. The parser will return when it get a grammatical statement.
you can get more infos from the issue #693 
Fixes #693 
```docs
```

fix(sql-parser): failed to report syntax error if the input's any prefix is grammatical

---

server/odc-core/src/main/java/com/oceanbase/odc/core/sql/execute/model/JdbcGeneralResult.java
server/odc-core/src/main/java/com/oceanbase/odc/core/sql/util/FullLinkTraceUtil.java
server/odc-core/src/test/java/com/oceanbase/odc/core/sql/util/FullLinkTraceUtilTest.java
server/odc-server/src/main/resources/data.sql
server/odc-service/src/main/java/com/oceanbase/odc/service/session/ConnectConsoleService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/OdcStatementCallBack.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/SessionProperties.java

type-bug
When sql executing failed, ODC would not query trace id for it. In this PR, there will always be trace id, no matter it's succeeded or failed.
Fixes #697

fix(sql-execute): no trace id when sql executing failed

---

server/odc-server/src/main/java/com/oceanbase/odc/server/config/MvcConfiguration.java
server/odc-service/src/main/java/com/oceanbase/odc/config/RestTemplateConfig.java

type-bug
module-web
The [PR](https://github.com/oceanbase/odc/pull/338) involves a problem that the response header `content-type` would be `application/xml` while using RestTemplate. The root cause is that after importing the dependency `jackson-dataformat-xml`, Spring will automatically register a `MappingJackson2XmlHttpMessageConverter` whose order is higher than `MappingJackson2HttpMessageConverter`. If the request header Accept is like `'text/plain, */*'`, Spring will firstly use `MappingJackson2XmlHttpMessageConverter` to convert the response to an xml format which would cause the issue.
This PR swap the order of `MappingJackson2HttpMessageConverter` and `MappingJackson2XmlHttpMessageConverter` to make `MappingJackson2XmlHttpMessageConverter` work before …

fix(web): response header content-type would be application/xml while using RestTemplate

---

server/odc-service/src/main/java/com/oceanbase/odc/service/session/factory/OBConsoleDataSourceFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/interceptor/SqlCheckInterceptor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/model/SqlExecuteResult.java

type-bug
out parser can not behaves same with the observer's parser completely so that a sql may be executed completely but get a syntax error from sql-check in odc which will confuse user.
this pr fix this issue.
I have tested 2.2.77, 3.2.4 and 4.2.1 for both MySQL and Oracle mode and I asked kernel R&D classmates for help, and what I can confirm is that
```shell
mysql324: ErrorCode = 1064, SQLState = 42000
mysql2277: ErrorCode = 1064, SQLState = 42000 
mysql421: ErrorCode = 1064, SQLState = 42000
mysql57: ErrorCode = 1064, SQLState = 42000
oracle2277: ErrorCode = 900, SQLState = 42000
oracle324: ErrorCode = 900, SQLState = 42000 
oracle421: ErrorCode = 900, SQLState = 42000
```
Fixes #746 
```docs
```

fix(sql-check): avoid reporting syntax error when sql is executed successfully

---

server/odc-core/src/main/java/com/oceanbase/odc/core/sql/execute/mapper/DefaultJdbcRowMapper.java
server/odc-core/src/main/java/com/oceanbase/odc/core/sql/execute/mapper/MySQLNumberMapper.java
server/odc-core/src/test/java/com/oceanbase/odc/core/sql/execute/mapper/MySQLNumberMapperTest.java

type-bug
the number content will be displayed by using scientific notation when the value is 0.0000000 which confused the user. this pr fix this problem.
I have tested for three number datatype: `number`, `decimal` and `fixed` and I have also tested these datatypes with zerofill settings. Both two scenarios are normal.
Fixes #762 
```docs
```

fix(sql-execute): fix the issue where the number type is displayed using scientific notation when the value is 0.0000000

---

server/plugins/schema-plugin-odp-sharding-ob-mysql/src/main/java/com/oceanbase/odc/plugin/schema/odpsharding/obmysql/ODPShardingOBMySQLTableExtension.java

type-bug
module-Database object
fix cannot get table detail in odp sharding mysql when lower_case_table_names = 1 or 2.
In ODP sharding mysql mode, when variable lower_case_table_names = 1 or 2, the table name will be stored in uppercase letters. There is no need to automatic lowercase conversion of table name when database is Case Sensitive.
Fixes #793
```docs
```

fix(schema-plugin):  cannot get table detail in odp sharding mysql mode when lower_case_table_names = 1 or 2

---

server/plugins/schema-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/schema/oboracle/OBOracleTableExtension.java
server/plugins/schema-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/schema/oboracle/parser/OBOracleGetDBTableByParser.java

module-Database object
1. Use `sqlParser` to determine whether there is a SchemaName in the DDL of the table. If not, splice the SchemaName in DDL.
2. Optimize `OBOracleGetDBTableByParser#listIndexes` and `OBOracleTableExtension#getTableDDL` repeatedly execute the query SQL to obtain the DDL of the index
Fixes #571
```docs
```

enhancement(schema-plugin): speed up getting index and improve code robustness when getting table ddl

---

server/odc-service/src/main/java/com/oceanbase/odc/service/automation/model/CreateRuleReq.java
server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/model/MaskingAlgorithm.java
server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/model/SensitiveRule.java
server/odc-service/src/main/java/com/oceanbase/odc/service/iam/model/CreateRoleReq.java
server/odc-service/src/main/java/com/oceanbase/odc/service/iam/model/CreateUserReq.java
server/odc-service/src/main/java/com/oceanbase/odc/service/integration/model/IntegrationConfig.java
server/odc-service/src/main/java/com/oceanbase/odc/service/resourcegroup/model/ModifyResourceGroupReq.java

type-bug
In cloud mode, the user name may longer than 64 chars. This PR change resource name length limit from 64 to 128.

fix(name): change resource name length limit from 64 to 128

---

server/odc-server/src/main/resources/data.sql
server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/LocalFileTransferService.java

type-bug
module-database change
In current, When user init a database change task and upload SQL script files, the single file size limit is <=256MB, and user can upload multiple files with size 256MB. ODC will read SQL files to a single Java String object. So if the SQL files is very large, then OOM may happened.
The most directly solution is decrease the upload SQL file's size. We will make it as 32 MB at largest in a task.
Fixes #409

fix(database-change): OOM may occur when executing database change task with large SQL files

---

server/odc-service/src/main/java/com/oceanbase/odc/service/session/util/SqlRewriteUtil.java
server/odc-service/src/test/java/com/oceanbase/odc/service/session/SqlRewriteUtilTest.java

type-bug
avoid adding rowid when dblink exists
Fixes #214 
```docs
```

fix(sql-execution): avoid adding rowid when dblink exists

---

server/odc-service/src/main/java/com/oceanbase/odc/service/session/util/SqlRewriteUtil.java
server/odc-service/src/test/java/com/oceanbase/odc/service/session/SqlRewriteUtilTest.java

type-bug
When executing a sql like `select a, b from xxx order by 2`, the result will be sorted by the `b` column .
But in ODC, it would be rewrite into `select ROWID AS "__ODC_INTERNAL_ROWID__" , a, b from xxx order by 2`, which will get a result sorted by the `a` column.
In this PR, we move rowid part to after last select item position. So the sql above would be rewrite as `select a, b, ROWID AS "__ODC_INTERNAL_ROWID__"   from xxx order by 2`. The result will be corrected.
Fixes #742

fix(sql-execute): move internal rowid to after last select item when rewriting sql

---

server/odc-service/src/main/java/com/oceanbase/odc/service/db/util/OBMysqlCallFunctionCallBack.java
server/odc-service/src/test/java/com/oceanbase/odc/service/db/util/OBMysqlCallFunctionCallBackTest.java
server/odc-service/src/test/resources/db/mysql_function_callback_test.sql

type-bug
When executing PL in MySQL mode, the input params are just wrapped but not escaped. This leads to syntax errors.
Fixes #174

fix(PL): PL params of MySQL mode are not escaped

---

server/integration-test/src/test/java/com/oceanbase/odc/service/datasecurity/SensitiveColumnScanningTaskManagerTest.java
server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/SensitiveColumnScanningTask.java

type-bug
ODC recognize and store sensitive columns by `databaseId`, `tableName` and `columnName`.  And, the `varchar` in meta DB is case-insensitive. So if there are two columns with case-sensitive same `tableName` + `columnName`, then we cannot add both of them as sensitive column. In ODC 4.2.3, ODC will recognize both two columns when scan and this PR fix it.
Fixes #1005 
```docs
```

fix(data-security): create sensitive columns failed due to scanning duplicated columns

---

server/integration-test/src/test/java/com/oceanbase/odc/service/iam/UserPermissionServiceTest.java
server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/IamController.java
server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/project/ProjectService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/iam/UserPermissionService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/permissionapply/project/ApplyProjectPreprocessor.java

type-bug
module-user permission
In ODC 4.2.3, if a user join a project with OWNER or DBA role, then ODC  will grant `create` permission of `CONNECTION:*`  to this user. But when the user leave the project, these permission is not reclaimed. So user can create datasource without any project and role. 
In this PR, I fix it by delete the internal grant permission operation.
Fixes #1013 #683 
```docs
```

fix(permission): user can create datasource without any project and role

---

libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/OBMySQLNoGreaterThan1479SchemaAccessor.java
libs/db-browser/src/main/resources/schema/sql/obmysql/obmysql_1_4_79.yaml

type-bug
The partition plan uses SchemaAccessor to obtain range partition info. But in obmysql 1479, the query SQL is wrong because `oceanbase.__all_part` doesn't have `list_val` column(higher version does).
This PR corrects the partition info query SQL by deleting the non-existing column. It only affects the partition plan given that it uses Parser to obtain partition info in other scenery. And partition plan doesn't care about the list partition info so deleting this column will be fine.
Fixes #969 
```docs
```

fix(partition-plan): create partition plan task failed in obmysql 1479

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionService.java

type-bug
I create a data source and bind a project. Then I manually add the built-in database oceanbase to the project. Now I unbind the datasource to the project, but the oceanbase database is still bound to the previous project.
This PR fix it.
Fixes #1058 
```docs
```

fix(datasource): built-in database still belong to previous project when datasource unbind project

---

server/odc-server/src/main/java/com/oceanbase/odc/server/web/websocket/WebSocketServer.java

type-bug
When ODC opening a obclient window, it would call useradd command to create a os user .This is for security issues and for resource isolation.
However , this user would not be deleted. So the logs of the operating system will have some records of user creation failures.
So we will query whether this user already exists by grep file `/etc/passwd`. All users have read access to this file. If it exists, we won't create repeatedly.
Fixes #972

fix(obclient): do not create os user when it already exists

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/SensitiveColumnService.java

type-feature
In ODC 4.2.3, we support exporting data for native MySQL but data masking is not supported yet. So, we should prohibit the use of data-masking for native MySQL datasource by prohibitting user to create sensitive columns. This PR just do these.
Close #1054 
```docs
```

feat(data-masking): prohibit data-masking for native MySQL datasource

---

server/odc-service/src/main/java/com/oceanbase/odc/service/datatransfer/DataTransferService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/datatransfer/task/DataTransferTaskContext.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DataTransferRuntimeFlowableTask.java
server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/datatransfer/factory/BaseParameterFactory.java

type-bug
There are some issues,  such as #1030 and #1158 , are caused by the sys tenant configs. 
On the one hand, due to the fact that after OceanBase4.x, ob-loader-dump no longer relies on the account and password of sys tenants. On the other hand, this configuration has security issues. 
Therefore, we prohibit users from filling in the sys tenant account password when initiating transfer tasks.
Fixes #1030 and #1158

fix(data-transfer): only inject sys tenant config when it's configured in datasource

---

.gitattributes
.github/workflows/build_artifact.yaml
.github/workflows/build_daily.yaml
.github/workflows/build_dev.yaml
.github/workflows/build_release.yaml
server/integration-test/src/test/java/com/oceanbase/odc/service/datatransfer/MySQLTransferServiceTest.java

Due to the large volume of datax.zip, we use git lfs to store it. We could track the lfs files in `.gitattributes`.
The changes in build_*.yaml is because: Github does not replace the pointer file of LFS with the actual file when executing actions. So we need to manually execute the `git lfs checkout` to obtain it.
I have tested building artifacts, and this passed them.

enhancement: use git-lfs to storage datax.zip

---

server/odc-service/src/main/java/com/oceanbase/odc/config/CsrfConfigureHelper.java
server/odc-service/src/main/java/com/oceanbase/odc/service/iam/auth/CustomInvalidSessionStrategy.java
server/starters/web-starter/src/main/java/com/oceanbase/odc/config/PlaySiteSecurityConfiguration.java
server/starters/web-starter/src/main/java/com/oceanbase/odc/config/WebSecurityConfiguration.java

…ror message
type-bug
Fixes #591
the CsrfFilter in spring secuity will refer InvalidSessionStrategy before self defined AccessDeniedHandler.
while CSRF protection enabled, skip set InvalidSessionStrategy.
here is the test result
*scenario MissingCsrfToken*
curl -iL -XPOST \
"http://localhost:8989/api/v2/database/databases/1000215currentOrganizationId=1&ignoreError=true&taskType=ONLINE_SCHEMA_CHANGE"
HTTP/1.1 400
Set-Cookie: XSRF-TOKEN=813a1677-0508-4dc4-96b8-c4b221ce8fea; Domain=localhost; Path=/
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
Content-Type: application/json;charset=UTF-8
Content-Length: 265
Date: Tue, 19 Dec 2023 11:55:01 GMT
Connection: close …

fix(web-framework): invalid csrf token result into Invalid session error message

---

server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/RollbackPlanRuntimeFlowableTask.java

type-bug
NPE occurs when user input sql content is empty during generating rollback plan. This PR fix it by using `CollectionUtils.isNotEmpty(userInputSqls)` replace `!userInputSqls.isEmpty()`
Fixes #1240 
```docs
```

fix(rollback-plan): NPE when user input sql content is empty

---

server/odc-service/src/main/java/com/oceanbase/odc/config/BeanConfiguration.java

type-bug
module-datasource
The back-end `DialectType` has added `ODP_SHARDING_OB_MYSQL`, which may cause the front-end page to crash. This hidden bug has not been triggered so far.
In order to avoid this bug, `ODP_SHARDING_OB_MYSQL` is converted to `OB_MYSQL` during serialization.
Fixes #1252
```docs
```

fix(datasource):  convert the type of ob-mysql-sharding data source to ob-mysql

---

server/odc-common/src/main/java/com/oceanbase/odc/common/json/NormalDialectTypeOutput.java
server/odc-service/src/main/java/com/oceanbase/odc/config/BeanConfiguration.java
server/odc-service/src/main/java/com/oceanbase/odc/service/audit/model/AuditEvent.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/model/MockDataTaskResult.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/model/OnlineSchemaChangeScheduleTaskResult.java
server/odc-service/src/main/java/com/oceanbase/odc/service/regulation/ruleset/model/Rule.java
server/odc-service/src/main/java/com/oceanbase/odc/service/regulation/ruleset/model/RuleMetadata.java

type-bug
Fix the bug introduced by this PR：https://github.com/oceanbase/odc/pull/1253
There are some special scenarios, such as the optional DialectType in security rules and the DialectType displayed in operation records. In these cases, ODP_SHARDING_OB_MYSQL should not be converted to OB_MYSQL.
Fixes #1279
```docs
```

fix(datasource): make ODP_SHARDING_OB_MYSQL not be converted to OB_MYSQL in some special cases

---

server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/OdcConstants.java
server/odc-service/src/main/java/com/oceanbase/odc/service/resultset/ResultSetExportFlowableTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/resultset/ResultSetExportTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/ResultSetExportPreprocessor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/util/SqlRewriteUtil.java
server/plugins/task-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/task/mysql/datatransfer/job/datax/ConfigurationResolver.java

Fix #1283 . When exporting result set, we would rewrite query sql into like `select * from (<original sql>) limit xxx` . 
In ob-mysql , this works normally. But in native mysql, this rewrite would get a syntax error 'Every derived table must have its own alias'. 
Therefore, we will add a `as  __ODC_INTERNAL_RESULT_SET__` into query to fix this.
Fix #1282 . When user set skip header, the `TxtWriterPluginParameter#header` field should not be set.

fix(result-set-export): failed to rewrite sql for mysql

---

server/odc-service/src/main/java/com/oceanbase/odc/service/datatransfer/DefaultDataTransferAdapter.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowTaskInstanceService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/MockDataRuntimeFlowableTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/model/MockDataTaskResult.java
server/odc-service/src/main/java/com/oceanbase/odc/service/resultset/ResultSetExportTask.java

type-bug
Now ODC would upload some task results to cloud object storage if it's available. But the `objectName` is storaged in memory of `OssTaskReferManager`. If the odc-server is reboot, these all data will be lost.
So we remove the dependency on this cache in this PR.

fix(object-storage): remove dependency on OssTaskReferManager

---

server/odc-service/src/main/java/com/oceanbase/odc/service/session/factory/OBConsoleDataSourceFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/SqlCheckService.java

type-bug
Fixes #1337 
```docs
```

fix(sql-check): failed to check statement when connect to a lower case schema 

---

server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/AuthorizationType.java
server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/PermissionSourceType.java
server/odc-core/src/main/resources/i18n/BusinessMessages.properties
server/odc-core/src/main/resources/i18n/BusinessMessages_zh_CN.properties
server/odc-core/src/main/resources/i18n/BusinessMessages_zh_TW.properties
server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/DataBaseController.java
server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/DatabasePermissionController.java
server/odc-server/src/main/resources/log4j2.xml
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/model/Database.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/model/QueryDatabaseParams.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowTaskInstanceService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/model/CreateFlowInstanceReq.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/model/FlowInstanceDetailResp.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/mapper/OdcRuntimeDelegateMapper.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/util/FlowTaskUtil.java
server/odc-service/src/main/java/com/oceanbase/odc/service/permission/database/DatabasePermissionService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/permission/database/model/CreateDatabasePermissionReq.java
server/odc-service/src/main/java/com/oceanbase/odc/service/permission/database/model/DatabasePermissionModel.java
server/odc-service/src/main/java/com/oceanbase/odc/service/permission/database/model/DatabasePermissionType.java
server/odc-service/src/main/java/com/oceanbase/odc/service/permission/database/model/QueryDatabasePermissionParams.java
server/odc-service/src/main/java/com/oceanbase/odc/service/permission/database/model/UnauthorizedDatabase.java
server/odc-service/src/main/java/com/oceanbase/odc/service/permission/database/model/UserDatabasePermission.java
server/odc-service/src/main/java/com/oceanbase/odc/service/permission/project/ApplyProjectFlowableTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/permission/project/ApplyProjectParameter.java
server/odc-service/src/main/java/com/oceanbase/odc/service/permission/project/ApplyProjectPreprocessor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/permission/project/ApplyProjectResult.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/model/SqlAsyncExecuteResp.java

type-feature
module-Database permission control
This PR adds API definition for DB permission control. This PR's merged will not influence existing function, so can be merge without any risk.
Fixes #
```docs
```

feat(database-permission): add API definition

---

libs/ob-sql-parser/README.md

type-docs
update ob-sql-parser's document and correct several documentation errors
Fixes #
```docs
```

docs: update ob-sql-parser's document

---

server/integration-test/src/test/java/com/oceanbase/odc/service/onlineschemachange/OnlineSchemaChangeMultiTaskTest.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/OnlineSchemaChangeFlowableTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/pipeline/ScheduleCheckOmsProjectValve.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/rename/SwapTableUtil.java

type-bug
fix osc percentage continue execute when `isManualSwapTableEnabled` is true, we should update it to task result json, the swap table button show or not based on `isManualSwapTableEnabled`
```docs
```

fix(osc): osc task don't show manual swap table name when full migrate is completed

---

server/odc-migrate/src/main/resources/migrate/common/V_4_2_4_5__add_flow_instance_index.sql
server/odc-service/src/main/java/com/oceanbase/odc/metadb/flow/FlowInstanceRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/factory/FlowResponseMapperFactory.java

add index to flow_instance;
alter list_flow_instance_view view
Fixes #
```docs
```

fix(flow):improve list API rt

---

server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/OnlineSchemaChangeFlowableTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/OscService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/model/OnlineSchemaChangeParameters.java

type-bug
module-onlineSchemaChange
exists horizontal overstep access data permission when swap table manual
add permission valid, only flow instance  creator can operate swap table name.
```docs
```

fix(osc): exists horizontal overstep access data permission when swap table manual

---

server/odc-core/src/main/java/com/oceanbase/odc/core/sql/split/SqlCommentProcessor.java

type-bug
we can not set a delimiter longer than 2:
```SQL
delimiter $$$
select 1
from dual $$$
```
which cause an out of bound exception, this issue may cause by this pr #976 
Fixes #1412 
```docs
```

fix(sql-execution): can not set a delimiter longer than 2

---

script/functions.sh
script/start-odc.sh
server/odc-common/src/main/java/com/oceanbase/odc/common/security/SensitiveDataUtils.java
server/odc-common/src/test/java/com/oceanbase/odc/common/security/SensitiveDataUtilsTest.java
server/odc-server/src/main/java/com/oceanbase/odc/server/OdcServer.java

type-feature
sometimes odc-server may crash, ob-odc-web.std.log offer valuable information for diagnose.
however there is no datetime info in ob-odc-web.std.log. this pr add datetime.
Fixes #1353 
```docs
```

feat(deployment): add datetime output for ob-odc-web.std.log

---

server/integration-test/src/test/java/com/oceanbase/odc/metadb/dlm/DlmLimiterConfigRepositoryTest.java
server/integration-test/src/test/java/com/oceanbase/odc/service/dlm/RateLimitConfigurationServiceTest.java
server/odc-service/src/main/java/com/oceanbase/odc/metadb/dlm/DlmLimiterConfigRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DlmLimiterService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/model/RateLimitConfiguration.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/factory/ScheduleResponseMapperFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/AbstractDlmJobPreprocessor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/model/ScheduleDetailResp.java

…iguration
type-bug
The schedule entity will no longer be modified when updating the limiting configuration to ensure the correctness of task parameters.
Fixes #
```docs
```

fix(dlm): the data cleaning task scheduling failed after editing the rate limit configuration

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/permission/database/DatabasePermissionHelper.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/ConnectSessionService.java

type-bug
module-database permission control
In perosnal space, user has all permission for all databases but there is no permission records in metaDB. So the DB permission will failed and user cannot create session. This PR fix it by skipping permission check in personal space.
Fixes #
```docs
```

fix(database-permission): failed to verify database permission in personal space

---

server/odc-server/src/main/java/com/oceanbase/odc/server/web/websocket/WebSocketServer.java

type-bug
When odc are running on ubuntu as client mode , we will create a new os user to run obclient. But if current os user doesn't have access to create user, an exception will be thrown and obclient could not be opened.
In fact we don't need to create a user in client mode , so I changed this assert.
Fixes #1300

fix(data-transfer): do not create os user in client mode

---

server/odc-service/src/main/java/com/oceanbase/odc/service/datatransfer/DataTransferService.java
server/plugins/task-plugin-api/src/main/java/com/oceanbase/odc/plugin/task/api/datatransfer/model/ObjectResult.java

type-bug
When use ob-loader-dumper to transfer data, we should use `ObjectType#name` as displayed name. But `ObjectType#getName` was used instead, causing miss match with front-end.
Fixes #1333

fix(data-transfer): fix wrong object type names were used

---

server/odc-service/src/main/java/com/oceanbase/odc/service/session/OdcStatementCallBack.java

type-bug
Now when odc user has enabled manual commit, the transaction will still be rollbacked when exception occurs.
However this action is incorrect. Transactions should only end when the user manually rolls back or commits. ODC should not control transaction status.
Fixes #1352

fix(sql-execute): do not follback execute when manual commit enabled

---

libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/parser/listener/OracleModePLParserListener.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/interceptor/SqlConsoleInterceptor.java

type-bug
This PR recognized executing anonymous block sql and set its sql type to `OTHERS`, otherwise, it will cause NPE.
Fixes #1422
```docs
```

fix(sql-execute): executing anonymous block causes NPE in the team space

---

libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OBOracleLessThan400SchemaAccessor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/db/browser/DBSchemaAccessors.java
server/plugins/schema-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/schema/oboracle/browser/DBSchemaAccessors.java

type-bug
module-db-browser
1. ob oracle 2230 do not have `SYS.ALL_VIRTUAL_DATABASE_REAL_AGENT` internal table, In ob oracle mode, `ALL_TABLES` view information is uniformly queried to listTables.
2. fix get the DBSchemaAccessor for different versions
Fixes #1476
```docs
```

fix(db-browser): failed to list tables when ob's version is no greater than 2.2.30

---

server/odc-common/src/main/java/com/oceanbase/odc/common/util/ReflectionUtils.java
server/odc-common/src/test/java/com/oceanbase/odc/common/util/ReflectionUtilsTest.java
server/odc-core/src/main/java/com/oceanbase/odc/core/datasource/SingleConnectionDataSource.java
server/plugins/connect-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/connect/obmysql/OBMySQLSessionExtension.java
server/plugins/connect-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/connect/oboracle/OBOracleSessionExtension.java

type-bug
`userenv('sessionid')` are not supported on OB 2230, so we use `OceanBaseConnection#getServerThreadId` instead.
But in `BaseSqlExecuteCallable` , the connection is generated from `SingleConnectionDataSource`. It's not instance of `OceanBaseConnection`. So we should get the real connection to get the id.
Fixes #1475

fix(sql-execute): fail to execute statement on OceanBase 2.2.30

---

server/odc-service/src/main/java/com/oceanbase/odc/service/session/ConnectConsoleService.java

type-bug
When querying table data, there is no column comment info. But it works correctly in sql console.
This is because the query api didn't set `SqlAsyncExecuteReq#showTableColumnInfo` to true when calling `execute` method.
Fixes #1482

fix(table): query table data with no column comments

---

server/odc-service/src/main/java/com/oceanbase/odc/service/task/dispatch/ImmediateJobDispatcher.java

type-feature
1. read system config is empty string but not null,  use `StringUtils.isNotBlank` to predicate string is blank or not
2. start pod command by start-job.sh
test passed
Fixes #
```docs
```

fix(taskframework): k8s system config from data.sql is empty string 

---

server/odc-service/src/main/java/com/oceanbase/odc/service/session/util/SchemaExtractor.java
server/odc-service/src/test/java/com/oceanbase/odc/service/session/SchemaExtractorTest.java

type-bug
module-database permission
When user has no DB `change` permission, and executing a PL/SQL in SQL  console such as:
```sql
CREATE FUNCTION `gaoda_test_data`.`func2` (
`str1` VARCHAR ( 45 ),
`str2` VARCHAR ( 45 )) RETURNS VARCHAR ( 128 ) BEGIN
RETURN ( SELECT concat( str1, str2 ) FROM DUAL );
END;
```
Then the DB permission interceptor will be invalid, the SQL will be executed.
The root cause is that the `SchemaExtractor` does not care about PL/SQL, this PR add these solution and fix this bug.
Fixes #1581 
Slef-test passed. 
Note that if the database is accessed from within PL, it may not be detected.
```docs
```

fix(database-permission): DB permission interceptor invalid when executing PL in the SQL console

---

server/integration-test/src/test/java/com/oceanbase/odc/service/flow/FlowInstanceServiceTest.java
server/odc-core/src/main/resources/i18n/BusinessMessages.properties
server/odc-core/src/main/resources/i18n/BusinessMessages_zh_CN.properties
server/odc-core/src/main/resources/i18n/BusinessMessages_zh_TW.properties
server/odc-server/src/main/resources/data.sql
server/odc-service/src/main/java/com/oceanbase/odc/metadb/flow/ServiceTaskInstanceRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DatabaseChangeRuntimeFlowableTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DatabaseChangeRuntimeFlowableTaskCopied.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/PreCheckRuntimeFlowableTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/model/DatabaseChangeResult.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/model/FlowTaskProperties.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/model/SqlCheckTaskResult.java
server/odc-service/src/main/java/com/oceanbase/odc/service/partitionplan/PartitionPlanService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/SqlCheckService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/model/SqlCheckRuleType.java
server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/IndexChangeTimeConsumingExists.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/DatabaseChangeTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/runtime/DatabaseChangeTaskParameters.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/runtime/PreCheckTask.java
server/odc-service/src/test/java/com/oceanbase/odc/service/sqlcheck/MySQLCheckerTest.java
server/odc-service/src/test/java/com/oceanbase/odc/service/sqlcheck/OracleSqlCheckerTest.java

type-feature
module-database change
Automatically adjust the timeout if the database change task involves time-consuming index change operations.
1. create `IndexChangeTimeConsumingExists` to check if sqls involve time-consuming operations like creating index and modifying primary key. This SQL check result should not be displayed to the user, so this check result will be filtered out at the end.
2. if involves, `SqlCheckTaskResult#timeConsumingSqlExists` will be true, and `DatabaseChangeResult#isAutoModifyTimeout` will be true.
`ServiceTaskInstanceRepository#findByFlowInstanceId` is a bug, it would return multiple rows of data，But this method is not actually called. Delete this method.
Fixes #772 
```docs
```

feat(databaseChange): Automatically adjust the timeout if the database change task involves time-consuming index change operations

---

server/odc-service/src/main/java/com/oceanbase/odc/config/CacheConfiguration.java

type-bug
In some scenery, the business logic needs a null-free cache, so I added an `allowNullCacheManager` in this PR.
Fixes #
```docs
```

fix(cloud): add a CacheManager bean which allows null values

---

server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java

type-bug
module-structure-comparison
fix failed to create structure-comparison task in personal space because the flowInstance id was not set
Fixes #1620
```docs
```

fix(structure-comparison):failed to create structure-comparison task in personal space

---

server/odc-service/src/main/java/com/oceanbase/odc/service/integration/HttpOperationService.java

type-bug
type-external integration
There is a bug: Garbled code exists when using Chinese in request body of external integration configuration.
Root cause: When the content-type is RAW, then we build HTTP request entity through `EntityBuilder.create().setText(encryptedBody).build()`. Then the default charset is `ISO_8859_1` rather than `UTF_8` causing garbled code for Chinese.
This PR fix it by using `StringEntity(bodyString, StandardCharsets.UTF_8)`.
Fixes #1624 
Self-test Passed.
```docs
```

fix(integration): garbled code exists when using Chinese in request body

---

libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/MySQLNoGreaterThan5740SchemaAccessor.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/OBMySQLSchemaAccessor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBIdentitiesService.java

type-bug
1. `DBIdentitiesService#list` return all SchemaIdentities even the schema has no tables or views
2. fix `DBSchemaAccessor#listTables` do not return tables in `mysql` schema, because we can not get tables in `mysql` by query `information_schema.tables `in ob mysql mode
Fixes #1628 
Fixes #1428 
```docs
```

enhancement(db-browser): return all SchemaIdentities even the schema has no tables or views

---

libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/OBMySQLSchemaAccessor.java
libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/schema/OBMySQLSchemaAccessorTest.java

type-bug
`OBMySQLSchemaAccessor#listTables` correctly returns the table under the specified schema
Fixes #
```docs
```

fix(db-browser): listTables correctly returns the table under the specified schema

---

server/odc-service/src/main/java/com/oceanbase/odc/service/common/util/SqlUtils.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DatabaseChangeThread.java
server/odc-service/src/main/java/com/oceanbase/odc/service/rollbackplan/AbstractRollbackGenerator.java
server/odc-service/src/main/java/com/oceanbase/odc/service/rollbackplan/RollBackPlanJdbcRowMapper.java
server/odc-service/src/main/java/com/oceanbase/odc/service/rollbackplan/RollbackGeneratorFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/rollbackplan/oracle/OracleDeleteRollbackGenerator.java
server/odc-service/src/main/java/com/oceanbase/odc/service/rollbackplan/oracle/OracleUpdateRollbackGenerator.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/initializer/ConsoleTimeoutInitializer.java
server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/BaseSqlChecker.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/DatabaseChangeTask.java

type-feature
module-database change
database change task adaption for oracle dialect type.
1. `ConsoleTimeoutInitializer` adaption for oracle mode.
2. `GenerateRollbackPlan` adaption for oracle mode.
3.  `SqlSpliter` used by database change task adaption for oracle mode to not append delimiter in sql.
Fixes #396
```docs
```

feat(database-change): adaption for oracle11g

---

libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/adapter/mysql/MySQLAlterTableActionFactory.java
libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/statement/alter/table/AlterTableAction.java
libs/ob-sql-parser/src/main/resources/obmysql/sql/OBParser.g4
libs/ob-sql-parser/src/test/java/com/oceanbase/tools/sqlparser/adapter/MySQLAlterTableActionFactoryTest.java
server/odc-service/src/main/java/com/oceanbase/odc/service/structurecompare/model/DBObjectComparisonResult.java

type-bug
module-structure compare
mysql 5.7 support convert partitioned table to non-partitioned table by sql:
`alter table table_name remove partitioning`
In fact, this is also a SQL statement for deleting table attributes which should be placed in comments. 
Add `REMOVE PARTITIONING` to `alter_partition_option` in the obmysql syntax file.
Fixes #1666 
```docs
```

fix(structure-compare): alter table remove partitioning sql is not put in comment

---

libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/editor/DBTableIndexEditor.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/model/DBTableIndex.java
libs/db-browser/src/test/resources/table/operator/ob/mysql/index/update_single_index_test_cases.json

module-db-browser
ob mysql and oracle support alter index invisible by ‘ALTER TABLE tab_name ALTER INDEX idx_name VISIBLE /INVISIBLE; ’
I have tested that ob 2.2.30、3.2.4、4.2.2  all support this statement.
mysql 8.x also support it
Fixes #380
```docs
```

enhancement(db-browser): optimize the generated sql that modifies the visibility of the index

---

libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OracleSchemaAccessor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBPLService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/OdcStatementCallBack.java
server/plugins/connect-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/connect/oboracle/OBOracleConnectionExtension.java
server/plugins/connect-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/connect/oboracle/initializer/OracleDBMSOutputInitializer.java
server/plugins/connect-plugin-oracle/src/main/java/com/oceanbase/odc/plugin/connect/oracle/OracleConnectionExtension.java

type-bug
module-sql-execution
module-db-browser
1. Anonymous block execution module adapted to oracle11g
- rename `OBOracleDBMSOutputInitializer` to `OracleDBMSOutputInitializer`
2. Fixed the problem of error reporting when viewing packages without package body
Fixes #1729 
Fixes #1754 
```docs
```

fix(sql-execute): anonymous block execution module adapted to oracle11g

---

server/plugins/task-plugin-api/src/main/java/com/oceanbase/odc/plugin/task/api/datatransfer/model/DataTransferConfig.java
server/plugins/task-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/task/mysql/datatransfer/common/Constants.java
server/plugins/task-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/task/mysql/datatransfer/job/datax/DataXTransferJob.java
server/plugins/task-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/task/mysql/datatransfer/job/factory/BaseTransferJobFactory.java
server/plugins/task-plugin-oracle/src/main/java/com/oceanbase/odc/plugin/task/oracle/datatransfer/job/OracleSchemaExportJob.java

type-bug
Fixes #1742  #1746  . Export Oracle object ddl without line breaks.
Fixes #1671  . When start a export task ,the front-end don't send `stopWhenError` param in request, so it would use false as it's value. If a object failed, the other would continue transfering.

fix(data-transfer): export Oracle object ddl without line breaks

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/ConnectionConfig.java

type-bug
`ConnectionConfig.defaultSchema` is deprecated at the API level, so this PR adds `@JsonIgnore` on this field to prevent the issue which is that when users update the data source username, the front-end will pass the `defaultSchema` which is obtained from the `detail` API, and this will cause some logic error in the back-end: the odc server will not update the default schema using the username, it will use the old default schema passed by the front-end.
Fixes #1626 
```docs
```

fix(datasource): connecting failed in OceanBase Oracle after correcting the username

---

server/odc-service/src/main/java/com/oceanbase/odc/service/datatransfer/task/DataTransferTask.java
server/plugins/task-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/task/mysql/datatransfer/MySQLDataTransferJob.java
server/plugins/task-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/task/mysql/datatransfer/job/BaseSqlScriptImportJob.java
server/plugins/task-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/task/mysql/datatransfer/job/MySQLSqlScriptImportJob.java
server/plugins/task-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/task/mysql/datatransfer/job/datax/DataXTransferJob.java
server/plugins/task-plugin-oracle/src/main/java/com/oceanbase/odc/plugin/task/oracle/datatransfer/job/OracleSqlScriptImportJob.java

type-bug
Fixed:
1. When import sql scripts for orarcle mode, we used `SqlCommentProcessor` to split sql. But it should use `SqlSplittter` instead. 
2. In MySQLDataTransferJob, schema jobs and data jobs will be initialized first before task transfer. Actually, this is incorrect because when creating a data job, table information will be queried. If the table has not been imported yet, an error will occur.
Fixes #1761 #1773

fix(data-transfer): oracle mode import with incorrect splitted sqls

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java

type-feature
module-database permission management
This PR makes the detail database API returns authorized permission types information, so that the front-end can determine whether to display some databse operation button. This is required by the front-end.
Fixes #
```docs
```

fix(database-permission): return authorized permission types for detail database interface

---

server/integration-test/src/test/java/com/oceanbase/odc/service/notification/BrokerTest.java
server/integration-test/src/test/java/com/oceanbase/odc/service/notification/JdbcNotificationQueueTest.java
server/odc-migrate/src/main/resources/migrate/common/V_4_2_4_12__update_system_config.sql
server/odc-migrate/src/main/resources/migrate/common/V_4_2_4_12__update_task_framework_enabled.sql
server/odc-migrate/src/main/resources/migrate/common/V_4_2_4_16__update_system_config.sql
server/odc-migrate/src/main/resources/migrate/common/V_4_2_4_2__alter_notification_schema.sql
server/odc-server/src/main/resources/data.sql
server/odc-service/src/main/java/com/oceanbase/odc/metadb/notification/MessageEntity.java
server/odc-service/src/main/java/com/oceanbase/odc/service/notification/Broker.java
server/odc-service/src/main/java/com/oceanbase/odc/service/notification/Converter.java
server/odc-service/src/main/java/com/oceanbase/odc/service/notification/HttpSender.java
server/odc-service/src/main/java/com/oceanbase/odc/service/notification/NotificationDispatcher.java
server/odc-service/src/main/java/com/oceanbase/odc/service/notification/NotificationScheduleConfiguration.java
server/odc-service/src/main/java/com/oceanbase/odc/service/notification/helper/ChannelConfigValidator.java
server/odc-service/src/main/java/com/oceanbase/odc/service/notification/model/Message.java

type-feature
The notification channel of ODC currently supports custom webhook channel, allowing users to input custom HTTP headers and body. But this template does not support variables, and some users require this feature. So we are increasing this support.
The specific method is to add event_id into the message entity for querying variables in event labels when sending messages. Using these variables to replacing the placeholders in the body and header.

enhancement(notification): support using variables in http header and body

---

server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DatabaseChangeThread.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/model/DatabaseChangeParameters.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/runtime/DatabaseChangeTask.java

type-feature
Currently, if a database change task fails due to external factors, it terminates. There is a need to add a retry mechanism that allows users to attempt to retry the failed task.
So we add retry capabilities to the product functionality.
Fixes #1802

feat(database-change): support retry execute in database change task

---

server/odc-migrate/src/main/resources/migrate/common/V_4_2_3_18__create_list_flow_instance_view.sql
server/odc-service/src/main/java/com/oceanbase/odc/metadb/flow/FlowInstanceViewSpecs.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java

`list_flow_instance_view` may have bad performance if there exists a huge amount of records in `flow_instance` and `flow_instance_node_task`. The root reason is that it used group by in the view which cause the filter cannot be applied to the basic tables.
This PR moved the `group by` to the outer query and added a hint to indicate the SQL optimizer using merge join instead of nested loop join.
Fixes #
```docs
```

enhancement: optimize list tickets api RT

---

server/odc-service/src/main/java/com/oceanbase/odc/service/state/StateRouteAspect.java
server/odc-service/src/main/java/com/oceanbase/odc/service/state/StatefulRouteConfiguration.java

fix maxPoolSize may less than core
Fixes #
```docs
```

fix(stateful): max pool size may less than core pool size and cause error

---

server/odc-core/src/main/java/com/oceanbase/odc/core/datasource/SingleConnectionDataSource.java

fix singleConnectionDataSource concurrent getConnection may have  problems
Fixes #
```docs
```

fix(connection): SingleConnectionDataSource concurrent getConnection may have  problems

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/permission/database/model/UnauthorizedDatabase.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/runtime/PreCheckTask.java

type-bug
module-database permission management
In SQL console, if user try to access an unauthorized database, then the SQL executing will be intercepted and prompt user to apply database permission. But there are two case that DB permission can not be applied:
1. The database has not owned by a project.
2. The user has not involved in the project that the database owned to.
This PR fix it by add a `applicable` field for the front-end.
Fixes #1886 #1887 
```docs
```

fix(database-permission): unable apply for database permission

---

server/integration-test/src/test/java/com/oceanbase/odc/service/flow/FlowInstanceServiceTest.java
server/odc-service/src/main/java/com/oceanbase/odc/config/jpa/EnhancedJpaRepository.java

type-bug
When querying the flow instances in pages via `flow_instance_view`, it will return the wrong `totalElements` and `pageSize` consequently.
The root cause is that Spring Data JPA gives a wrong SQL to count the total elements when the SQL has a **`GROUP BY`** statement. I assume it's a Spring's issue while they don't think so. Some other developers also encountered this problem. For more discussion, you can see at https://github.com/spring-projects/spring-data-jpa/issues/2361
Here is what happened in Spring Data JPA: When we use `GROUP BY` in our query sql, what we want to obtain is how many rows of the query sql will be returned by the query, but Spring just return the sum of each group's size. For example, let's say we have a table:
```
CREATE TABLE `test` (
`a` bigint(20) DEFAULT …
```

fix(flow): wrong total elements and total pages of flow instances while querying in page

---

libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OracleSchemaAccessor.java
libs/db-browser/src/main/resources/schema/sql/oboracle/oboracle_3_x.yaml
libs/db-browser/src/main/resources/schema/sql/oboracle/oboracle_4_0_x.yaml
server/integration-test/src/test/java/com/oceanbase/odc/service/structurecompare/oboracle/DefaultDBStructureComparatorTest.java

type-bug
1. fix the order of column names in Index and constraint are inconsistent
2. fix display package body even when there is no package body in the native Oracle package
Fixes #1942
Fixes #1895
```docs
```

fix(db-browser): the order of column names in Index and constraint are inconsistent

---

server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DBStructureComparisonFlowableTask.java

type-bug
`ConnectionService.getForConnect` need update connection permission, use `ConnectionService.getForConnectionSkipPermissionCheck` instead
Fixes #2003
```docs
```

fix(structure-compare): failed to run structure compare task without update connection permission

---

server/integration-test/src/test/java/com/oceanbase/odc/service/dml/UpdateGeneratorTest.java
server/odc-service/src/main/java/com/oceanbase/odc/service/dml/TableDataService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/dml/UpdateGenerator.java

type-bug
module-resultset
When I update 100 rows and 1 column in the result set, then ODC will cost about 16.5 second. The root cause is that the `UpdateGenerator` has repeated SQL query. This PR fix it and the time elapsed decrease to about 700ms.
Fixes #2005 
```docs
```

fix(resultset-edit): bad performance when modifing query result set

---

server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/BaseRestrictIndexDataTypes.java
server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/BaseRestrictPKDataTypes.java
server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/MySQLRestrictAutoIncrementDataTypes.java
server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/NoDefaultValueExists.java
server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/ProhibitedDatatypeExists.java
server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/RestrictColumnNotNull.java
server/odc-service/src/test/java/com/oceanbase/odc/service/sqlcheck/OracleSqlCheckerTest.java

type-bug
the dataType is null when a column is a virtual column and it will lead to null pointer exception, this pr fix this problem.
Fixes #2028
```docs
```

fix(sql-check): avoid npe when virtual column exists

---

server/plugins/connect-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/connect/obmysql/OBMySQLConnectionExtension.java

When user test connection failed, the exceptio would be eaten. Make some modifications here and print the complete exception stack.

enhancement(connection): print exception stack when test connection failed

---

server/odc-service/src/main/java/com/oceanbase/odc/service/session/factory/DruidDataSourceFactory.java

type-bug
The durid connection pool will try again when it is not full, and the previously waiting time for getting connection is 10s, so the total waiting time is 20s. we just modify the max wait time to 5s.
`com.alibaba.druid.pool.DruidDataSource#getConnectionDirect`:
```
public DruidPooledConnection getConnectionDirect(long maxWaitMillis) throws SQLException {
int notFullTimeoutRetryCnt = 0;
DruidPooledConnection poolableConnection;
while(true) {
while(true) {
try {
poolableConnection = this.getConnectionInternal(maxWaitMillis);
break;
} catch (GetConnectionTimeoutException var23) {
if (notFullTimeoutRetryCnt > this.notFullTimeoutRetryCount || this.isFull()) {
throw var23;
}
++notFullTimeoutRetryCnt;
if (LOG.isWarnEnabled()) {
LOG.warn("get connection timeout retry : " + …
```

fix(connection):modify DruidDataSource MaxWait timeout

---

server/odc-service/src/main/java/com/oceanbase/odc/service/resultset/DumperResultSetExportTaskManager.java
server/odc-service/src/main/java/com/oceanbase/odc/service/resultset/ResultSetExportTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/util/SqlRewriteUtil.java
server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/datatransfer/factory/BaseParameterFactory.java

type-bug
1. The `fetch first x rows only` syntax is only available on oracle after 12c. So we change it into `where rownum<=x`.
2. When export result-set, the `maxDumpSizeBytes` was not set. Fixed this.
Fixes #2017

fix(result-set-export): fix export result-set for oracle failed

---

libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/stats/mysql/OBMySQLNoLessThan400StatsAccessor.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/stats/oracle/OBOracleNoLessThan400StatsAccessor.java

type-bug
while connec to oceanbase 4.2.1, commit/rollback button does not sync with trans state. 
Fixes #2096 
odc get transaction state from gv$ob_processlist, 
however it may result into empty while connect to oceanabase 4.2.1.1~4.2.1.4.
change to access `v$ob_processlist` instead of `gv$ob_processlist` will workaround this issue.
```docs
```

fix(sql-execute): commit/rollback button does not sync with trans state

---

server/integration-test/src/test/java/com/oceanbase/odc/service/partitionplan/PartitionPlanScheduleServiceTest.java
server/odc-service/src/main/java/com/oceanbase/odc/service/partitionplan/PartitionPlanScheduleService.java

type-bug
The partition plan configuration of a specific table cannot be viewed when the partition plan is not in effect. This is because the relevant records have been inserted into the corresponding table when the partition plan is started (usually in the antenna), so they cannot be found.
This PR fixes this problem. When the relevant records cannot be found, they are obtained from the parameters of the task.
Fixes #2089 
```docs
```

fix(partition-plan): failed to view partition plan tables when partition is not active

---

libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/editor/DBTablePartitionEditor.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/editor/mysql/MySQLDBTablePartitionEditor.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/editor/oracle/OracleDBTablePartitionEditor.java
libs/db-browser/src/test/resources/table/operator/ob/mysql/partition/update_multi_partition_test_cases.json
libs/db-browser/src/test/resources/table/operator/ob/oracle/partition/delete_multi_partition_test_cases.json
libs/db-browser/src/test/resources/table/operator/ob/oracle/partition/update_multi_partition_test_cases.json
server/integration-test/src/test/java/com/oceanbase/odc/service/partitionplan/PartitionPlanServiceTest.java
server/plugins/task-plugin-ob-mysql/src/test/java/com/oceanbase/odc/plugin/task/obmysql/partitionplan/OBMySQLAutoPartitionExtensionPointTest.java
server/plugins/task-plugin-ob-oracle/src/test/java/com/oceanbase/odc/plugin/task/oboracle/partitionplan/OBOracleAutoPartitionExtensionPointTest.java

type-bug
wrap the identifier with '"' or '`' to make partition work normally when identifier is in lower case
Fixes #2086 
```docs
```

fix(partition-plan): failed to execute partition ddl when schema or table name is in lower case

---

server/odc-core/src/main/java/com/oceanbase/odc/core/authority/session/DefaultSecuritySession.java
server/odc-core/src/main/java/com/oceanbase/odc/core/authority/session/manager/BaseSecuritySessionManager.java
server/odc-core/src/main/java/com/oceanbase/odc/core/session/BaseConnectionSessionManager.java
server/odc-core/src/main/java/com/oceanbase/odc/core/session/BaseValidatedConnectionSessionManager.java
server/odc-core/src/main/java/com/oceanbase/odc/core/session/ConnectionSessionValidateTask.java
server/odc-core/src/main/java/com/oceanbase/odc/core/session/DefaultConnectionSession.java
server/odc-core/src/main/java/com/oceanbase/odc/core/session/DefaultConnectionSessionManager.java
server/odc-service/src/main/java/com/oceanbase/odc/service/common/util/SqlUtils.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/ConnectConsoleService.java
server/plugins/task-plugin-ob-mysql/src/test/java/com/oceanbase/odc/plugin/task/obmysql/partitionplan/OBMySQLHistoricalPartitionPlanDropGeneratorTest.java

type-bug
1. this pr fix an issue that a session will not be removed when it is expired.
2. there is a security risk attached to horizontal ultra vires
Fixes #
```docs
```

fix(session): failed to remove session when session is expired

---

server/odc-service/src/main/java/com/oceanbase/odc/service/pldebug/session/AbstractDebugSession.java
server/odc-service/src/main/java/com/oceanbase/odc/service/pldebug/session/DebuggeeSession.java
server/odc-service/src/main/java/com/oceanbase/odc/service/pldebug/session/DebuggerSession.java

type-bug
the pldebug's session timeout settings is hard code and can not be modified.
I run these timeout settings after session init script to avoid this issue~
Fixes #2172 
```docs
```

fix(pl-debug): make timeout settings can be overwritten by session init script

---

server/odc-service/src/main/java/com/oceanbase/odc/service/datatransfer/task/DataTransferTask.java
server/plugins/task-plugin-api/src/main/java/com/oceanbase/odc/plugin/task/api/datatransfer/dumper/ExportOutput.java

type-bug
In the earlier version, ob-loader-dumper would save binary files like `MANIFEST.bin` in data directory. 
But in obloader-2.4.8.2, it has changed the file path into root directory. So ODC has adapted this feature.
FROM
```
root
└── data
   ├── TABLE
   │      └── xxx.sql
└── MANIFEST.bin
```
TO
```
root
├── data
│     └── TABLE
│          └── xxx.sql
└── MANIFEST.bin
```
Fixes #2176

fix(data-transfer): obloader fail to load MANIFEST.bin

---

server/odc-core/src/main/java/com/oceanbase/odc/core/sql/execute/mapper/DefaultJdbcRowMapper.java
server/odc-core/src/main/java/com/oceanbase/odc/core/sql/execute/mapper/OBOracleGeometryMapper.java
server/odc-service/src/main/java/com/oceanbase/odc/service/dml/converter/DataConverters.java
server/odc-service/src/main/java/com/oceanbase/odc/service/dml/converter/OBOracleGeometryConverter.java
server/odc-service/src/main/java/com/oceanbase/odc/service/rollbackplan/RollBackPlanJdbcRowMapper.java

module-resultset
type-feature
support gis datatype: `sdo_geometry` for ob oracle mode.
OB Oracle and OB mysql store gis datatype both in `wkb` format, but in order to be compatible with display, the oracle mode applies a layer of format conversion when outputting, and converts it into Oracle's sdo_geometry format. So we can use `resultset.getString()` to get `sdo_geometry` format ：
Fixes #2215
```docs
```

feat(resultset): support gis datatype for ob oracle mode

---

.github/workflows/build_artifact.yaml
.github/workflows/build_daily.yaml
.github/workflows/build_release.yaml
distribution/docker/odc-build/create_node_env.sh
script/functions.sh

Set the pnpm version to v8 to avoid incompatibility with node16
Fixes #
```docs
```

builds: fix failed to install pnpm

---

server/integration-test/src/test/java/com/oceanbase/odc/service/collaboration/ProjectServiceTest.java
server/integration-test/src/test/java/com/oceanbase/odc/service/iam/UserServiceTest.java
server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/ProjectController.java
server/odc-service/src/main/java/com/oceanbase/odc/config/HookConfiguration.java
server/odc-service/src/main/java/com/oceanbase/odc/metadb/iam/UserEntity.java
server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/project/ProjectService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/project/model/QueryProjectParams.java
server/odc-service/src/main/java/com/oceanbase/odc/service/iam/UserService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/iam/auth/CustomAuthenticationSuccessHandler.java
server/odc-service/src/main/java/com/oceanbase/odc/service/iam/model/User.java
server/starters/web-starter/src/main/java/com/oceanbase/odc/service/iam/auth/SsoUserDetailService.java
server/starters/web-starter/src/main/java/com/oceanbase/odc/service/iam/auth/bastion/BastionUserDetailService.java
server/starters/web-starter/src/main/java/com/oceanbase/odc/service/iam/auth/play/PlaysiteUserDetailService.java

type-bug
module-bastion integration
When using Oauth for account integration, then can not using bastion integration for accessing a temp SQL console.
The root cause is that ODC must create a built-in project for user and then the bastion integration will work. But if user use Oauth for login, then the project will not be create.
In This PR, I fix it by create user related built-in project once the bastion integration is enbled. 
Fixes #
```docs
```

fix(bastion): could not access SQL console when using OAuth for account integration

---

server/odc-common/src/main/java/com/oceanbase/odc/common/security/OdcBigDecimalChecker.java
server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/MaskingAlgorithmService.java

type-bug
When I test masking using rounding algorithm, and input a big decimal such as 100e999999, then it occupied large CPU usage. And if I mock many these request at same time ,then DoS may occur.
This PR fix it by adding a `OdcBigDecimalChecker` to check if the BigDecimal value passed in has a denial of service risk.
Fixes #2270 
```docs
```

security: test masking using rounding algorithm may cause denial of service (DoS) risk

---

pom.xml

type-security
ODC indirectly relies on the insecure version of `org.xerial.snappy:snappy-Java` by `ob-loader-dumper`. It should be excluded.
Fixes #2316

security: exclude dependency on snappy-Java

---

server/integration-test/src/test/java/com/oceanbase/odc/service/notification/NotificationServiceTest.java
server/odc-service/src/main/java/com/oceanbase/odc/metadb/notification/ChannelRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/service/notification/NotificationService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/notification/helper/ChannelMapper.java
server/odc-service/src/main/java/com/oceanbase/odc/service/notification/model/WebhookChannelConfig.java

type-bug
When user edit and update channel with sign, the sign would be lost after updating.
This is due to the annotation of `@OneToMany`, which caused the new `ChannelPropertyEntity` to overwrite the old ones when editing `ChannelEntity`.
This PR modifies the `save` to the `update` method of `ChannelRepository`. And abandoned the cascading updates of JPA, instead manually deleting ChannelProperty and inserting them again.
Fixes #2305

fix(notification): lost sign when updating channel

---

server/odc-service/src/main/java/com/oceanbase/odc/service/resultset/ResultSetExportTask.java

type-bug
Now ODC use backend datasource of session to export result set. But it's socket timeout is 60 seconds and cannot be configured.
If a query is executed for more than 60 seconds, such as `select sleep (70)`, the socket will time out with an error: Read timed out.
So we use console datasource , which socket timeout could be configured.
Fixes #2115

fix(result-set-export): use console datasource to avoid socket timeout

---

server/plugins/connect-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/connect/obmysql/initializer/EnableTraceInitializer.java

type-bug
Sometimes, due to performance issues, some tenants may default to disabling full link traces. This will result in the trace function of ODC becoming unavailable.
To avoid this issue, we enabled full link trace by default on version 4. x.
Please note that `DBMS_MONITOR.OB_SESSION_TRACE_ENABLE` called here  is session level and does not affect the overall tenant. Therefore, the impact on tenant performance should be controllable

fix(full-link-trace): enable trace by default on OB 4.x

---

server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/SensitiveColumnService.java

type-bug
module-sql execution
This PR fix a boundary bug for data masking.
Fixes #2357 
```docs
```

fix(data-masking): unavailable when existing invalid database with duplicated name

---

server/odc-common/src/main/java/com/oceanbase/odc/common/crypto/RsaBytesEncryptor.java
server/odc-common/src/test/java/com/oceanbase/odc/common/crypto/RsaBytesEncryptorTest.java

type-bug
module-RSA encryption
There exist concurrent issue in RSA encryption and this PR fix it by add `sychronized` keyword for the `encrypt` and `decrypt` methods.
Fixes #2368 
```docs
```

fix(encryption): exception occurs when invoking RSA decryption concurrently

---

.idea/runConfigurations/mvn_clean_install_test.xml
server/odc-service/src/main/java/com/oceanbase/odc/config/HookConfiguration.java

type-bug
If the user joins a project that has been archived, deleting the user fails.
PS: Only when the user is the admin/DBA of the project will it not be deleted.
Fixes #2284

fix(iam): failed to delete a user who is an archived project's Owner or DBA

---

server/odc-service/src/main/java/com/oceanbase/odc/service/websocket/OBClientReadThread.java

type-bug
When input a long sequence in obclient, it would return a sequence with ` \r` in it. And it would cause the cursor going back to head of the line . 
So we replace these unexpected characters manually.
Fixes #2301

fix(obclient): remove unexpected characters to avoid obclient display incorrectly

---

server/odc-common/pom.xml
server/odc-common/src/main/java/com/oceanbase/odc/common/util/StringUtils.java
server/odc-service/src/main/java/com/oceanbase/odc/service/shadowtable/ShadowTableComparingTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/structurecompare/DefaultDBStructureComparator.java

type-bug
When the original table column's default is a string type, the generated ddl does not quote the default value which causes to sql execution failed.
Fixes #2379 
This issue was introduced by https://github.com/oceanbase/odc/pull/1401
```docs
```

fix(shadowtable): bad sql grammer when table column's default value is a string type in MySQL

---

server/odc-common/src/main/java/com/oceanbase/odc/common/crypto/RsaBytesEncryptor.java
server/odc-common/src/test/java/com/oceanbase/odc/common/crypto/RsaBytesEncryptorTest.java

type-bug
This PR #2371 does not really fix the bug #2368 , and this PR fix it. 
Fixes #2368 
Unit test case added.
```docs
```

fix(encryption): RSA decrypting failed if already decrypted a invalid input string

---

server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMJobFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMTableStructureSynchronizer.java
server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DataSourceInfoMapper.java
server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/model/DataArchiveParameters.java
server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/model/DlmTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/AbstractDlmJob.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DLMJobParameters.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataArchiveJob.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataDeleteJob.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/DataArchiveTask.java

type-feature
Synchronize the table structure based on the results from the table structure comparator. After this PR is merged, DLM tasks will support automatic table structure synchronization for both MYSQL and OB data sources.
Fixes #
```docs
```

feat(dlm): incremenntal table structure synchronization

---

server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/BaseODCFlowTaskDelegate.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/FlowTaskCallBackApprovalService.java

type-bug
In DataTransferRuntimeFlowableTask, we use TaskService#update to upgrade task result, then use TaskService#success to finish task. 
If the `success` is called before `update`, the real result woule be overwriten.

fix(data-transfer): fix incorrect task result update

---

server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/TaskType.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/BaseODCFlowTaskDelegate.java

type-bug
When invoking `BaseODCFlowTaskDelegate#callback()`, the actual task may not executed adn has no log file. In this case, odc will throw exception. This  PR fix it.
Fixes #
```docs
```

fix(ticket): failed to set download log file url

---

server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/ProcessJobCaller.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/DefaultJobConfiguration.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/DefaultSpringJobConfiguration.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/JobConfiguration.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/TaskFrameworkConfiguration.java

daemon job running be fired at one time in cluster model, so we remove datasource and quartz will use RAMJobStore as non-cluster model
Fixes #
```docs
```

fix(taskframework): daemon job be fired at one time in cluster model

---

server/odc-service/src/main/java/com/oceanbase/odc/service/common/response/PaginatedData.java
server/odc-service/src/main/java/com/oceanbase/odc/service/common/response/PaginatedResponse.java

fix(deserialization): failed to deserialize the page object

---

server/integration-test/src/test/java/com/oceanbase/odc/service/permission/PermissionCheckWhitelistTest.java
server/odc-server/src/main/resources/data.sql
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/permission/common/PermissionCheckWhitelist.java

type-bug
module-database permission
When execute:
```sql
call DBMS_OUTPUT.putline('aaaa');
```
We cannot judge `DBMS_OUTPUT` is name of a database or a package. Now we will recognize them as database name, but the "database" is not exist, so the SQL will be intercepted during permission check.
This PR fix it by add a whitelist, the default vaule is all OB inside system packages. User can add items by config metaDB. If a new dialect type is supported, we no need to change codes, but add config key as `odc.permission-check.whitelist.database.[dialect-type]`.
Fixes #2391 
```docs
```

fix(database-permission): could not call inside dbms package in SQL console

---

server/integration-test/src/test/java/com/oceanbase/odc/metadb/config/SystemConfigRepositoryTest.java
server/odc-service/src/main/java/com/oceanbase/odc/metadb/config/ConfigEntity.java
server/odc-service/src/main/java/com/oceanbase/odc/metadb/config/SystemConfigEntity.java
server/odc-service/src/main/java/com/oceanbase/odc/metadb/config/SystemConfigRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/service/config/SystemConfigService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/systemconfig/DbConfigChangeMatcher.java

The field ConfigEntity.key is a reserved word in MySQL, so the workaround employed is using @Column("\`key\`") to avoid conflicts. However, due to differences in how H2 and MySQL handle reserved keywords, the original method is still implemented using jdbcTemplate to maintain compatibility with integration tests.
Fixes #
```docs
```

fix(metadb): change systemConfigDao to systemConfigRepository.

---

server/odc-server/src/main/resources/data.sql
server/odc-service/src/main/java/com/oceanbase/odc/service/config/UserConfigKeys.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseSyncManager.java
server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/DBSchemaIndexService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/DBSchemaSyncScheduler.java
server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/DBSchemaSyncTaskManager.java
server/odc-service/src/main/resources/config-meta/user-config-meta.yml

type-feature
module-global object search
This PR add support for global object search:
1. Add system config `odc.database.schema.global-search.enabled` to control the database object sync, the default value  is `true`.
2. Add a user config `odc.database.default.enableGlobalObjectSearch` to control whether open the global object search UI, the default value is `true`.
3. For web mode, if the system config value is `false`, then all sync operation will be ignored; if it is `true`, then we will only sync  databases in team space and these in individual space that the user config is `true`.
4. For desktop mode, if user config is `false`, then sync will be ignored.
Fixes #2432 
Fixes #2443 
```docs
```

feat(object-search): individual space support global object search

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/AbstractDlmJobPreprocessor.java

type-bug
optimize error message
Fixes #[2495](https://github.com/oceanbase/odc/issues/2495)
```docs
```

fix(dlm): optimize error message

---

server/odc-common/src/main/java/com/oceanbase/odc/common/i18n/Translatable.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/util/DescriptionGenerator.java

type-bug
module-i18n, ticket
The task created by Scheduler has wrong locale context. And then the task description generated by `DescriptionGenerator` is wrong.
This PR fix it by using i18n key replace using actual characters.
Fixes #2345 
Self-test Passed.
```docs
```

fix(ticket): wrong i18n description for task

---

server/odc-service/src/main/java/com/oceanbase/odc/metadb/connection/DatabaseRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/service/databasechange/DatabaseChangeChangingOrderTemplateService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/databasechange/model/DatabaseChangeFlowInstanceDetailResp.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowTaskInstanceService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/BaseODCFlowTaskDelegate.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/MultipleDatabaseChangeRuntimeFlowableTask.java

…played in real time
type-bug
1. Previously, the multi-database change ticket would have  execution records only after finishing the first batch. Now it's changed to that there are records of execution displaying once the multi-database change ticket is created.
2. Added the execution progress display.
Fixes #2516
```docs
```

fix(multiple database): no execution record is generated before or during a multi-database change task 

---

server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/DBSchemaIndexService.java

type-bug
module-object search
In individual space, when sync a database manually, NPE exception will be thrown.
The root cause is typo and this PR fix it.
Fixes #2551 
```docs
```

fix(object-search): failed to sync database metadata in individual space

---

server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java

type-bug
module-ticket
When I approve a ticket and input a comment with more than 1024 chars, then exception will be thrown. And the approval status will be failed but the task still executed.
This PR fixd it!
Fixes #2554 
```docs
```

fix(ticket): failed to approve ticket when input over-sized comment

---

server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/OdcJobListener.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/AbstractDlmJob.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataArchiveDeleteJob.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataArchiveJob.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataArchiveRollbackJob.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataDeleteJob.java

several bugfix:
1. Fixed the issue of failing to specify the partition.
2. Fixed the issue where switching tasks within the task framework caused tasks to be unschedulable.
3. Fixed the issue where the data cleaning task retry failed.
Fixes #2504 #2348 #2515 
```docs
```

fix(dlm): data delete retry failed

---

server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/datatransfer/factory/DumpParameterFactory.java
server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/datatransfer/task/BaseOceanBaseTransferJob.java
server/plugins/task-plugin-oracle/src/main/java/com/oceanbase/odc/plugin/task/oracle/datatransfer/job/factory/OracleTransferJobFactory.java

type-bug
When a imported object exists , obloader would report error even if user configured continue when error. So we should eat this exception in this case. To fix #2583 .
And obdumper could only dump table and index with column group configuration by `show create table`. It's configured by the `compactSchema` option. To fix #2555 
Fixes #
```docs
```

fix(data-transfer): exception occurs when object exists  and configured continue when error

---

server/odc-service/src/main/java/com/oceanbase/odc/metadb/flow/FlowInstanceApprovalViewEntity.java
server/odc-service/src/main/java/com/oceanbase/odc/metadb/flow/FlowInstanceApprovalViewRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/instance/FlowApprovalInstance.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/listener/ApprovalStatusNotifyListener.java

type-bug
module-flow
For multiple database change task, if the flow config is using db owners for approving, then can not find any approvers.
This PR fix it. And the approvers will be any one of all the database owners.
Fixes #2609 
```docs
```

fix(flow): cannot find approvers for multiple database change task when using database owner 

---

server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/PLController.java

Fixes #
https://github.com/oceanbase/odc/issues/2366
```docs
```

fix(stateful): batch compile failed with message 'stateId'

---

server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/ErrorCodes.java
server/odc-core/src/main/resources/i18n/ErrorMessages.properties
server/odc-core/src/main/resources/i18n/ErrorMessages_zh_CN.properties
server/odc-core/src/main/resources/i18n/ErrorMessages_zh_TW.properties
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java

type-bug
When cancel a database change task, if this task is not started yet, there may be an error 'RollBack task can not be cancelled'. This error message is confusing, we should optimize it.
Fixes #2418 
```docs
```

fix(flow-task): optimize error message of flow task cancelation

---

libs/db-browser/pom.xml
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/parser/CacheElement.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/parser/PLParser.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/parser/SqlParser.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/doris/DorisSchemaAccessor.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/MySQLNoLessThan5700SchemaAccessor.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/OBMySQLSchemaAccessor.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OBOracleSchemaAccessor.java
server/plugins/schema-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/schema/obmysql/parser/OBMySQLGetDBTableByParser.java
server/plugins/schema-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/schema/oboracle/OBOracleTableExtension.java
server/plugins/schema-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/schema/oboracle/parser/OBOracleGetDBTableByParser.java

type-bug
we parse table's ddl too many times which is not necessary, I add a cache to let a ddl only be parsed once.
the time consuming reduced by 90% (20s+ -> 1.44s)
Fixes #2440
```docs
```

fix(schema): loading table detail costs too much time

---

libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/doris/DorisSchemaAccessor.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/MySQLNoLessThan5700SchemaAccessor.java

type-bug
this pr fix an issue that the procedure and function list os not ordered by their name
Fixes #
```docs
```

fix(schema): function and procedure list is not ordered by their name in ob-mysql

---

server/integration-test/src/test/java/com/oceanbase/odc/metadb/connection/ConnectionAttributeRepositoryTest.java
server/odc-service/src/main/java/com/oceanbase/odc/metadb/connection/ConnectionAttributeRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionTesting.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/TestConnectionReq.java

type-bug
Fixes #2573 #2570 
```docs
```

fix(connect): failed to connect to a standby cluster and view table structure

---

server/integration-test/src/test/java/com/oceanbase/odc/service/collaboration/ProjectServiceTest.java
server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/project/ProjectService.java

type-bug
module-collaboration
This PR fix a bug.
Fixes #2602 
```docs
```

fix(collaboration): can not modify the description of project

---

server/plugins/connect-plugin-oracle/src/main/java/com/oceanbase/odc/plugin/connect/oracle/OracleSessionExtension.java
server/plugins/connect-plugin-oracle/src/main/java/com/oceanbase/odc/plugin/connect/oracle/OracleTraceExtension.java

type-bug
Fixes #2422
```docs
```

fix(schema): failed to query variables on native oracle

---

pom.xml
server/odc-service/pom.xml
server/plugins/connect-plugin-oracle/pom.xml

type-bug
When Oracle character set is ZHS16GBK, ODC cannot open the table structure.
According to https://stackoverflow.com/questions/36775398/java-sql-sqlexception-non-supported-character-set-oracle-character-set-178 , it's because we lack i18n dependency.
Add this dependency should fix this.
Fixes #2262

fix(db-object): exception occurred when open oracle table in GBK encoding

---

server/odc-service/src/main/java/com/oceanbase/odc/service/databasechange/DatabaseChangeChangingOrderTemplateSchedules.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/PreCheckRuntimeFlowableTask.java

type-bug
The previous isIntercepted method logic was incorrect. In the pre-check node, the judgment on the violation level of the multiple database result is skipped
Fixes #
```docs
```

fix(multiple database): the method isIntercepted in multiple database pre check node is error

---

pom.xml

security: upgrade spring-security from 5.1.10 to 5.7.12, fix CVE-2024-22257
fix https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-22257

security: upgrade spring-security from 5.1.10 to 5.7.12

---

server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMTableStructureSynchronizer.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/AbstractDlmJob.java

type-bug
Fixes #2703 
```docs
```

fix(dlm): the task status does not update properly when structural synchronization fails

---

server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBTableService.java
server/plugins/schema-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/schema/oboracle/parser/OBOracleGetDBTableByParser.java

type-bug
If fail to parse index ddl, there is an coding problem causing NPE. It should be avoided.
And the exception of viewing table now is eaten. It's difficult to find the problem's root cause.
Fixes #2747

fix(table-object): there would be an NPE if fail to parse index ddl

---

server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/datatransfer/task/BaseOceanBaseTransferJob.java

type-bug
Sometimes ob-loader-dumper's error messages are confusing. 
1. If we catch an exception 'No subfiles are generated from path', it's because all the data files are empty. In this case , the task state should not be failed.
2. If we catch an exception 'table or view does not exist', This may be because the user lacks query permissions for the DBA view. We could give users a prompt in the log.
Fixes #2774

fix(data-transfer): avoid task failure by processing exception messages

---

server/odc-service/src/main/java/com/oceanbase/odc/service/session/ConnectSessionService.java

type-bug
module-connection
Fixed the issue that the connection could not be automatically reconnected during the cloud upgrade process.
The `stateRouteMethods` method has already determined whether the forwarded node is a healthy node before forwarding, so there is no need to change the code logic of `StateRouteAspect`：
Fixes #
```docs
```

fix(connection): automatically reconnect during the cloud upgrade process

---

server/odc-service/src/main/java/com/oceanbase/odc/service/session/ConnectSessionService.java

type-bug
When automatically reconnecting in the cloud upgrade scenario, the host is obtained according to `req.getFrom()`, so that the created sessionId is consistent with the previously not found sessionId
Fixes #
```docs
```

fix(session): support auto recreate session when upgrade

---

server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/DestroyExecutorJob.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java

fix(task-framework): the pod was not released after the task was completed

---

server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/server/TaskMonitor.java

fix(task-framework): throw NPE when uploading log to object storage fails

---

server/odc-service/src/main/java/com/oceanbase/odc/service/datatransfer/task/DataTransferTask.java

If ODC was upgraded from versions earlier than 4.2.3, and the metadb files are deleted, we may import some dirty data files. So we should clean the work directory first.
fix #3005

fix(data-transfer): clean work directory before import

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/DataArchivePreprocessor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/AbstractDlmJob.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/DataArchiveTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/listener/DefaultJobTerminateListener.java

type-bug
1. Don't compare the table structure if syncTableStructure is off.
2. Sync table structure only supports MySQL and OMySQL. It throws an unsupported exception if other databases are chosen.
Fixes #2844 #2845 
```docs
```

fix(dlm): don't compare the table structure if syncTableStructure is off

---

server/odc-server/src/main/resources/log4j2-task.xml

type-bug
triggering task log rollover when task start up, and the history log will not show in new task log.
Fixes https://github.com/oceanbase/odc/issues/2203

fix(task):  show history log when odc upgrade use same mount path but with a new meta db

---

server/plugins/schema-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/schema/oboracle/parser/OBOracleGetDBTableByParser.java
server/plugins/schema-plugin-ob-oracle/src/test/java/com/oceanbase/odc/plugin/schema/oboracle/parser/OBOracleGetDBTableByParserTest.java

type-bug
If the table's DDL does not explicitly show `on delete`, the default rule is ON ACTION:
```
REFERENCES [ schema. ] object [ (column_name [, column_name...]) ] [ON DELETE { CASCADE | SET NULL } ]
```
Fixes #3028 
```docs
```

fix(schema): show constraint's on delete rule correctly by parser

---

server/integration-test/src/test/java/com/oceanbase/odc/service/connection/model/ConnectionConfigTest.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/ConnectionConfig.java

type-bug
odc can not connect to the obcloud's instance, the reason is below:
the connection info of the obcloud instance may contain tenant id or cluster id, just like this:
`obclient -h tenantId.xxx.xxx -P 1521 -u ODCTEST@tenantId -pxxxx`
but we expect that the connection info does not contain tenant or cluster info when user select 'OBCloud Oracle/MySQL' connect type.
To solve this problem, we add some specific logic: we check the username and find out if there is '@' or '#' char in it. we will split the username by '@' or '#'.
Fixes #
```docs
```

fix(connect): make odc connect to the obcloud instance

---

server/odc-common/src/main/java/com/oceanbase/odc/common/util/ResourceUtils.java
server/odc-core/src/main/java/com/oceanbase/odc/core/migrate/resource/ResourceManager.java

type-refactor
the migrator can only load sql script from its own classpath and this pr change this default behavior
Fixes #
```docs
```

refactor(migrate): supports load sql script from custom jar file

---

server/integration-test/src/test/java/com/oceanbase/odc/service/config/SystemConfigBootstrapTest.java
server/odc-common/src/main/java/com/oceanbase/odc/common/jdbc/JdbcTemplateUtils.java
server/odc-common/src/test/java/com/oceanbase/odc/common/jdbc/JdbcTemplateUtilsTest.java
server/odc-server/src/main/java/com/oceanbase/odc/server/OdcServer.java
server/odc-service/src/main/java/com/oceanbase/odc/service/config/SystemConfigBootstrap.java

type-bug
ODC startup environment variable ODC_APP_EXTRA_ARGS does not works.
root cauase was RefreshScope mechasnim reload configuration from MetaDB config_system_configuration.
involved persistence process for configuration items set via ODC_APP_EXTRA_ARGS.
Fixes #2781

fix(deployment): ODC_APP_EXTRA_ARGS not works

---

server/odc-service/src/main/java/com/oceanbase/odc/service/resultset/ResultSetExportTask.java

type-bug
when exporting result set in oracle mode  and using a lower case table name , the exported file would be empty.
It's because obdumper would always generate a file with upper case name.

fix(resultset-export): the exported file is empty if use lower table name for oracle mode

---

server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/FlowStatus.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowTaskInstanceService.java

type-bug
At present, after clicking manual execution button on the ticket, the status of ticket in the database will remain in wait_for_execution for a period of time, and the front end displays the execution button according to this status. Therefore, after clicking manual execution, the execution button will appear for a period of time, and an error will be reported when the user clicks execution button again.
The improvement is to change the status of the ticket to not ‘wait_for_execution’ immediately after clicking Manual execution button
Fixes #
```docs
```

fix(manual execution):manual execution button should not be displayed after clicking manual execution

---

server/plugins/task-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/task/mysql/datatransfer/job/datax/DataXTransferJob.java

type-bug
We use `Paths#get` to get class path for datax task. But on windows, the classpath like 'lib/*:.' are illegal file path. The get method would raise an illegal path format exception.
So we concat the path straightly instead of using `Paths`
Fixes #3125
```docs
```

fix(data-transfer): fail to start transfer task on windows

---

server/odc-core/src/main/java/com/oceanbase/odc/core/alarm/AlarmEventNames.java
server/odc-core/src/main/java/com/oceanbase/odc/core/dfa/AbstractDfa.java
server/odc-core/src/main/java/com/oceanbase/odc/core/dfa/DfaStateTransfer.java
server/odc-core/src/test/java/com/oceanbase/odc/core/dfa/DfaTest.java
server/odc-core/src/test/java/com/oceanbase/odc/core/dfa/K8sPodStatusDfa.java
server/odc-core/src/test/java/com/oceanbase/odc/core/dfa/K8sPodStatusDfaTransfer.java
server/odc-server/src/main/java/com/oceanbase/odc/server/OdcServer.java

type-build
merge from dev/4.3.x into dev/obcloud_ap_202410
Fixes #
```docs
```

merge from dev/4.3.x into dev/obcloud_ap_202410

---

server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/model/OnlineSchemaChangeTaskResult.java
server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/OnlineSchemaChangeFlowableTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleTaskService.java

…sult to fix json deserialize problem
type-bug
Revert ScheduleTask to ScheduleTaskEntity of OnlineSchemaChangeTaskResult to fix json deserialize problem.
ScheduleTask contains interface member with type ScheduleTaskParameters. Serialization  not add information about this filed. So JsonUtil.fromJson(String, Class) will failed cause deserializer can't determinate which implementation class should used.
The failure of deserialization will cause the task_task result field missing and that  leads to OSC module's 'enableManualSwap' flag missing in flowinstace/id/tasks/result response. The final result is manual swap flag not present.
Fixes #
```docs
```

fix(osc): osc manual swap table button not displayed 

---

server/odc-service/src/main/java/com/oceanbase/odc/service/session/OdcStatementCallBack.java

type-bug
fix OBJECT_VALUE_PATTERN does not match for spaces and newlines after `load_file`
Fixes #3260 
```docs
```

fix(execute-sql): failed to execute insert upload file sql

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/core/executor/sql/SqlExecutionHandler.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/LogicalDatabaseChangeTask.java

type-bug
Some unexpected errors happen if the physical database does not need to run SQL in this round. This PR set a default SQL '-- No SQL needs to execute in this run' to mock the running, and it will always succeed.
Fixes #3373 
```docs
```

fix(logicaldatabase): unexpection exception throwed when there is no SQL needs to run in some physical database

---

server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/oscfms/action/CreateGhostTableAction.java

type-bug
set ScheduleTask.OnlineSchemaChangeScheduleTaskParameters.newTableCreateDdlForDisplay to correct value when use alter table mode.
Fixes #
1. Front end fetch newTableDDL in ScheduleTask.OnlineSchemaChangeScheduleTaskResult.newTableDdl
2. newTableDdl is assigned by OnlineSchemaChangeScheduleTaskParameters.newTableCreateDdlForDisplay
3. if OnlineSchemaChangeScheduleTaskParameters.newTableCreateDdlForDisplay not set, OnlineSchemaChangeScheduleTaskResult.newTableDdl will be covered to null
4. this patch set newTableCreateDdlForDisplay to guarantee the following operation always fetch right value for newTableDdl
```docs
```

fix(osc): new create table ddl not display when use alter table mode

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleTaskService.java

The `com.oceanbase.odc.service.schedule.ScheduleTaskService#listByJobNames` method was deleted in PR https://github.com/oceanbase/odc/pull/3335 .
But we still need this. So  restore it.

fix(schedule): restore deleted method

---

server/integration-test/src/test/java/com/oceanbase/odc/service/connection/logicaldatabase/LogicalDatabaseServiceTest.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/LogicalDatabaseChangeService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/LogicalDatabaseService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/core/executor/execution/ExecutionResult.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/core/executor/execution/ExecutionStatus.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/core/executor/execution/ExecutionSubGroupUnit.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/LogicalDatabaseChangeTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/processor/LogicalDBChangeResultProcessor.java

type-bug
1. Fix the incorrect logic for changing the status of logical database subtasks. Previously, the implementation involved updating the metadb first and then publishing an action to the task framework when skipping or terminating, which was incorrect. Now, the implementation introduces three new states: `SKIPPING`, `TERMINATING`, and `TERMINATE_FAILED`. The odc-server layer no longer actively updates the result; instead, everything is handled by the task update, and the odc-server is responsible only for retrieval.
2. Make the rewrite and preview logic more robust. 
Fixes #3458 #3466 #3354 
```docs
```

fix(logicaldatabase): incorrect status transform logic of logical database change subtasks

---

server/integration-test/src/test/resources/connection/logicaldatabase/invalid_logical_table_expression_resolve.yaml
server/odc-service/src/main/resources/antlr/logicaldatabase/LogicalTableExpression.g4

type-bug
`db.tb.xxx ` should be a bad syntax expression. I edited .g4 to fix it.
Fixes #3463 
```docs
```

fix(logicaldatabase): failed to recognize the wrong expression like db.tb.xxx

---

server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/factory/ScheduleResponseMapperFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/listener/DefaultJobTerminateListener.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/processor/DLMResultProcessor.java

type-bug
task framework refresh the results updates the task status, causing it to become abnormal.
Fixes #
```docs
```

fix(dlm): task status is wrong

---

server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/factory/ScheduleResponseMapperFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/listener/DefaultJobTerminateListener.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/processor/DLMResultProcessor.java

type-bug
cherry-pick commit acf70aaa14eb0ad1ef964fc521ddcda2d9635931
Fixes #
```docs
```

fix(dlm): cherry-pick from 4.3.x

---

server/odc-core/src/main/resources/i18n/BusinessMessages.properties
server/odc-core/src/main/resources/i18n/BusinessMessages_zh_CN.properties
server/odc-core/src/main/resources/i18n/BusinessMessages_zh_TW.properties
server/odc-migrate/src/main/resources/init-config/init/regulation-rule-applying.yaml
server/odc-migrate/src/main/resources/init-config/init/regulation-rule-metadata.yaml
server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/factory/Unable2JudgeAffectedRowsFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/model/SqlCheckRuleType.java
server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/BaseAffectedRowsExceedLimit.java
server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/MySQLAffectedRowsExceedLimit.java
server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/MySQLUnable2JudgeAffectedRows.java
server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/SqlCheckRules.java
server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/Unable2JudgeAffectedRows.java
server/odc-service/src/test/java/com/oceanbase/odc/service/sqlcheck/MySQLCheckerTest.java

bugfix
added a new rule to deal with the unable to judge the affected rows.
restrict affected rows can not work when use insert statement.
because native mysql explain the insert ... statement have difference process from update/delete.
Process mode:
* case1: For INSERT INTO ... VALUES(...) statements, ODC checks the count of value list.
* case2: For INSERT INTO ... SELECT ... statements, ODC runs EXPLAIN statements to get affected rows.
Fixes #3316 
```docs
```

fix(sqlcheck): affected rows for the native MySQL INSERT statement cannot take effect

---

server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/JobCallerBuilder.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/JobEnvironmentEncryptor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/JobEnvironmentFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/constants/JobEnvKeyConstants.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/TaskApplication.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/context/JobContextProviderFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/context/K8sJobContextProvider.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/context/ProcessJobContextProvider.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/util/JobUtils.java

type-bug
Starting task fails when environment variables exceed 2MB in Process Mode.
The solution is that write `JobContext` into file, and set the file path into the environment variable, instead of setting the `JobContext` into the environment variable directly.
The solution is 
Fixes #
```docs
```

fix(task-framework): starting task fails when environment variables exceed 2MB in Process Mode

---

server/odc-service/src/main/java/com/oceanbase/odc/service/task/listener/JobTerminateNotifyListener.java

type-bug
We've added a hook for notification in `JobTerminateNotifyListener` , and determine the type of notification to be sent based on the status in `job_job` table.
But for DLM tasks , the job status is Incorrect. The real status should be found in `schedule_task`.
Fixes #3591

fix(notification): incorrent status of DLM task notification

---

server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/MySQLOfflineDdlExists.java
server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/OracleOfflineDdlExists.java
server/odc-service/src/test/java/com/oceanbase/odc/service/sqlcheck/MySQLCheckerTest.java

type-bug
cherry pick fix(sql-check): a specific sql will lead to npe (#3611)
Fixes #
```docs
```

fix(sql-check): a specific sql will lead to npe (#3611)

---

server/odc-service/src/main/java/com/oceanbase/odc/config/ScheduleConfiguration.java

type-bug
modify `syncDatabaseTaskExecutor`QueueCapacity  to `Integer.MAX_VALUE` to avoid the situation where the data source cannot trigger synchronization forever after the submitted synchronization database task exceeds the maximum number of thread pools.
Fixes #3670
```docs
```

fix(sync-database): modify syncDatabaseTaskExecutor QueueCapacity to Integer.MAX_VALUE

---

server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleTaskService.java

type-bug
The schedule task shows the wrong status if the task is restarted.
Fixes #
```docs
```

fix(scheduleTask): correct status on task restart

---

server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java

type-bug
If the task is immediately stopped, its resultJson field will not be updated. So before changing the task status, update the task results first.

fix(task-framework): update task result before canceling

---

server/plugins/connect-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/connect/obmysql/diagnose/PlanGraphBuilder.java

type-bug
When query from `gv$ob_sql_plan` view, the `fiter` value could be null. But we missed this, so there may be a NPE for some queries.

fix(query-profie): NPE occurred when `filter`'s value is null

---

server/odc-server/src/main/resources/data.sql
server/odc-service/src/main/java/com/oceanbase/odc/service/datatransfer/model/DataTransferProperties.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/OdcInternalFileService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DataTransferRuntimeFlowableTask.java

type-bug
When getting internal file for datatransfer, the default timeout was 10s . This is to small. ODC allows importing up to 2 GB of files.  So We estimate a 5-minute timeout based on transmission rate of 10 MB/s.
Fixes #3759

fix(data-transfer): read timout occurred when getting large for internal usage

---

server/integration-test/src/test/java/com/oceanbase/odc/ITConfigurations.java
server/integration-test/src/test/java/com/oceanbase/odc/service/objectstorage/cloud/GCSObjectStorageServiceIT.java
server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/client/CloudObjectStorageClient.java
server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/client/LocalObjectStorageClient.java
server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/client/ObjectStorageClient.java
server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/cloud/CloudObjectStorage.java
server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/cloud/CloudObjectStorageService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/cloud/CloudResourceConfigurations.java
server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/cloud/client/AlibabaCloudClient.java
server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/cloud/client/AmazonCloudClient.java
server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/cloud/client/NullCloudClient.java
server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/cloud/model/DeleteObjectRequest.java

type-feature
This PR uses the S3 SDK to support for Google Cloud Storage (GCS).
Most of the object storage operations currently supported by ODC are compatible with the S3 protocol in GCS.
However, please note that batch deletion in GCS is not compatible with the S3 SDK. Therefore, a separate `deleteObject` method has been added for deleting objects.

feat(object-storage): use s3 sdk for google cloud storage

---

server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DatabaseChangeRuntimeFlowableTask.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/model/DatabaseChangeParameters.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/PartitionPlanJob.java

type-bug
the task status will be set to 'sucess' even there are several errors in sql execution when we set 'ignore any errors' as the error process strategy which is not as expected.
Fixes #3784
```docs
```

fix(partition-plan): task's status is not as expected when error strategy is set to 'ignore any errors'

---

libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/DBSchemaAccessor.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/doris/DorisSchemaAccessor.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/MySQLNoLessThan5700SchemaAccessor.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/OBMySQLSchemaAccessor.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OBOracleBetween410And432SchemaAccessor.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OBOracleSchemaAccessor.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OracleSchemaAccessor.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/postgre/PostgresSchemaAccessor.java
server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/DBTableController.java
server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBTableService.java
server/plugins/schema-plugin-api/src/main/java/com/oceanbase/odc/plugin/schema/api/TableExtensionPoint.java
server/plugins/schema-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/schema/mysql/MySQLTableExtension.java
server/plugins/schema-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/schema/obmysql/OBMySQLTableExtension.java
server/plugins/schema-plugin-odp-sharding-ob-mysql/src/main/java/com/oceanbase/odc/plugin/schema/odpsharding/obmysql/ODPShardingOBMySQLTableExtension.java
server/plugins/schema-plugin-oracle/src/main/java/com/oceanbase/odc/plugin/schema/oracle/OracleTableExtension.java
server/plugins/schema-plugin-postgres/src/main/java/com/oceanbase/odc/plugin/schema/postgres/PostgresTableExtension.java

type-feature
Fixes #
```docs
```

feat(external tables): supports syncing external table files

---

server/odc-service/src/main/java/com/oceanbase/odc/service/session/util/DBSchemaExtractor.java
server/odc-service/src/test/resources/session/test_db_schema_extractor.yaml

type-bug
When doing pl editing ,procedure name in drop procedure statement is recognized as the table name, which trigger the table permission check.
the improved approach is to have DBSchemaExtractor omit the procedure name when extracting the table names
Fixes #
```docs
```

fix(pl-edit): procedure name in drop procedure statements are recognized as the table name in DBSchemaExtractor

---

server/odc-service/src/main/java/com/oceanbase/odc/service/session/ConnectSessionService.java

type-feature
support execute chart
- add param createConnectionSessionSupplier in nullSafeGet, for custom creating connectSession 
- add param maxConcurrentTaskCount in createPhysicalConnectionSession
Fixes #
```docs
```

feat(ConnectSession):  add param createConnectionSessionSupplier in nullSafeGet,  add param maxConcurrentTaskCount in createPhysicalConnectionSession 

---

server/odc-core/src/main/java/com/oceanbase/odc/core/sql/execute/task/DefaultSqlExecuteTaskManager.java

type-bug
Use LinkedList is concurrent unsafe ，replace with ConcurrentLinkedQueue. 
Concurrent access to LinkedList may result in npe
Fixes #
```docs
```

fix(DefaultSqlExecuteTaskManager): npe in DefaultSqlExecuteTaskManager

---

server/odc-service/src/main/java/com/oceanbase/odc/config/BeanConfiguration.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/CloudMetadataClient.java

add getConfiguration method in CloudMetadataClient
Fixes #
```docs
```

feat(cloud): add getConfiguration method in CloudMetadataClient

---

server/odc-common/src/main/java/com/oceanbase/odc/common/util/StringUtils.java
server/odc-common/src/test/java/com/oceanbase/odc/common/util/StringUtilsTest.java
server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBPLModifyHelper.java

type-bug
For the name `FuN_tesT@111~! The #$%^&*()_+` function, which contains special regular expression characters, was recognized as a regular match using `String.replaceFirst` method, resulting in an uncompleted replacement. 
Invalid the special characters of the regular expression contained in the function name, then use the `replaceFirst` method to complete the replacement
Fixes #3941 
```docs
```

fix(db): cannot replace original pl name where editing pl

---

server/odc-service/src/main/java/com/oceanbase/odc/service/session/util/DBSchemaExtractor.java
server/odc-service/src/test/resources/session/test_db_schema_extractor.yaml

type-bug
if the user does not have the change permission of database db1. `drop procedure 'db1'. 'testName' `in sql window will be intercepted. But executing `drop procedure testName `will not be intercepted. This pr is so that the latter will also be intercepted
Fixes #3908 
```docs
```

fix(session):drop pl require database change permission

---

server/odc-service/src/main/java/com/oceanbase/odc/service/db/session/DefaultDBSessionManage.java

type-bug
The current method for determining whether a global session is enabled applies only to `system` tenants, but not to `mysql` and `oralce` tenants. Instead, should adopt this way that determining whether the result set after running `show processlist` contains the column `time`.
Fixes #
```docs
```

fix(db): The method of determining whether opening the global client session is incorrect

---

server/odc-service/src/main/java/com/oceanbase/odc/config/BaseAuthConfiguration.java
server/odc-service/src/main/java/com/oceanbase/odc/config/DefaultAuthConfiguration.java
server/odc-service/src/main/java/com/oceanbase/odc/metadb/iam/PermissionRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/ApprovalPermissionService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowPermissionHelper.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowTaskInstanceService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/factory/FlowResponseMapperFactory.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/listener/ApprovalStatusNotifyListener.java
server/odc-service/src/main/java/com/oceanbase/odc/service/iam/GlobalResourceRoleService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/iam/ResourceRoleService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/iam/auth/DefaultAuthorizationFacade.java
server/odc-service/src/main/java/com/oceanbase/odc/service/iam/auth/ResourceRoleAuthorizer.java
server/odc-service/src/main/java/com/oceanbase/odc/service/iam/model/UserResourceRole.java
server/odc-service/src/main/java/com/oceanbase/odc/service/iam/util/GlobalResourceRoleUtil.java

type-bug
This PR fixed several bugs related to the global project roles. The main update of this PR is that I changed all `UserResourceRoleRepository` references to `ResourceRoleService` references, which adds global role business logic.
The main reason is that I did not adapted the permission part entirely in the previous code.
Fixes #
```docs
```

fix(permission): global project roles cannot view/execute/approve tickets

---

server/odc-service/src/main/java/com/oceanbase/odc/service/resource/k8s/status/K8sDeploymentStatusDfa.java
server/odc-service/src/main/java/com/oceanbase/odc/service/resource/k8s/status/K8sServiceStatusDfa.java

type-bug
Now when k8s resource's state is UNKNOWN, it would be it's final state. And when the real resource is back to normal , the state could not be changed.

fix(workflow): add dfa transfer from unknown state

---

server/odc-service/src/main/java/com/oceanbase/odc/service/structurecompare/StructureComparisonService.java

type-bug
fix the structure synchronization task cannot be initiated when the structure comparison task is not created by yourself, because the object storage is isolated by user id so that user1 can not see user2's object storage.
Fixes #
```docs
```

fix(structure-compare):the structure synchronization task cannot be initiated when the structure comparison task is not created by yourself

---

libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/MySQLNoLessThan5700SchemaAccessor.java
libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/schema/MySQLNoLessThan5700SchemaAccessorTest.java

type-bug
fix can not get the precision of year data type column.
The precision of the year field type can only be 4，It can be declared as YEAR with an implicit display width of 4 characters, or equivalently as YEAR(4) with an explicit display width. We can only get the precision by parse COLUMN_TYPE or use default width of 4 .
Fixes #3713
```docs
```

fix(db-browser):can not get the precision of year data type column

---

libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/model/DBTableStats.java

type-bug
remove @JsonProperty in DBTableStats.dataSizeInBytes so that we can provided the size of table in bytes to the front end
Fixes #
```docs
```

fix(db-browser): remove @JsonProperty in DBTableStats.dataSizeInBytes

---

server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/iam/ResourceRoleService.java

type-bug
This PR fixed 2 bugs:
1. Even if the external approval has approved the flow instance, the approval process in ODC will not proceed. The reason is that when calling `approve` method, authentication fails due to a code modification introduced in version 4.3.3. The fix is to differentiate between scenarios that require authentication and those that do not.
2. The global project owner is unable to approve because of a logical error. When constructing `resourceRoleIdentifiers`, all project IDs should be enumerated instead of using `*` as a substitute.
Fixes #
```docs
```

fix(permission): external approval integration doesn't take effect

---

server/odc-service/src/main/java/com/oceanbase/odc/service/task/base/logicdatabasechange/LogicalDatabaseChangeTask.java

type-bug
The logical database task may have NPE in the log, but the task will success.
This is because when `TaskMonitor` call `getTaskResult`, the `executionGroupContext` may be null.
I fixed this by moving the process of init the `executionGroupContext` into `doInit` method.
Fixes #
```docs
```

fix(logicaldatabase): it may NPE when the logical database task starts

---

server/odc-migrate/src/main/java/com/oceanbase/odc/migrate/VectorDBMigrate.java

type-bug
VectorDBMigrate only load on server mode.
Fixes #
```docs
```

fix(migrate): vectorydb only load on server mode

---

server/odc-common/src/main/java/com/oceanbase/odc/common/util/HostUtils.java
server/odc-common/src/test/java/com/oceanbase/odc/common/util/HostUtilsTest.java
server/odc-service/src/main/java/com/oceanbase/odc/service/db/session/DefaultDBSessionManage.java

type-bug
The previous regex to extract observer IP and port is wrong. This regular expression has two issues:
1. It allows any characters before and after, which can cause logical errors. For example, with an input like 1.1.1.1:8888, the IP will be captured as 1.1 instead of 1.1.1.1 because .* is a greedy pattern that tries to match as many characters as possible. 
3. The dot (.) is not escaped, which means it matches any character in regex, but it should actually represent the dot (.) itself.
Fixes #
```docs
```

fix(session): killing session may fail due to a wrong regex

---

server/odc-service/src/main/java/com/oceanbase/odc/service/resource/k8s/status/K8sDeploymentStatusDfa.java

There are more than one routes for state UNKNOWN of deployment. We should delete the useless ones.

fix(resource):  delete redundant status transfer of k8s deployment

---

server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMTableStructureSynchronizer.java

type-bug
generate table ddl error because of the default value  for table column.
Fixes #
```docs
```

fix(dlm): failed to execute dlm task because of sync table structure failed

---

server/odc-service/src/main/java/com/oceanbase/odc/service/datatransfer/task/DataTransferTask.java

4.3.3 would fail to re-import odc exported zip file.
Fixes #
```docs
```

fix(datatransfer): failed to re-import odc exported zip file

---

server/odc-migrate/src/main/java/com/oceanbase/odc/migrate/jdbc/common/R4237DefaultRuleApplyingMigrate.java

type-bug
It doesn't distinguish between updating and creating scenarios when migrating the SQL rules. 
We should only handle the creating scenarios, and ignore the updating scenarios. If not (as the bug's root cause), it will cause a unique key conflict.
Fixes #
```docs
```

fix(migrate): upgrade to 4.3.3 will fail if it exists custom environments before

---

server/odc-service/src/main/java/com/oceanbase/odc/config/HookConfiguration.java
server/odc-service/src/main/java/com/oceanbase/odc/service/regulation/risklevel/model/RiskDetectRule.java

type-bug
The `RiskDetectRule.rootNode` could be null, but the caller side does not consider it, which may cause NPE.
Fixes #
```docs
```

fix(risklevel): delete user defined environments may cause NPE due to the detect rule could be null

---

server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionTesting.java

type-bug
We do not verify whether the `ConnectType`  selected by the user is consistent with the actual `ConnectType`, because for ob sharding type, it is not possible to obtain it‘s real `ConnectType` through the `ConnectTypeUtil#getDialectType` method.
Fixes #
```docs
```

fix(connection): failed to connect to ob sharding mysql

---

server/odc-server/pom.xml

type-bug
Remove useless sshd-common dependence to avoid some security vulnerabilities.
Fixes #
```docs
```

security: remove useless sshd-common dependence

---

server/integration-test/src/test/java/com/oceanbase/odc/service/session/NlsFormatInterceptorTest.java
server/odc-service/src/main/java/com/oceanbase/odc/service/session/interceptor/NlsFormatInterceptor.java

type-bug
The NlsFormatInterceptor failed to recognize statement like `set variables='xxx'`.

fix(sql-execute): nls_format invalidation

---

server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/DBObjectIndexController.java
server/odc-service/src/main/java/com/oceanbase/odc/metadb/connection/DatabaseRepository.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/DBSchemaIndexService.java

type-feature
At present, the section that groups databases in the resource tree will obtain all databases that the user has the right to operate. In this case, all data objects under the project that the user has joined need to be synchronized

feat(database): Sync current user database objects when grouping databases

---

server/odc-core/src/main/java/com/oceanbase/odc/core/shared/Verify.java
server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/DataBaseController.java
server/odc-service/src/main/java/com/oceanbase/odc/metadb/connection/DatabaseSpecs.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/model/QueryDatabaseParams.java
server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/InnerQueryConnectionParams.java

type-feature
Databases can be queried by tenantName, clusterName and dataSourceName

feat(database): supports query database by tenantName、clusterNam and dataSourceName

---

server/odc-server/src/main/java/com/oceanbase/odc/supervisor/runtime/SupervisorApplication.java
server/odc-server/src/test/java/com/oceanbase/odc/supervisor/SupervisorApplicationTest.java
server/odc-server/src/test/java/com/oceanbase/odc/supervisor/runtime/TaskSupervisorServerTest.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/BaseJobCaller.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/ExecutorIdentifier.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/ExecutorInfo.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/JobCallerBuilder.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/K8sJobCaller.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/ProcessJobCaller.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/DefaultSpringJobConfiguration.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/dummy/LocalMockK8sJobClient.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/resource/LocalProcessResource.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/v2/DoFinishJobV2.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/TaskFrameworkService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/supervisor/DefaultJobEventListener.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/supervisor/TaskSupervisor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/supervisor/endpoint/ExecutorEndpoint.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/supervisor/proxy/LocalTaskSupervisorProxy.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/util/JobUtils.java
server/odc-service/src/test/java/com/oceanbase/odc/service/task/schedule/daemon/v2/DaemonV2TestBase.java
server/odc-service/src/test/java/com/oceanbase/odc/service/task/schedule/daemon/v2/StartPreparingJobV2Test.java
server/odc-service/src/test/java/com/oceanbase/odc/service/task/supervisor/TaskSupervisorTest.java

…cause log get required this port
type-bug
the Port in ExecutorIdentifier have different meaning in different run mode.
In process mode, it represent the ODC server port and will be used for log content get request process.
In K8s mode, it represent the Agent port for future request send.
Correct logic to fix previous logic.
Fixes #
```docs
```

fix(task): correct executorIdenfifier port to odc server port for process mode

---

server/integration-test/src/test/java/com/oceanbase/odc/service/script/ScriptServiceWithLocalTest.java
server/odc-service/src/main/java/com/oceanbase/odc/service/script/ScriptService.java

type-bug
fix bug: only one script download when select many same name scripts
Fixes #
```docs
```

fix(Script): only one script download when select many same name scripts

---

server/integration-test/src/test/java/com/oceanbase/odc/service/iam/ResourceRoleBasedPermissionExtractorTest.java
server/odc-service/src/main/java/com/oceanbase/odc/service/iam/ResourceRoleBasedPermissionExtractor.java
server/odc-service/src/main/java/com/oceanbase/odc/service/iam/ResourceRoleService.java

type-bug
This PR fixed two issues of permission framework:
1. when quering resource roles, it does not query by organization id, which may cause to horizontal authetication bug;
2. when resource ids are the same, but they are different resource types, it has logic error when authentication.
Fixes #
```docs
```

fix(permission): authentication will wrongly fail when resource ids are the same but resource types are different

---

libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/DBSchemaAccessor.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/constant/Statements.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/doris/DorisSchemaAccessor.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/MySQLNoLessThan5700SchemaAccessor.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/OBMySQLBetween432And4351SchemaAccessor.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/OBMySQLSchemaAccessor.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OBOracleSchemaAccessor.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OracleSchemaAccessor.java
libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/postgre/PostgresSchemaAccessor.java
libs/db-browser/src/main/resources/schema/sql/obmysql/obmysql_4_3_2_x.yaml
libs/db-browser/src/main/resources/schema/sql/oboracle/oboracle_4_3_2_x.yaml
libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/schema/OBMySQLSchemaAccessorTest.java
libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/schema/OBOracleSchemaAccessorTest.java
server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/OdcConstants.java
server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/SensitiveColumnService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/model/DatabaseWithAllColumns.java
server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/syncer/column/DBTableAndViewAndExternalTableColumnSyncer.java
server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/syncer/column/DBTableAndViewColumnSyncer.java
server/plugins/schema-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/schema/obmysql/OBMySQLTableExtension.java

1. Sensitive column function adapts to materialized view
2. Obtain the table list that filters out materialized view logs and container tables
Fixes #
```docs
```

feat(materialized view):data desensitization supports materialized views

---

server/odc-core/src/main/java/com/oceanbase/odc/core/sql/util/OBUtils.java
server/plugins/connect-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/connect/obmysql/OBMySQLDiagnoseExtension.java
server/plugins/connect-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/connect/oboracle/OBOracleDiagnoseExtension.java

type-bug
OB 4.2.5 has added an internal variable, which is named ''eable_sql_audit_query_sql'. If this variable is true, then the query SQL in the SQL audit view is empty.

fix(sql-execute): remove length check when querying sql audit

---

server/odc-service/src/main/java/com/oceanbase/odc/service/config/OrganizationConfigUtils.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DatabaseChangeThread.java
server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/model/DatabaseChangeParameters.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/SqlPlanJob.java
server/odc-service/src/main/java/com/oceanbase/odc/service/task/base/databasechange/DatabaseChangeTask.java

bugfix
The constant value used by `query limit` defined in the `databaseChangeParameters` is not synchronized with the value of the organization configuration, causing the partition plan subtask database change failed to execution.
Fixes #
```docs
```

fix(flow): fix the partition plan subtask database change execution failed

---

server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/model/ScheduleStat.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/model/ScheduleTaskStat.java
server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/model/ScheduleTaskType.java

type-bug
- Adjust the logic for obtaining the number of enabled partitions by querying the flow_isntance table
- Adjusted to get all sub-tasks of a periodic parent task instead of grouping them. For example, the sub-tasks of a periodic data archiving task include data cleaning + data archiving. The actual number of tasks should be 2 instead of 1
- Adjust the structure of the code to make it more concise

fix(schedule): landing page displayed number of partition plans enabled is incorrect

---

server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/model/MultipleDatabaseChangeParameters.java

fix
There is no query limit for the database change subtask due to multiple database change task parameter incompleteness.
```docs
```

fix(flow): fix multiple database change task parameter incompleteness

---

server/integration-test/src/test/java/com/oceanbase/odc/migrate/jdbc/common/V43411RectifyDetectRuleOfTaskTypeMigrateTest.java
server/odc-migrate/src/main/java/com/oceanbase/odc/migrate/jdbc/common/V42415AddDefaultRiskDetectRules.java
server/odc-migrate/src/main/java/com/oceanbase/odc/migrate/jdbc/common/V43410RectifyDetectRuleOfTaskTypeMigrate.java
server/odc-migrate/src/main/java/com/oceanbase/odc/migrate/jdbc/common/V43411RectifyDetectRuleOfTaskTypeMigrate.java

type-bug
Provide the default highest risk level identification rule condition for users upgrading to ODC 434 or later for the first time: Task type equal to APPLY_TABLE_PERMISSION

fix(riskLevel): add default detect rule condition that is task type equals APPLY_TABLE_PERMISSION

---

server/odc-service/src/main/java/com/oceanbase/odc/service/task/resource/K8sPodResource.java
server/odc-service/src/test/java/com/oceanbase/odc/service/task/resource/K8sPodResourceTest.java

type-bug
if use StringUtils, splitByWholeSeparator should be used if we want split by characters but not a single character
Fixes #
```docs
```

fix(task): k8s parse resource identifier failed

---

server/odc-service/src/main/java/com/oceanbase/odc/service/session/model/SqlExecuteResult.java

fix
Fixed the issue where `queryTableOrViewData.getMorResults` failed due to duplicate keys in the `toMap` method, which in turn affected the failure of some sql console rule.
```docs
```

fix(session): fix SQL execute generate result failed caused by material view
